### ISSUE TITLE
[Bug]: Stuck on "Joining World" with HUD on screen

### ISSUE THREAD

**Issue by Dervysh** [FTBTeam/FTB-Modpack-Issues#1133] opened 2022-07-20 21:48 UTC
### Modpack

Direwolf20 1.18

### Modpack version

1.8.0

### Describe the bug

After clicking to load into a world, either singleplayer or multiplayer, it loads until the point it says "joining world" which remains on screen until my hud appears. The game freezes there indefinitely.

### Steps to reproduce

1. launch the modpack
2. click singleplayer/multiplayer
3. select world/server
4. click whichever button to load the world/server
5. wait for world/server to load

### Expected behaviour

the world/server to load without error and to be able to play

### Screenshots

![image](https://user-images.githubusercontent.com/109700267/180087684-a9ce5886-6d67-4e6b-af04-b3afbf4b39d0.png)

### Additional information

This problem occurred only after updating to 1.8.0. Playing previous to the update was uneventful.

I attempted to use a locally hosted server to work around the issue, which met with failure. But I was able to see the world running instead of the grey backdrop hopefully shown in the screenshot.

**Comment by Raidobw2** [comment] 2022-07-21 03:34
Hi, do you have game logs or more information on your instance? How much RAM is allocated and does reverting to 1.7.0 solve it?

Thanks in advance

**Comment by Dervysh** [comment] 2022-07-21 08:53
I had 16GB of RAM, have 32GB so I don't think that's the issue.
I can revert to 1.7.0, but my original save file no longer works, dumbass here forgot to make a backup.
I can send a crashlog I got from forcing a crash, and if there's any other way to get logs then please let me know.
https://paste.feed-the-beast.com/view/c8f43d09
Not sure if I've done it right, but I hope this helps.

**Comment by Raidobw2** [comment] 2022-07-21 22:10
Ah in that case, you can put your world here if you want. That'll require you to use a file sharing service, the easiest is usually Google Drive.

I believe the "serverconfig" could be the issue here, though I'm unsure since you managed to get a peek at the GUI in-game, which isn't normally the case.

I'll probably be able to fix your world and at the same time find out the issue for the future, so feel free.

Also you could have some backups in the `backups` folder, that's from FTB Backups 2. Maybe that can help, in any case I think the timer is 1 or 2 hours so you may have lost some progress, so sometimes that's not the best solution.

**Comment by Dervysh** [comment] 2022-07-21 22:22
https://drive.google.com/drive/folders/1ZMxpct9GPgd-4rYzgqPxb5A3pAD3DFDS?usp=sharing
^^Here is the world files. Hope I've done that correctly, I don't have much experience with this sort of thing.

I have no idea how I've managed to do this. I've spent hours looking for anyone else who's been in a similar situation, either with this pack or with minecraft generally and come up with nothing. Although I will admit I don't have the best luck looking things up in general.

Couldn't find anything in the backups folder, but I think that may be partly due to the way the pack updates, but I'm not sure.

**Comment by Raidobw2** [comment] 2022-07-22 22:10
Hi sorry for the small delay, I've went ahead and played in 1.8.0 with your world and it somehow works. I don't see anything wrong with it at the moment unfortunately.
![image](https://user-images.githubusercontent.com/17010632/180574806-28734035-aa81-4e30-81ae-dcf0f1910e39.png)
What I could recommend is to install a clean Direwolf20 1.18 instance and to transfer your world to it. Allocate 8GB of RAM and try to load the world -- it took me about 2 minutes after main menu to join the world successfully.
Let me know if that works, else I'll see if I can verify some of the level files to make sure they are in good form.

**Comment by Dervysh** [comment] 2022-07-22 22:56
I followed your recommendation.
Nothing has changed on my end.
Guess my computer is cursed.
¯\_(ツ)_/¯

**Comment by Raidobw2** [comment] 2022-07-23 00:22
I'll make some modifications to your world and I'll put it back here in that case.
- I'll cleanup the extra level files I'm seeing
- I'll regenerate your level.dat to a good one with the same seed, on 1.8.0
- I'll put everything in a chest in your base
- I'll change your player location and I'll put it inside the void dimension, which will lead back to your base
- I won't truncate any chunks to shrink your world size or delete things unneccessarily

Hopefully this will allow you to at least enter the world correctly, then click the portal block and get your stuff and resume playing. I've got some small things to take care of before, so I'll be able to start working on that in about an hour. Thanks for your patience so far as well!

**Comment by Dervysh** [comment] 2022-07-23 00:28
Well, it's hope for a fix here or quit playing minecraft for a while again. 
I can't even make a new world on this update, the same thing is happening.

I'm thinking there may be a deeper issue than simply my world files being funky, but if this works then at least I'll be able to play. 

I'd be happy to keep helping out in any way I can to find a fix if this doesn't fully fix the problem, although I'm not sure how much help I will be. I'm no expert, that's why I came here looking for people who understand this better than I do.

**Comment by Raidobw2** [comment] 2022-07-23 01:17
Hmm. While I try and repair it now, you can send me your game log when the game is freezing. While the game is running and frozen, you can actually go in the `logs` folder and copy-paste the latest.log to another location. Then drag that latest.log here in the window and upload it with your message. Hopefully that log contains more info about that error, if it affects new worlds as well.

**Comment by Raidobw2** [comment] 2022-07-23 01:26
Oh also, are there any added mods to your Direwolf20 1.18 instance? I see a HardcoreQuesting folder, a RPGAdvMod folder, a JABBA folder, etc. As far as I know, these are not in the 1.18 version of the modpack

**Comment by Dervysh** [comment] 2022-07-23 01:27
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9172846/latest.log)
Hope this is what you meant.

I haven't added any mods myself. If it's there and it's not meant to be, it's not directly my doing.

**Comment by Dervysh** [comment] 2022-07-23 01:38
Quickly tried searching for those mods you mentioned using the search function in windows explorer while in the modpack files, didn't come up with anything.

**Comment by Raidobw2** [comment] 2022-07-23 01:39
Yup that's what I wanted thanks. In that log there's a lot of HTTP errors (internet errors). Mostly that's the mod's version check on launch. Maybe you'd have an antivirus or firewall that's blocking things?

Also concerning the world, I'm actually quite confused if you didn't add any mods. There's a lot of random files from older Minecraft versions and there's even empty corrupted region files. A lot of things are wrong or damaged in that save.
![image](https://user-images.githubusercontent.com/17010632/180585424-b1fe4732-dbf9-40f8-ab3a-21491d118d05.png)

Can you check your firewall/antivirus, maybe have them off and load the modpack. See if you manage to create a new world in the Direwolf20 1.18 modpack. I'll post a picture just in case, it's this modpack:
![image](https://user-images.githubusercontent.com/17010632/180585467-8fc58dc2-fa14-4168-a320-b392e2c8d8e4.png)

P.S. Maybe what you put in the Google Drive was the wrong save? I tripled checked I downloaded the right thing

**Comment by Dervysh** [comment] 2022-07-23 01:50
That's the correct modpack alright, but I can understand why you'd want to confirm that.

I may have accidently copied one save file over another, which would probably cause that to happen.
And probably make that file simply no longer work...

Not sure why my firewall/antivirus would be screwing up this update in particular and not every other modpack I've ever downloaded. Turning off the active protections hasn't made the world load correctly though. I'll try redownloading the modpack entirely with them off tomorrow.

https://drive.google.com/drive/folders/1XZs3tQ3WETsfPEIK0DTVrGWZi8rnYkKF?usp=sharing
Here's a newly created world to look at. That should solve one mystery at least.

**Comment by Raidobw2** [comment] 2022-07-23 04:48
Alrighty I've managed to cleanup your save a bunch.
- Nether, End, etc. Other dimensions than the Overworld reset
- Old region files from Blightfall 1.7.10 removed
- Player inventory reset (your items are in a chest to the left of your refined storage system)
- Player coords reset (you'll be at spawn, your house is at (x: 2936, y: 64, z: -962). You should be able to use `/home` to get to your home, trust me on that one)
- Gamerules kept intact
- Level data regenerated with the same seed
- World name and icon adjusted
- Other data like advancements, mod data and stats should be unchanged

\* You'll spawn with the Eccentric Tome as well which should contain all the guides.

Here is the corrected world https://drive.google.com/file/d/1D0UBQN7Qx5rLCk9S6SGZmzbiIOIawRc9/view?usp=sharing, which has shrunk a little bit with the above changes (by 100 megabytes).

That works for me on 1.8.0 of the FTB Presents Direwolf20 1.18 modpack, let me know later if it works for you and if you have everything as well

**Comment by Dervysh** [comment] 2022-07-23 09:58
Still the same thing,
The problem must be something on my end, but not the world itself.

Sorry for bringing in a difficult problem. I'm still willing to keep going if you've got any ideas.

**Comment by Raidobw2** [comment] 2022-07-24 05:23
Oh, I'll keep going as long as the problem is not solved, don't worry. Though here it's less live support, since Github isn't made for that. But we can still find the issue for sure. If you want you can pass by the Discord and throw me a ping for live support, up to you if you have time.

As for what I think would be going on then, the Forge version might have changed in 1.8.0. If that is the case and if you happen to have antiviruses that could block Java, *maybe* that'll make some sense why the game is frozen like that.

What I'd ask to check is to launch the game until you get that grey backdrop. Then I assume the window appears frozen and the program is still running.
When you get there, open Task Manager. You can right click your taskbar and open it from there if you want. Find the Java program in the list and check if it's "Suspended" in the status column:
![image](https://user-images.githubusercontent.com/17010632/180633240-06c3a35b-9a81-4476-9a73-e38444644afc.png)

If it is suspended, there's probably an antivirus that's stopping it. Check if there's one in the list called like that:
- AVG
- Avast
- Acronis True Image
- Comodo Internet Security
- MalwareBytes

If yes, you might want to try to stop it/disable it in its settings and to allow Java at all times.

If not, then the problem is tough but we won't give up. If you can manage to get a few screenshots of your Task Manager, hopefully I can figure out what's messing with Minecraft. You can restart before doing so if you want to reduce the amount of programs in the list. You can also put screenshots of the RAM usage at that time and CPU usage.
Of course, try not to include any personal information, since I don't need any -- though in Task Manager there isn't anything personal usually.

Also, try with a different 1.18 modpack to compare, like FTB Chocolate, that one will load fast. Let me know if you're able to create a new world and play it for 1 minute.

As a side note as well, do your Windows Updates if you have any. We'll clear that out of the way at least.

Feel free to try out these things and come back with some more info, thanks

**Comment by Dervysh** [comment] 2022-07-24 14:19
Had a moment where it was being suspended, but it had nothing to do with my antivirus because it unsuspended without me doing anything and it's still broken.

The program isn't throwing any errors in task manager like "not responding" or anything, it's just locked up on this all too familiar screen.

FTB Chocolate works fine, but I had a small hang up downloading it. Wouldn't progress past "Preparing" the first time around. Closed and reopened the program, it was in my library. I deleted that and tried again, it downloaded properly the second time around. not sure if that means anything, but it's information for you.

I've checked windows updates and the only thing it has for me is to update to Windows 11, which I don't think is the problem.

Here's some pretty pictures that maybe add something to the investigation:
![image](https://user-images.githubusercontent.com/109700267/180650444-a6f7ef52-7d4c-4f44-a0a1-a756282693cf.png)
![image](https://user-images.githubusercontent.com/109700267/180650463-176f6364-e39d-491d-85c6-1cfa4f26f7c1.png)
![image](https://user-images.githubusercontent.com/109700267/180650467-40c23a19-2496-4be4-97d7-20b066b0e414.png)

**Comment by Raidobw2** [comment] 2022-07-26 00:43
Yup I meant the FTB Discord https://go.ftb.team/discord.

Hmm that looks ok. Try closing as much apps you don't need when playing the pack (steam, spotifiy, opera, gog, and even the FTB App itself with Overwolf). I've went and checked the full log again and thought we could try more things that could only be with your computer.

-----

### 1: Hosts file
We can check the hosts file first, in `C:\Windows\System32\drivers\etc` you can open the `hosts` file with Notepad. Normally that file is empty, it's only filled with lines starting with a `#`. If you see anything else, remove it and save the file.

-----

### 2: Clean Forge and modpack installation

Next we can try and repair Forge if that is the issue. Press Windows + R and paste `%localappdata%\.ftba\bin` then press Ok. In there you'll see a lot of folders. Left click the `libraries` folder once, then press and hold the Ctrl key and left click the `versions` folder. Both of them will be highlighted. Press Ctrl + X to cut them. You'll go somewhere else, such as in `C:\Temp` can be a good location (create the folder if it's not there). Press Ctrl + V when you are in that Temp folder to paste the files.

What you'll do next is to install a new instance of Direwolf20 1.18 on the version you want to play. Keep that instance for a bit. This will reinstall partly the `libraries` and `versions` folder.

Then you'll want to paste back the libraries and versions from earlier since some will have populated again. Go to `C:\Temp` and select the two folders from earlier. Press Ctrl + C to copy them this time. Go to `%localappdata%\.ftba\bin` again and paste the two folders there with Ctrl + V. You'll be prompted if you want to overwrite the files => do not overwrite any of them. Ignore all of them that are the same, simply paste what's missing on top.

Effectively this makes sure you're using a freshly downloaded modloader to start the modpack.

After that, use this fresh instance of Direwolf20 with the old world fixed I posted above.

-----

### 3: Antivirus and firewall

Though I don't recommend doing that often, also make sure your firewall/antivirus is turned off when about to join your Singleplayer world. If there's anything being blocked, you'll know since you'll then be able to join the world normally.

-----

### 4: Hamachi
Make sure that Hamachi is not active when playing. Also make sure you're not using any VPN.
I'd also recommend to turn off the Ethernet adapter that currently was installed by Hamachi. Press Windows + R and put `ncpa.cpl` in the box then press Ok. In the view there, right click the Ethernet adapter for Hamachi and disable it. You can active it again later if you want through the same process.

-----

Hopefully something along those lines will show us some improvement of the issue or will even solve it... Let me know if anything changes after trying out some of the things here

**Comment by Raidobw2** [comment] 2022-07-26 02:23
Wow! I'm glad we managed to find the issue :) The screenshots did help a lot in seeing Hamachi there haha.

That was a lengthy list but at least the mystery is solved and you can resume playing.

You're welcomed, if you get any more issues in the future let us know through here or the FTB Discord. Thank you for your patience as well.

Have fun playing!

**Closed by Raidobw2** 2022-07-26 02:23 UTC
Labels: 3: Support Request, FTB Presents Direwolf20 1.18
