### ISSUE TITLE
[Bug]: Instant crash when i open chat

### ISSUE THREAD

**Issue by LJLittleman7** [FTBTeam/FTB-Modpack-Issues#1594] opened 2022-11-03 10:58 UTC
### Modpack

FTB Stoneblock 3

### Modpack version

1.0.1

### Log Files

too late now, i am already reinstalling sorry :(

### Describe the bug

When in game, i go onto my server i made with a friend. I open chat, because i had a bug where i had the same messages from MineTogether repeat, so i tried to change to server chat, but the option wasnt there, so i tried to disconnect from MineTogether, which then just made it so i couldnt use chat at all, and then when i reopened chat, i instantly crashed. i reopened the game, went back to the server, opened chat and CRASHED AGAIN. I am reinstalling the modpack but hopefully this can be fixed

### Steps to reproduce

Im not 100% Sure but this may work
1. Load onto a server
2. Open chat
3. Have MineTogether ask if you'd like to join MineTogether or disconnect (idk how)
4. Disconnect from MineTogether
5. Open chat

### Expected behaviour

I expected to be able to use chat lol

**Comment by LJLittleman7** [comment] 2022-11-03 11:24
Re installing worked

**Comment by natsukashiixo** [comment] 2022-11-03 12:19
[crash-2022-11-03_12.24.42-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9928127/crash-2022-11-03_12.24.42-client.txt)
[crash-2022-11-03_12.37.04-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9928128/crash-2022-11-03_12.37.04-client.txt)
Two log files for this same issue. 

### Steps to reproduce:
Join a server
Opt out of using MineTogether chat
Try using chat and/or try opening command console (default key "-")
Java instance will force close itself

### Expected behaviour
I expected MineTogether to de-load and put me back into the Vanilla chat when I declined using MineTogether.

### Additional information
Considering removing the MineTogether mod to see what happens. It provides no functionality for me after all.

**Comment by Raidobw2** [comment] 2022-11-04 09:48
Compatibility is fine if you remove the mod. Update to 1.0.2, the instant crash should be fixed.

There is another issue in 1.0.2, but a 1.0.3 patch is also on the way to solve that.
If you crash in 1.0.2 while loading the game (red Mojang screen), remove MineTogether until you update the game again.

I will close this since the issue should have been fixed in 1.0.2

**Closed by Raidobw2** 2022-11-04 09:48 UTC
Labels: 3: Support Request, FTB StoneBlock 3
