### ISSUE TITLE
FTB Inferno ArrayIndexOutOfBoundsException rubidium crash

### ISSUE THREAD

**Issue by Hachuurui** [FTBTeam/FTB-Modpack-Issues#1357] opened 2022-09-29 00:06 UTC
### Modpack

FTB Inferno

### Modpack version

1

### Log Files

https://pastebin.com/8PuJvada

### Describe the bug

Game crashes at random intervals because of this error. Sometimes its instant, other times it takes an hour or so.

### Steps to reproduce

Load modpack, load world (SP or MP). it'll happen eventually. has happened twice in 3hrs.

### Expected behaviour

For mods to play nice and sanity check their array indexes. But I'm probably asking too much.

### Additional information

I've put in an issue involving this here.
https://github.com/Asek3/Rubidium/issues/297

**Comment by Saereth** [comment] 2022-09-29 04:00
We are still working to resolve this and trying to gather more information on the issue. It happens to some people but not everyone, if it is anything more than a rare occurrence for you, I'd suggest just turning off Rubidium/oculus/milk of magnesium until there are further fixes in the future, which is basically our advice on the shaders section on the pack page. The crash log is useful though, ty.

**Comment by Hachuurui** [comment] 2022-09-29 05:03
@Saereth it may be unrelated, but I can say every pack I have seen this issue on had alex's mobs. It was the reason we were using InControl (the mod I first saw the error in with the -1 index) in the first place. The number of mobs (peaceful and otherwise) was insane.

**Comment by Saereth** [comment] 2022-09-29 05:16
yeah I've heard of that but dug into the render code quite a bit and alex isnt doing any mixins in this particular area, unfortunately. I can't reproduce the crash myself so I have to rely on those that can for more info. Could you also screenshot your video options as well, might be useful to start looking for some similarities there. Ty!

**Comment by MichaelHillcox** [comment] 2022-09-29 07:41
If anyone can find a way to consistently reproduce this crash please let us know. If this continues to happen randomly. We recommend you remove rubidium and oculus, this will fix the issue but at the same time will disable shaders from working. Double edged sword

**Comment by Hachuurui** [comment] 2022-09-29 09:04
![2022-09-29 05_00_25-Window](https://user-images.githubusercontent.com/2464584/192989756-1638d332-fa6c-4d1f-b870-2ab8ebbc7548.png)
![2022-09-29 05_00_47-Window](https://user-images.githubusercontent.com/2464584/192989757-91eaa61c-49ba-4a07-b1f0-807ea11994c4.png)
![2022-09-29 05_01_07-Window](https://user-images.githubusercontent.com/2464584/192989760-54291fd1-4b8d-4739-870b-243145a92d7f.png)
![2022-09-29 05_01_22-Window](https://user-images.githubusercontent.com/2464584/192989761-27932f5f-50cc-4a58-beee-ae840bc240f6.png)
[DxDiag.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9673032/DxDiag.txt)

![2022-09-29 05_01_42-Window](https://user-images.githubusercontent.com/2464584/192989762-e92024ec-5744-4bd6-9596-304bf112d1d4.png)
![2022-09-29 05_02_09-Window](https://user-images.githubusercontent.com/2464584/192989764-97ad2faa-a0f6-4b66-927d-00417b17b668.png)

**Comment by Hachuurui** [comment] 2022-09-29 09:04
there is also a dxdiag in the middle of those @Saereth

**Comment by Saereth** [comment] 2022-09-29 15:45
@Hachuurui you're settings are identical to mine except for shadows I set those at 12 chunks as well the dxdiag may be helpful once we can get some more to compare to for similarities.

**Comment by Hachuurui** [comment] 2022-09-29 19:12
Those are the default settings btw. I made no alterations aside from changing the ui scaling.

**Comment by Hachuurui** [comment] 2022-09-29 20:18
I was re-reading what you said earlier @Saereth... Do you happen to be using a Geforce RTX card per chance?

**Comment by Saereth** [comment] 2022-09-29 20:53
Yeah I'm using an RTX 3060 with the latest drivers

**Comment by Hachuurui** [comment] 2022-09-29 21:18
[DxDiag.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9679149/DxDiag.txt)
This is their Dxdiag - No crash after an hour or so.

**Comment by Hachuurui** [comment] 2022-09-29 21:21
> Yeah I'm using an RTX 3060 with the latest drivers.

wonder if its my 2060 super :/

**Comment by ztahenakos** [comment] 2022-09-29 21:48
I have an RTX 3070 and I've run into this issue a few times today. The driver is not up to date (latest being 517.48, current is 512.59). The few times I encountered this I was just running around.

**Comment by impucky** [comment] 2022-09-30 12:27
Getting the same crash with an older GPU (GTX 970)

[crash-2022-09-30_14.21.34-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9684107/crash-2022-09-30_14.21.34-client.txt)

**Comment by ztahenakos** [comment] 2022-09-30 12:41
Might be worth seeing if someone with an AMD or Intel GPU can reproduce this to rule out this being specific to Nvidia.

**Comment by ztahenakos** [comment] 2022-09-30 15:29
I managed to reproduce this on my Linux box after about 10 minutes or so of the instance running. No more than half of that I just had my character auto-running while the game window had focus. Auto-run was achieved via:
1. F3+P to disable pause on focus.
2. Rebound moving forward to right click
3. Used F3+T while moving to keep the right click going on the window after alt-tabbing.

CPU is an AMD R5 5500U, GPU is an AMD Lucienne GPU (1002:164c). Kernel is 5.18.10-76051810, version of mesa is 21.2.2-1ubuntu1pop0~1634226723~20.04~b715ae2.

[crash-2022-09-30_11.22.46-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9685809/crash-2022-09-30_11.22.46-client.txt)

**Comment by Novasiri** [comment] 2022-10-01 07:16
Same issue here, for some reason I've gotten it to reliably trigger when looking at Striders, for some reason?

[crash-2022-09-30_21.20.10-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9689796/crash-2022-09-30_21.20.10-client.txt)

**Comment by ztahenakos** [comment] 2022-10-02 01:16
I tried to reproduce your issue by spawning a bunch of Striders in my world and things seem to be happy even with upwards of 50 striders running around in lava, my system doesn't chug and will happily draw them. Could just be a different reproduction path to the same issue, perhaps this could provide a hint as to what is happening. When I reproduce the issue, I've done it by just running which would cause chunks to come into play and phase out, which depending on the JVM state could require a bit more effort, especially depending on how fast I am going. If your system reliably reproduces it when rendering striders, then maybe its that, Minecraft is unable to process things fast enough so maybe an assumption that would normally hold true is not true in this state.

**Comment by therob** [comment] 2022-10-02 12:38
I also had this crash and i think it's possible that Striders are causing it. It started happening when i got a Strider at my base after reentering the world and looking in this direction. Maybe only freezing Striders?

Using OpenJDK 17.0.4 instead of the Mojang provided one seems to fix this problem for me.

**Comment by tyra314** [comment] 2022-10-02 14:44
I also got this crash three times already. I'm sure it was happening every time I walked on top of the nether in some random direction.

I'm running Linux with an RTX card as well.

[crash-2022-10-02_16.34.14-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9692810/crash-2022-10-02_16.34.14-client.txt)
[crash-2022-10-01_23.07.57-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9692811/crash-2022-10-01_23.07.57-client.txt)
[crash-2022-10-01_21.22.21-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9692812/crash-2022-10-01_21.22.21-client.txt)

**Comment by MichaelHillcox** [comment] 2022-10-02 15:49
Hi, if you're having this issue, can you try this jar instead and let me know if the crash stops happening. Also let me know if this causes any new crashes :+1:

https://c.mikey.pro/data/mods/third-party/rubidium-0.5.4

**Comment by Hachuurui** [comment] 2022-10-02 21:57
@MichaelHillcox I'll do some testing.

**Comment by Hachuurui** [comment] 2022-10-02 23:37
@MichaelHillcox  So far, no crashes. Been going for two hours now.

**Comment by Hachuurui** [comment] 2022-10-05 19:34
@MichaelHillcox  I have not had any issues since but I also have not been on since then. Clients requested a bunch of changes so I've been super busy. I'll try to fit some time in soon to do more testing though.

**Comment by lslinnet** [comment] 2022-10-08 10:05
The patch seems to fix the issue for me at least @MichaelHillcox thanks!

**Comment by Novasiri** [comment] 2022-10-09 11:01
0 issues with this patch file, thanks @MichaelHillcox !! You're a life saver!

**Comment by Saereth** [comment] 2022-10-13 18:48
If you're still getting this issue make sure you have updated to v 1.0.3.

**Closed** 2022-10-13 18:48 UTC
Labels: 1: Mod Issue, state: Fixed in Dev :hammer_and_wrench:, FTB Inferno
