### ISSUE TITLE
[Bug]: when you press U on moded enderchest game crash

### ISSUE THREAD

**Issue by orekiller** [FTBTeam/FTB-Modpack-Issues#1803] opened 2022-11-09 18:35 UTC
### Modpack

stoneblock 3

### Modpack version

1.0.2

### Describe the bug

i am still on a older version 1.0.2 for a server when you press U on the moded enderchest your game crash

### Steps to reproduce

go to a made enderchest
press key u
game crash

### Expected behaviour

game crash

**Comment by Sunekaer** [comment] 2022-11-09 20:40
Duplicate of #1574

**Closed by Sunekaer** 2022-11-09 20:40 UTC
Labels: FTB StoneBlock 3
