### ISSUE TITLE
HOW TO FIX THE CRASH YOU ARE GETTING 9TH OF DESEMBER (READ IF YOU ARE CRASHING)

### ISSUE THREAD

**Issue by NordicGamerFE** [FTBTeam/FTB-Modpack-Issues#2278] opened 2022-12-09 11:02 UTC
### Modpack

FTB StoneBlock 3

### Modpack version

all

### Describe the bug

If you are crashing and your crash log contains ```net.minecraftforge.fml.ModLoadingException: Better Than Llamas (betterthanllamas) encountered an error during the done event phase``` at the top, delete BetterThenLlamas and BetterThenBunnies from your mods folder, you can reach your mod folder by pressing the 3 dots beside play in the ftb app when clicking a profile, then open... then mods folder. Be sure to take a backup of your world before doing this.

### Steps to reproduce

N/A

### Expected behaviour

N/A

**Comment by manmaed** [comment] 2022-12-09 11:43
Duplicate of #2269

**Closed by manmaed** 2022-12-09 11:43 UTC
Labels: FTB StoneBlock 3

**Comment by NordicGamerFE** [comment] 2022-12-09 12:08
This was not really an issue, More of a guide.
