### ISSUE TITLE
AA Drill increases base damage

### ISSUE THREAD

**Issue by whydisnec** [FTBTeam/FTB-Modpack-Issues#5410] opened 2024-06-28 12:24 UTC
### Modpack

FTB NeoTech

### Modpack version

1.3.0

### Has the pack been modified

No

### Describe the bug

Holding a Drill from Actually Additions seems to increase your base damage based on the charge level and the time you hold it (higher=higher dmg increase). Dying resets your damage.

### Steps to reproduce

1. Get an ActuallyAdditions drill
2. Hold it for some time in your main hand
3. Hit any mob or entity

### Expected behaviour

Drills shouldn't increase damage

### Screenshots

https://github.com/FTBTeam/FTB-Modpack-Issues/assets/131700287/0d2eb8e3-63ff-4331-8d8d-22916f9a3bac

### Additional information

Cheats were on on the world where I encontered the issue

**Comment by Gaz492** [comment] 2024-06-28 12:41
This looks to be a duplicate of #5333 or related to it so I will close this issue.

**Closed by Gaz492** 2024-06-28 12:41 UTC
Labels: Bug, FTB NeoTech
