### ISSUE TITLE
[Bug]: Client crashes when trying to break floating Botania flowers

### ISSUE THREAD

**Issue by Drakkim** [FTBTeam/FTB-Modpack-Issues#1115] opened 2022-07-15 01:13 UTC
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.7.0

### Log Files

https://paste.atlauncher.com/view/9ea77b24-1e5b-4de2-8d54-318a63b9de45

### Describe the bug

Client crashes when trying to break floating Botania flowers

### Steps to reproduce

Place a floating Bellthorne or Orechid Ignem (probably more, but those are the ones I've tried)
Attempt to break the flower
Client turns grey and crashes.

### Expected behaviour

The item should break and the game should not crash

### Additional information

I'm running on a server, not sure if that makes a difference.

**Comment by TheonlyTazz** [comment] 2022-07-15 08:30
Duplicate of:
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1088
Please disable `experimentalForgeLightPipelineEnabled` in the meantime in `forge-client.toml` as that caused more issues than it did good, this will be changed in the next version

**Closed by TheonlyTazz** 2022-07-15 08:30 UTC
Labels: FTB Presents Direwolf20 1.18
