### ISSUE TITLE
[Bug]: Sapphire and Angel Ring

### ISSUE THREAD

**Issue by CtNeal** [FTBTeam/FTB-Modpack-Issues#1068] opened 2022-07-04 19:58 UTC
### Modpack

FTB Plexiglass Mountain

### Modpack version

1.1.1

### Describe the bug

Highest tier Angel Ring now requires sapphire gears, but after searching thoroughly, I am unable to find any sapphire ore in the overworld or the mining dimension. Is a sapphire creeper from resourceful creepers intended to be the only way to obtain sapphire in the pack, or does sapphire ore generate in only specific biomes, or am I missing something?

### Steps to reproduce

Cannot locate sapphire ore, used mekanism's digital miner in various biomes and still unable to locate any.

### Expected behaviour

Sapphire ore in world gen

**Comment by quietust** [comment] 2022-07-04 21:19
Duplicate of #1030?

**Comment by CtNeal** [comment] 2022-07-04 22:10
Ah, my apologies, yes it is. Thanks for pointing me there!

**Comment by Raidobw2** [comment] 2022-07-05 05:20
Thanks for the report! We'll handle it at #1030 so I'll close this issue to avoid redundancy. You'll find ways to get sapphire in the linked issue for now, there are a few

**Closed by Raidobw2** 2022-07-05 05:20 UTC
Labels: state: Duplicate :books:, 2: Enhancement, FTB Plexiglass Mountain
