### ISSUE TITLE
Health resets to 20 when leaving world even if equipment raises max health

### ISSUE THREAD

**Issue by rmedzihradsky** [FTBTeam/FTB-Modpack-Issues#2511] opened 2023-01-14 10:55 UTC
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.1.0

### Describe the bug

I made some armor, used Reforging Table from Apotheosis (6.0.2) to get some affixes and gem slots. I got some bonus to max health from affixes and some more from added gems. I put on the armor and my max health was over 60. I regenerated the over 40 health to fully heal and left the game. Once I came back, my health was back to 20. I tested this several more times with various total health, I always had 20 when I came back.

### Steps to reproduce

1. Get equipment that raises your maximal health
2. Regenerate health to have more than 20
3. Save and quit to title
4. Join the same world

### Expected behaviour

Health remaining the same as when I left

**Comment by adam-miller** [comment] 2023-01-20 02:48
Confirming this happens in 1.1.0 for me as well.
It does not occur in 1.0.4. 
In 1.1.1 the issue is mitigated some, but still present. New behavior is that I start with normal HP, but will begin healing up to max as soon as I log in, rather than starting with the increased max HP.

**Comment by Saereth** [comment] 2023-01-30 18:07
This is an apotheosis thing, due to the way extra health from the gems works it has to be recalculated on login so you regen when it happens. This is effectively from a "fixed" state where before you would just completely lose the hearts. I've mentioned it to shadows so maybe can improve it more but this is essentially fixed in its current state, or as much as it will be for right now

**Closed by Saereth** 2023-01-30 18:07 UTC
Labels: FTB Presents Direwolf20 1.19
