### ISSUE TITLE
Mekanism Dust / Ores smelting into FTBIC ingots

### ISSUE THREAD

**Issue by seitzbg** [FTBTeam/FTB-Modpack-Issues#2788] opened 2023-03-05 04:21 UTC
### Modpack

FTB One

### Modpack version

2.0.0

### Log Files

N/A

### Describe the bug

When I smelt Mekanism ore and or dust, I am getting FTBIC ingots :(

Dust
<img width="845" alt="dust" src="https://user-images.githubusercontent.com/171158/222941497-84277aa7-b8a5-4b1c-a85b-794b277d01c4.png">

Result
<img width="848" alt="ingot" src="https://user-images.githubusercontent.com/171158/222941504-73a69bfd-7086-43e1-8147-43168510a87c.png">

This also happens with say raw uranium ore, or tin.

### Steps to reproduce

1. Create mekanism bronze dust with 3 tin dust and 1 copper dust
2. Smelt bronze dust
3. Observe the FTBIC ingot 

### Expected behaviour

Smelting Mekanismi ore/dust should give Mekanism ingots

### Screenshots

<img width="845" alt="dust" src="https://user-images.githubusercontent.com/171158/222941537-d40ca9c0-3e85-4a8c-a690-abd0c283405f.png">
<img width="848" alt="ingot" src="https://user-images.githubusercontent.com/171158/222941538-c9581ad0-2f08-484a-ab09-bd958fd6606a.png">

**Comment by MechBFP** [comment] 2023-03-05 13:21
Duplicate of my post here. https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2784

**Closed** 2023-03-06 22:39 UTC
Labels: state: Fixed in Dev :hammer_and_wrench:, FTB One
