### ISSUE TITLE
FTB Genesis soft lock

### ISSUE THREAD

**Issue by TemporalWolf** [FTBTeam/FTB-Modpack-Issues#4189] opened 2023-11-09 14:03 UTC
### Modpack

Other...

### Modpack version

1.0.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13308901/latest.log)

### Describe the bug

Game softlocks "waiting for server"

last entry before I forced closed java:
`[09Nov2023 05:49:55.726] [ModernFix integrated server watchdog/ERROR] [org.embeddedt.modernfix.world.IntegratedWatchdog/]: A single server tick has taken 245704, more than 40000 milliseconds`

### Steps to reproduce

Unknown

### Expected behaviour

Not soft locking

**Comment by Raidobw2** [comment] 2023-11-09 21:50
Hello @TemporalWolf, if possible could you send me your world here or on the [FTB Discord](https://go.ftb.team/discord) (`@raidobw2`) so we can check this further. The issue seems to come from an arrow projectile that could be causing the soft lock.

The entities such as this arrow would be stored in your `saves/world/entities` folder by region name. If you wanted to delete the contents of that folder as a test make sure you have a backup, since this deletes all entities (monsters, villagers, arrows, animals).

Thanks in advance

**Comment by TemporalWolf** [comment] 2023-11-09 22:39
I can do that, but on restart the world had rolled back a couple minutes and I was able to continue without an issue... so it's now several hours ahead of this issue. Would you still like a copy?

**Comment by Raidobw2** [comment] 2023-11-10 01:48
I see, I misinterpreted the issue, I thought it was happening when joining the world. In that case no it's ok, but thanks! The information you provided about the ruined city will be enough for us to try and reproduce the issue 🙂

**Comment by Saereth** [comment] 2023-11-18 18:04
This was a bug with lostcities that should now be resolved with the 1.1.1 update

**Closed** 2023-11-18 18:04 UTC
Labels: 1: Mod Issue, state: Fixed :heavy_check_mark:, FTB Genesis
