### ISSUE TITLE
[Bug]: Frequent crashes in Inferno

### ISSUE THREAD

**Issue by madasi** [FTBTeam/FTB-Modpack-Issues#1427] opened 2022-10-13 00:45 UTC
### Modpack

FTB Inferno

### Modpack version

1.0.2

### Log Files

https://pste.ch/puyanabohu.rb
https://pste.ch/kahonijoxi.pl
https://pste.ch/emuroyeraq.pl
https://pste.ch/ebelucexer.pl
https://pste.ch/ceqefotivi.pl
https://pste.ch/eguzahabuw.pl

### Describe the bug

I'm experiencing very frequent crashes while playing on a multiplayer server. Sometimes I can play for hours, other times I crash every 15-20 minutes. The crashes don't appear to be tied to any specific activity, I'm usually just walking or running along and then everything freezes for a second and then I see the saving message and know I'm crashing.

### Steps to reproduce

Launch Inferno
Connect to server
Walk around - it happens randomly

### Expected behaviour

Not crashing

### Additional information

Other player on the same server (at the same time, with the same version of the modpack) is not experiencing these crashes.

**Comment by Saereth** [comment] 2022-10-13 01:03
this a duplicate of the pinned issue with sodium, this is resolved in 1.0.3 which should be out tomorrow, for the mean time you can manually update rubidium to the latest version on curseforge and it will stop the crashes

**Closed by Saereth** 2022-10-13 01:03 UTC
Labels: state: Duplicate :books:
