### ISSUE TITLE
[Bug]: Portals spawning mobs under the floor

### ISSUE THREAD

**Issue by onelegger** [FTBTeam/FTB-Modpack-Issues#1912] opened 2022-11-13 02:19 UTC
### Modpack

FTB Inferno

### Modpack version

1.3.0

### Describe the bug

I was doing the portal for the bellringer, but noticed it doing this on normal portals before. Whenever a portal spawns, it spawns the mobs below the ground i'm standing on. For example. I attempted to fight the bell ringer on the bedrock ceiling at my spawn the first time, but it spawned the mobs down in the normal nether. I spawned a portal in the nether, It spawned them all the way to the floor of the nether in a lava lake. I built two floors, one on top of the other separated by 10 blocks or so. I spawned the nether on the top floor, but it spawn the mobs underneath my bottom floor. 

### Steps to reproduce

Spawn a portal (Bellringer's portal for example)
mobs spawns under the floor

### Expected behaviour

Mobs spawn on same level as me

**Comment by orbidlo** [comment] 2022-11-13 09:47
Duplicate of issue https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1905 and  https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1858

**Closed** 2023-03-06 22:39 UTC
Labels: state: Fixed in Dev :hammer_and_wrench:, FTB Inferno
