### ISSUE TITLE
[Bug]: Powah X Pipez mod crash, cables connecting = Ticking TE

### ISSUE THREAD

**Issue by Army25Papa** [FTBTeam/FTB-Modpack-Issues#221] opened 2021-10-31 08:57 UTC
### Modpack

FTB OceanBlock

### Modpack version

1.3.0 (first happened on 1.5.0

### Log Files

Crash Report

https://paste.feed-the-beast.com/view/94ae35b7

(The crash report had 2055 lines of the same six lines over and over, so I've just put it in once.)

Six lines in crash report.

at owmii.lib.logistics.energy.Energy.receive(Energy.java:381) ~[lollipop:3.2.9] {re:classloading}
	at owmii.powah.block.cable.CableTile.pushEnergy(CableTile.java:119) ~[powah:2.3.16] {re:classloading}
	at owmii.powah.block.cable.CableTile.receiveEnergy(CableTile.java:96) ~[powah:2.3.16] {re:classloading}
	at owmii.lib.block.AbstractEnergyStorage$1.receiveEnergy(AbstractEnergyStorage.java:62) ~[lollipop:3.2.9] {re:classloading}
	at de.maxhenkel.pipez.blocks.tileentity.types.EnergyPipeType.receiveEqually(EnergyPipeType.java:163) ~[pipez:1.16.5-1.2.10] {re:classloading}
	at de.maxhenkel.pipez.blocks.tileentity.types.EnergyPipeType.receive(EnergyPipeType.java:104) ~[pipez:1.16.5-1.2.10] {re:classloading}
	at de.maxhenkel.pipez.utils.PipeEnergyStorage.receiveEnergy(PipeEnergyStorage.java:28) ~[pipez:1.16.5-1.2.10] {re:classloading}

### Describe the bug

Had Fluid Extractors and Universal Pipe (from Pipez) to extract latex.  When adding a power source, the Universal Pipe was not transferring power.  Switched to the Energy Cable (Basic), which I just laid over the top of the Universal Pipe for a quick and dirty job to keep fluids pumping but also get power.  Went back with a wrench to remove the pipes from trying to connect.  Clicked one too many times on one Universal Pipe connected with the Energy Cable.  When the two touched, the game instantly crashed and have not been able to get it to run since.  Anytime I launch the world, it crashes when it reaches 100%.

Have tried launching on newest release, as well as rolling it back to 1.3.0

### Steps to reproduce

1. Use four fluid extractors around one log.  Stack four more fluid extractors on top of first set with another log (one set).
2. Build a second set. (sixteen fluid extractors total).
3. Use Universal Pipe to connect them all, and have them empty into an Advanced Black Hole Tank.
4. Use a Dimensional Cell for power, linked with your main power source.
5. Dimensional Cell did not transfer power, so switch to Energy Cable (basic) and lay over universal pipe.
6. Use wrench to connect energy cable and universal pipe together instead of remove them from trying to connect.
7. World should crash and not let you rejoin.

### Expected behaviour

The game crashes and world is unable to load.

### Additional information

Is this world dead or is there a way to save the world?  It seems that the world is stuck in some sort of endless crash loop.
Edit:  Just wanted to notate it here in case it wasn't clear.  I am able to create new worlds and everything runs fine!

**Comment by Sunekaer** [comment] 2021-11-01 22:42
Duplicate of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/138

**Closed by Sunekaer** 2021-11-01 22:42 UTC
Labels: FTB OceanBlock, cat: Bug, des: Mod Issue, state: Mod Update Needed
