### ISSUE TITLE
[Bug]: Rainbow Lamp from Random Things mod doesn't change colour

### ISSUE THREAD

**Issue by SometimesClueless** [FTBTeam/FTB-Modpack-Issues#1425] opened 2022-10-12 15:37 UTC
### Modpack

FTB Stoneblock 2

### Modpack version

Latest one

### Describe the bug

I created a rainbow lamp after seeing it change colour in the JEI. It changes colour in my hand. But the moment I place it down, it changes colour to a gray/white lamp. It doesn't change colour at all.

### Steps to reproduce

1. Create rainbow lamp using the dyes from the Botanica flowers
2. Place lamp down.

### Expected behaviour

I expected the lamp to change colour where I had placed it down.

**Comment by Raidobw2** [comment] 2022-10-14 01:28
Try giving it a different redstone signal strength to change its color (source https://lumien.net/rtwiki/blocks/rainbow-lamp/)
![image](https://user-images.githubusercontent.com/17010632/195740825-2bcfc034-8a25-4bae-b2d8-13feaa803783.png)
What they use in the image to give it a different redstone signal everytime is an analog emitter (https://lumien.net/rtwiki/blocks/analog-emitter/)

> The Analog Emitter is a block that allows you to easily produce analog redstone signals with a custom strength. If its input side (circle) is powered (strength is irrelevant) it will output a redstone signal of the strength specified in its gui on the other sides (Squares).

**Comment by SometimesClueless** [comment] 2022-10-18 12:16
OK, this did work. But is there no way to make it cycle through the colours? Kinda would have loved having lights that changed. I wish this mod had redstone lamps in different colours, would have been simpler.

**Comment by Raidobw2** [comment] 2022-10-20 08:56
Huh, you kinda can. It's a bit complicated though. I didn't find a better solution for now, so just follow along and you'll learn a few more things (cool!).

## How to make an RGB controller with RFTools Control

RFTools Control allows you to make programs that run in the game and interact with the world. In our case that's useful for making a "loop" that cycles through all the redstone signals and thus changes the color of the lamps.

First you're gonna need a program to do that. Here's one:
![image](https://user-images.githubusercontent.com/17010632/196892803-b236ff23-d1d0-47da-add2-dc4b3d8d03d8.png)

Probably not the best, but it works and that'll all I can give now. You'll need the item in-game called the program card to use it. Unless you can reproduce that 1:1 just with this, you can cheat it in. There's no good way to share that program unfortunately, so here's how to do it.
Open this file and Ctrl + C the text inside: [Redstone Loop Program](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9828001/RedstoneLoop.txt)

In-game, give yourself a command block with `/give @p minecraft:command_block`:
![image](https://user-images.githubusercontent.com/17010632/196894230-5ea75861-5b34-4990-b580-0ac980caebe8.png)

Place it down, and paste all the code in the top part, then hit done:
![image](https://user-images.githubusercontent.com/17010632/196894458-04c1e55d-95e5-426b-98a5-5d6773ff05df.png)

Then place a button and trigger the command block. You should receive a program card. If it's named `RedstoneLoop`, you got that right!
![image](https://user-images.githubusercontent.com/17010632/196894664-f4fb75a3-1b25-4902-a001-ca0ff8fefa11.png)

The program card:
![image](https://user-images.githubusercontent.com/17010632/196894775-5b3c260d-d1c9-4c0f-a64b-46a175ef641d.png)

Then place your lamps where you want them to be, mine are on a fancy bridge:
![image](https://user-images.githubusercontent.com/17010632/196894915-5e8d6e17-0ec1-4277-ad7a-702703ac50ce.png)

Connected to each lamp set a redstone relay in OUTPUT mode like so:
![image](https://user-images.githubusercontent.com/17010632/196895436-88fca972-1a41-48d5-b9c1-0ddb6bdb29d4.png)

You place them onto structural ducts:
![image](https://user-images.githubusercontent.com/17010632/196895561-073b0bff-c879-4432-8d5f-051eae4e1d0a.png)

Connect all your lamps to one point, next to a machine you'll craft called a "Processor" from RFTools Control:
![image](https://user-images.githubusercontent.com/17010632/196895878-6d183664-d137-438b-b8e6-65728eee00b3.png)

The redstone relay right under the processor is set in INPUT mode instead. It can ONLY BE PLACED UNDER the Processor, important!
![image](https://user-images.githubusercontent.com/17010632/196896053-e19dfcb6-55e3-429a-a286-2bfcdcaf500d.png)

Then enter the Processor's GUI:
![image](https://user-images.githubusercontent.com/17010632/196896262-c7feee19-e649-4304-b866-efde7ea2f423.png)

Put the program card at the top and a "CPU Core B500" (item) that you crafted in the slots down there:
![image](https://user-images.githubusercontent.com/17010632/196896534-0d0a71cc-1e1d-4f72-806d-5d19995ba780.png)

Next, craft an RFTools Screen and place it somewhere you want to control your lights! I have it on this wall for instance. Use a Smart Wrench from RFTools to make it bigger (right-click):
![image](https://user-images.githubusercontent.com/17010632/196896859-47b218f2-223f-4e87-92ad-7ca97eec6cb5.png)

It looks like this so far, nothing too fancy:
![image](https://user-images.githubusercontent.com/17010632/196896991-a39e7e4c-4c3e-448f-8180-3cebfbba82fd.png)

Craft and place a screen controller near the screen:
![image](https://user-images.githubusercontent.com/17010632/196897451-f2296649-7a0b-44ce-90fd-96778ad254a9.png)

Give it power with your flux points from Flux Networks:
![image](https://user-images.githubusercontent.com/17010632/196897617-7780a7e5-3b5e-46e3-a066-58cade041307.png)

Same for the processor:
![image](https://user-images.githubusercontent.com/17010632/196897705-fb8ccbfd-cc82-485b-9670-c0498e9dd1b8.png)

Above the processor, craft and place a Redstone Receiver. It can only be above, this is VERY important! Use the Smart Wrench to rotate it.
![image](https://user-images.githubusercontent.com/17010632/196897879-170b19c5-83ae-4cf1-aee4-8edc9bb2d1d4.png)

Then craft those 2 items:
![image](https://user-images.githubusercontent.com/17010632/196898041-5a117693-7c63-42d3-8d3e-e1a96ebeb9fb.png)
![image](https://user-images.githubusercontent.com/17010632/196898109-2e521bf9-66d6-4cc4-99e1-39d96f1317af.png)

With the "Interaction Screen Module" in hand, sneak + right-click the Processor. It will show this message:
![image](https://user-images.githubusercontent.com/17010632/196900651-faba4b50-2643-43ca-b0a9-070f931dcdd0.png)

With the "Button Screen Module" in hand, sneak + right-click the Redstone Receiver. I did it twice so it shows '2', but for you it will be '1' most likely:
![image](https://user-images.githubusercontent.com/17010632/196898382-f3703f4f-f89d-4029-b467-3f543b9b0b03.png)

Go to the screen, take the "Interaction Screen Module" and right click it onto it. Same for the other module, in that order. The screen will look like so:
![image](https://user-images.githubusercontent.com/17010632/196898681-ad7cba8e-0533-4768-9bad-b727b442047a.png)

Right click the Screen Controller nearby and click "Scan", it will detect the screen:
![image](https://user-images.githubusercontent.com/17010632/196898840-9a1ddb2d-02dc-4858-beda-00bed6aa162c.png)

Now buttons appear. Shift + right-click the screen to enter the configuration of the modules:
![image](https://user-images.githubusercontent.com/17010632/196899035-c43a9890-660a-45af-b09b-09e2caa7e33b.png)

Do the first one with that info and the "start" signal:
![image](https://user-images.githubusercontent.com/17010632/196900000-018941ba-018d-4fcb-8d3c-5d1564e016db.png)

Then the second one:
![image](https://user-images.githubusercontent.com/17010632/196899885-46b96c4b-47e2-4162-b6e2-bb4dae7be0e0.png)

Looks like that:
![image](https://user-images.githubusercontent.com/17010632/196900089-b8f316c1-01eb-4274-a8f6-1aaeafa5b473.png)

Right-click the button on the screen with your hand, it will dig into the screen a little bit. Here you could use a redstone module to make it look prettier to display a ON/OFF message, but this single button module will do.
![image](https://user-images.githubusercontent.com/17010632/196900366-2f3a55df-fe84-4c3b-b85d-079d3f23ffac.png)

Then right click the "Go!" button to start the light show:
![image](https://user-images.githubusercontent.com/17010632/196901703-dd76abfa-e89b-4f4f-9da8-952802e84048.png)

RGB Bridge example:

https://user-images.githubusercontent.com/17010632/196902191-e521d75b-b9bf-4480-b444-a54996462fc1.mp4

If you get tired of the switching lights, then unpress the "Allow lightshow" button. After it did all the lights once, it will stop until  you allow it again, and that you press the "Go!" button to start it again.
![image](https://user-images.githubusercontent.com/17010632/196902638-2146db8e-415b-4151-b88e-c11fcb9d8af9.png)

I hope this was fun, and if that solves the case of them not changing color, then feel free to close this issue! Cheers

**Closed** 2022-10-21 11:56 UTC
Labels: FTB Presents Stoneblock 2, 3: Support Request
