### ISSUE TITLE
[Bug]: Random crashes in Inferno

### ISSUE THREAD

**Issue by razgriz5000** [FTBTeam/FTB-Modpack-Issues#1407] opened 2022-10-09 01:39 UTC
### Modpack

FTB Inferno

### Modpack version

1.0.2

### Log Files

[2022-10-08-4.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9740563/2022-10-08-4.log.gz)
[2022-10-08-3.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9740568/2022-10-08-3.log.gz)
[2022-10-08-2.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9740569/2022-10-08-2.log.gz)
[2022-10-08-1.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9740570/2022-10-08-1.log.gz)

### Describe the bug

Misc crashes to desktop.  

### Steps to reproduce

Game has crashed when transversing the nether, interacting with chest, interacting with storage drawers.  

### Expected behaviour

game not to crash

**Comment by Raidobw2** [comment] 2022-10-10 01:13
Please see https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1357 and let me know if that sounds like the issue. Also, you can attach your crash logs from the `crash-reports` folder instead of the `logs` folder, unfortunately the current logs don't print the full crash. Thanks!

**Comment by razgriz5000** [comment] 2022-10-10 03:58
Requested crash logs + plus a new one that was created by flying around with creative mode.  That bug seems similar.  

Trying the patch that @MichaelHillcox posted on #1357

GDLauncher's java.  17.0.1+12
only video setting changed is max fps to 145.  gui scale to 3x.
FOV of 80
RTX 2080 Super. 

[crash-2022-10-08_15.25.50-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9743218/crash-2022-10-08_15.25.50-client.txt)
[crash-2022-10-08_17.02.35-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9743219/crash-2022-10-08_17.02.35-client.txt)
[crash-2022-10-08_21.00.19-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9743220/crash-2022-10-08_21.00.19-client.txt)
[crash-2022-10-08_21.30.13-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9743221/crash-2022-10-08_21.30.13-client.txt)
[crash-2022-10-09_11.56.22-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9743222/crash-2022-10-09_11.56.22-client.txt)
[crash-2022-10-09_17.46.15-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9743223/crash-2022-10-09_17.46.15-client.txt)
[crash-2022-10-09_23.37.57-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9743247/crash-2022-10-09_23.37.57-client.txt)

**Comment by Saereth** [comment] 2022-10-10 20:35
this is duplicate of the pinned issue and should be sorted with Mikey's patch, re-open if you get anymore of the sodium crashes with his patch

**Closed by Saereth** 2022-10-10 20:35 UTC
Labels: 3: Support Request, FTB Inferno
