### ISSUE TITLE
Modpacks crashing in loading phase

### ISSUE THREAD

**Issue by Mootze** [FTBTeam/FTB-Modpack-Issues#1698] opened 2022-11-06 20:33 UTC
### Modpack

all 1.18+ modpacks

### Modpack version

All

### Log Files

[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9946778/console.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9946779/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9946780/latest.log)

### Describe the bug

Whenever i click play on a 1.18+ modpack it crashes at one speciffic point every time i start it

### Steps to reproduce

1. open the ftb app
2. click on a 1.18 modpack
3. click play
4. wait a few seconds

### Expected behaviour

I expected the modpacks to launch properly

### Screenshots

![image](https://user-images.githubusercontent.com/117600419/200193571-fa4b2323-25e7-4857-8177-2965bd353c16.png)

**Comment by Raidobw2** [comment] 2022-11-07 11:46
Does a modpack like FTB Chocolate do this as well? What happens if you remove kubejs-ui/all kubejs mods from the mods? Make sure to post your logs on FTB Chocolate or other packs as well so we can compare... The current logs abruptly stop without errors. Thanks

**Comment by Mootze** [comment] 2022-11-07 12:55
I tried running FTB chocolate where I deleted the kubejs folder and all the kubejs mod. I also tried running ftb inferno, they both didn't work
FTB Chocolate without  kubejs :
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9951764/latest.log)
FTB Inferno:
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9951767/latest.log)

**Comment by Sunekaer** [comment] 2022-11-07 17:40
Hmm how much ram do you have assigned to the pack?

**Comment by Mootze** [comment] 2022-11-07 19:47
I have tried both 6GB,, 8GB and 10GB, none of them work

**Comment by gimemy2bucksback** [comment] 2022-11-07 21:58
@Mootze 
Looks like there could be something wrong with setting your user/loading client.

    _[Render thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: 
    [Render thread/INFO] [net.minecraft.client.Minecraft/]: Backend library: LWJGL version 3.2.2 SNAPSHOT
    [Render thread/INFO] [KubeJS/]: Loaded client.properties_



See if modpacks work on a different launcher. If not then its probably something to do with Java. Can also try this

1.  Go to "C:\Users\USER\curseforge\minecraft\Install\versions"
2.  Delete the 1.12.2 or whatever Version folder.
3.  Reinstall Pack

Here is the path to what its hangning on, but im not sure what could be wrong with it.
**%AppData%\Local\.ftba\instances\73bab484-5ed1-42e8-8ef0-04fe19458c4f\kubejs\config**
^Has client.properties

Regardless reinstalling Java and  minecraft isnt a bad idea. Looks like a problem with Java though.

@onura46 Have you tried reinstalling mc and Java?

**Comment by Raidobw2** [comment] 2022-11-08 03:30
Can you navigate to `c:\Windows\System32\Drivers\etc` and open the `hosts` file with Notepad? Delete any lines no starting with `#`, then save the file.

Then, make sure any VPNs are turned off. If you have Hamachi, uninstall it, it adds another network adapter that causes issues.

If you have an antivirus/firewall, you could deactivate it only while the pack is initially launching to see if that's the issue.

Then in FTB Chocolate, open the modpack files and delete `options.txt`.

Then put `-Duser.language=en -Duser.country=US` in the additional java arguments in the FTB App.

And finally start the game... Let me know if any of that works

**Comment by onura46** [comment] 2022-11-08 19:55
I'm not sure what happened, but after a reboot I can't currently reproduce this bug. I didn't make any other changes. Loading continues as expected and the game boots normally. I should note that I tried rebooting at another point and was still running into the bug. I'm sensing it might have something to do with Java weirdness. I don't run many other programs; no VPNs or 3rd party firewalls. But I _do_ have Java SDKs and stuff like that installed for light dev work. I'll continue testing to see if I can narrow it down more.

**Comment by Raidobw2** [comment] 2022-11-10 09:27
@Mootze Could you try to delete the file at `kubejs/config/defaultoptions.txt` as well as the file `options.txt` (on the root of the modpack folder)?
Then start FTB Chocolate and let me know, looks like there's an error loading the options, somehow, for the left alt key:
```
[08Nov2022 15:26:01.568] [Render thread/ERROR] [net.minecraft.client.Options/]: Failed to load options
java.lang.NumberFormatException: For input string: "key.keyboard.left.alt"
	at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:?]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:?]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:?]
	at net.minecraft.util.datafix.fixes.OptionsKeyLwjgl3Fix.m_145579_(OptionsKeyLwjgl3Fix.java:162) ~[client-1.18.2-20220404.173914-srg.jar%23190!/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
```

**Comment by Raidobw2** [comment] 2022-11-13 07:29
I see, I'm not sure what the issue is in that case, I'm running out of suggestions... If you remove all mods from the `mods` folder, does the game launch?

**Comment by Mootze** [comment] 2022-11-15 01:04
no, it does not, still ends at loading phase
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10008200/latest.log)

**Comment by Sunekaer** [comment] 2022-11-17 13:19
Can you provide the debug.log?

**Comment by Mootze** [comment] 2022-11-22 00:50
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10061606/debug.log)

**Comment by Raidobw2** [comment] 2022-12-02 12:08
Sorry been mostly unavailable these past days... This issue is a really tough problem, I've spoken with Sunekaer more about it but we haven't got any clue... The pack is basically running no mods and only Forge, so I'm a bit clueless why it still errors out. Especially how you mentioned Prism Launcher works Offline, but not Online...

If you try with the recommended Java (17.0.2) instead of Java 17.0.5, do you get any difference? Of course do this with the `mods` folder emptied, that's quicker to test. The last lines of your debug log are a tiny bit different to mine.

Also about my comment at https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1698#issuecomment-1306579445, just wanted to confirm you tried checking the hosts file and adding the java argument in the FTB App? You add the argument in the settings of the modpack.
Thanks for letting me know and sorry again for the delays!

------------------

## Advanced troubleshooting if you have time:
1. Empty the `mods` folder
2. Delete the `config` folder completely of the StoneBlock 3 instance
3. Install Forge manually from the Forge site, follow this procedure: https://feedthebeast.notion.site/Installing-Forge-for-Windows-448dee0e8ab74c78b56f444bdc45cd85
4. Hit Play, see if it works after that
5. In the [FTB Discord](https://go.ftb.team/discord), type "`!ftbdebug`" in the `#ftb-app-support` channel and use the debug tool the FTB Bot will link there to generate a code. You can post the code here, the tool uploads game and app logs, and I'm starting to sense an app problem if you get here.
6. Open Task Manager and close as much programs as you can that you don't need to play a FTB modpack (especially networking ones or service programs that "enhance" connectivity/your computer", other game launchers, etc).
7. Try playing SB3 again, see if that worked
8. I'm running out of ideas, I'll need your feedback to continue!

**Comment by Mootze** [comment] 2022-12-02 16:44
I tried running SB3 on both 17.0.5 and 17.0.2, same results

I did do the things you commented 
![image](https://user-images.githubusercontent.com/117600419/205342265-81199c1b-2899-4e79-bf84-741ab7a937d0.png)
![image](https://user-images.githubusercontent.com/117600419/205342380-00488a29-de91-49fc-bf8a-e853e6bd25f0.png)

Code from debugging tool
FTB-DBGUFIMAZUBEZ

I tried launching SB3 on prismlauncher and i got to here, it might have been because of low ram allocated
![Skjermbilde_20221202_161354](https://user-images.githubusercontent.com/117600419/205340979-c87235ad-ff11-4add-81af-8a40b1340338.png)
When following the procedure for manually installing forge i couldn't install it because it was missing a launcher profile, even though i followed the correct path, this looks to be a big issue
![Skjermbilde_20221202_164804](https://user-images.githubusercontent.com/117600419/205341000-1dc9cc07-11b6-408a-bba8-e6275492cc28.png)

**Comment by Raidobw2** [comment] 2022-12-19 01:10
Interesting, I've looked at the debug and seeing this error message: `[13:57:12] [Render thread/ERROR] [minecraft/Minecraft]: Failed to verify authentication
com.mojang.authlib.exceptions.AuthenticationException: com.mojang.authlib.exceptions.MinecraftClientException: Failed to read from https://api.minecraftservices.com/player/attributes due to Connect timed out`

It looks like your machine is unable to access "https://api.minecraftservices.com/player/attributes". That error coincides exactly with where your game stops loading, and the online/offline thing could make sense.

The things I can think of that would prevent your machine from reaching that address would be antivirus or some network configuration. Do you have the possibility to try with another Internet network (through Wifi, a hotspot, etc)?

Also, the FTB App allows playing offline now, so you could try that as a test as well. If you disconnect from Wifi or unplug the Ethernet cable (network cable) when you're about to hit "Play" on the FTB App, it should prompt you to play offline. If that works, then we might be onto something.

Also, sorry again for the late reply... Been busy with university, but now I'm much more available. Feel free to `@` me in your replies so I can see this quicker

**Comment by Mootze** [comment] 2023-01-05 13:26
I have tried 4 different wifi internet networks, I get the same error on all of them

I get this error when trying to launch offline through the ftb app
![image](https://user-images.githubusercontent.com/117600419/210790449-c3378877-5a32-4905-9074-44f3b2bb1b1f.png)

Also sorry for the late reply, I have had a busy Christmas

**Comment by Raidobw2** [comment] 2023-01-26 06:52
Hi @Mootze, I've been mostly unavailable recently as well, I apologize. It seems I might be unable to properly help you fix this into the FTB App... This is the toughest issue I've had so far, it's rare I can't figure problems out.

I've spoken with the devs during the holidays and they wanted to rework websockets used by the FTB App, which could solve issues like you're having.

Since I'd like to get your game working still so that you can enjoy the modpacks, contact me with a ping on the [FTB Discord](https://go.ftb.team/discord), my username is `@R3GEN` (same profile picture) and we'll work something out for you so that you can play. Hopefully I can learn you some basic instance setup knowledge so that you're not left with issues like these in the future, even if the modpacks aren't from us.

I'll be waiting for your contact and thanks a lot for your multiple efforts troubleshooting this issue and your patience

**Closed** 2023-04-09 13:21 UTC
Labels: 3: Support Request, FTB StoneBlock 3
