### ISSUE TITLE
[Bug]: MultiMC breaks stoneblock 2

### ISSUE THREAD

**Issue by emir4169** [FTBTeam/FTB-Modpack-Issues#1459] opened 2022-10-18 15:31 UTC
### Modpack

FTB presents STONEBLOCK 2

### Modpack version

1.22.0

### Log Files

https://paste.ee/p/YUuIb

### Describe the bug

The game doesnt launch with the error code -1

### Steps to reproduce

1. Go on multimc
2. Import the modpack
3. launch
4. profit with a error

### Expected behaviour

The game launches

**Comment by Raidobw2** [comment] 2022-10-20 09:05
Hi, you need to use Java 8 instead of Java 19 to play StoneBlock 2. If you want to keep it simple the FTB App already takes care of selecting the right java version for each modpack, meaning StoneBlock 2 on the FTB App uses Java 8 by default.

Please close this issue if the problem is solved after using Java 8

**Closed** 2024-06-04 07:17 UTC
Labels: FTB Presents Stoneblock 2
