### ISSUE TITLE
Single Player / Multiplayer Server crash on Pedestal placement

### ISSUE THREAD

**Issue by MrGcGamer** [FTBTeam/FTB-Modpack-Issues#4965] opened 2024-03-14 12:33 UTC
### Modpack

FTB Skies Expert

### Modpack version

1.4.1

### Log Files

https://paste.ee/p/pIZ0H

### Describe the bug

The (internal) Server crashes, when the pedestal (as shown in the video) is placed for some reason.

### Steps to reproduce

1. Replace the pedestal

### Expected behaviour

Server not crashing

### Screenshots

https://cdn.discordapp.com/attachments/1208057038438006865/1217806839954018324/Screen_Recording_2024-03-14_at_13.01.29.mp4?ex=66055e00&is=65f2e900&hm=aae6d5f71d4462d61b0ea070cd802a9dc1ee990b229d997f9c40955d252f34fb&

^Video of the Problem

### Additional information

I was unable to reproduce this in a new single player world, but it crashes our server and trying the same with a world download in single player also crashes the internal server

**Comment by Saereth** [comment] 2024-03-15 20:39
I also cant reproduce this but the logs may be useful to mowmaster, I'll link the issue to him.

**Comment by Mowmaster** [comment] 2024-03-15 20:55
is there any way you could get a world download to me? you can IM me on discord, or email me a drop/mega link if necessary (mowmaster@outlook.com)

Ive been unable to reproduce this issue as well, if it seems to be world specific, that might be why.

**Comment by Mowmaster** [comment] 2024-03-15 20:58
We've also had a similar server crash with fluid packages, as you also have one in your inventory, im wondering if its due to the fluid package and not the block placement.

**Comment by Mowmaster** [comment] 2024-03-15 20:58
im guessing the fluid in the package is milk?

**Comment by MrGcGamer** [comment] 2024-03-15 23:51
The fluid is indeed milk.
I will send you the world on Discord

**Comment by Atherum** [comment] 2024-03-29 07:14
Bumping this as well. I'm having the same issue while using pedestals to move milk around. Breaking a pedestal to move it while it has the milk inside is causing the game to crash, likely due to the bulk fluid item.

**Comment by Saereth** [comment] 2024-03-29 16:16
this has been reported to the dev, I'd suggest not using pedestals for moving around milk presently until it can be fixed, we have 3 other issues open about this so closing this one to consolidate.

**Closed by Saereth** 2024-03-29 16:16 UTC
Labels: 1: Mod Issue, state: Duplicate :books:, FTB Skies Expert
