### ISSUE TITLE
Game crashes when hovering over 2nd schematic in Tetra section 

### ISSUE THREAD

**Issue by AshtrayDev** [FTBTeam/FTB-Modpack-Issues#3837] opened 2023-08-23 17:12 UTC
### Modpack

FTB University 1.19

### Modpack version

1.0.0

### Log Files

[crash-2023-08-23_18.08.38-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12421697/crash-2023-08-23_18.08.38-client.txt)

### Describe the bug

In the Tetra section in the Quest Book, there is a quest called Schematics. Hovering your mouse over the tasks crash the game.  

### Steps to reproduce

1. Go to quest book
2. Find Tetra section
3. Click on Schematics quest
4. Hover the 2nd task/item

### Expected behaviour

Item name should show instead of a crash

**Comment by aaronhowser1** [comment] 2023-08-24 09:38
Duplicate of #3826

**Closed by aaronhowser1** 2023-08-24 09:38 UTC
Labels: FTB University 1.19
