### ISSUE TITLE
[Bug]: Server keeps crashing after setting up a sluice linked to a item pipe and black hole unit

### ISSUE THREAD

**Issue by NunbearTWITCH** [FTBTeam/FTB-Modpack-Issues#38] opened 2021-09-28 19:45 UTC
### Modpack

FTB Oceanblock

### Modpack version

1.1.0

### Log Files

[crash-2021-09-28_16.18.19-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7246856/crash-2021-09-28_16.18.19-server.txt)

### Describe the bug

unable to get the server working since setting up a diamond sluice linked to a pipez item pipe and a black hole unit with sand in it.

### Steps to reproduce

cant do steps

### Expected behaviour

server not to crash

**Comment by NunbearTWITCH** [comment] 2021-09-28 19:47
server is on shockbyte installed using their installer fresh install

**Comment by Raidobw2** [comment] 2021-09-28 23:18
This is a crash caused by the server watchdog. More information about it is found on a bug report from Mojang at: https://bugs.mojang.com/browse/MC-63590. The watchdog thread keeps watch of the game and shuts it down if it notices lag. This can be useful on large servers and on good hardware to quickly detect hardware issues and prevent downtimes.

However, on hosts with budget plans, you are prone to have occasionnal lag due to hardware not being fully dedicated. The watchdog can then mistake this lag as hardware issues and close the server.
Setting `max-time-time=-1` in `server.properties` will disable the watchdog thread and solve this issue.

Afterwards, give your server a few seconds to load in, and verify the lag with `/forge tps` in-game. TPS should be 20.0 and the "ms" needs to be under 50 to be considered not laggy.

Please do the above and close the ticket if this solved the issue for you, i do not think this is related to the code of the FTB Sluice mod. Have a good day!

**Comment by NunbearTWITCH** [comment] 2021-09-29 07:03
That has not helped and still keeps crashing, I took a copy of the world over into a single player game and that crashed the game as well as soon as it loaded up (the whole game closed).

This is not a budget server and has been used for months with no issues on larger packs.

[crash report from single playert.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7249552/crash.report.from.single.playert.txt)
[crash report from server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7249554/crash.report.from.server.txt)

**Comment by Jake-E** [comment] 2021-09-29 08:39
This is the same issue as #4 and has been fixed in dev.

**Closed by Jake-E** 2021-09-29 08:39 UTC
Labels: FTB OceanBlock, State: Duplicate :books:
