### ISSUE TITLE
[Bug]: [FTB Stoneblock1.3.0] ME Pattern Encoding Terminal does not put in items in Processing Patterns

### ISSUE THREAD

**Issue by LuciusV** [FTBTeam/FTB-Modpack-Issues#2079] opened 2022-11-21 06:29 UTC
### Modpack

FTB Stoneblock

### Modpack version

1.3.0

### Describe the bug

When I use  ME Pattern Encoding Terminal to create processing recipe, using "+" encode pattern in REI UI does not move items to pattern grid. I had to drag all items manually in order to complete a pattern.
Meanwhile, fluids work normally and are placed into encoded pattern.

### Steps to reproduce

1. Setup ME autocrafting system with item processing 
2. Put pattern in ME Pattern Encoding Terminal 
3. Open target recipe in REI and press "+"
4. Items do not appear in encode pattern UI

### Expected behaviour

 Items should appear in encode pattern UI

### Screenshots

![2022-11-21_14 26 57](https://user-images.githubusercontent.com/11925386/202980555-0af2df30-01a2-42da-94d9-ffe360340ee8.png)
![2022-11-21_14 27 07](https://user-images.githubusercontent.com/11925386/202980559-1402b2c1-9e92-48f6-8f4b-70890d0fb325.png)

**Comment by Sunekaer** [comment] 2022-11-22 10:27
duplicate of #1800

**Closed by Sunekaer** 2022-11-22 10:27 UTC
