### ISSUE TITLE
Restoring from backup after dying from radiation, I am still dead and radiation is still present

### ISSUE THREAD

**Issue by jamie-jshunter** [FTBTeam/FTB-Modpack-Issues#5915] opened 2024-10-06 20:45 UTC
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.2.1

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

My Mekanism Fission Reactor blew up (didn't know it could do that - still learning).  I thought I'd restore from backup and not make the same mistakes.  However, on restoring from several previous backups I was saddened to see I was still dead and radiation is still everywhere.

Edit: missed the key issue - after respawning I always die before escaping the radiation, seems to be a pretty terminal end to the game (without resorting to cheats).

### Steps to reproduce

1. backup world
2. build fission reactor
3. let it explode
4. respawn, radiation is everywhere
5. quit
6. restore from backup
7. ...still dead and radiation is still present

### Expected behaviour

backup should restore the state to the exact position of everything as it was when the backup completes.

**Comment by jamie-jshunter** [comment] 2024-10-07 08:36
@Gaz492 I used the "Restore" option from the World backups in the FTB Launcher.  I don't know what's its doing behind the scenes.

**Comment by Gaz492** [comment] 2024-10-07 09:38
Ok, could you try the following?

1. Right click the modpack you want to restore the backup on in the app, then hover over `Open folder` and then click on `Instance Folder`
2. In the window that opens, open the backups folder
3. Extract/unzip the backup you would like to restore
4. Depending on how the backup was extracted, you may see a folder named the same as the backup file was or one named saves.
5. Open the folder that was extracted, you should now see a folder named the same as your world.
6. Right click the folder thats the same name as your world and select copy.
7. Go back out of the backups folder and now open the saves folder
8. Rename your nuked world to something such as `nuked_world`
9. Paste the folder we copied earlier
10. Start minecraft and see if the restore worked.

**Comment by jamie-jshunter** [comment] 2024-10-07 09:52
Brilliant, @Gaz492, thanks for the clear instructions.  This has resolved my issue. 

Is there a bug in the FTB restore functionality, should this bug remain open?

**Comment by Gaz492** [comment] 2024-10-07 09:53
Fantastic, It looks like the restore feature in the app is not working correctly as I was able to reproduce this.
I will close this issue and make a new issue on the app issue tracker we have.

**Closed by Gaz492** 2024-10-07 09:53 UTC
Labels: Bug, FTB Presents Direwolf20 1.21

**Comment by Eyelikegiants** [comment] 2026-04-06 16:44
Wish it worked for me. Whole reason I got this mod.
