### ISSUE TITLE
[Bug]: Auto Smithing Table + Hopper Ticking block entity

### ISSUE THREAD

**Issue by MisterSoandSo** [FTBTeam/FTB-Modpack-Issues#1766] opened 2022-11-08 16:39 UTC
### Modpack

Stoneblock 3

### Modpack version

1.1.0

### Log Files

https://pste.ch/uzoxagodez.pl

### Describe the bug

Autosmithing causing hoppers to error tick to the point where the server will crash when the player loads the dimension/area where the entity error occurred. I don't know if this is similar issue like #1723 but based on the OP of the post they just placed it down and nothing else. I'ved included a copy of the affected [region file](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9963273/r.-1.0.zip)

### Steps to reproduce

Place down an autosmithing table.
Place a hopper on the side of the table.
Server goes poof ...

### Expected behaviour

To not entity tick the hopper to the point where it kills the server when someone logs into the affected dimension

**Comment by Sunekaer** [comment] 2022-11-08 17:03
duplicate of #1723

**Closed by Sunekaer** 2022-11-08 17:03 UTC
