### ISSUE TITLE
[Bug]: Bellringer wave mobs spawn at world bottom instead of at portal

### ISSUE THREAD

**Issue by orbidlo** [FTBTeam/FTB-Modpack-Issues#1858] opened 2022-11-11 11:14 UTC
### Modpack

FTB Inferno

### Modpack version

1.3.0

### Describe the bug

During Bellringer fight, mobs keep spawning at the bottom of the world at y=0 which prevents them to be killed.

### Steps to reproduce

1. Summon Bellringer
2. Mobs from wave spawn at the bottom of world 
3. Fail the wave

### Expected behaviour

Mobs spawn close to portal

### Additional information

Reported on Discord by two people.
https://discord.com/channels/372448486723158016/1024733922745122897/1040491713673838663
https://discord.com/channels/372448486723158016/1024733922745122897/1040578582780596254

**Comment by Carlton-Perkins** [comment] 2022-11-13 19:51
For anyone who finds this prior to there being an official pack update issues, you can mitigate the issue by manually updating the mod `GatewaysToEternity` to version 2.2.0 (from 2.1.5 with ftbinferno 1.3.0)

[Mod](https://www.curseforge.com/minecraft/mc-mods/gateways-to-eternity)

[Ref](https://discord.com/channels/372448486723158016/1024733922745122897/1041413452570304632)

**Comment by ztk4** [comment] 2023-01-16 08:00
In case anyone else is playing with a dedicated server which crashes on the 1.4.0 build (https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2510), you can patch the 1.3.0 client + server in a way that doesn't skip the invasion delay:

Make the following changes to both your client and your server:
  1. In the mods/ directory, replace `GatewaysToEternity-1.18.2-2.1.5.jar` with `GatewaysToEternity-1.18.2-2.2.1.jar` (either from the 1.4.0 pack, or from https://www.curseforge.com/minecraft/mc-mods/gateways-to-eternity/files)
  2. Update kubejs/server_scripts/invasion.js to have 1200 instead of 600 as the `scheduleInTicks` delay.

AFAICT step 2. is just backporting a fix in 1.4.0 for making the invasion delay 1 minutes (as was intended) rather than 30 seconds... BUT considering that it was reported the delay was broken after updating, I figured I'd port this 1.4.0 change to help guarantee that the delay was WAI.

In my testing, this resulted in mobs _mostly_ spawning at the correct y-level from gates, and invasions did take a full minute to start once announced. That said, I still had 1 mob from my invasion spawn below the bedrock ceiling and I was unable to find and kill it in time. :(

**Comment by Saereth** [comment] 2023-01-18 22:14
This should be fixed in 1.5.0

**Closed** 2023-01-18 22:31 UTC
Labels: state: Fixed in Dev :hammer_and_wrench:, FTB Inferno
