### ISSUE TITLE
[Bug]: Redundant copper ore generation

### ISSUE THREAD

**Issue by LuciusV** [FTBTeam/FTB-Modpack-Issues#338] opened 2021-11-19 04:24 UTC
### Modpack

FTB Endeavour

### Modpack version

1.6.0

### Describe the bug

Both Immersive Engineering and Thermal expansion ores generate in world

### Steps to reproduce

Just create a world

### Expected behaviour

Expect only one kind of every ore type generated

**Comment by LuciusV** [comment] 2021-11-19 08:30
Sorry I forgot to mention it was copper

**Comment by Raidobw2** [comment] 2022-01-06 12:59
Appears to have been fixed in an earlier version of the modpack -- I can't reproduce in newly generated chunks.

**Closed by Raidobw2** 2022-01-06 12:59 UTC
Labels: FTB Endeavour, state: Fixed :heavy_check_mark:, 1: Configuration
