### ISSUE TITLE
EMC Bug

### ISSUE THREAD

**Issue by Mental-Cube** [FTBTeam/FTB-Modpack-Issues#2303] opened 2022-12-11 11:19 UTC
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.3

### Describe the bug

Good day i have an issue with the compressed EMC link in the pack some items don't want to extra properly but tested with EMC tablet works perfectly so if I downgrade my pack to 1.3.0 the EMC generation and the compressed EMC link also works correctly.,

### Steps to reproduce

1. Spawn in some form of EMC generation (fading power flower Mk 15)
2.  Now spawn in compressed EMC link can configure it with a fading power flower MK 15
3. now if you try to pull one or even a stack from that compressed EMC link it does not allow you to
4. and so are there many other items that do this.

### Expected behaviour

You cant pull the items even thow you have the emc for it

**Comment by Mental-Cube** [comment] 2022-12-20 09:26
are people even seeing my report?

**Comment by MaxNeedsSnacks** [comment] 2022-12-20 13:08
Duplicate of #2119, this is pending a config change in an upcoming Stoneblock 3 update

**Closed by MaxNeedsSnacks** 2022-12-20 13:08 UTC
Labels: FTB StoneBlock 3
