### ISSUE TITLE
[Bug]: LaserIO Energy Cards Not Pulling Energy from Pipez or Mekanism Energy Pipes/Cables

### ISSUE THREAD

**Issue by JRizzle** [FTBTeam/FTB-Modpack-Issues#1065] opened 2022-07-04 04:43 UTC
### Modpack

FTB Presents DireWolf20 1.18

### Modpack version

1.6.1

### Describe the bug

LaserIO Energy cards are not pulling Energy from either Pipez or Mekanism Energy pipes/cables. 

### Steps to reproduce

1. Setup a Mekanism machine with Energy to be Input from the back.
2. Put LaserIO node behind the machine with an Energy card in the side facing the machine and set to insert.
3. Put a Pipez Energy pipe or Mekanism pipe that has FE power on another side of the Laser Node.
4. Put an Energy card in the side of the Laser Node facing the pipe and set to extract. 
5. Notice how no energy is making it to the machine

### Expected behaviour

Energy should be pulled from the pipes using the Laser Node and machine should fill up with power. 

### Screenshots

![image](https://user-images.githubusercontent.com/3836233/177081996-17d08f7f-4d44-41c7-9eea-e50b304c4b00.png)

![image](https://user-images.githubusercontent.com/3836233/177082248-4cd5fcd9-a3f4-41c1-a330-619e32c081e8.png)

![image](https://user-images.githubusercontent.com/3836233/177082932-4d4e7193-7bfb-4767-9849-93fe6c6e00bd.png)

### Additional information

When trying to use Pipez, the energy laser doesn't render which DireWolf20 pointed out in episode 47 of his 1.18 LP Series, but in this case energy is also not flowing. When using Mekanism Energy cable, the energy laser does render, but still energy doesn't flow to the machine. The machines in question were Mekanism machines and their config was set to insert energy from the back. Other spots were tried as well, but also did not work. It seems that the pipes/cable don't see laser io node as a valid connection point as shown in screen shot. In DireWolf20's LP Series, the Pipez he used looks like the linked up to the laser node, but not in this case.

**Comment by TheonlyTazz** [comment] 2022-07-05 12:45
![image](https://user-images.githubusercontent.com/3908847/177330395-46d594a7-4fce-498c-a30b-d1425d35ae05.png)
Fixed in LaserIO 1.3.1 which gets added in the next update (v1.7.0)
The visual effect is caused by Tempad, needs to disable fancydoor in the tempad client config (also implemented in the V1.7.0 version)

**Closed** 2022-07-07 19:15 UTC
Labels: 1: Mod Issue, state: Fixed in Dev :hammer_and_wrench:, FTB Presents Direwolf20 1.18
