### ISSUE TITLE
[Bug]: Cyclic and Brutal Bosses make the world hang at 98% when loading

### ISSUE THREAD

**Issue by 5ully** [FTBTeam/FTB-Modpack-Issues#1242] opened 2022-08-09 18:58 UTC
### Modpack

DW20 1.18.2

### Modpack version

1.9.0

### Log Files

[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9293842/debug.log)

### Describe the bug

Starting up a server on the latest 1.9.0 without creating a world in SP causes the launcher to get stuck at Preparing spawn area: 97% or 98%

### Steps to reproduce

1. Download server files for 1.9.0
2. Start the launcher after fixing the "jre" issue by replacing the "/"
3. Wait
4. Look at server log.

### Expected behaviour

To generate a world and a spawn area and start the server successfully

### Additional information

Waited for up to 20 min on 2 tries, ive seen other people also have this issue and was following up a message from discord.

**Comment by TheonlyTazz** [comment] 2022-08-10 05:25
This is very strange, as i had tested this before releasing.
I installed a 1.8.0 Server, updated the mods, configs, kubejs folder, forge etc. and ran it for the first time, creating a world, this worked flawlessly

now with the released version of 1.9.0, creating a new world is also broken.

**Comment by ymjstevens** [comment] 2022-08-10 22:08
I noticed a similar issue since updating, where random chunks will cause the server to timeout as players explore unrendered areas.

**Comment by Raidobw2** [comment] 2022-08-11 04:43
Seems to be caused by a weird interaction between Cyclic and Brutal Bosses. Maybe some Brutal Boss has a potion effect and Cyclic mixes into those functions and issues stuff to find Anti Beacons? Which seems to be blocking world load... If I remove Cyclic, the world creation goes through successfully for me.

Got that info from doing a `jstack PID` with the Java process, which just dumps the threads. Then usually the issue is on the server thread:
```
"Server thread" #99 prio=8 os_prio=1 cpu=3031.25ms elapsed=76.70s tid=0x0000018c3854a380 nid=0x4770 runnable  [0x00000079cf0fd000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@17.0.2/Native Method)
        - parking to wait for  <0x00000006c4200170> (a java.lang.String)
        at java.util.concurrent.locks.LockSupport.parkNanos(java.base@17.0.2/Unknown Source)
        at net.minecraft.util.thread.BlockableEventLoop.m_5667_(minecraft@1.18.2/BlockableEventLoop.java:152)
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(minecraft@1.18.2/BlockableEventLoop.java:142)
        at net.minecraft.server.level.ServerChunkCache.m_7587_(minecraft@1.18.2/ServerChunkCache.java:129)
        at net.minecraft.world.level.Level.m_6522_(minecraft@1.18.2/Level.java:169)
        at net.minecraft.world.level.LevelReader.m_46819_(minecraft@1.18.2/LevelReader.java:123)
        at net.minecraft.world.level.Level.m_6325_(minecraft@1.18.2/Level.java:164)
        at net.minecraft.world.level.Level.m_8055_(minecraft@1.18.2/Level.java:390)
        at com.lothrazar.cyclic.util.BlockstatesUtil.findBlocks(cyclic@1.18.2-1.7.6/BlockstatesUtil.java:41)
        at com.lothrazar.cyclic.block.antipotion.BlockAntiBeacon.isPotionApplicable(cyclic@1.18.2-1.7.6/BlockAntiBeacon.java:114)
        at com.lothrazar.cyclic.event.PotionEvents.isPotionApplicable(cyclic@1.18.2-1.7.6/PotionEvents.java:25)
        at net.minecraftforge.eventbus.ASMEventHandler_1672_PotionEvents_isPotionApplicable_PotionApplicableEvent.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(eventbus@5.0.3/ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus$$Lambda$4543/0x0000000801824cf8.invoke(eventbus@5.0.3/Unknown Source)
        at net.minecraftforge.eventbus.EventBus.post(eventbus@5.0.3/EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(eventbus@5.0.3/EventBus.java:283)
        at net.minecraft.world.entity.LivingEntity.m_7301_(minecraft@1.18.2/LivingEntity.java:908)
        at net.minecraft.world.entity.LivingEntity.m_147207_(minecraft@1.18.2/LivingEntity.java:888)
        at net.minecraft.world.entity.LivingEntity.m_7292_(minecraft@1.18.2/LivingEntity.java:884)
        at com.brutalbosses.entity.BossType.initStats(brutalbosses@1.18.2-5.4/BossType.java:189)
        at com.brutalbosses.entity.BossType.initForEntity(brutalbosses@1.18.2-5.4/BossType.java:133)
        at com.brutalbosses.entity.capability.BossCapability.deserializeNBT(brutalbosses@1.18.2-5.4/BossCapability.java:132)
        at net.minecraftforge.common.capabilities.CapabilityDispatcher.deserializeNBT(forge@40.1.69/CapabilityDispatcher.java:127)
        at net.minecraftforge.common.capabilities.CapabilityProvider.deserializeCaps(forge@40.1.69/CapabilityProvider.java:148)
        at net.minecraft.world.entity.Entity.m_20258_(minecraft@1.18.2/Entity.java:1570)
        at net.minecraft.world.entity.EntityType.m_185988_(minecraft@1.18.2/EntityType.java:472)
        at net.minecraft.world.entity.EntityType$$Lambda$35032/0x000000080479ce10.accept(minecraft@1.18.2/Unknown Source)
        at net.minecraft.Util.m_137521_(minecraft@1.18.2/Util.java:395)
        at net.minecraft.world.entity.EntityType.m_20642_(minecraft@1.18.2/EntityType.java:469)
        at net.minecraft.world.entity.EntityType.m_20669_(minecraft@1.18.2/EntityType.java:552)
        at net.minecraft.world.entity.EntityType.m_20645_(minecraft@1.18.2/EntityType.java:508)
        at net.minecraft.world.entity.EntityType$1.m_147056_(minecraft@1.18.2/EntityType.java:529)
        at net.minecraft.world.entity.EntityType$1$$Lambda$35029/0x000000080479c760.accept(minecraft@1.18.2/Unknown Source)
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(java.base@17.0.2/Unknown Source)
        at net.minecraft.world.entity.EntityType$1.tryAdvance(minecraft@1.18.2/EntityType.java:528)
        at java.util.Spliterator.forEachRemaining(java.base@17.0.2/Unknown Source)
        at java.util.stream.ReferencePipeline$Head.forEach(java.base@17.0.2/Unknown Source)
        at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157559_(minecraft@1.18.2/PersistentEntitySectionManager.java:121)
        at net.minecraft.server.level.ServerLevel.m_143327_(minecraft@1.18.2/ServerLevel.java:1507)
        at net.minecraft.server.level.ChunkMap.m_143064_(minecraft@1.18.2/ChunkMap.java:634)
        at net.minecraft.server.level.ChunkMap.m_203035_(minecraft@1.18.2/ChunkMap.java:651)
        at net.minecraft.server.level.ChunkMap$$Lambda$34905/0x000000080476ebe8.m_196866_(minecraft@1.18.2/Unknown Source)
        at net.minecraft.world.level.chunk.LevelChunk.m_62952_(minecraft@1.18.2/LevelChunk.java:417)
        at net.minecraft.server.level.ChunkMap.m_202988_(minecraft@1.18.2/ChunkMap.java:659)
        at net.minecraft.server.level.ChunkMap$$Lambda$34904/0x000000080476e170.apply(minecraft@1.18.2/Unknown Source)
        at com.mojang.datafixers.util.Either.lambda$mapLeft$0(datafixerupper@4.1.27/Either.java:162)
        at com.mojang.datafixers.util.Either$$Lambda$34659/0x000000080472bbc8.apply(datafixerupper@4.1.27/Unknown Source)
        at com.mojang.datafixers.util.Either$Left.map(datafixerupper@4.1.27/Either.java:38)
        at com.mojang.datafixers.util.Either.mapLeft(datafixerupper@4.1.27/Either.java:162)
        at net.minecraft.server.level.ChunkMap.m_202985_(minecraft@1.18.2/ChunkMap.java:643)
        at net.minecraft.server.level.ChunkMap$$Lambda$34901/0x000000080476daf0.apply(minecraft@1.18.2/Unknown Source)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(java.base@17.0.2/Unknown Source)
        at java.util.concurrent.CompletableFuture$Completion.run(java.base@17.0.2/Unknown Source)
        at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(minecraft@1.18.2/ChunkTaskPriorityQueueSorter.java:62)
        at net.minecraft.server.level.ChunkTaskPriorityQueueSorter$$Lambda$34547/0x000000080470bcb0.run(minecraft@1.18.2/Unknown Source)
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(minecraft@1.18.2/BlockableEventLoop.java:157)
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(minecraft@1.18.2/ServerChunkCache.java:542)
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(minecraft@1.18.2/BlockableEventLoop.java:131)
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(minecraft@1.18.2/ServerChunkCache.java:550)
        at net.minecraft.server.level.ServerChunkCache.m_8466_(minecraft@1.18.2/ServerChunkCache.java:266)
        at net.minecraft.server.MinecraftServer.m_129961_(minecraft@1.18.2/MinecraftServer.java:787)
        at net.minecraft.server.MinecraftServer.m_7245_(minecraft@1.18.2/MinecraftServer.java:776)
        at net.minecraft.util.thread.BlockableEventLoop.m_18699_(minecraft@1.18.2/BlockableEventLoop.java:116)
        at net.minecraft.server.MinecraftServer.m_130012_(minecraft@1.18.2/MinecraftServer.java:761)
        at net.minecraft.server.MinecraftServer.m_129940_(minecraft@1.18.2/MinecraftServer.java:475)
        at net.minecraft.server.MinecraftServer.m_130006_(minecraft@1.18.2/MinecraftServer.java:318)
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(minecraft@1.18.2/DedicatedServer.java:173)
        at net.minecraft.server.MinecraftServer.m_130011_(minecraft@1.18.2/MinecraftServer.java:661)
        at net.minecraft.server.MinecraftServer.m_177918_(minecraft@1.18.2/MinecraftServer.java:261)
        at net.minecraft.server.MinecraftServer$$Lambda$34203/0x0000000804638468.run(minecraft@1.18.2/Unknown Source)
        at java.lang.Thread.run(java.base@17.0.2/Unknown Source)
```

After removing Cyclic and creating another world, success:
![image](https://user-images.githubusercontent.com/17010632/184065909-be384da3-13a8-4ed3-8471-51d243680e9d.png)

**Comment by Raidobw2** [comment] 2022-08-11 05:04
Reverting to Cyclic 1.7.3 would also solve that issue, I can confirm I've loaded the server on a brand new world twice with it now (that also was the version the DW20 1.18 modpack was using last update)

Seems to have been a bug in Cyclic 1.7.4+ I think, the incompatibility might have been introduced in this particular commit
https://github.com/Lothrazar/Cyclic/commit/cb49405a75efc9b18d563fca0fc100aa2314c493

I'll follow up with mod author

**Comment by Raidobw2** [comment] 2022-08-11 05:14
I put in a report ^

**Comment by TheonlyTazz** [comment] 2022-08-11 05:46
I have reverted back to v1.9.3 on the in-dev enviroment and can confirm that this has fixed it for now, i will leave the issue open even tho it has been "resolved" untill Cyclic decides to update the mod and it can get properly resolved

**Comment by TheonlyTazz** [comment] 2022-11-10 19:19
updated cyclic, closing issue

**Closed by TheonlyTazz** 2022-11-10 19:19 UTC
Labels: 1: Mod Issue, state: Awaiting Mod Update, FTB Presents Direwolf20 1.18
