### ISSUE TITLE
[Bug]: BotanyTrees Hopper Pots not working

### ISSUE THREAD

**Issue by githubuser1256** [FTBTeam/FTB-Modpack-Issues#219] opened 2021-10-31 01:31 UTC
### Modpack

FTB Direwolf20 1.16

### Modpack version

1.11

### Describe the bug

Botany trees with hopper pots do not deposit anything in a chest underneath. This is for things like sugarcane and trees. 

### Steps to reproduce

Place chest. Place hopper pot on top of chest. Place soil of any kind e.g. phyto soil or sand. Place sugarcane. Wait till maturity. Watch block break. Check chest and see nothing in it.

### Expected behaviour

Sugarcane or wood (for trees) should be deposited in chest.

**Comment by Raidobw2** [comment] 2021-10-31 02:11
Thanks for the report, for now you can try updating the mods in the mods folder directly to see if that solves it. The mods are found on the CurseForge site.
Once development continues for the mopdack, in the next development cycle, we'll look at this more in detail.

**Comment by githubuser1256** [comment] 2021-10-31 02:20
Thanks. I have newer than the latest version, which is stock DW20 modpack.

The version in the modpack is 3.0.6. 

The version available via Curseforge is 3.0.5.

**Comment by MichaelHillcox** [comment] 2021-10-31 02:28
Have you tried downgrading to 3.0.5?

**Comment by githubuser1256** [comment] 2021-10-31 02:32
No I haven't.

**Comment by MichaelHillcox** [comment] 2021-10-31 02:33
You should try that <3

**Comment by Raidobw2** [comment] 2021-10-31 02:53
I've tried with the modpack version 1.11.0 and the files `BotanyPots-1.16.5-7.1.23.jar` and `BotanyTrees-1.16.5-3.0.6.jar` and it works. See the gif below.
I'm using a Hopper Botany Pot (no color) with sand in it, and I placed a sugarcane on top. Can you verify you're doing the same as I'm doing, just to be sure? No extra cables or blocks, just go away from your base, place down the stuff like I placed it and let me know if that still doesn't work.

![Botany_pots](https://user-images.githubusercontent.com/17010632/139564850-226430bc-d936-49d3-8026-79cc0c54fe1b.gif)

**Comment by githubuser1256** [comment] 2021-10-31 03:00
Ok before I get to @Raidobw2's comment, I downgraded to 3.0.5. and now sugarcane appears to be working 100%, except the first break it didn't give any back.

Trees on the other hand, appear not to be working correctly. Upon a break, it has broken a matured tree about 20 times and has given only two logs in that time.

I'll go fulfill @Raidobw2's request.

**Comment by githubuser1256** [comment] 2021-10-31 03:32
`BotanyPots-1.16.5-7.1.23.jar` and `BotanyTrees-1.16.5-3.0.6.jar`

Ok. Did exactly what you did. 

Had about 80% return rate, possibly more if it ran for a long time. In other words, so it partially worked, but definitely not as expected.

I don't know what happened with my initial test. Maybe I didn't run it long enough with the chest. I used an iron chest. 

Either way, I tested it again, this time along side the regular chest (in my base this time) and I am getting about a 50% return rate.

**Comment by Raidobw2** [comment] 2021-10-31 07:02
Yup, sounds like it's working like intended. Use JEI to check return rates. You might have had something in your base taking items out like a pipe or hopper beneath the chest, or simply you had not checked the return rates yet, which I strongly recommend you to do.
Here are examples:
![image](https://user-images.githubusercontent.com/17010632/139572119-687b1240-ab11-4d25-8c58-7164b760bcca.png)
Mod is working as intended, so I'll be closing this as the mystery is solved.

**Closed by Raidobw2** 2021-10-31 07:02 UTC
Labels: FTB Presents Direwolf20 1.16, cat: Bug, des: Mod Issue, state: Approved

**Comment by githubuser1256** [comment] 2021-11-01 01:07
First of all, I want to thank you for taking the time to go over this with me. It can be very frustrating to me to spend my precious time working through something this basic with someone else. It's appreciated.

It was not immediately clear to me that botany pots have a chance to drop, and I didn't see the notation in REI. 
It does seem like it was closer to 50% for sugar cane in my base, but to really know this, I would have to do a precise test, and currently I don't see a reason to do that. 

The hopper pots are definitely dropping a significant amount. I have both of the hopper pots sitting over chests and there's about 20 in each chest after about 15 minutes give or take. 

Trees seem much less than 50%, but again, I would need to do a strict analysis to know for sure.

**Comment by Raidobw2** [comment] 2021-11-01 01:45
The learning curve for modded Minecraft isn't always easy for new players. In all modpacks, using JEI and the search box it adds is very helpful, some will say it's their best friend to help them in their journey. Left-clicking an item shows recipes for that item, and right-clicking and item shows uses for that item in other recipes.

If you're starting to get into modded Minecraft and haven't already checked any of the two FTB Academy modpacks, I'd recommend you to do so. They teach intuition basics and concepts in modded Minecraft which is very useful and important, because not everything is clearly documented. Overall, you've learned something today, and that will help you in the future. :)
