### ISSUE TITLE
[Suggestion]: Please add Integrated Dynamics

### ISSUE THREAD

**Issue by e30Birdy** [FTBTeam/FTB-Modpack-Issues#1919] opened 2022-11-13 09:47 UTC
### Modpack

FTB StoneBlock 3

### Is your suggestion related to a problem? Please describe.

Not really a problem but some automation is really lovely with ID. Many people do not know the power of the mod. Yes, some may say it is overused, but I do not understand that as it may be in packs, but people do not know how to use it or even use it at all. Create and XNET is in about every pack and way more used. Things like automating flux would be really lovely or things like automating chickens to 10/10/10 and so on.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/integrated-dynamics

**Comment by richie3366** [comment] 2022-11-13 10:38
+1!

I'd also suggest the [Integrated Proxy](https://www.curseforge.com/minecraft/mc-mods/integrated-proxy) mod, which adds a layer of iteration-ness which has the benefit of limiting the number of tileentities on a server (because you don't need to scale by adding more machines/readers/writers)

**Note:** There is a 1.18.1 version available in the Files tab, fully compatible with 1.18.2.

**Comment by e30Birdy** [comment] 2022-11-13 13:10
> +1!
> 
> I'd also suggest the [Integrated Proxy](https://www.curseforge.com/minecraft/mc-mods/integrated-proxy) mod, which adds a layer of iteration-ness which has the benefit of limiting the number of tileentities on a server (because you don't need to scale by adding more machines/readers/writers)
> 
> **Note:** There is a 1.18.1 version available in the Files tab, fully compatible with 1.18.2.

Never heard of proxy but sounds neat

**Comment by richie3366** [comment] 2022-11-13 14:26
It is not well known, that's for sure, but it is really powerful when you want to interact with (&/or monitor) an area. I would definitely use it to farm the emerald clusters without spamming AE2 Annihilation Planes.

Btw, it would be pointless to have integrated dynamic without at least Integrated Tunnels. Maybe you should edit your issue to specify it, along with a 2nd link.

I'm so excited by the idea of (maybe) adding it to the modpack that I've [made a PR](https://github.com/shBLOCK/IntegratedProxy/pull/30) to fix an issue as well as upgrading its dependencies (including MC 1.18.2).
I hope the mod developer will merge it soon enough 🤞

**Comment by Sunekaer** [comment] 2022-11-13 16:55
Duplicate of #1842

**Closed by Sunekaer** 2022-11-13 16:55 UTC
Labels: FTB StoneBlock 3
