### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by DemiPluto** [FTBTeam/FTB-Modpack-Issues#2017] opened 2022-11-17 20:59 UTC
### Modpack

StoneBlock 3

### Modpack version

1.3.0

### Log Files

https://pastebin.com/aZfbNrN6

### Describe the bug

When launching Stoneblock 3 1.3.0 on OS I keep on getting stuck on a loading section called "Processing work INJECT_CAPABILITIES". I have tried multiple times to restart the launcher and even my laptop but neither of that is working. 

### Steps to reproduce

1 go to stoneblock 3 

2 click on play

3 wait for java to launch

4 encounter error "Processing work INJECT_CAPABILITIES"

### Expected behaviour

I expected the game to be able to launch albeit slowly as I have a MacBook from 2013, but I expected it to load

**Comment by Raidobw2** [comment] 2022-11-18 09:06
Duplicate of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1807, please see the conversation in the linked issue there and try modifying the Flywheel config.
Let's keep the conversation there as well to avoid having 2 separate conversations for this issue, thanks in advance!

**Closed by Raidobw2** 2022-11-18 09:06 UTC
Labels: 3: Support Request, FTB StoneBlock 3
