### ISSUE TITLE
FTB Stoneblock 3 - Mining Gadget does not mine certain blocks

### ISSUE THREAD

**Issue by Natervater** [FTBTeam/FTB-Modpack-Issues#2792] opened 2023-03-05 21:47 UTC
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Describe the bug

Mining gadget does not mine certain blocks, which seems random. Blocks get stuck in an in-between state and do not fully mine through, yet other blocks mine through just fine. Seems to be arbitrary, please see this video: 
https://www.screencast.com/t/peU5TxtzX

Ive tried removing mining gadgets upgrades, reinstalling them, turning off, turning them on, crafting a new gadget, restarting the client, nothing seems to help. 

### Steps to reproduce

My Gadget has the following upgrades if it matters:
-Fortune
-Silk Touch
-level 5 speed
-Light Placer
-Magnet

1. Select Block
2. Fire at it
3. Mining gadget will either mine the block or not

### Expected behaviour

Mining gadget mines out blocks its fired at

### Screenshots

Video of issue: https://www.screencast.com/t/peU5TxtzX

For some reason Github wont let me upload here

**Comment by Natervater** [comment] 2023-03-05 22:05
Forgot to add that this is a SP world

**Comment by Sunekaer** [comment] 2023-04-12 17:50
Duplicate of #2155

**Closed by Sunekaer** 2023-04-12 17:50 UTC
Labels: FTB StoneBlock 3
