### ISSUE TITLE
Crash when mining Openblocks Trophys

### ISSUE THREAD

**Issue by kingrex1997** [FTBTeam/FTB-Modpack-Issues#5867] opened 2024-09-28 23:28 UTC
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.2.1

### Launcher

CurseForge

### Has the pack been modified

No

### Log Files

https://pastebin.com/8mHL2dab
https://pastebin.com/LzD3tjCZ

### Describe the bug

When punching/mining openblocks trophies game crashes with the following exit code -1

The game crashed whilst tesselating block model
Error: java.lang.IllegalStateException: Missing elements in vertex: UV0, Normal

reproducible, crashes with both empty hand and with tools(mekanism atomic disassembler tested), tested on both creeper and enderman trophies. 

### Steps to reproduce

1. place Openblock Trophy
2. left click the trophy
3. observe crash

### Expected behaviour

block breaking without crashing

### Additional information

pack recently updated from 1.0.0 to 1.2.1

**Comment by Gaz492** [comment] 2024-09-29 09:20
Duplicate of #5846

**Closed by Gaz492** 2024-09-29 09:20 UTC
Labels: Bug, FTB Presents Direwolf20 1.21

**Comment by RedDamer** [comment] 2024-10-01 02:23
Having the same issue as mentioned here , and as the "duplicate" where game crashes when mining trophies.
