### ISSUE TITLE
Continuation of Inconsistent detection of quest completion

### ISSUE THREAD

**Issue by Shelaba** [FTBTeam/FTB-Modpack-Issues#3316] opened 2023-05-06 17:19 UTC
### Modpack

FTB Skies

### Modpack version

1.0.9

### Describe the bug

This issue was reported in 1.0.7, see #3281. Symptoms are exactly in line. It usually fails to detect item based quest completion. Often, it requires you to log out/in or interact with things like the furnace to force detection.

It was posited that it was due to the detection_delay being set to 20. I cannot rule that out as contributory, but it is set to 5 in 1.0.9 and the problem persists.

### Steps to reproduce

1. Complete an item related quest. <Stringing you along> for example.
2. If it detects completion, attempt again with another quest.
3. Wait indefinitely for it to detect completion. I've waited over a minute.
4. It will then detect completion.

### Expected behaviour

It should automatically detect the quest within a reasonable time.

**Comment by Jreil1981** [comment] 2023-05-06 22:18
I am having this issue as well. Not sure what the cause is.

**Comment by ceilingfan123** [comment] 2023-05-06 23:47
Having the same problem on 1.0.9.  Just started a new game. The cobblestone and string quests are not completing

**Comment by zakhildev** [comment] 2023-05-07 14:54
Unfrotunately, I am facing the same issue.

**Comment by zakhildev** [comment] 2023-05-07 15:35
### POTENTIAL FIX

Downgrade `FTB Quests` from version `1902.4.14-build.223` to `1902.4.13-build.219`.

Can someone confirm this please?
Download older version from here: **[Link](https://www.curseforge.com/minecraft/mc-mods/ftb-quests-forge/files)**

**Comment by Shelaba** [comment] 2023-05-07 16:33
I didn't need to adjust the detection_delay, but 1902.4.13-build.219 appears to work correctly.

**Comment by ramdor** [comment] 2023-05-08 22:29
yeah same issue here. Playing MP (not dedicated) and completing a quest is very hit and miss.

**Comment by desht** [comment] 2023-05-09 09:42
It's strange that 1902.4.13 works and 1902.4.14 doesn't.  I would expect 1902.4.13 to have more problems.  What makes it more difficult to track down is that neither I nor others here are able to reproduce the problem right now (items always get detected correctly).

The issues appear to stem from a TPS performance fix added in 1902.4.13. I'd rather not have to back this out, since the TPS hit can be severe depending on what items are in your inventory.  So I'd like to gather as much info as possible here.

* Is everyone here running in online mode?
* Does moving items around in your inventory trigger an item detection?  In theory any change to your 36 inventory slots (incl. hotbar) should trigger a check to be scheduled, within the number of ticks specified in config (probably 5 or 20).
* Is anyone here willing to add a dev build of FTB Quests to their instance with a possible fix? If so, please let me know.

**Comment by ShuzzDE** [comment] 2023-05-09 21:04
- Running in online mode.
- daytime tick IS true.
- juggling items around in the inventory does not help. Sometimes crafting something triggers the update, but not always.

I just noticed that while building a sifter and hand crank for one of the very early quests the sifter I crafted did NOT count towards the quest "Sifter go Brrrr", but it DID count towards "Getting resources".

**Comment by Taytheer** [comment] 2023-05-10 21:20
I am having a similar issue with the FTB screen not turning in the 10k power quest. I have restated MC a few times and it still shows 0/10k energy in the quest log but 10k/10k on the FTB screen. Not sure if I am doing something wrong or if the quest is being weird.

**Comment by kingchills** [comment] 2023-05-11 02:22
Not sure if it makes much of a difference, but the first world I created with 1.0.9 all of the quests worked fine.  But I deleted that world and started a new, and now the quests aren't working as expected.

**Comment by Rithenar** [comment] 2023-05-11 11:57
Any updates on this or a workaround? I started my world, and the quests were working just fine. Two days later the mod stop recognizing quest items and would not complete them

**Comment by desht** [comment] 2023-05-11 12:44
There should be a new Skies release very soon, including the latest version of FTB Quests, which is already out on Curseforge: https://www.curseforge.com/minecraft/mc-mods/ftb-quests-forge/files/4530022.

This should hopefully resolve the problem (I say "hopefully" since the problem is not easy to reproduce).

**Comment by NinjaBanjo** [comment] 2023-05-11 23:35
Update to 1.1.0 today, but re-used my existing save.


> I just noticed that while building a sifter and hand crank for one of the very early quests the sifter I crafted did NOT count towards the quest "Sifter go Brrrr", but it DID count towards "Getting resources".

Still seeing this same issue reported here. Same quest and everything

**Comment by grapedragon** [comment] 2023-05-12 00:08
I don't know if my problem is this same one - I can't complete a quest, I have tried crating something else, getting a new achievement, using a furnace, Restarted the game, downloaded a newer version. The biggest thing is it is only this one quest I have to build two things a sifter and a hand crank and the quest mod registers my hand crank but not my sifter. This is extra strange since my sifter is registered in other quests, the quest mod sees and reads my sifter for other quests but not for this one quest ( of course the important one that connects to a bunch of other quests)

**Comment by NinjaBanjo** [comment] 2023-05-12 07:03
> Update to 1.1.0 today, but re-used my existing save.
> 
> > I just noticed that while building a sifter and hand crank for one of the very early quests the sifter I crafted did NOT count towards the quest "Sifter go Brrrr", but it DID count towards "Getting resources".
> 
> ~Still seeing this same issue reported here. Same quest and everything~
> 
> I've confirmed that I'm using the new FTB Quests packaged linked above. ![image](https://user-images.githubusercontent.com/1912336/237834973-dd0d7c7a-3ee6-4352-bfe3-23c4ddd9cc3a.png)
> 
> EDIT: this seems to be user error. I had prerequisite quests that I hadn't complete. Quest completion is working great in 1.1.0. And I might not have even had a problem with it before..
> 
> Both a new world and my existing world are completing this and other quests fine.

See my update above. I believe I was misguided in my previous reports.

**Comment by destinatech** [comment] 2023-05-12 08:15
I might be wrong but, here at least, I'm still seeing this inconsistency on 1.1.0.

For example, the `Click to collect all rewards!` button in the top-right of the main quests UI shows me as having pending rewards but clicking shows an empty `Rewards` screen. This one way be something else though? Unsure.

More in line with this bug, the steel casing quest part of the Mekanism line is showing incomplete after crafting a casing and slotting it into my inventory while the metallurgic infuser quest is complete and showing as such. Just one such example; I've not searched out others.

**Comment by desht** [comment] 2023-05-12 08:33
> For example, the Click to collect all rewards! button in the top-right of the main quests UI shows me as having pending rewards but clicking shows an empty Rewards screen. This one way be something else though? Unsure.

That sounds completely unrelated.

> the steel casing quest part of the Mekanism line is showing incomplete after crafting a casing and slotting it into my inventory while the metallurgic infuser quest is complete and showing as such

I just went into Skies to test this.  Crafted a steel casing (with the Infuser quest complete), and the steel casing quest completed, no problem.

**Comment by desht** [comment] 2023-05-12 08:35
> The biggest thing is it is only this one quest I have to build two things a sifter and a hand crank and the quest mod registers my hand crank but not my sifter. 

Just tested this too; the quests completed without issue.

**Comment by destinatech** [comment] 2023-05-12 08:46
Bah. Forgot to sign out of my work alt again...

> > For example, the Click to collect all rewards! button in the top-right of the main quests UI shows me as having pending rewards but clicking shows an empty Rewards screen. This one way be something else though? Unsure.
> 
> That sounds completely unrelated.

Thought it might be. Cheers for confirming!

> > the steel casing quest part of the Mekanism line is showing incomplete after crafting a casing and slotting it into my inventory while the metallurgic infuser quest is complete and showing as such
> 
> I just went into Skies to test this. Crafted a steel casing (with the Infuser quest complete), and the steel casing quest completed, no problem.

Yeah that doesn't surprise me :grin:

Tbf I only restarted the pack a few days ago after a ~month pause and, for the first, I dunno... 15 hours of game play, all quests seemed to be completing just fine. It's only now I'm getting further through the various quest lines that quests aren't being recognised.

Tried another random one that was crafted but not showing as complete (basic magnet from Simple Magnets) and that one completes fine.

**Comment by grapedragon** [comment] 2023-05-12 20:19
I went back into my world and look at the prerequisite quests and then noticed the arrows - I too was missing prerequisite quests, that were underneath the quest I was having trouble with, they looked like future quests not quests I needed to do first. I would recommend a re- arranging of the quest layout so that there is less confusion

**Comment by ShuzzDE** [comment] 2023-05-15 07:57
> My guess is that @ShuzzDE was also missing prerequisites. Hopefully they can confirm

No, I wasn't missing prereqs unfortunately. But I've updated to the latest release and it seems to have fixed the issues for me.

**Closed** 2023-05-20 07:49 UTC
Labels: 1: Mod Issue, state: Fixed in Dev :hammer_and_wrench:, FTB Skies

**Comment by AlaskanPurged** [comment] 2023-07-08 20:34
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

There is no issues!!!

You have to complete all surrounding Quests that are linked to that quest for it to be completed. Its like a chain quest.

**Comment by gnosthi** [comment] 2023-07-26 14:13
Currently playing FTB Skies 1.3.1 and I'm experiencing this issue with the 'Sifter Go Brrr' quest. 

I have completed prerequisite quests and currently have both the sifter and hand crank in my inventory. 

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/17650528/5e3ea92b-d251-48b9-b758-e6d70c851203)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/17650528/f0bf8662-3f46-497b-8fab-29233919cece)

I've tried logging out and logging back in, I've tried interacting with other objects and have even crafted the items a second time to try to trigger the quest completion and it has not completed. 

So far, this is the only quest that I've experienced this issue on but since it's part of the main quest line, it's kind of game breaking. 
Let me know if I can provide any logs or anything.

**Comment by desht** [comment] 2023-07-26 15:02
No need, it's very clear from your screenshot.  You haven't finished Dust to Dust (the quest immediately underneath Sifter go Brr), or any of its prerequisites.  Look at the direction of the arrows in the lines leading to/from quests.

**Comment by res0nat0r** [comment] 2024-04-10 01:51
My dependencies appear to be correct, but I'm having the same issue, as Dust to Dust is complete? 

![2024-04-09 20_49_58-Window](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/24287/7289c02d-bd0d-499b-bd31-a3988b5a17e8)

**Comment by itsBasti** [comment] 2024-12-24 13:03
Crafting the "String Mesh" item marks the quest as complete on version 1.10.2 of the mod pack. A bit confusing if it's not listed as required but good to know if anyone comes accross this again. Merry christmas
