### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Pirxt1560** [FTBTeam/FTB-Modpack-Issues#440] opened 2021-12-08 03:19 UTC
### Modpack

FTB OceanBlock

### Modpack version

1.10.0

### Log Files

[crash-2021-12-07_21.04.43-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7673091/crash-2021-12-07_21.04.43-client.txt)

### Describe the bug

Crashing when looking at JEI or inventory of chest where Ender tank is listed.. Crash report indicates that there is an issue rendering the Ender tank.

### Steps to reproduce

Open JEI or inventory where Ender tank is displayed

### Expected behaviour

Crash when displaying Ender tank in inventory screen

**Comment by Raidobw2** [comment] 2021-12-08 05:06
Duplicate of #433, update to 1.10.1 since it contains a hotfix to correct that error.
![image](https://user-images.githubusercontent.com/17010632/145151412-21818e8b-a35b-43b1-b0d2-6202919aa42c.png)
CodeChicken was updated with a patch in that hotfix, cheers.

**Closed by Raidobw2** 2021-12-08 05:06 UTC
Labels: FTB OceanBlock
