### ISSUE TITLE
Game crashing when I try to launch modpack (Stoneblock3)

### ISSUE THREAD

**Issue by NohadX** [FTBTeam/FTB-Modpack-Issues#2274] opened 2022-12-09 09:35 UTC
### Modpack

FTB StoneBlock 3

### Modpack version

1.18.1

### Log Files

[crash-2022-12-09_19.58.35-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10193382/crash-2022-12-09_19.58.35-client.txt)

### Describe the bug

I trying to launch modpack and then it crushing after a few minutes loading.
I already tried to uninstall modpack  and it didnt't get me any results, then I tried to unistall all the FTB launcher and ftb folder
It also diding get any results

### Steps to reproduce

1. Press button "Play"
2. wait for launch minecraft 
3. appear red minecraft preview 
4. wait a minute
5. screen with words "sawing world"
6. CRASH

### Expected behaviour

cant launch modpack

### Screenshots

![image](https://user-images.githubusercontent.com/120172415/206670474-3080fa5f-0599-43d6-9f10-96e9f64ac757.png)
![image](https://user-images.githubusercontent.com/120172415/206671151-90bfb42a-f2b8-4f41-900f-3c2997a76f7c.png)
![image](https://user-images.githubusercontent.com/120172415/206671198-78e4e6c6-8b53-4c8a-8878-8f0293d91e4b.png)

### Additional information

uwu

**Comment by briosky** [comment] 2022-12-09 10:08
the same thing happens to me

**Comment by andrealmeida19** [comment] 2022-12-09 10:21
Me too, the mod BetterThanLlamas seems to be crashing the game now.

**Comment by NohadX** [comment] 2022-12-09 10:32
i hope ftb team will fix it

**Comment by NordicGamerFE** [comment] 2022-12-09 10:55
Duplicate of #2269

**Closed** 2022-12-09 11:44 UTC
Labels: state: Duplicate :books:, FTB StoneBlock 3
