### ISSUE TITLE
Some potion effects remove all of my ability to read anything in my inventory.

### ISSUE THREAD

**Issue by DisclexUser** [FTBTeam/FTB-Modpack-Issues#6260] opened 2024-11-25 12:14 UTC
### Modpack

FTB Evolution

### Modpack version

1.3

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

As the title said, some potion effect (not sure which ones as I cant read them) call my inventory to loose all UI associated with the mouse. this has happened to me a lot and to my friends as well (we are on a server). The only way we are able to fix it is to either open another type of inventory like a backpack, die, or wait for the affect to clear. [This is what it looks like as I asked about it on reddit.](https://www.reddit.com/r/feedthebeast/comments/1gx0sps/help_with_jei_and_names_of_items_not_showing_up/)[](url)

### Steps to reproduce

1. get some healing potion effect
2. open inventory and look at items
3. clear status effect
4.  open inventory and look at items again
5. profit

### Expected behaviour

Exactly what I said in "Describe the bug" I cant see any time or jei when Im in my inventory.

**Comment by ttechr** [comment] 2024-11-25 19:54
For the jei and tooltip thing this is a known bug and is looking to be caused by the just enough potion effects(or something like that) A workaround for this is to go into your inventory and right click the gear on the top left. Once there press the little red x on the top right of each of the options on the top row. That has worked for me.

**Comment by alfredggttv** [comment] 2024-11-25 21:09
This seems to be an issue that was fixed with an update to a mod. Let me know if it happens after the next update!

**Closed** 2024-12-04 03:27 UTC
Labels: state: Fixed in Dev, Bug, FTB Evolution
