### ISSUE TITLE
Electrodynamics bronze ingots try to get into processing patterns using those machines

### ISSUE THREAD

**Issue by knzconnor** [FTBTeam/FTB-Modpack-Issues#4490] opened 2023-12-18 20:11 UTC
### Modpack

FTB Genesis

### Modpack version

1.4.0

### Describe the bug

Ae2 processing patterns using Electrodynamics machines will try to use their version of the bronze ingot. They don't show the darker bronze ingot, so it's really easy to miss. But then when you try to use that recipes in a nested production chain it chokes and shows the darker ED bronze ingot icon.

### Steps to reproduce

1. Open a pattern making terminal in Ae2
2. Search bronze wire
3. Make a processing pattern for bronze wire (uses the ED wire machine)
4. Note that it uses the unobtainable ED bronze ingot (but uses the other bronze graphic).

You may actually have to insert it into a provider and try to make it and then it forces it to use the ED ingot, that is the order I did because I didn't notice.

Also, you may need to do this in a nested pattern. I don't recall but it may have worked when directly making bronze wire.

### Expected behaviour

Since ED bronze is unobtainable, it should never show up when crafting from JEI, even for a pattern.

### Additional information

Thanks!

**Comment by ArtpokeBr** [comment] 2024-04-26 23:31
Yeah, this seems to be a limitation with JEI and Almost Unified JEI Preview.... unfortunatly we can't fix it on our side =/

**Comment by ArtpokeBr** [comment] 2024-04-26 23:38
Actually, just confirmed with Saereth, this should be fixed in the most recent ED Update, please, if this issue still occurs, reopen it or open a new issue =)

**Closed** 2024-04-27 01:28 UTC
Labels: 1: Mod Issue, state: Fixed in Dev :hammer_and_wrench:, FTB Genesis
