### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ayoo0** [FTBTeam/FTB-Modpack-Issues#216] opened 2021-10-30 13:42 UTC
### Modpack

FTB Oceanblock

### Modpack version

Beta (Current)

### Log Files

.

### Describe the bug

XNET wont transfer energy

### Steps to reproduce

.

### Expected behaviour

.

### Screenshots

![Jre-legacy Screenshot 2021 10 30 - 09 40 08 26](https://user-images.githubusercontent.com/79774753/139535064-73d0cbec-bcfa-4fe7-add7-f2c99a55cfdb.png)

![Jre-legacy Screenshot 2021 10 30 - 09 40 10 100](https://user-images.githubusercontent.com/79774753/139535067-c5d33060-077a-4963-9133-aea866c0ca3b.png)

![Jre-legacy Screenshot 2021 10 30 - 09 40 16 35](https://user-images.githubusercontent.com/79774753/139535072-1f18ded5-1b38-4586-936c-5666fd702f2a.png)

![Jre-legacy Screenshot 2021 10 30 - 09 40 23 56](https://user-images.githubusercontent.com/79774753/139535076-43f92f4a-49e5-4b1e-a9fc-eff9fbf22211.png)

### Additional information

Im new to XNET but my machine is to compact to use cables and also fluid transfer is working

**Comment by Raidobw2** [comment] 2021-10-31 02:00
You might want to invert your Inputs with your Outputs. Think of it like a network. It imports (input) in the network and exports (outputs) from it.

I suggest going in the FTB Discord in the "oceanblock" channel and chatting with people there, they'll be able to help you out. There is also a manual for Xnet in JEI, search for `@xnet` in the search box and you should see it appear.

If you still have issues or didn't get a good reply in the oceanblock channel, come see me in the "support" channel after, I'll help you out.

I'll need to close this as it's not a bug with XNet in our modpacks, you simply need to configure it correctly and give power to your XNet controller. See you soon perhaps!

-R3GEN

**Closed by Raidobw2** 2021-10-31 02:00 UTC
Labels: FTB OceanBlock
