### ISSUE TITLE
[Bug]: REI cannot show recipe ingredient or use after search in ae2 crafting terminal

### ISSUE THREAD

**Issue by Nizaki** [FTBTeam/FTB-Modpack-Issues#1290] opened 2022-08-25 10:42 UTC
### Modpack

FTB Plexiglass mountain

### Modpack version

1.1.1

### Describe the bug

after search in ae2 terminal REI recipe not showing up by using hot key, It need to use left or right button on something to use hot key again

### Steps to reproduce

1. open crafting terminal from ae2
2. press r or u on some item
3. recipe not showing

### Expected behaviour

REI show ingredient by hotkey after search

**Comment by Raidobw2** [comment] 2022-08-26 03:42
I believe that was fixed some time ago in the REI builds. I'll check and report back here, that might be fixed in-dev already. If you want I think updating your REI might fix that, plus the weird encapsulator recipes too

**Comment by Raidobw2** [comment] 2022-08-26 07:01
Can't reproduce in-dev with the crafting terminal and pressing R or U on items in REI. I believe this was fixed already in a later version than PGM 1.1.1 has!

**Comment by Nizaki** [comment] 2022-09-09 06:05
Look like this bug happend on wireless terminal that open with shortcut
step to reproduce:
Bind wireless terminal to r.
Press r to open wireless terminal.
Search something.
woola r and u shortcut stop working until use mouse to open recipe from rei.
ps. test on 1.2.0

**Comment by Raidobw2** [comment] 2022-09-09 07:31
Hmm I see. I've asked the REI author about this. If you bind wireless terminal to 'p' instead, if you press 'p', then 'r' to see a recipe does that work correctly?

**Comment by Nizaki** [comment] 2022-09-09 07:51
It seem to be working now, I will test again later.

**Comment by Raidobw2** [comment] 2022-09-09 07:59
Hmm that's possibly a keybind conflict between the 2 mods, usually it's what happens if two mods have the same keybind. What I'd suggest is to keep your terminal bound on another key, I use 'g' for the terminal myself. 'f' could also be good, just unbind the "swap item with offhand" if you do that.

I'll wait to see what the REI author says, but if they tell me it's a conflict too, then the solution is to use 2 separate keybinds and I'll close this.

**Comment by Nizaki** [comment] 2022-09-10 03:05
Seem like this bug only happend when use "Tall Centered Terminal" even with R keybind it still working maybe bug with style

**Comment by Raidobw2** [comment] 2022-09-10 06:19
Hey, I got feedback from the REI author and they say it's a keybind conflict between mods. I'd recommend to not bind R to both show recipes and to open the terminal.
If you must put your terminal on R, maybe you can change the REI keybind for show recipe to some other key (this is done in the REI config from the Mods menu).

Since this is not a bug in REI and is instead a keybind conflict, I will close the issue

**Closed by Raidobw2** 2022-09-10 06:19 UTC
Labels: 1: Mod Issue, FTB Plexiglass Mountain
