### ISSUE TITLE
[Bug]: Crash Upon Start

### ISSUE THREAD

**Issue by Ankit17430** [FTBTeam/FTB-Modpack-Issues#1811] opened 2022-11-10 02:25 UTC
### Modpack

StoneBlock 3

### Modpack version

1.2.0

### Log Files

[crash-2022-11-10_10.15.55-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9976761/crash-2022-11-10_10.15.55-client.txt)

### Describe the bug

Upon Starting the game crashes, I was able to run 1.1.0 with no issues.

### Steps to reproduce

1. Lunch the instance from FTB app
2. It crashes within 2 mins

### Expected behaviour

Lunch the modpack

**Comment by Sunekaer** [comment] 2022-11-10 09:25
Duplicate of  #1768

**Closed by Sunekaer** 2022-11-10 09:25 UTC
Labels: 1: Mod Issue, FTB StoneBlock 3
