### ISSUE TITLE
Game doesn't close

### ISSUE THREAD

**Issue by vl0fast** [FTBTeam/FTB-Modpack-Issues#2537] opened 2023-01-19 19:56 UTC
### Modpack

FTB DIrewolf 1.19

### Modpack version

1.1.1

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10460554/latest.log)

### Describe the bug

Everytime I try to close my game I get a error spawm and my game never closes. I had this for a while, I tried everything but nothing works. The only way to close the game is killing the instance or using task manager to close it. either of those removes the last 5/10min of things I did in my world. I also went to those exact coords and removed some pipes, cables and machines that were there, placed a solid cube of block and still had the issue while logging out of the world

### Steps to reproduce

1. Enter the world
2. Click to save and exit the world
3. Game permantly stays on "Saving" screen and the massage gets spammed on the console

### Expected behaviour

I expect to be able to close my world and game without having to force it

### Screenshots

![image](https://user-images.githubusercontent.com/96571121/213545919-d6791b2c-1b99-4838-9bfc-1e5caf289477.png)

**Comment by vl0fast** [comment] 2023-01-19 19:57
Its the Worng label, Its on Direwolf 1.19 not legend of the Eyes

**Comment by Saereth** [comment] 2023-01-30 17:15
ton of mod updates in the new version I'm working on have left me unable to reproduce this now so I'm marking this as fixed, if after 1.2 comes out you still have this issue please reopen

**Closed** 2023-02-02 02:24 UTC
Labels: state: Fixed in Dev :hammer_and_wrench:, FTB Presents Direwolf20 1.19
