### ISSUE TITLE
[Bug]: Infinity Backpack from industrial foregoing 

### ISSUE THREAD

**Issue by Ghost-Asood** [FTBTeam/FTB-Modpack-Issues#344] opened 2021-11-19 15:37 UTC
### Modpack

DireWolf20 1.16

### Modpack version

1.11.0

### Describe the bug

duplication bug.

there's a video of the issue, keep your eyes on the amount of the items.

### Steps to reproduce

1. get a infinity backpack
2. toggle "refill" mode to disabled in every slot
3. fill your inventory 
4. drop something that already exists in the backpack
5. stand where it is
6. watch the item amount go up 

### Expected behaviour

i don't know, maybe uh .... not to give free items?

### Screenshots

here's a video:
https://user-images.githubusercontent.com/17010632/143186087-1aec4d46-3ce4-42ba-b3d6-7d0e67cdd2b5.mp4

**Comment by Raidobw2** [comment] 2021-11-24 06:44
Hey, I've went in-dev and tried to replicate the issue by doing the same thing as you did but I'm unable to recreate the bug.

Going to Industrial Foregoing's issue tracker, there's multiple mentions of that issue being fixed, [this one](InnovativeOnlineIndustries/Industrial-Foregoing/issues/1052) for example.

I can't see any commit information that would have solved the issue between the version of IF in 1.11 and 1.12, but the bug doesn't seem to be in 1.12 of this current modpack (haven't tested 1.11).

I'll most likely close this as `industrial-foregoing-1.16.5-3.2.14.6-14.jar` seems to work as intended. If you could confirm the information in the next days or deny it, it would be great! Thanks

**Comment by Ghost-Asood** [comment] 2021-11-24 07:03
Hello, I'll re-test it when I finish work today, and will inform you if I can replicate it again or no.

**Comment by Raidobw2** [comment] 2021-11-24 07:20
Sure, no stress, thank you very much!

**Comment by Raidobw2** [comment] 2021-12-26 12:34
Hello, I'm unable to reproduce this behavior, it works fine for me. Looks like this maybe have been fixed in a prior version.

**Comment by Raidobw2** [comment] 2022-01-03 07:39
Could not reproduce in-dev, I assume this is fixed in 1.13.

**Closed by Raidobw2** 2022-01-03 07:39 UTC
Labels: FTB Presents Direwolf20 1.16, 1: Mod Issue, state: Fixed :heavy_check_mark:
