### ISSUE TITLE
[Bug]: Server operators can't invite people to teams.

### ISSUE THREAD

**Issue by Ketrai** [FTBTeam/FTB-Modpack-Issues#369] opened 2021-11-23 07:22 UTC
### Modpack

FTB Oceanblock

### Modpack version

1.6.0

### Describe the bug

Can't invite people to teams you didn't create as an server operator.

### Steps to reproduce

1. Be a server operator.
2. Join a team you didn't create.
3. Frantically try to use /ftbteams party invite, and other such commands.

### Expected behaviour

For operators to be infallible regarding commands.

**Comment by Raidobw2** [comment] 2021-11-23 09:12
Hi, are you using plugins? Plugins can cause errors since they can disable all commands, including FTB commands. There's nothing we can do about it in that case, since it's not our fault. You can generate the list of command nodes with `/ftbranks refresh_readme`, and that'll be a text file inside `world/serverconfig/ftbranks` called "README.txt". Some of those commands need to be added to your plugin (I'm not familiar with that sorry).

Let me know, since the bug you're describing is not common at all from what I've seen from people playing the modpack.

**Comment by Ketrai** [comment] 2021-11-23 21:36
> Hi, are you using plugins? Plugins can cause errors since they can disable all commands, including FTB commands. There's nothing we can do about it in that case, since it's not our fault. You can generate the list of command nodes with `/ftbranks refresh_readme`, and that'll be a text file inside `world/serverconfig/ftbranks` called "README.txt". Some of those commands need to be added to your plugin (I'm not familiar with that sorry).
> 
> Let me know, since the bug you're describing is not common at all from what I've seen from people playing the modpack.

There are no plugins installed on the server. It's just a fresh install of oceanblock. No idea why the commands are acting so funky.

**Comment by Raidobw2** [comment] 2021-11-24 01:28
Hmm I see, thanks for the reply. Interesting behaviour, this might be a mod issue with FTB Teams, we will have to test it out on our side.
We'll be testing on the latest version when we get the time, you can update if you want too, since OceanBlock is now version 1.9.0, 1.6.0 was a while ago!

**Comment by LatvianModder** [comment] 2021-12-06 13:04
Why would you be able to invite people to someone else's team as op? 🤔 Only team owner can invite people, that's normal

**Comment by Raidobw2** [comment] 2021-12-07 09:33
@Ketrai ask the owner to either transfer ownership or have you as moderator in their team, then invite someone. If it works, we'll go ahead and close the issue.

If the team owner isn't there anymore, if you own the server, you'll need to mess with the NBT of files to gain ownership. Even simpler solution, unclaim the chunks as op then ask the person to create their team.

We'll be waiting on your reply if one of those solutions did it for you, since the behavior seems intended, even confirmed by our mod dev!
Thanks

**Closed** 2021-12-09 11:32 UTC
Labels: FTB OceanBlock, state: Awaiting Reply :speaking_head:
