### ISSUE TITLE
[Bug]: Steves Carts progress timer sometimes goes negative

### ISSUE THREAD

**Issue by AdamBundschuh** [FTBTeam/FTB-Modpack-Issues#504] opened 2021-12-27 05:35 UTC
### Modpack

FTB Ultimate Anniversary

### Modpack version

1.1.0

### Log Files

[06:17:18] [Server thread/INFO] [minecraft/DedicatedServer]: Stopping the server
[06:17:18] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[06:17:18] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[06:17:18] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[06:17:18] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[06:17:19] [Server thread/INFO] [minecraft/ChunkManager]: ThreadedAnvilChunkStorage (world): All chunks are saved [06:17:19] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[06:17:19] [Server thread/INFO] [minecraft/ChunkManager]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[06:17:19] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[06:17:19] [Server thread/INFO] [minecraft/ChunkManager]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[06:17:19] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[world]'/twilightforest:twilightforest
rate limit exceeded
2021-12-27 06:18:22,969 main WARN Advanced terminal features are not available in this environment
[06:18:23] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.22, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, nogui]
[06:18:23] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_312 by Private Build
[06:18:23] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[06:18:23] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/home/sid_596155/minecraft_ftb_ultimate_anniversary_edition/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=SERVER
[06:18:26] [main/ERROR] [mixin/]: Mixin config retroexchange-common.mixins.json does not specify "minVersion" property
[06:18:26] [main/ERROR] [mixin/]: Mixin config myrtrees-common.mixins.json does not specify "minVersion" property
[06:18:26] [main/ERROR] [mixin/]: Mixin config minetogether.mixins.json does not specify "minVersion" property
[06:18:26] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [vazkii.patchouli.common.MixinConnector]
[06:18:26] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlserver' with arguments [--gameDir, ., nogui]
[06:18:26] [main/WARN] [mixin/]: Reference map 'yungsbridges.refmap.json' for yungsbridges.mixins.json could not be read. If this is a development environment you can ignore this message
[06:18:26] [main/WARN] [mixin/]: Reference map 'rhino-forge-refmap.json' for rhino.mixins.json could not be read. If this is a development environment you can ignore this message
[06:18:26] [main/INFO] [RoadRunner Early Loading/]: Loaded rule configuration file for RoadRunner: 81 options available, 0 override(s) found
[06:18:28] [main/INFO] [ne.mi.co.Co.placebo/COREMODLOG]: Patching LivingEntity#attackEntityFrom
[06:18:28] [main/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
[06:18:28] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/entity/player/ClientPlayerEntity (java.lang.RuntimeException: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER)
[06:18:28] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.entity.player.ClientPlayerEntity was not found ars_nouveau.mixins.json:ClientElytraMixin
rate limit exceeded
[06:18:31] [main/INFO] [ne.mi.co.Co.placebo/COREMODLOG]: Patching LivingEntity#attackEntityFrom
[06:18:32] [main/INFO] [FerriteCore - class definer/]: Using Java 8 class definer
[06:18:32] [main/INFO] [ne.mi.co.Co.placebo/COREMODLOG]: Patching ItemStack#onItemUse
[06:18:33] [main/INFO] [FTB Janitor/]: Lazy DFU Loaded
[06:18:37] [main/INFO] [PluginManager/]: Scanning classes for titanium
[06:18:37] [main/INFO] [PluginManager/]: Found FeaturePluginInstance for class IndustrialForegoingResourcePlugin for plugin resources
[06:18:37] [main/INFO] [PluginManager/]: Found FeaturePluginInstance for class DefaultResourceRegistryPlugin for plugin resources
[06:18:37] [modloading-worker-36/INFO] [Advanced Peripherals/]: AdvancedPeripherals says hello!
[06:18:37] [modloading-worker-8/WARN] [ReAuth/]: #########################################
[06:18:37] [modloading-worker-8/WARN] [ReAuth/]: # ReAuth was loaded on Server #
rate limit exceeded
[06:18:37] [modloading-worker-4/WARN] [yungsapi/]: WARNING: duplicate block Block{minecraft:air} added to BlockSelector!
[06:18:38] [modloading-worker-17/INFO] [co.re.re.ResourcefulBees/]: Registering Custom Honeys..
[06:18:40] [main/INFO] [ne.mi.re.GameData/]: Potentially Dangerous alternative prefix `xencraft` for name `xen_ore`, expected `kubejs`. This could be a intended override, but in most cases indicates a broken mod.
[06:18:40] [main/INFO] [ne.mi.re.GameData/]: Potentially Dangerous alternative prefix `xencraft` for name `xenstone`, expected `kubejs`. This could be a intended override, but in most cases indicates a broken mod.
[06:18:41] [main/INFO] [patchouli/]: Loaded book jsons on Thread[main,5,main] in 103 ms
[06:18:41] [main/INFO] [ne.mi.re.GameData/]: Potentially Dangerous alternative prefix `xencraft` for name `xen_gem`, expected `kubejs`. This could be a intended override, but in most cases indicates a broken mod.
[06:18:42] [main/INFO] [STDOUT/]: [com.hollingsworth.arsnouveau.client.particle.ModParticles:registerParticles:23]: Rendering particles
rate limit exceeded
[06:18:43] [main/INFO] [PluginManager/]: Executing phase CONFIG_LOAD for plugin class FarmersDelightPlugin [06:18:43] [main/INFO] [PluginManager/]: Executing phase CONFIG_LOAD for plugin class ImmersiveEngineeringPlugin
[06:18:43] [modloading-worker-9/INFO] [co.re.re.ResourcefulBees/]: Registering Default Bee Traits...
[06:18:47] [main/INFO] [mojang/YggdrasilAuthenticationService]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[06:18:48] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [c, coupling, add, cart1] and [c, coupling, add, carts] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[06:18:48] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [c, coupling, add, carts] and [c, coupling, add, cart1] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[06:18:48] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [cofh, ignite, duration] and [cofh, ignite, targets] with inputs: [0, -123, 123]
[06:18:48] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [cofh, ignite, targets] and [cofh, ignite, duration] with inputs: [0123]
rate limit exceeded
[06:18:49] [Worker-Main-5/ERROR] [minecraft/JsonReloadListener]: Couldn't parse data file powersuits:modules/environmental/active_camoflage from powersuits:recipes/modules/environmental/active_camoflage.json com.google.gson.JsonParseException: java.io.EOFException: End of input at line 1 column 1 path $ at net.minecraft.util.JSONUtils.func_188173_a(SourceFile:495) ~[?:?] {re:classloading} at net.minecraft.util.JSONUtils.func_193839_a(SourceFile:532) ~[?:?] {re:classloading} at net.minecraft.client.resources.JsonReloadListener.func_212854_a_(JsonReloadListener.java:48) ~[?:?] {re:computing_frames,re:mixin,re:classloading} at net.minecraft.client.resources.JsonReloadListener.func_212854_a_(JsonReloadListener.java:22) ~[?:?] {re:computing_frames,re:mixin,re:classloading} at net.minecraft.client.resources.ReloadListener.func_215270_b(SourceFile:11) ~[?:?] {re:computing_frames,re:mixin,re:classloading} at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) [?:1.8.0_312] {} at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) [?:1.8.0_312] {} at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_312] {} at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_312] {} at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_312] {re:computing_frames} at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_312] {} Caused by: java.io.EOFException: End of input at line 1 column 1 path $ at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1393) ~[server-1.16.5-20210115.111550-extra.jar:?] {} at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:549) ~[server-1.16.5-20210115.111550-extra.jar:?] {} at com.google.gson.stream.JsonReader.peek(JsonReader.java:425) ~[server-1.16.5-20210115.111550-extra.jar:?] {} at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:716) ~[server-1.16.5-20210115.111550-extra.jar:?] {} at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714) ~[server-1.16.5-20210115.111550-extra.jar:?] {} at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:910) ~[server-1.16.5-20210115.111550-extra.jar:?] {} at net.minecraft.util.JSONUtils.func_188173_a(SourceFile:493) ~[?:?] {re:classloading} ... 10 more
[06:18:49] [Worker-Main-5/ERROR] [minecraft/JsonReloadListener]: Couldn't parse data file powersuits:modules/environmental/mob_repulsor from powersuits:recipes/modules/environmental/mob_repulsor.json com.google.gson.JsonParseException: java.io.EOFException: End of input at line 1 column 1 path $ at net.minecraft.util.JSONUtils.func_188173_a(SourceFile:495) ~[?:?] {re:classloading} at net.minecraft.util.JSONUtils.func_193839_a(SourceFile:532) ~[?:?] {re:classloading} at net.minecraft.client.resources.JsonReloadListener.func_212854_a_(JsonReloadListener.java:48) ~[?:?] {re:computing_frames,re:mixin,re:classloading} at net.minecraft.client.resources.JsonReloadListener.func_212854_a_(JsonReloadListener.java:22) ~[?:?] {re:computing_frames,re:mixin,re:classloading} at net.minecraft.client.resources.ReloadListener.func_215270_b(SourceFile:11) ~[?:?] {re:computing_frames,re:mixin,re:classloading} at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) [?:1.8.0_312] {} at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) [?:1.8.0_312] {} at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_312] {} at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_312] {} at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_312] {re:computing_frames} at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_312] {} Caused by: java.io.EOFException: End of input at line 1 column 1 path $ at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1393) ~[server-1.16.5-20210115.111550-extra.jar:?] {} at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:549) ~[server-1.16.5-20210115.111550-extra.jar:?] {} at com.google.gson.stream.JsonReader.peek(JsonReader.java:425) ~[server-1.16.5-20210115.111550-extra.jar:?] {} at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:716) ~[server-1.16.5-20210115.111550-extra.jar:?] {} at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714) ~[server-1.16.5-20210115.111550-extra.jar:?] {} at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:910) ~[server-1.16.5-20210115.111550-extra.jar:?] {} at net.minecraft.util.JSONUtils.func_188173_a(SourceFile:493) ~[?:?] {re:classloading} ... 10 more
[06:18:50] [Worker-Main-9/INFO] [KubeJS Server/]: Found 8450 recipes and 1 failed recipes in 579.9 ms
[06:18:51] [Worker-Main-9/INFO] [KubeJS Server/]: server_scripts:ftbees/bees.autogen_materials.js:44: --- Creating Recipes for Material: apatite
[06:18:52] [Worker-Main-9/ERROR] [minecraft/LootTableManager]: Couldn't parse loot table pipez:blocks/gas_pipe com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'pipez:gas_pipe' at net.minecraft.util.JSONUtils.func_219793_a(SourceFile:127) ~[?:?] {re:classloading} at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_312] {} at net.minecraft.util.JSONUtils.func_188172_b(SourceFile:127) ~[?:?] {re:classloading} at net.minecraft.util.JSONUtils.func_188180_i(SourceFile:135) ~[?:?] {re:classloading} at net.minecraft.loot.ItemLootEntry$Serializer.func_212829_b_(SourceFile:55) ~[?:?] {re:classloading} at net.minecraft.loot.ItemLootEntry$Serializer.func_212829_b_(SourceFile:40) ~[?:?] {re:classloading} at net.minecraft.loot.StandaloneLootEntry$Serializer.func_230421_b_(SourceFile:151) ~[?:?] {re:classloading} at net.minecraft.loot.StandaloneLootEntry$Serializer.func_230421_b_(SourceFile:129) ~[?:?] {re:classloading} at net.minecraft.loot.LootEntry$Serializer.func_230423_a_(SourceFile:86) ~[?:?] {re:classloading} at net.minecraft.loot.LootEntry$Serializer.func_230423_a_(SourceFile:74) ~[?:?] {re:classloading} at net.minecraft.loot.LootTypesManager$Serializer.deserialize(SourceFile:83) ~[?:?] {re:classloading} at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[server-1.16.5-20210115.111550-extra.jar:?] {} at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[server-1.16.5-20210115.111550-extra.jar:?] {} at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[server-1.16.5-20210115.111550-extra.jar:?] {} at com.google.gson.Gson.fromJson(Gson.java:887) ~[server-1.16.5-20210115.111550-extra.jar:?] {} at com.google.gson.Gson.fromJson(Gson.java:952) ~[server-1.16.5-20210115.111550-extra.jar:?] {} at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[server-1.16.5-20210115.111550-extra.jar:?] {} at net.minecraft.util.JSONUtils.func_188179_a(SourceFile:440) ~[?:?] {re:classloading} at net.minecraft.util.JSONUtils.func_188174_a(SourceFile:448) ~[?:?] {re:classloading} at net.minecraft.loot.LootPool$Serializer.deserialize(LootPool.java:183) ~[?:?] {re:classloading} at net.minecraft.loot.LootPool$Serializer.deserialize(LootPool.java:180) ~[?:?] {re:classloading} at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[server-1.16.5-20210115.111550-extra.jar:?] {} at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[server-1.16.5-20210115.111550-extra.jar:?] {} at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[server-1.16.5-20210115.111550-extra.jar:?] {} at com.google.gson.Gson.fromJson(Gson.java:887) ~[server-1.16.5-20210115.111550-extra.jar:?] {} at com.google.gson.Gson.fromJson(Gson.java:952) ~[server-1.16.5-20210115.111550-extra.jar:?] {} at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[server-1.16.5-20210115.111550-extra.jar:?] {} at net.minecraft.util.JSONUtils.func_188179_a(SourceFile:440) ~[?:?] {re:classloading} at net.minecraft.util.JSONUtils.func_188177_a(SourceFile:456) ~[?:?] {re:classloading} at net.minecraft.loot.LootTable$Serializer.deserialize(LootTable.java:252) ~[?:?] {re:classloading} at net.minecraft.loot.LootTable$Serializer.deserialize(LootTable.java:249) ~[?:?] {re:classloading} at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[server-1.16.5-20210115.111550-extra.jar:?] {} at com.google.gson.Gson.fromJson(Gson.java:887) ~[server-1.16.5-20210115.111550-extra.jar:?] {} at com.google.gson.Gson.fromJson(Gson.java:952) ~[server-1.16.5-20210115.111550-extra.jar:?] {} at com.google.gson.Gson.fromJson(Gson.java:925) ~[server-1.16.5-20210115.111550-extra.jar:?] {} at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:881) ~[forge:?] {re:mixin,re:classloading,pl:mixin:APP:fastbenchminusreplacement.mixins.json:ForgeHooksMixin,pl:mixin:A} at net.minecraft.loot.LootTableManager.lambda$apply$0(LootTableManager.java:40) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:placebo:lootmanager,re:classloading,pl:accesstransformer:B,xf:fml:placebo:lootmanager,pl:mixin:A} at dev.latvian.kubejs.core.LootTablesKJS.applyKJS0(LootTablesKJS.java:38) ~[kubejs:1605.3.19-build.229] {re:mixin,re:classloading} at net.minecraft.loot.LootTableManager.redirect$zhj000$applyKJS(LootTableManager.java:521) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:placebo:lootmanager,re:classloading,pl:accesstransformer:B,xf:fml:placebo:lootmanager,pl:mixin:A} at net.minecraft.loot.LootTableManager.func_212853_a_(LootTableManager.java:38) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:placebo:lootmanager,re:classloading,pl:accesstransformer:B,xf:fml:placebo:lootmanager,pl:mixin:A} at net.minecraft.loot.LootTableManager.func_212853_a_(LootTableManager.java:16) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:placebo:lootmanager,re:classloading,pl:accesstransformer:B,xf:fml:placebo:lootmanager,pl:mixin:A} at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?] {re:computing_frames,re:mixin,re:classloading} at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_312] {} at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_312] {} at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_312] {} at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:computing_frames,re:classloading} at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?] {re:computing_frames,re:classloading} at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543) ~[?:1.8.0_312] {} at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667) ~[?:1.8.0_312] {} at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_312] {} at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_312] {} at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575) ~[?:1.8.0_312] {} at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:649) ~[?:1.8.0_312] {} at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_312] {} at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:computing_frames,re:classloading} at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?] {re:computing_frames,re:classloading} at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543) ~[?:1.8.0_312] {} at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667) ~[?:1.8.0_312] {} at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_312] {} at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_312] {} at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575) ~[?:1.8.0_312] {} at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:649) ~[?:1.8.0_312] {} at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_312] {} at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:computing_frames,re:classloading} at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?] {re:computing_frames,re:classloading} at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543) ~[?:1.8.0_312] {} at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667) ~[?:1.8.0_312] {} at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_312] {} at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_312] {} at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575) ~[?:1.8.0_312] {} at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:649) ~[?:1.8.0_312] {} at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_312] {} at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:computing_frames,re:classloading} at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?] {re:computing_frames,re:classloading} at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543) ~[?:1.8.0_312] {} at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667) ~[?:1.8.0_312] {} at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_312] {} at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_312] {} at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) ~[?:1.8.0_312] {} at net.minecraft.resources.AsyncReloader$1.func_216873_a(SourceFile:53) ~[?:?] {re:classloading} at net.minecraft.resources.AsyncReloader$1.func_216872_a(SourceFile:50) ~[?:?] {re:classloading} at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966) [?:1.8.0_312] {} at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940) [?:1.8.0_312] {} at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_312] {} at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609) [?:1.8.0_312] {} at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) [?:1.8.0_312] {} at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_312] {} at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_312] {} at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_312] {re:computing_frames} at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_312] {}
[06:18:53] [Worker-Main-9/INFO] [placebo/]: Registered 0 additional loot tables.
rate limit exceeded
[06:18:53] [Worker-Main-9/INFO] [minecraft/AdvancementList]: Loaded 5372 advancements
[06:18:56] [Server thread/INFO] [minecraft/DedicatedServer]: Starting minecraft server version 1.16.5 [06:18:56] [Server thread/INFO] [minecraft/DedicatedServer]: Loading properties
[06:18:56] [Server thread/INFO] [minecraft/DedicatedServer]: Default game type: SURVIVAL
[06:18:56] [Server thread/INFO] [minecraft/MinecraftServer]: Generating keypair
[06:18:56] [Server thread/INFO] [minecraft/DedicatedServer]: Starting Minecraft server on 45.35.66.75:25835
[06:18:57] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing start region for dimension minecraft:overworld
[06:18:58] [Server thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 0%
rate limit exceeded
[06:18:58] [Server thread/INFO] [ne.cr.mi.MineTogether/]: Current discoverability: unlisted
[06:18:59] [Server thread/INFO] [FTB Utilities Backups/]: Backups folder - /home/sid_596155/minecraft_ftb_ultimate_anniversary_edition/backups
[06:19:00] [Server thread/INFO] [ne.mi.co.AdvancementLoadFix/]: Using new advancement loading for net.minecraft.advancements.PlayerAdvancements@532d0ef3

### Describe the bug

Early game I created a basic Steve's Cart setup: Crafted the cart assembler bench, made a basic wood cutter cart, and everything worked fine.

Several days later I decided to make a more advanced setup (reinforced hull, hardened wood cutter, etc). When I started the assembly of the cart, the time to complete was negative in percentage. It started at -100% and went to zero. When it finished, there was no cart, all the items disappeared. I deleted the bench, and crafted a new one. I console gave myself the pieces back and tried again, got the same result. I thought maybe one/some of the components for the cart was bugged, so I created an identical setup to the original basic cart I made, and it also suffered from the same bug. Now I can no longer craft a cart.

When enabling debug mode in game, and hovering over the Cart Assembler (and some other Steve's Cart items) in the JEI browser I noticed item tags of "resourcefulbees:valid_apiary" instead of "stevescarts:module_etc_etc" (screenshot attached).

### Steps to reproduce

1. Try and craft a cart with the following components:
- Reinforced Hull
- Coal Engine
- Hardened Wood Cutter
- Side Chests

### Expected behaviour

The cart is created and able to retrieve from the Cart Assembler bench.

### Screenshots

![cart-assembler-jei-bees](https://user-images.githubusercontent.com/82165558/147437843-5d306a9b-8bb2-45ab-95f0-9ff2d9291e40.jpg)

### Additional information

It's only me and 3 other friends on the server, we haven't modified anything since we launched the server (hosted through gPortal). My one friend recently started messing around with the Resourceful Bee mod, and he hadn't when I had crafted the original cart successfully. Considering the odd item tags, maybe once he crafted/placed something from the resourceful bee mod it messed up something with Steve's Carts? Not sure.

The log file attached is the server console when I restarted the server. If there is somewhere else I should be grabbing log files from I can get those as well, I am the server admin.

**Comment by Raidobw2** [comment] 2021-12-27 05:40
Will check in a bit to see if I can reproduce it. I don't know the mod, so I thank you for this report and the info to create a cart. To my knowledge that tag shouldn't mess with anything, but I'll report back here with results in a bit. Might need a mod update, I'll take care of forwarding that if so.

**Comment by AdamBundschuh** [comment] 2021-12-27 05:42
> Will check in a bit to see if I can reproduce it. I don't know the mod, so I thank you for this report and the info to create a cart. To my knowledge that tag shouldn't mess with anything, but I'll report back here with results in a bit. Might need a mod update, I'll take care of forwarding that if so.

Unfortunately the bug probably won't replicate for you, as Steve's Carts worked fine originally for me. I'll assemble another cart with a screenshot of the bugged cart UI/interface.

**Comment by AdamBundschuh** [comment] 2021-12-27 05:51
Okay, another wrench in the recreation steps. 

I was able to create a basic setup with the following items (although this setup did bug on me before):
Basic Hull
Coal Engine
Basic Wood Cutter
Side Chests

I got the negative percentage bug with the following components:
Reinforced Hull
Coal Engine
Hardened Wood Cutter
Side Chests


![after_clicking_assemble_01](https://user-images.githubusercontent.com/82165558/147438954-3998c38f-e140-4b84-8483-744dd598cb4b.jpg)

**Comment by AdamBundschuh** [comment] 2021-12-27 06:27
The negative percentage finally stopped here (and did not produce the cart):

![negative_finish](https://user-images.githubusercontent.com/82165558/147441419-e6fec204-4b82-4b42-aece-18ef3e7d8763.jpg)

**Comment by Raidobw2** [comment] 2021-12-27 08:03
Hmm after testing it I think you're missing fuel. You don't have any more coal in the last picture. The timer is off for sure going negative, leave this issue opened please for that matter.

As for the cart, given enough fuel and time, it looks like it works (I used the reinforced hull and woodcutter things):
![image](https://user-images.githubusercontent.com/17010632/147449445-9d1749b9-e4fe-48ef-8ea1-7460b3668d85.png)
Cheers

**Comment by AdamBundschuh** [comment] 2021-12-27 13:08
Wow, confirmed, I got the same results after 3ish+ stacks of coal. Nice catch!

**Comment by LatvianModder** [comment] 2021-12-31 16:40
Dupe of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/430 and also reported to mod author

**Closed by LatvianModder** 2021-12-31 16:40 UTC
Labels: 1: Mod Issue, state: Awaiting Mod Update, FTB Ultimate: Anniversary Edition
