### ISSUE TITLE
Digital Miner in RFToolsDimension Dimension randomly started crashing server.

### ISSUE THREAD

**Issue by JoshWidrick** [FTBTeam/FTB-Modpack-Issues#2698] opened 2023-02-09 19:59 UTC
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.3.2

### Log Files

[crash-2023-02-09_14.37.20-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10700996/crash-2023-02-09_14.37.20-server.txt)
[crash-2023-02-09_14.38.23-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10700997/crash-2023-02-09_14.38.23-server.txt)

### Describe the bug

My server just randomly crashed today, and crashes upon starting up. Looking through the crash files, it appears that it is caused by a Digital Miner in an RFToolsDimensions Dimension.  

### Steps to reproduce

I can provide server files if required.

1. Create RFToolsDimensions Dimension
2. Put Digital Miner in
3. Let Digital Miner finish mining
4. Wait

### Expected behaviour

The server starts up normally and doesn't crash.

**Comment by DeadlySaint** [comment] 2023-02-09 21:02
Was coming here to post the same thing. This looks like an issue with the Mekanism main mod. There appears to be a fix for it in the latest version. So manually updating the mod should solve the issue until the modpack is updated.

**Comment by Shiny1708** [comment] 2023-02-10 04:43
Same thing, but in the overworld

**Comment by jondwaite** [comment] 2023-02-19 08:21
Pretty sure this is the same issue I had earlier today caused by having a Digital Miner (Mekanism) with an Anchor upgrade in it. Manually updating the 4 Mekanism .jar files from 10.3.7 to 10.3.8 fixed it for me.

**Comment by Saereth** [comment] 2023-02-22 03:42
this should be fixed in the update

**Closed** 2023-02-23 01:13 UTC
Labels: state: Fixed in Dev :hammer_and_wrench:, FTB Presents Direwolf20 1.19
