### ISSUE TITLE
[Suggestion]: Refined Storage addons

### ISSUE THREAD

**Issue by PianoHallvard** [FTBTeam/FTB-Modpack-Issues#1641] opened 2022-11-04 23:36 UTC
### Modpack

StoneBlock 3

### Is your suggestion related to a problem? Please describe.

Not really, just a QoL kinda thing

### Mod suggestion

3 mods, all refined storage addons

External Storage, adds better crafters which are faster and have more pattern space (that's what I've used this mod for at least): https://www.curseforge.com/minecraft/mc-mods/extrastorage

Reborn Storage, which primarily adds a multiblock crafter: https://www.curseforge.com/minecraft/mc-mods/rebornstorage

Extra Disks, adds larger disks: https://www.curseforge.com/minecraft/mc-mods/extra-disks

I was also gonna request RSRequestify (pun intended), but saw that it was already in the pack

**Comment by Sunekaer** [comment] 2022-11-05 16:49
Duplicate of #1599

**Closed by Sunekaer** 2022-11-05 16:49 UTC
Labels: FTB StoneBlock 3
