### ISSUE TITLE
Raw iron ore can't be pulverized

### ISSUE THREAD

**Issue by mikesellt** [FTBTeam/FTB-Modpack-Issues#2713] opened 2023-02-13 18:41 UTC
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.3.2

### Describe the bug

Thermal series Pulverizer doesn't accept raw iron.  The recipe for thermal iron dust shows you can put raw iron in the pulverizer to get it.  

### Steps to reproduce

1. put raw iron in pulverizer
2. nothing happens

### Expected behaviour

Raw iron in the pulverizer should output one or more iron dust.

**Comment by FagSoft** [comment] 2023-02-14 09:46
Duplicate of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2688

**Comment by FagSoft** [comment] 2023-02-14 09:48
Copy of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2631

**Closed** 2023-02-22 03:08 UTC
Labels: state: Duplicate :books:, FTB Presents Direwolf20 1.19
