### ISSUE TITLE
Constant message: Can't keeup up! is the server overloaded? Running x ticks behind

### ISSUE THREAD

**Issue by Pecako2001** [FTBTeam/FTB-Modpack-Issues#3333] opened 2023-05-09 13:56 UTC
### Modpack

FTB Skies

### Modpack version

1.0.9

### Log Files

[2023-05-09-6.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11431833/2023-05-09-6.log.gz)

### Describe the bug

Game is really laggy since the new version. Game fps and usage of CPU and RAM seem normal 

### Steps to reproduce

-

### Expected behaviour

Normal behavior of the modpack without lag.

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/77498283/abdc1803-09e5-4537-bcd1-0ba12a1d5581)

**Comment by MichaelHillcox** [comment] 2023-05-09 21:58
Duplicate of #3334

**Closed by MichaelHillcox** 2023-05-09 21:58 UTC
Labels: FTB Skies
