### ISSUE TITLE
[Bug]: FTB Guides icon keeps blinking

### ISSUE THREAD

**Issue by No-steve** [FTBTeam/FTB-Modpack-Issues#1319] opened 2022-09-11 12:02 UTC
### Modpack

ftb sky odyssey

### Modpack version

v1.4.1

### Describe the bug

The [!]icon in the upper left is blinking

### Steps to reproduce

bug

### Expected behaviour

hide the icon

### Screenshots

![2022-09-11_20 46 43](https://user-images.githubusercontent.com/105639186/189526348-39feb8be-2034-452b-a9a5-760fea02bcfe.png)

**Comment by Raidobw2** [comment] 2022-09-14 03:31
These are the FTB guides to help you play the modpack, because there are many changes. If you read those guides, does it stop blinking or does it continually blink even if you've read all the pages?

**Comment by No-steve** [comment] 2022-09-14 13:58
Yes

**Comment by Raidobw2** [comment] 2022-09-15 09:43
Ok, if it stops blinking that would be normal FTB Guides behavior, so it's not a bug. The guides exist to be read after all, Slowpoke and the rest of the FTB Team wrote those for gameplay tips. I'll close this then

**Closed by Raidobw2** 2022-09-15 09:43 UTC
Labels: FTB Sky Odyssey, 3: Support Request

**Comment by No-steve** [comment] 2022-09-15 13:21
Blinking icons are an eyesore, so I created the issue.
Is it possible to turn off the blinking after reading the guide?

**Comment by MichaelHillcox** [comment] 2022-09-15 14:38
Nope

**Comment by No-steve** [comment] 2022-09-15 15:54
Oh god
