### ISSUE TITLE
Muramasa/Katana from tetra not considered weapons by apotheosis

### ISSUE THREAD

**Issue by charlesgael** [FTBTeam/FTB-Modpack-Issues#3191] opened 2023-04-20 22:41 UTC
### Modpack

FTB Skies

### Modpack version

1.0.4

### Describe the bug

Tried doing reforging at the apotheosis table with katana and muramasa, but only "tools" upgrade are showing.

### Steps to reproduce

1. Forge katana/muramasa (you need the recipes scrolls) with any materials
2. Put it in the reforging table with dust and material
3. Only tool related upgrades are showing

### Expected behaviour

Weapon related upgrades should be showing

### Here is muramasa in table
![image](https://user-images.githubusercontent.com/4885210/233501805-beb3bc82-ebe7-4d24-a8a3-fe6c48183fd8.png)

### When using with **other tetra weapons**, it is working fine:
![image](https://user-images.githubusercontent.com/4885210/233501880-fb474788-6984-44a9-a270-bbe8647f5073.png)

**Comment by Saereth** [comment] 2023-04-26 19:13
This the way tetra defines their tools as part of their customization process. It's been reported and Shadows wont be changing it in apotheosis so it'll rely on tetra or an addon mod to fix it eventually

**Comment by Saereth** [comment] 2023-05-19 02:43
I have confirmed this wont be fixed by apotheosis and since it doesnt impact Tetras' design it likely just wont be fixed in general. Unfortunate

**Closed by Saereth** 2023-05-19 02:43 UTC
Labels: 1: Mod Issue, FTB Skies
