### ISSUE TITLE
[Suggestion]: [Stoneblock 3] Add Extrastorage or Reborn storage

### ISSUE THREAD

**Issue by Anoyomouse** [FTBTeam/FTB-Modpack-Issues#1788] opened 2022-11-09 09:13 UTC
### Modpack

Stoneblock 3

### Is your suggestion related to a problem? Please describe.

I've just started a Stoneblock with my friends, and we're extreme users of crafting automation (getting Refined Storage to craft everything for us). however, only having access to the default crafters in Refined Storage is limiting, but can be worked around by having a huge pile of crafters in the world (we're talking more than 64 tucked away).

### Mod suggestion

My suggestion would be to add [Extra storage](https://www.curseforge.com/minecraft/mc-mods/extrastorage) mostly for the Tiered crafters (Iron, Gold, Diamond and Netherite), and potentially the expanded Exporters and Importers. (the extra storage though nice could also be disabled).

An alternative would be [Reborn Storage](https://www.curseforge.com/minecraft/mc-mods/rebornstorage) with it's multiblock crafter and extra crafting CPUs.

**Comment by Sunekaer** [comment] 2022-11-09 16:56
Duplicate of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1599

**Closed by Sunekaer** 2022-11-09 16:56 UTC
