### ISSUE TITLE
Crash when sorting inventory with Soul Crystal in it

### ISSUE THREAD

**Issue by siconnellym** [FTBTeam/FTB-Modpack-Issues#2793] opened 2023-03-05 23:22 UTC
### Modpack

FTB Legend of the Eyes

### Modpack version

1.4.0

### Log Files

03/05/2023 - 15:12:27
INSTANCE
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1937.method_8433()" because "level" is null
	at me.codexadrian.spirit.data.Tier.getTiers(Tier.java:86)
	at me.codexadrian.spirit.data.Tier.getTier(Tier.java:53)
	at me.codexadrian.spirit.data.Tier.getTier(Tier.java:82)
	at me.codexadrian.spirit.utils.SoulUtils.getTier(SoulUtils.java:36)
	at me.codexadrian.spirit.items.SoulCrystalItem.shiftToolTipComponents(SoulCrystalItem.java:50)
	at me.codexadrian.spirit.items.SoulCrystalItem.method_7851(SoulCrystalItem.java:42)
	at net.minecraft.class_1799.method_7950(class_1799.java:699)
	at snownee.jade.addon.vanilla.ItemTooltipProvider.appendTooltip(ItemTooltipProvider.java:29)
	at snownee.jade.impl.EntityAccessorImpl._gatherComponents(EntityAccessorImpl.java:81)
	at snownee.jade.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:127)
	at snownee.jade.util.ClientPlatformProxy.onClientTick(ClientPlatformProxy.java:156)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$cbg000$onEndTick(class_310.java:11473)
	at net.minecraft.class_310.method_1574(class_310.java:1907)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Describe the bug

When trying to sort the inventory containing any Soul Crystals (using middle mouse button), the game crashes.

### Steps to reproduce

1. Have Soul Crystal in the inventory
2. Middle mouse button in the inventory

### Expected behaviour

The inventory should sort without crashing

**Comment by TheonlyTazz** [comment] 2023-03-06 07:38
duplicate of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2598

**Closed by TheonlyTazz** 2023-03-06 07:38 UTC
Labels: FTB Legend of the Eyes
