### ISSUE TITLE
Crashing on FTB NeoTech 

### ISSUE THREAD

**Issue by ghostwalker788** [FTBTeam/FTB-Modpack-Issues#5393] opened 2024-06-25 22:41 UTC
### Modpack

FTB NeoTech

### Modpack version

1.2.1

### Has the pack been modified

Yes

### Log Files

[crash-2024-06-26_08.26.36-client.txt](https://github.com/user-attachments/files/15980042/crash-2024-06-26_08.26.36-client.txt)

### Describe the bug

crash to desktop no seaming consistency started when in a frost caven with skulk 3 times now its happend twice on the surface where im based. 

i did add Embedium extras to the pack to remove fog. i have disabled it now ill say if it crashes again after. (honestly i dont think that would crash it, extras is 1.20.4)

### Steps to reproduce

sorry i dont have a way to reproduce the issue like a i said its just happening at odd times and several hours between crashes

### Expected behaviour

not crashing?

**Comment by ghostwalker788** [comment] 2024-06-26 03:16
[app log.txt](https://github.com/user-attachments/files/15981826/app.log.txt)

had another crash this time there were no changes to the modpack embedium extras was both dissablesd and deleted

**Comment by Gaz492** [comment] 2024-06-26 07:40
Is this still an issue for you on the latest update?
Your initial crash looks to be caused by cooking for blockheads while your new log suggests java ran into a fatal error.

**Comment by ghostwalker788** [comment] 2024-06-26 13:40
it has been the latest update as i was playing although there is a update to the pack overnight

**Comment by Saereth** [comment] 2024-07-03 21:52
cooking for blockheads got a bug fix update which will be included in 1.4.0 of the pack

**Closed** 2024-07-10 21:38 UTC
Labels: state: Fixed in Dev, Bug, FTB NeoTech, @Mod issue
