### ISSUE TITLE
[Bug]: Game Crashes Randomly

### ISSUE THREAD

**Issue by demwara** [FTBTeam/FTB-Modpack-Issues#455] opened 2021-12-10 14:19 UTC
### Modpack

FTB OceanBlock

### Modpack version

1.10.0

### Log Files

[crash-2021-12-10_14.00.01-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7693259/crash-2021-12-10_14.00.01-client.txt)
[crash-2021-12-10_14.59.42-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7693260/crash-2021-12-10_14.59.42-client.txt)

### Describe the bug

I don't really know what happens. I look around and my it just crashes. It was fine in the beginning but since i made a boat and went to the nearest rafts. It crashes when i look around or when i exit JEI.

### Steps to reproduce

Don't really know
1. Went to a raft
2. Opened JEI sort inventory/search something/move an item around
3. Close it
4. Game crashes

### Expected behaviour

Preferable for ht game not to crash?

### Additional information

I looked around on here to see if there were others with the same problem. But I can perfectly search for draconic and it won't crash and I don't get any hs_err_pid files in thecrash-reports or logs folder.

**Comment by Raidobw2** [comment] 2021-12-11 07:03
Can you update to 1.10.1 and tell us if the issue is resolved? There was a hotfix distributed for 1.10.1 which fixed some CodeChicken issues, which do appear in your game log. Thanks!
And feel free to close the issue if that resolved it please! :)

**Comment by demwara** [comment] 2021-12-11 20:33
The problem was indeed fixed with updating to 1.10.1. thanks for the help. I had not updated yet because somehow ATLauncher sees 1.10.0 as the latest version and not the updated one, even when I updated to the 1.10.1 version my launcher was like there is a newer version and pointed to the .0 version. so was a bit confused XD

![image](https://user-images.githubusercontent.com/67229873/145690754-9cc29319-9246-4043-879d-cf206f2c0b6a.png)
![image](https://user-images.githubusercontent.com/67229873/145690792-266054e9-774f-443c-9d57-1977ece11083.png)

**Closed** 2021-12-11 20:34 UTC
Labels: FTB OceanBlock, cat: Support Request

**Comment by Raidobw2** [comment] 2021-12-12 12:11
Awesome! Glad to hear that solved it ^-^
