### ISSUE TITLE
[Bug]: Wave mobs from Gateways to Eternity spawning way below player's position

### ISSUE THREAD

**Issue by rmedzihradsky** [FTBTeam/FTB-Modpack-Issues#1905] opened 2022-11-12 20:04 UTC
### Modpack

FTB Inferno

### Modpack version

1.3.0

### Describe the bug

When opening a new gateway and fighting through waves, some of the mobs can spawn at vastly different y-level than the player is currently on. I tried to beat the Bellringer Gate twice, and both times on the second and third wave some (2 or 3) of the 5 spawned mobs were deep below my position (I was on the bedrock roof Y=128, they were at around Y=50). This makes the gates almost impossible to beat, as travelling up and down takes too much time.
This also happened with the randomly encountered gate, also on the 2nd or 3rd wave.

### Steps to reproduce

1. Wait for a Gate to appear or create a gate-opening item and use it
2. Fight through the wave
3. Wait for new wave
4. Try to locate newly spawned enemies; If all are on the same Y-level as player, go back to step 2
5. If not all enemies are located, go to spectator mode and search below the initial Y-level

### Expected behaviour

Mobs spawning at roughly the same Y-level as the player

**Comment by orbidlo** [comment] 2022-11-13 09:46
I've already created issue for it https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1858 but good point that all portals are affected.

**Comment by Saereth** [comment] 2022-11-21 07:12
this  issue is addressed in the update to be released soon but already referenced (same root cause) here:
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1858
so closing to avoid duplicates

**Closed by Saereth** 2022-11-21 07:12 UTC
Labels: FTB Inferno
