### ISSUE TITLE
Game "Waiting for server" near Iron's Spells 'n Magic Structures

### ISSUE THREAD

**Issue by Alsaraganza** [FTBTeam/FTB-Modpack-Issues#4465] opened 2023-12-13 18:44 UTC
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.10.0

### Log Files

[2023-12-13-5[1].log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13664359/2023-12-13-5.1.log)

### Describe the bug

While exploring, I came across a village with a nearby Iron's Spells 'n Magic structure. When the game tried to load those chunks, I could no longer interact with entities, sleep, etc. Broken blocks don't drop their items. Unloaded chunks around the area would not load and falling off the world keeps going past y: -10000. Quitting the game via the menu froze on the "saving world" screen. 

While testing, I disabled "Iron's Spells 'n Magic" and could explore the coordinates without issue. 

### Steps to reproduce

Create World with Seed 8297981308001627535.
Teleport to x:260, z:2200
Check "The One Probe" window for "Waiting for Server", the non-interactable villagers nearby or that broken blocks don't drop as items. 

### Expected behaviour

No permanent freezes while playing the game

**Comment by DinnerBeef** [comment] 2023-12-18 17:16
How much ram do you have assigned to the pack?

**Comment by Alsaraganza** [comment] 2023-12-18 17:41
I allocated 6144MB.

**Comment by SpiderNam219** [comment] 2023-12-21 00:40
I have the same issue and I have nearly 38288 ram dedicated to it

**Comment by Alsaraganza** [comment] 2023-12-24 09:50
> How much ram do you have assigned to the pack?
I allocated 6144MB.

**Comment by Ferrero1299** [comment] 2023-12-26 21:14
Same here, allocated 6144MB, any help?

**Comment by pilotstev** [comment] 2024-01-02 03:09
Having the same issue with a brand new install. World works fine until I came across one of the structures mentioned. Allocated a tonne of RAM (80+GB) and made no difference. Issue seems to cause game server to crash, noticeable when entities freeze, tool tip on top left says "waiting on server" instead of tool to use, and when saving and quitting it hangs on "Saving World"

Seed [-8328566712207997216]
XYZ: 82,336 / 70.00000/-1762201



![2024-01-01_21 27 26](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/155409091/1dd1160f-b112-4fcf-8db3-123c92ddc727)
![2024-01-01_21 48 32](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/155409091/952db4a0-2f01-447c-ae77-600e4664eca1)
![2024-01-01_21 54 12](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/155409091/ae1c3ac9-d5bc-4dec-a6a2-e52a21954846)

**Comment by Suni-Shinobi** [comment] 2024-01-16 21:16
disabling nomowanderer mod has fixed this in some cases its caused by loot chests or barrels?

**Comment by DinnerBeef** [comment] 2024-01-18 16:13
Can you please let me know if this issue is still happening for you after the next update?

**Comment by pilotstev** [comment] 2024-01-18 16:17
I cant speak for the others, but I created a new world after having that issue and havent had it again since, despite staying with that version of the pack. Sorry I dont have any more info for you guys, not sure exactly what may have caused it.

**Comment by M3L6H** [comment] 2024-01-19 00:37
Can confirm that I was experiencing a similar issue yesterday. Unsure about the Iron's Spells and Magic angle, but I was playing in my world for a few hours when it stopped responding with the same "Waiting for Server" message. Saving would stall and not complete. Tried force quitting and re-entering the world a few times. Interestingly it seemed to save the location of my player but not the torches I had placed in the last several minutes. The world would act normally for another few minutes then display this behavior again. 

Stumbled across this thread and tried disabling NoMoWanderer. Haven't had the issue since.

**Comment by Akivar** [comment] 2024-02-25 06:09
I can confirm I had this issue, it was like there was a "Zone" around an unloaded area in the world.
"NoMoWanderer - Disabled" 
I can confirm that immediately fixed the issue. 
I cannot explain what it is or why But I do have some logs that i'll save

**Closed** 2024-06-18 20:15 UTC
Labels: state: Fixed in Dev, FTB Presents Direwolf20 1.20
