### ISSUE TITLE
FTB Revelation Cant craft iron plate

### ISSUE THREAD

**Issue by lucasbdv** [FTBTeam/FTB-Modpack-Issues#4550] opened 2024-01-11 02:38 UTC
### Modpack

FTB Revelation

### Modpack version

3.6.0

### Describe the bug

![2024-01-10_23 35 42](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/82412600/62accce5-6a83-4762-9f25-f917c67c3c41)
![2024-01-10_23 35 47](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/82412600/07a6aa9e-df3a-4ce9-915e-b242b3da893b)

I Cant craft iron plate

### Steps to reproduce

trying to craft iron plate

### Expected behaviour

being able to craft iron plate

**Comment by lucasbdv** [comment] 2024-01-11 02:50
if you have this problem the solution is to downgrade to 3.5.0

**Comment by Gaz492** [comment] 2024-06-06 11:12
Duplicate of #5175

**Closed by Gaz492** 2024-06-06 11:12 UTC
Labels: FTB Revelation
