### ISSUE TITLE
[Bug]: Mekanism cardboard box void extra storage crafter inventory

### ISSUE THREAD

**Issue by Solousia** [FTBTeam/FTB-Modpack-Issues#296] opened 2021-11-10 19:04 UTC
### Modpack

FTB oceanblock

### Modpack version

1.7.0

### Describe the bug

Using cardboard box on any extra storage crafter with any pattern inside will void all the pattern when place it back down.
Not sure is it the mekanism side or extra storage side that have the problem.

### Steps to reproduce

1. Get mekanism cardboard box
2. Get refine storage addon extra storage crafter. i.e netherite crafter
3. Place any amount of pattern inside crafter
4. Try to move the crafter using cardboard box
5. Place the cardboard box down again
6. Now all pattern are gone

### Expected behaviour

Pattern stay inside after place the cardboard box

**Comment by Sunekaer** [comment] 2021-11-10 19:54
duplicate of #33

**Closed by Sunekaer** 2021-11-10 19:54 UTC
Labels: FTB OceanBlock, state: Duplicate :books:
