### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by joosthoi1** [FTBTeam/FTB-Modpack-Issues#1942] opened 2022-11-14 09:54 UTC
### Modpack

Ftb StoneBlock 3

### Modpack version

1.2.1

### Log Files

https://paste.ee/p/U8HFG

### Describe the bug

When trying to start the game it crashes. It crashes even before opening the Minecraft window (MultiMC, though it also crashes directly from the ftb app). It was working just fine when I first started the pack.

### Steps to reproduce

These are all the things I did thusly in the pack.

1. start the pack and it worked
2. create a world
3. I did do /backup create but idk if it matters
4. tried to launch the pack today

### Expected behaviour

It does not crash when I start the game

### Additional information

Disabling MineTogether worked, but obviously I lose backups.

I think its probably something about a creeperhost server being down or something being broken on their end. Though it should not have to connect with them when starting up IMO

**Comment by Sunekaer** [comment] 2022-11-14 17:11
Duplicate of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1768

**Closed by Sunekaer** 2022-11-14 17:11 UTC
