### ISSUE TITLE
[Suggestion]: ExtraStorage Addon SB3

### ISSUE THREAD

**Issue by Pienapples** [FTBTeam/FTB-Modpack-Issues#1941] opened 2022-11-14 09:24 UTC
### Modpack

FTB StoneBlock 3

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/extrastorage

The Mod adds some upgradable tiers to the RefinedStorage blocks (Crafter, Storage Blocks, Storage Disks, Fluid Blocks, Fluid Disks) adding 4 additional tiers. As well adds an Advanced Exporter/Importer that gives us double the slots of a normal Exporter/Importer. It's more of a QoL type of mod but allows you to be a bit more versatile with your System without the need of creating unorganized messes of Storage, Crafters, Cables, etc.

**Comment by Sunekaer** [comment] 2022-11-14 17:07
Duplicate of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1599

**Closed by Sunekaer** 2022-11-14 17:07 UTC
