### ISSUE TITLE
Resource pack fails to load

### ISSUE THREAD

**Issue by Gnomeo** [FTBTeam/FTB-Modpack-Issues#5807] opened 2024-09-22 01:26 UTC
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.1.2

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

none, just "resource failed to load" message

### Describe the bug

Trying to use a vanilla 1.21 resource pack to replace vanilla textures. Resource pack works in vanilla 1.21. Resource pack included below.

### Steps to reproduce

1. From main menu go to Options/Resource Packs...
2. Move resource pack from left side to right side, above the other resource packs
3. Select Done

### Expected behaviour

Resource pack loads and replaces vanilla textures

### Screenshots

![image](https://github.com/user-attachments/assets/0f4ec46c-0f2e-4da6-865d-9cf9d2e99417)
![image](https://github.com/user-attachments/assets/a08d9b15-7f28-4e89-9bca-a4d6827f6cd9)

### Additional information

[Isabella x 1.21.zip](https://github.com/user-attachments/files/17087881/Isabella.x.1.21.zip)

**Comment by Gaz492** [comment] 2024-09-22 11:32
This might be a duplicate of #5770, but ill keep this open just in case it's not.
!skip

**Comment by Saereth** [comment] 2024-09-25 20:01
yes this is a duplicate and should be fixed in 1.2 
<img width="1910" alt="image" src="https://github.com/user-attachments/assets/ee53bb5b-35bd-402e-8130-013b8292f989">

**Closed** 2024-09-25 20:02 UTC
Labels: state: Testing required, Bug, FTB Presents Direwolf20 1.21

**Comment by Gnomeo** [comment] 2024-09-25 23:25
Thank you!
