### ISSUE TITLE
Xycraft lava extractor recipe wrong in JEI

### ISSUE THREAD

**Issue by NotPiffany** [FTBTeam/FTB-Modpack-Issues#5823] opened 2024-09-23 23:52 UTC
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.1.2

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

The recipe in JEI for lava shows the extractor on top with a dripstone block underneath it and a lava source block underneath that. In the game, I had to reverse that in order for it to work: lava over dripstone over the extractor over a fluid drawer.

### Steps to reproduce

1. Place a lava source block.
2. Place a dripstone block over the lava.
3. Place an extractor on the dripstone block
4. Place a tank or fluid drawer on top of the extractor.
5. Nothing happens; the extractor stays dark.

### Expected behaviour

I expected the extractor to work with the dripstone and lava underneath it, following the JEI diagram.

**Comment by Saereth** [comment] 2024-09-25 21:12
reported to soaryn https://github.com/Soaryn/XyCraftTracker/issues/66

**Comment by Soaryn** [comment] 2024-09-25 21:25
Rotate the entire thing upside down. Think vanilla dripstone essentially. This is because the JEI integration atm is using itemstacks and not a blockstate rendered in UI atm. Is on the todo

**Comment by Saereth** [comment] 2024-09-25 21:53
As this is not a bug and more a display issue that will be worked on later I'm closing this issue, ty for reporting!

**Closed by Saereth** 2024-09-25 21:53 UTC
Labels: Bug, @Reported to Mod Dev, @Mod issue, FTB Presents Direwolf20 1.21
