### ISSUE TITLE
Tool dupe

### ISSUE THREAD

**Issue by Colin1232** [FTBTeam/FTB-Modpack-Issues#3143] opened 2023-04-16 07:15 UTC
### Modpack

FTB Skies

### Modpack version

1.0.6

### Describe the bug

it is a bug that duplicates that item

### Steps to reproduce

1. get a tool with the thing that says "This tool can place a torch at the cost of 7 durability" (i got it from a spoils bag)
2.  right click it on the ground and it should say you have 2 of them
3. right-click in your inventory to separate it and now you have 2

### Expected behaviour

The thing that makes it so you can place a torch creates another version of the item

### Screenshots

https://user-images.githubusercontent.com/130890781/232279767-49942dd2-569e-4279-bbe8-40df8f320722.mp4

**Comment by CrimsonXMC** [comment] 2023-04-16 09:01
Duplicate of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2963

**Closed** 2023-04-26 20:46 UTC
Labels: state: Duplicate :books:, FTB Skies
