### ISSUE TITLE
[Bug]:  Sluice null pointer exception

### ISSUE THREAD

**Issue by Ryulightorb** [FTBTeam/FTB-Modpack-Issues#262] opened 2021-11-06 07:51 UTC
### Modpack

Oceanblock

### Modpack version

1.1.0

### Log Files

https://pste.ch/yayuyeloga.rb

### Describe the bug

Two members of my server can't go near any empowered sluices and have re-downloaded their games multiple times apparently it's due to a null pointer exception, this only happens when they get close to it.

this seems like a pretty bad issue that if impacting a solo player could ruin the game

### Steps to reproduce

Placing an empowered sluice and running it can trigger this not sure how to replicate 100%

### Expected behaviour

Not a crash for sure

### Screenshots

![image](https://user-images.githubusercontent.com/49608619/140602334-0fb248a0-abaa-460e-a99e-dbc962ec90ba.png)

**Comment by Ryulightorb** [comment] 2021-11-06 07:58
If needed i can upload the world files.

**Comment by Raidobw2** [comment] 2021-11-06 09:34
Duplicate of #239
Follow the development of that bugfix there, and most likely you'll need to cleanly reinstall the clients.

To cleanly reinstall the client, delete the `.localCache` folder in your instances folder (FTB App).
Backup your worlds.
Reinstall the modpack, this will download the files again and should repair that missing registry entry.
Comment on 239 if you want to add any info, I'll be closing this as it is duplicate.

**Closed by Raidobw2** 2021-11-06 09:34 UTC
Labels: FTB OceanBlock, cat: Bug, state: Duplicate :books:
