### ISSUE TITLE
Stoneblock 2 cant update mods

### ISSUE THREAD

**Issue by Soyrez** [FTBTeam/FTB-Modpack-Issues#4494] opened 2023-12-19 21:15 UTC
### Modpack

FTB Genesis

### Modpack version

Version 1.22.0

### Describe the bug

when the game launches it requests that i update the mods, when i go to do that i click on update all mods and it does nothing, ive tried everything.

### Steps to reproduce

1. Click on update all mods
2. nothing happens

### Expected behaviour

should of updated the mods

### Screenshots

![fff](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/154378831/840d2704-5459-44cb-82eb-b68583b75a95)

### Additional information

how could i fix it?

**Comment by Soyrez** [comment] 2023-12-19 21:18
UPDATE: now it shows this when i launch the game, is there a way to fix it without losing my world? 
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/154378831/41edebf0-f331-4529-8698-f1e0d787bca1)

**Comment by Gaz492** [comment] 2024-06-05 16:11
> UPDATE: now it shows this when i launch the game, is there a way to fix it without losing my world? ![image](https://private-user-images.githubusercontent.com/154378831/291716109-41edebf0-f331-4529-8698-f1e0d787bca1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MDM5NzAsIm5iZiI6MTcxNzYwMzY3MCwicGF0aCI6Ii8xNTQzNzg4MzEvMjkxNzE2MTA5LTQxZWRlYmYwLWYzMzEtNDUyOS04Njk4LWYxZTBkNzg3YmNhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQxNjA3NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTA3NTZmOGM5MGIyNzliOTY1ZjVhYzNjY2UwMGI4ZWViMzhkYjI4Yzg5NjVhNDllYmMzMWU2ZTgwMDZmZDk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jfOeID0ui3YHbasrOklQdPaLGimgTS5hsE2WXqvAfzw)

If you click on the modpack in the app then click on the 3 vertical dots next to the play button, you can duplicate the instance from there. So that you can test if launching the pack breaks anything for you.
You can also validate/repair the instance by going to the settings page and clicking repair, this shouldnt break your world, but I would recommend doing this on a duplicate of your instance just incase.

**Closed** 2024-06-17 20:26 UTC
Labels: FTB Presents Stoneblock 2, state: Awaiting Reply
