### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by KingDs99** [FTBTeam/FTB-Modpack-Issues#1313] opened 2022-09-08 20:43 UTC
### Modpack

FTB University 1.16

### Modpack version

1.4.0

### Describe the bug

When I try to update my modpack to the 1.7.0 version, it's download 2 seconds and then the error ``Install Failed``  appears.
I don't have much more information. 

### Steps to reproduce

1. Click on the Update Button
2. Wait
3. The error message appears

### Expected behaviour

 I was waiting for the pack to update

### Screenshots

![FTB_bug](https://user-images.githubusercontent.com/113141618/189222014-0f077513-d747-407e-b338-3ef50db42791.PNG)

**Comment by Raidobw2** [comment] 2022-09-09 04:56
Hello, do you have a debug code from the FTB Discord or your app logs? App logs are at `%localappdata%\.ftba\logs\latest.log`

Also have you tried checking your firewall/antivirus if you have one?
You can also check in the hosts file at `c:\Windows\System32\Drivers\etc\hosts`, open the "`hosts`" file with Notepad and delete any lines that don't start with `#`, then save the file

**Comment by KingDs99** [comment] 2022-09-14 17:37
Hi, yes i have a debug code but in text form, sorry to do not have send this before :/
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9568598/debug.log)

And i checked for the antivirus and i don't have any lines without '#'

**Comment by Raidobw2** [comment] 2022-09-15 09:41
Hmm from that maybe the instance.json is partially corrupted, I'm not sure. Have you tried just installing a second instance on 1.7.0? You should be able to do that, possibly it'll yield a different result since it won't be using/updating the instance.json, but creating a new one.

Let me know. Also if that works, you can copy folders like `saves` (your worlds), `local` (ftb chunks map data) and the file `options.txt` (your keybinds) to the new instance, and keep the 1.6.0 for a while just in case.

**Comment by KingDs99** [comment] 2022-09-15 15:24
No I didn't because I don't know how to do it :/
If you can give me a tip it will be welcome :)

**Comment by Raidobw2** [comment] 2022-09-16 09:35
Sure thing. Follow my steps below to install a new instance and to copy your data to it:
1. Find your current install and click on it to enter the overview page
![image](https://user-images.githubusercontent.com/17010632/190600432-234efcab-8c5a-43f1-ad01-f362b4750dd9.png)
2. In the overview page, click settings
![image](https://user-images.githubusercontent.com/17010632/190600525-4c24071a-23e5-45b5-82fe-4d48c6e5f1b3.png)
3. Scroll down and click Open Folder. This is how you access the modpack files. Information required to start the game is there. What the modpack is, which mods there are, which configuration they are using, etc.
It also happens that your saves and world data is stored there too.
![image](https://user-images.githubusercontent.com/17010632/190600743-7a493bb1-af9d-4012-a11c-59780a7d1150.png)
4. Create a new text file there. It doesn't need to be named anything in particular, but I named it `this_is_the_old_instance.txt` so I know that this is the old instance when I look in the files :)
![image](https://user-images.githubusercontent.com/17010632/190601072-c9786a5e-2b2b-4399-8ae1-e927c440918b.png)
5. Back in the app, click Browse at the left
![image](https://user-images.githubusercontent.com/17010632/190601280-29a426ac-fdc6-476d-9c8e-49b80a776aa2.png)
6. Search the modpack and click Get and install 1.7.0 like you wanted
![image](https://user-images.githubusercontent.com/17010632/190601396-c86db268-e286-4db0-a3c3-d8aecf3dd288.png)
![image](https://user-images.githubusercontent.com/17010632/190601472-6d8a6c14-463b-4bbd-8cd5-333e2e314280.png)
![image](https://user-images.githubusercontent.com/17010632/190601515-a71c1dc0-42bf-4887-bb98-6bb8bef858ce.png)
7. When it's finished, click Go to Instance
8. Or else, you'll have two tiles in the menu
![image](https://user-images.githubusercontent.com/17010632/190601775-47d14ad9-710f-464d-b76e-095e5350cd66.png)
9. Click the leftmost University instance, open the folder. It should look like this, so that's your new instance
![image](https://user-images.githubusercontent.com/17010632/190601902-cf00cfb2-a8eb-448a-a72a-bf6a5e19de34.png)
10. Open both modpack folders in your Explorer/Finder/File Explorer, and copy-paste the `local`, `saves` and `options.txt` files/folder from the OLD instance to the NEW instance in version 1.7.0. Remember that you can see which one is the old instance with the file we created earlier :)
![image](https://user-images.githubusercontent.com/17010632/190606241-c2009211-6628-445f-be14-13978b45a363.png)
11. Once you've copied the files, it's all done. Just hit start and let me know if that works
![image](https://user-images.githubusercontent.com/17010632/190606571-800d24d4-c113-4d7f-ada8-9e9813b4b8ae.png)

I recommend you keep the 1.6.0 version of University for about a week, if all is fine after a week then you can get rid the old instance

**Comment by KingDs99** [comment] 2022-09-16 17:19
Also I tried to do what you told me (and it was very nice done) but when try to install the new instance it happen the same.
![Ftb_fail2](https://user-images.githubusercontent.com/113141618/190694158-f046ee02-4873-4b10-bab9-0c2f253a563c.PNG)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9585970/latest.log)

**Comment by Raidobw2** [comment] 2022-09-17 09:31
Hmm, let's take another approach then, maybe the issue isn't in the files.

Do you have an antivirus? If yes, try disabling it while downloading the pack maybe.

Also, check your `hosts` file at `c:\Windows\System32\Drivers\etc`, open it with Notepad. Remove all lines that don't start with `#`.

And lastly, restart your router! I've seen people have issues with internet until they restarted it.

Let me know if you've got more information after that, we'll continue narrowing it down

**Comment by KingDs99** [comment] 2022-09-18 20:24
I have tried all the things but still the same...
But this time I don't have any log

**Comment by Raidobw2** [comment] 2022-09-18 21:09
I see, do you have the possibility to try a new wifi or internet network (or a mobile hotspot also works if you have a data plan. A modpack is ~300MB)

**Comment by KingDs99** [comment] 2022-09-19 15:22
It's complicated because I don't have a WiFi card in my computer and have only one WiFi network...

**Comment by Raidobw2** [comment] 2022-09-20 03:06
No problem. Do you think you could be able to get in the FTB Discord https://go.ftb.team/discord in the ftb-app-support channel and ping me (`@R3GEN`) with a debug code?

If you type `!ftbdebug` in the ftb-app-support channel the FTB Bot will give you a link to the tool. The tool will check your instances and logs and give you a support code at the end looking like "FTB-DBG" with more letters and numbers. I can relay the code to the developers for more help since it's getting a bit out of my reach at the moment and I'm running out of things to try, so maybe it's an issue within the software of the FTB App.

Let me know here or ping me directly in the FTB Discord if that's alright, thanks

**Comment by KingDs99** [comment] 2022-09-20 16:31
So I pinged you on the discord :)

**Comment by KingDs99** [comment] 2022-10-04 16:58
Hi! I am pinging you to know if you had a response for the issue ?

**Comment by Raidobw2** [comment] 2022-10-07 06:39
Hey, sorry for the delay, been busy with school lately! I've checked back on when I poked the devs about this and they mentioned a patch with better app logging was going to be out, since no error was being logged in the app log you sent me.

Do you think you would be able to try reinstalling the modpack, and then use the debug tool again from the FTB Discord? Since the app patch is out, there should be better logging to show some error, at least I hope.

You can either put the new debug code here, or ping me on the Discord again, either is fine.

Thanks for your patience!

**Comment by KingDs99** [comment] 2022-10-07 10:54
Hey, no problem for the delay it's normal :)
Okay I will try this, in evening or this weekend.

Thanks for response and I will ping you directly in the discord like the last time.

**Comment by KingDs99** [comment] 2022-10-13 20:38
So do you had any info about my last début code? :)

**Comment by Raidobw2** [comment] 2022-10-14 01:53
Hey, thanks for sticking around, been very sick in the past days and struggled to keep up, now I'm doing ok. I've seen Mikey in the FTB Discord try to help you but it looks like the log didn't show much for him either. Maybe I can try to help here instead, at some point we're bound to get it to work... thanks for your patience, I appreciate it.

Try this:
1. Log out of the FTB App
2. Log in the FTB App
3. Try to install two any other modpacks than FTB University. You could try FTB Inferno and FTB OceanBlock, they use different Java, files and all so that would be a good test.
4. You can use the debug tool again right after trying to install the packs and put the code here. Maybe that'll help me with some more info, thanks in advance

That would do it for testing download/installation.

Next up if you want to check would be to open the Event Viewer. Press Windows + R and put `eventvwr` in the box, the press Ok. Assuming your screen will be in French you'll see "Journaux Windows" (Windows Logs) and then 5 tabs under that. You want to check the 3 tabs Application, Installation and System (Système). Each category has some lines in order from recent (top) to older logs (bottom). After installing a modpack you can check for the lines in those 3 categories and see if anything seems to have been blocked. If there are some, they'll look like this:
![image](https://user-images.githubusercontent.com/17010632/195743580-4085b52e-c058-4bcf-821c-6937fcfe304c.png)

If there are any yellow or red symbols near the time you tried to install a modpack, that might be good news in some way and it's possible one of those lines with the symbols contain information to help us resolve this case!

We'll continue with this and my future communications to you will be here as well. Let me know if you think you found an issue that way, or any information that could help us sort this out

**Comment by KingDs99** [comment] 2022-10-14 16:26
Hi, no problem for the waiting I understand :)

Thanks for the response I will try all this maybe this weekend if I have time or at the beginning of the next week.

I ping you here if I have some new :)

**Comment by Gaz492** [comment] 2024-06-04 10:54
The app has had quite a few updates since this issue was opened which may have resolved the issue(s) mentioned here so I will close this issue.
If the issue is still happening to you or anyone else please open an issue on our app tracker https://github.com/FTBTeam/FTB-App/issues

**Closed by Gaz492** 2024-06-04 10:54 UTC
Labels: FTB University 1.16
