### ISSUE TITLE
[Suggestion]: Endgame content (Infinity Catalysts, Ingots, singularities) Needs to be rebalanced

### ISSUE THREAD

**Issue by Mattabyte** [FTBTeam/FTB-Modpack-Issues#1889] opened 2022-11-12 06:01 UTC
### Modpack

FTB Stoneblock 3

### Is your suggestion related to a problem? Please describe.

Currently in FTB Stoneblock 3, the singularities (and most of the ingredients needed to craft them), do not have an EMC value. The infinity catalysts that are made with the singularities also do not have an EMC Value, nor the Infinity Ingots.

This means to craft a single Infinity Catalyst, a player has to produce each ingredient via automation. For some singularities (for example the Flux Block Singularity, this is not possible as it requires player intervention. In isolation this seems to be a minor time gate to progress, but the cumulative effect for all singularities required to make a single Infinity Catalyst I believe does not respect the players time. Compact Machine Wall, Ethereal Slate, Flux Block, Emerald Cluster and the Mana Steel singularities all require considerable time input from the player. I understand the amount required for a singularity is decreased to recognise this, but as I mentioned the effect of all of these together is still too much of a grind.

Machine Wall, Ethereal Slate, Flux Blocks, Emerald Clusters, and mana steel should have an EMC value - forcing the player to create the item at least once (and therefore experiencing some of a mod they might otherwise not have enjoyed), and still respecting their time when it comes time to mass produce these items for end game content.

**Comment by EeveeTC** [comment] 2022-11-12 09:08
Flux Dust is totally automatable via Create deployer.

And emerald clusters are easily mass produced with watch of flowing time. 
At that point pet filter singularity takes more time to make then emerald singularity because the time to convert 20k pet filter to singularity is way longer then converting 2k of emerald cluster to singularity.

Compact machine wall can be easily automatable as well, all you need is 2 block placer and one dropper, and some afk time, if you don’t want afk, you can easily scale it up as well. 

For mana steel, you only need a good way to produce mana, and with watch of flowing time, you can literally just speed up endoflame, the lowest tier of generating flower, and the easiest to automate.

To be honest, all the emc-able material singularity flower takes longer to do then the ones that doesn’t have emc, as the amount neeed for them and the conversion rate in the compressor is still slower even after 10 watch of flowing time.

I wish this pack doesn’t become something like SB2 where it’s literally just emc everything in the end game, it’s more fun automating all the resources then taking everything out of transmutation table.

And emc is super cheap with fading power flower in the pack, you can get more then 1 trillion emc in 1 minute with those.

At least SB2 has a challenge in producing enough emc, if anything having emc in this pack, the power flower would just make the endgame super fast and boring.

**Comment by richie3366** [comment] 2022-11-12 11:55
> the conversion rate in the compressor is still slower even after 10 watch of flowing time
That quote says it all: the modpack heavily relies on spamming watches on pedestals. It is not suitable for servers, and I think there is a in-between change to be done to address that issue.
EMC-ing singularities would be too OP, I agree with @EeveeTC on that. But I think we could tweak/lower the required quantities for each singularity (taking also into account that neutronium compressors are slow), and propose Mixer recipes for emerald shards (as proposed by @minecrafterseppe [here](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1852#issuecomment-1312438039))

**Comment by Sunekaer** [comment] 2022-11-13 17:50
Duplicate of #1852

**Closed by Sunekaer** 2022-11-13 17:50 UTC
Labels: 2: Enhancement, FTB StoneBlock 3
