### ISSUE TITLE
Industrial smelter not smelting raw ores?

### ISSUE THREAD

**Issue by ian09t1** [FTBTeam/FTB-Modpack-Issues#2599] opened 2023-01-26 17:08 UTC
### Modpack

FTB Legend of the Eyes

### Modpack version

1.1.1

### Describe the bug

the revolutionary guide says to put your ores into the industrial smelter, which then melts them down. No matter what raw ore I put in, it won't smelt it. Only smelts dust and already processed ingots. 
![issue 2](https://user-images.githubusercontent.com/123660726/214901496-3abed33f-995c-4bd0-9cab-d269c4c9e938.png)
![issue](https://user-images.githubusercontent.com/123660726/214901498-a8f0d93f-39eb-4214-862c-2946f83e851f.png)

### Steps to reproduce

put raw ore in an industrial revolution industrial smelter

### Expected behaviour

Melts raw ores

**Comment by TheonlyTazz** [comment] 2023-01-26 17:38
Duplicate of
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2548

**Closed by TheonlyTazz** 2023-01-26 17:38 UTC
Labels: FTB Legend of the Eyes
