### ISSUE TITLE
Magically Inclined Steel Block UI Glitch with ComplementaryReimagined Shaders

### ISSUE THREAD

**Issue by whatamike** [FTBTeam/FTB-Modpack-Issues#4779] opened 2024-02-27 16:40 UTC
### Modpack

FTB Skies Expert

### Modpack version

1.1.0

### Describe the bug

With the ComplementaryReimagined shader pack enabled, holding a block of Magically Inclined Steel in your hand causes the entire screen to flash white with black shadows.

### Steps to reproduce

1. Enable ComplementaryReimagined Shaders
2. Create a block of Magically Inclined Steel
3. Hold the block in your hand

### Expected behaviour

The block is visible and does not disrupt the screen

### Screenshots

![MIS_NoShaders](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/7999472/46d7fc38-7d35-45da-94fe-a2077115f22c)
![MIS_WithShaders](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/7999472/9e3b1114-bb35-45b3-b4d0-a9a90833e6cf)

**Comment by Saereth** [comment] 2024-02-27 17:25
![2024-02-27_09 24 00](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/9200909/f4eb131a-f012-43fb-a41e-51befe9f5745)
I cant reproduce this in dev but we do have a more updated version of embedium in the pack in dev which will release to everyone so maybe that fixes it? reopen this if not.  Marking as fixed for now

**Closed** 2024-02-28 06:57 UTC
Labels: state: Fixed in Dev :hammer_and_wrench:, FTB Skies Expert
