### ISSUE TITLE
[Bug]: Crash when opening Draconic Evolution category in the quest book

### ISSUE THREAD

**Issue by RCppkiller** [FTBTeam/FTB-Modpack-Issues#488] opened 2021-12-20 13:36 UTC
### Modpack

FTB OceanBlock

### Modpack version

1.11.0

### Log Files

[hs_err_pid7284.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7745647/hs_err_pid7284.log)

### Describe the bug

I was playing on a private server and collecting rewards from completed quests. I can access all categories fine except for Draconic Evolution where the game immediately crashes to desktop. The game doesn't even show the quests of the category before closing, as soon as I click on the icon it crashes. I was still able to collect rewards from that category by clicking the "collect all rewards" button on the top right of the quest book.

### Steps to reproduce

Log onto a server.
Open the quest book.
Attempt to access the Draconic Evolution category.

### Expected behaviour

The category opens and I can see and check the quests there

### Additional information

I am using Optifine if this changes anything

**Comment by RCppkiller** [comment] 2021-12-20 13:41
Somehow right after making this report, I was able to open the category without issue despite crashing three times in a row doing the exact same thing. I'm still unsure why this happened but maybe the log can explain it ?

**Comment by quietust** [comment] 2021-12-20 21:49
Duplicate of #40?

**Comment by Raidobw2** [comment] 2021-12-21 11:14
Yes thank you quietust, it's a duplicate of 40. @RCppkiller please read the last comment on the issue quietust wrote as reference.
It's a problem with AMD GPUs.
![image](https://user-images.githubusercontent.com/17010632/146920839-1d130186-7fda-4bc3-8132-12b47e4a4893.png)

**Closed by Raidobw2** 2021-12-21 11:14 UTC
Labels: FTB OceanBlock, cat: Bug, des: Mod Issue, state: Duplicate :books:
