### ISSUE TITLE
[FTB Skies Expert] Diesel Generators adding stress recursively when chained together

### ISSUE THREAD

**Issue by tiniestfeet** [FTBTeam/FTB-Modpack-Issues#5012] opened 2024-03-19 18:11 UTC
### Modpack

FTB Skies Expert

### Modpack version

1.5.0

### Describe the bug

I have 4 Diesel generators lined up, with a chaindrive running over top to connect them to my production chain. They are being fed force-infused biofuel and should be producing 6144SU each, for a total of 24,576 SU in the whole system. However, connecting a stressometer reads a total of 196,608 SU in the system. This is not a bug with the stressometer, as I'm utilizing more stress than the 24,576SU can accomodate.

### Steps to reproduce

Place Diesel engines next to each other, with encased chaindrive overtop connecting them. 

Connect Stressometer.

Feed fuel.

Get insane early amounts of stress.

### Expected behaviour

Diesel Generator SU output combining additively.

### Screenshots

![Screenshot 2024-03-19 140939](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/131112012/c693bd6b-787a-42a4-98ee-37045248dc50)
![Screenshot 2024-03-19 141023](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/131112012/ce41e660-2a80-4c65-8619-ad52e02d9b3b)

**Comment by tiniestfeet** [comment] 2024-03-19 18:12
I made an error tagging this. This is for FTB Skies Expert pack. I cannot find where to change tag.

**Comment by kmadstarh** [comment] 2024-03-20 01:37
That's a neat one. Given that the diesel generators don't _need_ any assistance connecting to transfer power (a shaft connected to just one of the connected generators would be sufficient), I think this is an issue with each block of the encased chaindrive thinking it's on the primary generator, and considering all of their outputs to belong to the one they are attached to.

If you're looking to not have this problem, just get rid of the chaindrive and it'll behave as you'd expect.

**Comment by Fabus1184** [comment] 2024-04-11 17:27
This also happens for me with just two generators placed directly beside each other, however this only seems to add stress units when reloading the world.

**Comment by md5i** [comment] 2024-06-23 06:11
I can confirm this.  I have two diesel generators, side-by-side.  Each is generating 2,122 su.  A stressometer on the system, however, thinks that the system is producing 54,912 su.  If I remove the fuel from both generators, they stop.  But part of the system continues to run with 50,688 su of capacity and no active su generators.

**Comment by Saereth** [comment] 2024-07-11 15:08
This should be fixed in the upcomming update

**Closed** 2024-07-12 00:18 UTC
Labels: state: Fixed in Dev, FTB Skies Expert

**Comment by md5i** [comment] 2024-07-14 16:11
Unfortunately, I have observed the behavior since upgrading to 1.9.  I did have to reset the system first by replacing the generators and removing some elements that were still running when everything was off.  And quite a few reload cycles, it did seem to have fixed the problem.  But I now have a system that reports 73,728 SU instead of the expected 24,576 SU, an increase of exactly a factor of three.
