### ISSUE TITLE
[Bug]: Game crashes when trying "texture" framed drawer.

### ISSUE THREAD

**Issue by hvdklauw** [FTBTeam/FTB-Modpack-Issues#2095] opened 2022-11-22 08:56 UTC
### Modpack

FTB Stoneblock 3

### Modpack version

1.3.0

### Log Files

https://pste.ch/eqinisuxur.md

### Describe the bug

Made 25 framed drawers (single storage)
Tried to frame them with pegged gray concrete and normal concrete (slots 1 and 2 respectivly)

Crash to desktop.

### Steps to reproduce

1. Make a chest
2. Surround the chest with iron nuggets
3. Get 2 gray concrete
4. Turn one of the concretes into pegged gray concrete from chipped.
5. Place the pegged gray concrete in slot one of your crafting table
6. Place gray concrete in the second slot
7. Place framed drawer in the third slot.

### Expected behaviour

For it to work.

**Comment by Sunekaer** [comment] 2022-11-22 11:32
Duplicate of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1650

**Closed by Sunekaer** 2022-11-22 11:32 UTC
Labels: FTB StoneBlock 3
