### ISSUE TITLE
[Bug]: [SB3] Can't see my hand when I rejoin the world.

### ISSUE THREAD

**Issue by dawidekkochany123** [FTBTeam/FTB-Modpack-Issues#1565] opened 2022-11-02 16:18 UTC
### Modpack

FTB StoneBlock 3

### Modpack version

1.0.0

### Describe the bug

When I left the world (without leaving the game) and entered again after about 15 minutes, I couldn't see my hand or any held items. I still could use the inventory, break and place blocks. I'm using Rubidium and Rubidium Extra for better fps if that makes any difference. When I restarted the client, the bug fixed itself. Happened two times so far.

### Steps to reproduce

1. Exit your world
2. Join the world again
3. Happened two times, doesn't happen every time

### Expected behaviour

I don't know if it is rubidium issue, because I can't run the pack without it. I hope I could help.

### Additional information

a small bug that doesn't make difference to the gameplay, I don't know if it is the issue of the pack or the Rubidium mod.

**Comment by Sunekaer** [comment] 2022-11-02 16:19
Duplicate of #1542 
Restart your game

**Closed by Sunekaer** 2022-11-02 16:19 UTC
