### ISSUE TITLE
[Bug]: Mekanism Rotary Condensentrator doesn't decondensentrate

### ISSUE THREAD

**Issue by Le-Stina** [FTBTeam/FTB-Modpack-Issues#1307] opened 2022-09-01 10:08 UTC
### Modpack

FTB Plexiglass Mountain

### Modpack version

1.1.1

### Describe the bug

When inputting water into the Rotary Condensentrator and setting it to decondensentrate it  doesn't produce water vapor for no obvious reason (supplied with sufficient energy, redstone mode to ignored)

### Steps to reproduce

1. place Rotary Condensentrator
2. insert water
3. toggle to 'decondensentrating'
4. input FE
5. redstone mode to 'ignored'

### Expected behaviour

turn water into water vapor

### Screenshots

![2022-09-01_12 06 11](https://user-images.githubusercontent.com/112622979/187889080-dad4972c-9538-46f5-bf54-6da3272d0461.png)

**Comment by Raidobw2** [comment] 2022-09-02 06:42
I can't reproduce this in the development build so I'll assume fixed. You can try updating Mekanism https://www.curseforge.com/minecraft/mc-mods/mekanism/files/3875976

![water_vapor](https://user-images.githubusercontent.com/17010632/188074775-7cdb55bf-1eee-42b8-b6cc-b09ed2c4b9a0.gif)

**Comment by quietust** [comment] 2022-09-02 18:40
I'm curious - if you hover over the water tank and press the JEI "show uses" key (`u` by default), does a Decondensentrating recipe show up? And if you click on the arrow in the machine's UI to show recipes, can you see one in there for water->steam?

**Comment by Raidobw2** [comment] 2022-09-05 08:49
For me in-dev, yes
![image](https://user-images.githubusercontent.com/17010632/188408371-5e8aa875-b204-4ec2-91f3-22929e7168d6.png)
Wrapping up the update for its release this week (likely Tuesday since Monday is labor day), so if this is an issue in 1.1.1 it won't be for long

**Comment by Raidobw2** [comment] 2022-09-09 07:34
This should be fixed in 1.2.0, let me know otherwise

**Closed by Raidobw2** 2022-09-09 07:34 UTC
Labels: 1: Mod Issue, state: Fixed :heavy_check_mark:, FTB Plexiglass Mountain
