### ISSUE TITLE
[Bug]: Game crashes upon dragging error text into REI display (could lead to players accidentally crashing and causing issues with their world). The text itself is also a bug.

### ISSUE THREAD

**Issue by ZinnGIT** [FTBTeam/FTB-Modpack-Issues#1813] opened 2022-11-10 02:39 UTC
### Modpack

Stoneblock 3

### Modpack version

1.1.0

### Log Files

Hastebin.) https://pste.ch/mogajijapi.pl

Raw file.) [crash-2022-11-09_21.21.09-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9976849/crash-2022-11-09_21.21.09-client.txt)

### Describe the bug

The Fluix Crystal "Throwing into water" recipe shows a red error, but along with that, it will crash your game as soon as you drag it into the REI display box. (as shown by the arrow)

### Steps to reproduce

1.) Go to the fluix crystal recipe in the image
2.) Drag the red box into the top left of the screen

### Expected behaviour

Crashes the game

### Screenshots

![2022-11-09_21 26 39](https://user-images.githubusercontent.com/99773767/200986768-2e09f93b-6b28-45d2-95ae-b099a3a6503a.png)

**Comment by Sunekaer** [comment] 2022-11-10 08:18
Duplicate of #1719

**Closed by Sunekaer** 2022-11-10 08:18 UTC
Labels: 1: Mod Issue, FTB StoneBlock 3
