### ISSUE TITLE
[Suggestion]: Replacement for a Storage Mod (for chests and barrels)

### ISSUE THREAD

**Issue by Wyvernity** [FTBTeam/FTB-Modpack-Issues#1955] opened 2022-11-14 20:39 UTC
### Modpack

FTB Stoneblock 3

### Is your suggestion related to a problem? Please describe.

Iron Chests was included in the mod pack. With the latest update, now Metal Barrels is in the pack, but instead of installing two different mods Sophisticated Storage could be installed. It adds iron, gold, diamond and netherite versions of chests, barrels and even shulker boxes. You can also dye them, use its pre-added item display feature or add different upgrades to change their usage. I think that it is currently the best storage mod that uses chests and such. Also its backpack counterpart (Sophisticated Backpacks) would be useful since you get a lot of loot from dungeons (yep this is also better than simply backpacks).

### Mod suggestion

Sophisticated Storage: https://www.curseforge.com/minecraft/mc-mods/sophisticated-storage
Sophisticated Backpacks: https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks

**Comment by Sunekaer** [comment] 2022-11-14 20:46
Duplicate of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1646

**Closed by Sunekaer** 2022-11-14 20:46 UTC
