### ISSUE TITLE
[Bug]: Power dupe bug with Starter, Basic, and Hardened tiers of Energy Cells

### ISSUE THREAD

**Issue by Punkinator2** [FTBTeam/FTB-Modpack-Issues#2149] opened 2022-11-25 23:18 UTC
### Modpack

Stoneblock 3

### Modpack version

1.3.0

### Describe the bug

I discovered a bug that involves utilizing multiple energy cells between starter and hardened tier energy cells. When the cells are touching eachother, on top of being connected with power cables, the cells will not run out of power once every single on has been fully charged.

### Steps to reproduce

1. Place energy cells adjacent to each other as shown in the pic
2. Connect the cells together using power cables
3. Fully charge the system (i.e. all cells are fully charged)
4. Begin to drain power by any means. The cells will remain topped up and won't drain past a small amount.

### Expected behaviour

Energy cells should run dry once power usage exceeds generation

### Screenshots

![2022-11-25_18 15 24](https://user-images.githubusercontent.com/53418907/204062514-6462b567-25ed-40e7-9a65-efed1edb77b0.png)
![2022-11-25_18 16 09](https://user-images.githubusercontent.com/53418907/204062519-f3c2289b-44c3-46f5-b349-42f596032e0a.png)

**Comment by Sunekaer** [comment] 2022-11-28 17:37
Duplicate of #2039

**Closed by Sunekaer** 2022-11-28 17:37 UTC
Labels: 1: Mod Issue, FTB StoneBlock 3
