### ISSUE TITLE
Random client disconnect 

### ISSUE THREAD

**Issue by mostlygizzards** [FTBTeam/FTB-Modpack-Issues#5923] opened 2024-10-08 16:06 UTC
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.2.1

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

[09:59:22] [Netty Server IO #1/ERROR] [minecraft/Connection]: Exception caught in connection
io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:level_particles'
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:55) ~[server-1.21.1-20240808.144430-srg.jar%23350!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:14) ~[server-1.21.1-20240808.144430-srg.jar%23350!/:?] {re:classloading}
        at TRANSFORMER/neoforge@21.1.61/net.neoforged.neoforge.network.filters.GenericPacketSplitter.encode(GenericPacketSplitter.java:104) ~[neoforge-21.1.61-universal.jar%23351!/:?] {re:classloading}
        at TRANSFORMER/neoforge@21.1.61/net.neoforged.neoforge.network.filters.GenericPacketSplitter.encode(GenericPacketSplitter.java:39) ~[neoforge-21.1.61-universal.jar%23351!/:?] {re:classloading}
        at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.97.Final.jar%23104!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar%23104!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection$2.write(Connection.java:528) ~[server-1.21.1-20240808.144430-srg.jar%23350!/:?] {re:classloading}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannel.write(AbstractChannel.java:296) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection.doSendPacket(Connection.java:364) ~[server-1.21.1-20240808.144430-srg.jar%23350!/:?] {re:classloading,re:mixin}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection.lambda$sendPacket$12(Connection.java:359) ~[server-1.21.1-20240808.144430-srg.jar%23350!/:?] {re:classloading,re:mixin}
        at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}
        at java.base/java.lang.Thread.run(Unknown Source) [?:?] {re:mixin}
Caused by: io.netty.handler.codec.EncoderException: Empty ItemStack not allowed
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.ItemStack$2.encode(ItemStack.java:167) ~[server-1.21.1-20240808.144430-srg.jar%23350!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.ItemStack$2.encode(ItemStack.java:155) ~[server-1.21.1-20240808.144430-srg.jar%23350!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$11.encode(StreamCodec.java:234) ~[server-1.21.1-20240808.144430-srg.jar%23350!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$6.encode(StreamCodec.java:117) ~[server-1.21.1-20240808.144430-srg.jar%23350!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.game.ClientboundLevelParticlesPacket.write(ClientboundLevelParticlesPacket.java:61) ~[server-1.21.1-20240808.144430-srg.jar%23350!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$2.encode(StreamCodec.java:42) ~[server-1.21.1-20240808.144430-srg.jar%23350!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:97) ~[server-1.21.1-20240808.144430-srg.jar%23350!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:87) ~[server-1.21.1-20240808.144430-srg.jar%23350!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:53) ~[server-1.21.1-20240808.144430-srg.jar%23350!/:?] {re:classloading}
        ... 31 more
[09:59:22] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: mostlygizzards lost connection: Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:level_particles'

### Describe the bug

In single player, I would get kicked to a disconnect screen.  I spun up a server to compare and the server doesn't crash.  Just a network disconnect with the error:  `Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:level_particles'`

### Steps to reproduce

1.  Join game
2.  Stay near base where machines, pipes, etc are running
3. After a random amount of time - usually 5-20 minutes, get disconnected

### Expected behaviour

Expectation of staying connected to the server

### Screenshots

![image](https://github.com/user-attachments/assets/0f22691f-8c6f-41d2-b666-eb11694941c7)

**Comment by mostlygizzards** [comment] 2024-10-08 16:07
Adding this note:  Leaving the base area and going somewhere like void or mining dimension stops the behavior.  It seems that something in the world near my home base is triggering the network drop.

**Comment by mostlygizzards** [comment] 2024-10-08 16:24
Log Files (started with clean log folder)


[debug.log](https://github.com/user-attachments/files/17296317/debug.log)
[latest.log](https://github.com/user-attachments/files/17296318/latest.log)
[console.log](https://github.com/user-attachments/files/17296319/console.log)

**Comment by mostlygizzards** [comment] 2024-10-08 19:47
Yes, I have a couple of the item collectors for scooping up geore shards.

**Comment by zperk13** [comment] 2024-10-08 20:48
@mostlygizzards No idea if this is causing the issue, but I have a suspicion; is it possible that multiple item collectors would try to grab the same item at the same time? By which I mean is there overlap in your item collectors' selected areas

**Comment by mostlygizzards** [comment] 2024-10-08 20:51
@zperk13 I can reduce to one and test.  I took them all down to let it simmer and see if I get that error again. 

I will confirm that the areas did slightly overlap.

If I don't get the d/c I'll put a single one back up among the xycraft collectors.  

Last test, I'll just do a single dire collector by itself.  I'll update the issue once I get those tested.

I snagged a copy of my world as it was, in case it's needed later.

**Comment by mostlygizzards** [comment] 2024-10-08 20:52
I guess if it all works fine I'll put 2 overlapping to see if I can repro after, assuming this is the culprit.

**Comment by zperk13** [comment] 2024-10-08 20:55
@mostlygizzards Since you mentioned copying thew world, just an FYI in case you didn't know, since you're on the latest version of the pack, FTB Backups should be making a backup of your world every 30 minutes (keeping the most recent 12) so you also have those backups if you need them. Not exactly relevant to the issue, just wanted to let you know

**Comment by mostlygizzards** [comment] 2024-10-08 21:13
Issue is gone with no dire collectors.  Now I'm doing a single dire collector with some xycraft ones around.

**Comment by mostlygizzards** [comment] 2024-10-08 21:24
Single dire with 3 xycraft collectors results in disconnect - they're within a few blocks of each other.

![image](https://github.com/user-attachments/assets/77e81cef-164a-47c2-87f9-99844ee2b9e2)

[15:23:12] [Netty Server IO #2/ERROR] [minecraft/Connection]: Exception caught in connection
io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:level_particles'
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:55) ~[server-1.21.1-20240808.144430-srg.jar%23350!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:14) ~[server-1.21.1-20240808.144430-srg.jar%23350!/:?] {re:classloading}
        at TRANSFORMER/neoforge@21.1.61/net.neoforged.neoforge.network.filters.GenericPacketSplitter.encode(GenericPacketSplitter.java:104) ~[neoforge-21.1.61-universal.jar%23351!/:?] {re:classloading}
        at TRANSFORMER/neoforge@21.1.61/net.neoforged.neoforge.network.filters.GenericPacketSplitter.encode(GenericPacketSplitter.java:39) ~[neoforge-21.1.61-universal.jar%23351!/:?] {re:classloading}
        at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.97.Final.jar%23104!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar%23104!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection$2.write(Connection.java:528) ~[server-1.21.1-20240808.144430-srg.jar%23350!/:?] {re:classloading}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannel.write(AbstractChannel.java:296) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection.doSendPacket(Connection.java:364) ~[server-1.21.1-20240808.144430-srg.jar%23350!/:?] {re:classloading,re:mixin}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection.lambda$sendPacket$12(Connection.java:359) ~[server-1.21.1-20240808.144430-srg.jar%23350!/:?] {re:classloading,re:mixin}
        at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}
        at java.base/java.lang.Thread.run(Unknown Source) [?:?] {re:mixin}
Caused by: io.netty.handler.codec.EncoderException: Empty ItemStack not allowed
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.ItemStack$2.encode(ItemStack.java:167) ~[server-1.21.1-20240808.144430-srg.jar%23350!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.ItemStack$2.encode(ItemStack.java:155) ~[server-1.21.1-20240808.144430-srg.jar%23350!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$11.encode(StreamCodec.java:234) ~[server-1.21.1-20240808.144430-srg.jar%23350!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$6.encode(StreamCodec.java:117) ~[server-1.21.1-20240808.144430-srg.jar%23350!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.game.ClientboundLevelParticlesPacket.write(ClientboundLevelParticlesPacket.java:61) ~[server-1.21.1-20240808.144430-srg.jar%23350!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$2.encode(StreamCodec.java:42) ~[server-1.21.1-20240808.144430-srg.jar%23350!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:97) ~[server-1.21.1-20240808.144430-srg.jar%23350!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:87) ~[server-1.21.1-20240808.144430-srg.jar%23350!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:53) ~[server-1.21.1-20240808.144430-srg.jar%23350!/:?] {re:classloading}
        ... 31 more

**Comment by mostlygizzards** [comment] 2024-10-08 21:26
Derp on my part - the dire collector was competing with the geore golems.  That's likely where this lines up with #5922

**Comment by zperk13** [comment] 2024-10-08 21:42
@mostlygizzards I'm writing a bug report for JustDireThings. Can you provide me with steps to reproduce the bug please since you seem to have a more reproducible setup than I do

**Comment by mostlygizzards** [comment] 2024-10-08 21:47
5 coal geore blocks - 10 diamond and 10 redstone.
1 golem per type

DC conditions were:
3 dire collectors with a mix of xycraft in the mix
1 dire collectors with 3 xycraft also triggered (but it could have been the golems)
I'm currently watching 1 dire solo between the golems to see if it triggers but so far it's ok.  I've tried the default 20 setting as well as 60 and 100 and it's still going ok.

![image](https://github.com/user-attachments/assets/f399e305-b5a0-45f2-aef8-d02f75534404)

**Comment by mostlygizzards** [comment] 2024-10-08 21:47
Better angle of the placement

![image](https://github.com/user-attachments/assets/0c23b172-7547-4721-8cc0-dc51500173b3)

**Comment by zperk13** [comment] 2024-10-08 21:53
@mostlygizzards If I sent you the jar file of my patched version of the mod that disables JustDireThings Item Collector particles, would you be able to test if my patch fixes your crashes? I understand if you don't trust a random compiled file from a stranger, in which case I can also try to provide the instructions to patch it yourself

**Comment by mostlygizzards** [comment] 2024-10-08 21:55
Happy to help

**Comment by mostlygizzards** [comment] 2024-10-08 21:57
https://tenor.com/view/dum-pick-em-gif-24573172

**Comment by zperk13** [comment] 2024-10-08 22:02
@mostlygizzards 

https://drive.google.com/file/d/1pOtVQXJofRp3ZTTmTOnaT5f13BzwkPr2/view?usp=sharing

I can't upload jar files directly on GitHub which makes sense.
Please recreate the situation where you did get crashes consistently then see if it still crashes with this version of the mod.

Also please note if this does fix the crashes, do not close this issue, this is an unofficial and not ideal patch.

If a mod (or maintainer? idk, someone with authority on this repo) is reading this and not happy that I'm sending somebody a jar file, I looked in the repo and did not see anything about rules. You are free to delete this comment though if you deem it necessary.

**Comment by mostlygizzards** [comment] 2024-10-08 22:09
@zperk13 Will do - I'm setting up a scenario now and once I've got some confirmed disconnects, I'll swap the test version in and let that simmer.

**Comment by zperk13** [comment] 2024-10-08 22:19
I'm struggling to recreate the bug with Xycraft collectors. Any recommendations?
![image](https://github.com/user-attachments/assets/575c329f-2ad0-4356-9c78-fceb1d996aa0)

**Comment by mostlygizzards** [comment] 2024-10-08 22:42
https://www.youtube.com/watch?v=VodWNl91vbQ

Here is the layout with the d/c at the end.

**Comment by zperk13** [comment] 2024-10-08 23:04
I managed to consistently recreate the bug with only JustDireThings using a fairly simple setup. I made a bug report for it on the mod itself as you can see above this comment. I'm 95% sure if the bug is fixed for the specific situation I built, it will be fixed for your situation as well. I would still like to hear if my patch stops it from crashing for you btw.

**Comment by mostlygizzards** [comment] 2024-10-08 23:07
So far so good.  I'm just hovering nearby while I feed my spawn their dinner.

I think you've nailed the core issue.  Hopefully it's just an order of operation issue, because the particles are nice to have.

Thanks for all of your hard work on this!

**Comment by mostlygizzards** [comment] 2024-10-08 23:11
Quite a few shards dropping at this point, so if it's going to bomb out I'll know pretty soon.

![image](https://github.com/user-attachments/assets/465e6241-cc2d-462b-814b-25c671cdabce)

**Comment by zperk13** [comment] 2024-10-08 23:12
If my patch "fixes" the issue, feel free to just use it until the bug is actually fixed. Yeah no particles isn't ideal but it's better than crashing.

**Comment by mostlygizzards** [comment] 2024-10-08 23:14
100%  I was initially thinking that my quantum computer setup was the issue.  It just lined up that I'd set up this monstrosity to top up my supplies to build the crazy thing.  That and Ars for the golems.  Juggling too many particle-creating items.

**Comment by mostlygizzards** [comment] 2024-10-08 23:50
@zperk13 It's been a while and no disconnect, so I think you're correct.  I'll run with your patch going forward and report back if I run into any issues.

**Comment by mostlygizzards** [comment] 2024-10-09 02:49
And as a final follow-up:   No disconnect in all of this time.

**Comment by zperk13** [comment] 2024-10-09 02:51
(for any maintainer reading that, that doesn't mean it's ready to be closed)

**Comment by zperk13** [comment] 2024-10-14 03:56
@mostlygizzards btw how did you move those geores into your base?

**Comment by zperk13** [comment] 2024-10-19 01:08
Direwolf20 has made a commit (https://github.com/Direwolf20-MC/JustDireThings/commit/ee212cff9e2ed44d1661f821ef9929938d5c43d7) and hopefully once it gets put into an update and that update gets put into the pack, the issue will be resolved for you.

**Closed** 2024-11-07 07:12 UTC
Labels: state: Fixed in Dev, Bug, FTB Presents Direwolf20 1.21
