### ISSUE TITLE
Drawer Quest does not work

### ISSUE THREAD

**Issue by plac3** [FTBTeam/FTB-Modpack-Issues#4829] opened 2024-03-03 03:38 UTC
### Modpack

FTB University 1.19

### Modpack version

1.4.2

### Describe the bug

It simply does not detect the quest completion, I made a birch drawer 
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/84245312/a0499814-d37e-4dd3-b9bc-e688981a1790)
Said birch drawer did not get detected, and I cannot submit my quest.
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/84245312/e2346d14-f10c-4b08-857a-16a145f129e6)
Same on another account:
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/84245312/fd43a0d2-c213-4aeb-8d7a-bdd1625f4e07)

### Steps to reproduce

1. Go through the introductory quests
2. Make a birch drawer
3. Open quests, it will not be complete

### Expected behaviour

Quest is completed and I can progress.

**Comment by plac3** [comment] 2024-06-25 16:45
We gave up on the modpack after a few days so I'm not able to precise this
information anymore

**Comment by UnRealDinnerbone** [comment] 2024-06-25 16:57
I was unable to reproduce this issue. I'm going to close it then

**Closed by UnRealDinnerbone** 2024-06-25 16:57 UTC
Labels: FTB University 1.19
