### ISSUE TITLE
[Suggestion]: Experience Obelisk XP Liquid in recipes

### ISSUE THREAD

**Issue by PopcraftReal** [FTBTeam/FTB-Modpack-Issues#1629] opened 2022-11-04 16:11 UTC
### Modpack

FTB StoneBlock 3

### Is your suggestion related to a problem? Please describe.

Can we have a more consistent recipe which can use Experience Obelisk XP Liquid in recipes such as the chicken feed?

**Comment by Sunekaer** [comment] 2022-11-05 16:41
Duplicate of 1576

**Closed by Sunekaer** 2022-11-05 16:41 UTC
Labels: FTB StoneBlock 3
