### ISSUE TITLE
[Bug]: Issue with Draconic Evolution

### ISSUE THREAD

**Issue by Thegrayjedi** [FTBTeam/FTB-Modpack-Issues#297] opened 2021-11-10 23:52 UTC
### Modpack

FTB Oceanblock

### Modpack version

1.7.0

### Log Files

https://pste.ch/raw/awozuwimef

### Describe the bug

Issue with Draconic Evolution. Doesn't happen 100% of the time. Seems to cause a full crash (Exit code 0) when one of it's animated icons is shown in either JEI, the quest log or the inventory. I couldn't trace exactly which one, I was only able to trace it to the mod itself.

### Steps to reproduce

1. Try page 23-27 in JEI
2. Try the Draconic Evolution page in the quest manual
3. Try the Draconic Evolution items in the inventory

### Expected behaviour

Instant crash once the offending icon is shown

### Additional information

I was able to repeat this about 3 out of every 5 tries. Easiest method is using JEI to verify.

**Comment by Raidobw2** [comment] 2021-11-11 06:58
Duplicate of #40
See this ^ issue for the fix, on my last comment. It's a known bug with Draconic Evolution shaders.

**Closed by Raidobw2** 2021-11-11 06:58 UTC
Labels: FTB OceanBlock, cat: Bug, des: Mod Issue, state: Duplicate :books:
