### ISSUE TITLE
Save corrupting crash from Pipez and Sluice: Oceanblock

### ISSUE THREAD

**Issue by sauerkrau5** [FTBTeam/FTB-Modpack-Issues#8] opened 2021-09-25 17:41 UTC
This is the second time it has happened. Here is part of the crash report after I tried to load the world after the crash.

Modpack
FTB OceanBlock

Modpack version
1.0.1 and 1.1.0

Describe the bug
This is the second time it has happened. Here is part of the crash report after I tried to load the world after the crash.

Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking block entity

Steps to reproduce
1. Unknown. Probably just from using Pipez.

Expected behaviour
Not to crash

Screenshots
No response

Additional information
No response

[25Sep2021 10:33:00.204] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 23f6a91a-478c-4bbc-bf01-e0bd52b23a2c
[25Sep2021 10:33:00.206] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$23643/1846496497.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at de.maxhenkel.pipez.blocks.tileentity.PipeLogicTileEntity.getCapability(PipeLogicTileEntity.java:59) ~[?:1.16.5-1.2.9]
	at net.minecraftforge.common.capabilities.ICapabilityProvider.getCapability(ICapabilityProvider.java:48) ~[?:?]
	at dev.ftb.mods.sluice.block.sluice.SluiceBlockEntity.seekNearestInventory(SluiceBlockEntity.java:442) ~[?:1.0.5-build.13]
	at dev.ftb.mods.sluice.block.sluice.SluiceBlockEntity.ejectItem(SluiceBlockEntity.java:413) ~[?:1.0.5-build.13]
	at dev.ftb.mods.sluice.block.sluice.SluiceBlockEntity.lambda$finishProcessing$5(SluiceBlockEntity.java:296) ~[?:1.0.5-build.13]
	at dev.ftb.mods.sluice.block.sluice.SluiceBlockEntity$$Lambda$24656/1140296760.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51]
	at dev.ftb.mods.sluice.block.sluice.SluiceBlockEntity.finishProcessing(SluiceBlockEntity.java:296) ~[?:1.0.5-build.13]
	at dev.ftb.mods.sluice.block.sluice.SluiceBlockEntity.func_73660_a(SluiceBlockEntity.java:226) ~[?:1.0.5-build.13]
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	... 6 more

**Comment by Sunekaer** [comment] 2021-09-25 18:46
Duplicate of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4

**Closed by Sunekaer** 2021-09-25 18:46 UTC
Labels: FTB OceanBlock, State: Duplicate :books:
