### ISSUE TITLE
FTB Skies Expert 1.8.1 Server Installer Installs Client-Side-Only Mods. 

### ISSUE THREAD

**Issue by Hunter19823** [FTBTeam/FTB-Modpack-Issues#5204] opened 2024-05-09 20:36 UTC
### Modpack

FTB Skies Expert

### Modpack version

1.8.1

### Log Files

[Crash 1](https://pastebin.com/WgWTQG1f)
[Crash 2](https://pastebin.com/j8MxTRLC)

### Describe the bug

After updating our FTB Skies Expert 1.7.0 server to 1.8.1, the following mods were present within the server instance:
- entity_model_features
- entity_textures_features

### Steps to reproduce

1. Install 1.7.0 FTB Skies Expert.
2. Start Server
3. Change the Installer to `serverinstall_117_11927.exe`
4. Run installer
5. Update pack to 1.8.1
6. Start Server
7. Crash.

### Expected behaviour

Game does not crash due to client-side only mods being present.

**Comment by Saereth** [comment] 2024-05-09 23:28
This is marked clientside in our deployment packager so I'll have to ask Jake or Gaz to investigate this soon, we'll get a fix out I imagine pretty soon

**Comment by rlnt** [comment] 2024-05-12 16:33
Is also a duplicate of this issue https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5180

**Closed** 2024-06-03 15:26 UTC
Labels: FTB Skies Expert
