### ISSUE TITLE
[Bug]: Using Sigil of the Green Grove on a Poppy (to duplicate it) uses up the Sigil of the Green Grove.

### ISSUE THREAD

**Issue by Wargoncz** [FTBTeam/FTB-Modpack-Issues#1454] opened 2022-10-17 18:02 UTC
### Modpack

FTB Inferno

### Modpack version

1.0.3

### Describe the bug

Using Sigil of the Green Grove on a Poppy (to duplicate it) uses up the Sigil of the Green Grove. 
Double checked if I have enough LP. 
Crafted another to confirm this - one right click on poppy on grass and POOF gone.

### Steps to reproduce

1. Place poppy on grass
2. Use Sigil of the Green Grove on it
3. POOF

### Expected behaviour

Poppy will duplicate as if using bonemeal

**Comment by Saereth** [comment] 2022-10-17 18:36
duplicate of 
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1398

**Closed by Saereth** 2022-10-17 18:36 UTC
Labels: state: Duplicate :books:, FTB Inferno
