### ISSUE TITLE
[Bug]: Every world spawn with errors blocking the tutorial and its other features

### ISSUE THREAD

**Issue by Haste69** [FTBTeam/FTB-Modpack-Issues#522] opened 2021-12-30 17:15 UTC
### Modpack

FTB Academia

### Modpack version

1.12.2

### Describe the bug

Every time i make a new world i spawn in with error that makes the quit school and reset course buttons to not work anymore and also when i get to the botania part of the tutorial the wand of the forest will not link the mana spreader with the mana pool if i try to quit school i get an error and the game lock itself if i try reset course i get put at the beggining of the map and nothing works anymore

### Steps to reproduce

1. Make a new world (the error appears the moment you have entered the world)
2. get to the botania stage of the tutorial
3.Try linking using wand of the forest with the mana spreader and the mana pool it will fail

### Expected behaviour

I expected everything will be fine but no the moment i get to the botania stage the map breaks and wont let me progress

### Screenshots

these are the error
![problem for ftb academia](https://user-images.githubusercontent.com/84870292/147773609-088a2bc7-806e-428c-841d-da0449263ff0.png)
the first red text appears when i press the reset course/quit school buttons
and the last red text is the error that appears when i enter the world

**Comment by Raidobw2** [comment] 2021-12-31 02:42
Have you tried reinstalling the modpack? Careful if you started a world, you want to copy it elsewhere to keep a copy before doing this.

In your instances folder, delete `.localCache` which is the download cache.
Then reinstall the modpack.
That seems to be a script error and I wonder if it could be caused by some files missing, which a reinstall could help solving.

Please let us know! Thanks.

**Comment by aaronhowser1** [comment] 2022-01-23 01:20
Closed as they haven't responded.

**Closed by aaronhowser1** 2022-01-23 01:20 UTC
Labels: FTB Academy 1.12, 3: Support Request
