### ISSUE TITLE
FTB Skies Expert - 1.4.1 - Recipe bug 

### ISSUE THREAD

**Issue by Grimjahk** [FTBTeam/FTB-Modpack-Issues#5020] opened 2024-03-20 22:35 UTC
### Modpack

FTB Skies Expert

### Modpack version

1.4.1

### Describe the bug

Issue: Recipe for Basic Control Circuit in the Fabrication Matrix is the same as the fluid Encapsulator Recipe for the Advanced Control Circuit.  Requiring a Signalum processor (2x basic Control Circuit) to make one Basic Control Circuit.  I think the intended recipe is for the Advanced Control Circuit instead.

### Steps to reproduce

Recipes shown in JEI

### Expected behaviour

Fabrication Matrix recipe for Advance control Circuit does not exist, instead rewards 1 Basic Control Circuit at the cost of 2 Basic Control Circuits

**Comment by krisavi** [comment] 2024-03-21 07:08
Duplicate of #5017 ?

**Comment by Grimjahk** [comment] 2024-03-21 19:46
Duplicate of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5017.

**Closed** 2024-03-21 19:45 UTC
Labels: FTB Skies Expert
