### ISSUE TITLE
[Bug]: Mega torch not blocking spawns

### ISSUE THREAD

**Issue by rebeldev** [FTBTeam/FTB-Modpack-Issues#34] opened 2021-09-28 13:13 UTC
### Modpack

FTB OceanBlock

### Modpack version

1.1.0

### Describe the bug

The mega torch does not block any aggressive mob spawns.  I turned on spawning debug logging for torchmaster and it shows the checkspawn and allows everything.  I've also tried specifically adding mobs to the block list override and it still allows the spawns.  Reverted to version 2.3.7 of torchmaster and still the same.  It is as if the block list is empty however I am not seeing anything that would cause that.

### Steps to reproduce

I'm playing on a server so not sure if this is reproduceable in single player or not but:
1. place mega torch close to dark area
2. get far enough way for mobs to spawn

### Expected behaviour

aggressive mobs shouldn't spawn

**Comment by MichaelHillcox** [comment] 2021-09-28 13:18
Duplicate of #16

Thanks for the report though :+1:

**Closed by MichaelHillcox** 2021-09-28 13:18 UTC
