### ISSUE TITLE
Leadstone angel ring missing crafting recipe

### ISSUE THREAD

**Issue by SineW4V3** [FTBTeam/FTB-Modpack-Issues#2292] opened 2022-12-10 04:01 UTC
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.4

### Describe the bug

Cannot make leadstone angel ring, recipe messing

### Steps to reproduce

1. Try to click on leadstone angel ring recipe
2. Can't
3. Cry

### Expected behaviour

Recipe for item should appear

**Comment by Saereth** [comment] 2022-12-10 14:35
This is not a bug, currently the mod doesnt have craft recipes for them so I've opened an issue with the mod author to see if they're going to be adding recipes soon now that thermal exists on 1.19.2. If I dont get it resolved on the mod side in a few days I'll add some custom recipes.

https://github.com/DenisMasterHerobrine/AngelRing/issues/43

**Comment by DenisMasterHerobrine** [comment] 2022-12-16 03:52
Just a heads up for this issue. Fixed the Leadstone Angel Ring recipe. It was missing due to refactoring the rings in 2.x when I started supporting 1.19.x versions.
Fixed in Angel Ring 2.1.5 for 1.19.2.

**Closed** 2023-01-09 19:08 UTC
Labels: 1: Mod Issue, state: Fixed in Dev :hammer_and_wrench:, 2: Enhancement, FTB Presents Direwolf20 1.19
