### ISSUE TITLE
FTB Inferno crashes before title screen

### ISSUE THREAD

**Issue by grencham** [FTBTeam/FTB-Modpack-Issues#2529] opened 2023-01-18 03:06 UTC
### Modpack

FTB Inferno

### Modpack version

1.2.1,1.4.0

### Log Files

![image](https://user-images.githubusercontent.com/62443958/213072310-ea277e69-e3e4-4148-be4b-1d6900ab0501.png)
[hs_err_pid14108.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10441605/hs_err_pid14108.log)

### Describe the bug

Unable to start game, it crashes on attempting to load.

### Steps to reproduce

1. Click Play button in FTB launcher
2. Wait
3. Game crashes

### Expected behaviour

I click play and then am able to play

### Additional information

8Gb ram allocated to instance, most recent version of java, intel arc a770 gpu with most up to date drivers

**Comment by ztk4** [comment] 2023-01-18 03:54
Disclaimer: I'm not a part of the FTB team, just happened to see this.

FWIW the crash you posted is an intel graphics driver crash, so the bug is likely an incompatibility with the way this program and your graphics driver are interacting. This could mean a bug in the intel driver, a bug in the JVM, a bug in one of the mods, or even generic corruption of files on your disk.

Personally, I'd first try a fresh install of FTB + a fresh install of the pack. If that doesn't work, I'd try a fresh install of graphics drivers.

Things you might want to try:
  * Can you run Vanilla minecraft on the same version this pack uses? If not, there's likely nothing you'll be able to solve here, try filing a bug in the Mojang issue tracker.
  * File a bug against intel, give steps to reproduce the error on a fresh install + info about your system configuration. If they can reproduce it they have an incentive to fix it (even if there's no bug in their code): customers frustrated by graphics crashes tend to not stay brand loyal LOL.

**Comment by grencham** [comment] 2023-01-18 04:07
Hey, appreciate the quick response, I'll give it a go. I know I can "play" stoneblock 3 which is minecraft version 1.18.2 as well (though there are other problems there) but ill be sure to give it a try on vanilla for comparisons sake.

**Comment by Saereth** [comment] 2023-02-28 21:11
Since this seems to be beyond the scope of pack dev I'm gonna close this

**Closed by Saereth** 2023-02-28 21:11 UTC
Labels: 3: Support Request, FTB Inferno
