### ISSUE TITLE
[Bug]: Framed Drawer crashing Minecraft

### ISSUE THREAD

**Issue by PdSiK** [FTBTeam/FTB-Modpack-Issues#1930] opened 2022-11-13 21:17 UTC
### Modpack

FTB Stoneblock 3

### Modpack version

v1.2.1

### Describe the bug

While changing the outside texture for Framed Drawer from **Functional Drawers**, if you attempt to use Slime block, the game crashes.

_*Not sure if its the same for inside texture*_

### Steps to reproduce

1. Craft Framed Drawer 
2. Craft Slime Block
3. Change the texture of the outside to Slime Block

### Expected behaviour

Either nothing happens (texture removed), or the texture doesn't crash the Minecraft

**Comment by Sunekaer** [comment] 2022-11-13 21:58
Please attach the crash log

**Comment by 5ully** [comment] 2022-11-13 22:22
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9998331/debug.log)

**Comment by Sunekaer** [comment] 2022-11-14 17:24
Duplicate of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1667

**Closed by Sunekaer** 2022-11-14 17:24 UTC
Labels: FTB StoneBlock 3
