### ISSUE TITLE
[Bug]: Gates Bugged

### ISSUE THREAD

**Issue by KiratoDHNK** [FTBTeam/FTB-Modpack-Issues#2151] opened 2022-11-26 01:30 UTC
### Modpack

Inferno

### Modpack version

1.3.0

### Log Files

No Logs,

### Describe the bug

Every Gate is bugged in some shape or Form. Some Spawn Mobs and sometimes Nothings Spawn.

This happens on my Server and Singleplayer World.

### Steps to reproduce

Just placing the Pearl.

### Expected behaviour

Spawning Mobs

### Screenshots

![2022-11-26_02 26 06](https://user-images.githubusercontent.com/59509809/204067274-c5288e8e-242e-421c-9d37-c0f2a99bf6a4.png)

**Comment by orbidlo** [comment] 2022-11-28 09:25
this is duplicate of #1858 and check out the comments for fix until modpack gets updated. Just be warned that updating the portal mob also makes you not have any 30sec warning between flavour text and invasion spawning.

**Closed** 2023-01-18 22:11 UTC
Labels: state: Duplicate :books:, FTB Inferno
