### ISSUE TITLE
[Bug]: Pipez x Powah cables causes crash

### ISSUE THREAD

**Issue by Lightopopo** [FTBTeam/FTB-Modpack-Issues#1197] opened 2022-08-01 14:10 UTC
### Modpack

FTB Oceanblock

### Modpack version

1.14.0

### Log Files

https://paste.feed-the-beast.com/view/8960dfca

### Describe the bug

Hey, on FTB OceanBlock I tried to build draconium farm in The End. I set up 2 Laser Drills (Industrial Foregoing) and 1 Laser Base but when they started to mine it crashed my game. Any help? 

### Steps to reproduce

Go to The End
Set up Laser Drills
Give it energy 

### Expected behaviour

Crash

**Comment by TheonlyTazz** [comment] 2022-08-01 18:12
it seems that, from reading your crash log, that the issue is caused by something from Pipez, please try to use something else to power it to see if that still causes the crash

**Comment by Lightopopo** [comment] 2022-08-01 20:24
Oh, okay thank you for answering

**Comment by Lightopopo** [comment] 2022-08-01 20:26
Thank you for the answer. Any idea how can I recover from this point my backup is really far behind it would be a huge help.

**Comment by Raidobw2** [comment] 2022-08-02 05:10
Delete `pipez-1.16.5-1.2.15.jar` from your mods folder and add https://www.curseforge.com/minecraft/mc-mods/pipez/files/3760254 instead. Normally from looking at https://github.com/henkelmax/pipez/issues/33 that should be fixed in that version of the mod, let us know.

**Comment by Lightopopo** [comment] 2022-08-02 16:50
> Delete `pipez-1.16.5-1.2.15.jar` from your mods folder and add https://www.curseforge.com/minecraft/mc-mods/pipez/files/3760254 instead. Normally from looking at [henkelmax/pipez#33](https://github.com/henkelmax/pipez/issues/33) that should be fixed in that version of the mod, let us know.

Thank you so much. I was able to fix my issue. Also, it fixed another problem where it wouldn't connect with the flux plug/point but it's all good now. Thanks again to both of you.

**Comment by Raidobw2** [comment] 2022-08-02 20:30
Please leave this opened for when we get to updating the pack :) this way other people can see the workaround in this issue if they need it, and it's a nice reminder for us and to include in the changelog as well

**Comment by Raidobw2** [comment] 2022-09-09 07:40
Oops, that's a mislabel on my part. That's still only fixed in a dev build only, not released yet

**Closed** 2023-02-07 21:17 UTC
Labels: FTB OceanBlock, 1: Mod Issue, state: Fixed in Dev :hammer_and_wrench:
