### ISSUE TITLE
[Suggestion]:  FTB Stoneblock 3 Add Extrastorage

### ISSUE THREAD

**Issue by Woodie6288** [FTBTeam/FTB-Modpack-Issues#1810] opened 2022-11-10 00:32 UTC
### Modpack

FTB Stoneblock 3

### Mod suggestion

I know a lot of people like AE2 but there are those of us who prefer Refined Storage. However, RS is missing a few advanced items that is taken care of by another mod that pairs very nicely with it and puts in on a level playing field with AE2 so those of use who prefer RS over AE2 don't feel like we are forced in to playing the other mod. Enter the mod Extrastorage. It adds in multiple tiered crafters and advanced exporters/importers as well as a few other things. Thanks for your consideration. 

https://www.curseforge.com/minecraft/mc-mods/extrastorage

**Comment by Sunekaer** [comment] 2022-11-10 08:17
Duplicate of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1599

**Closed by Sunekaer** 2022-11-10 08:17 UTC
Labels: 2: Mod Suggestion, FTB StoneBlock 3
