### ISSUE TITLE
[Bug]: Oceanblock server not starting 

### ISSUE THREAD

**Issue by MuffinGamezYT** [FTBTeam/FTB-Modpack-Issues#592] opened 2022-01-30 01:50 UTC
### Modpack

Oceanblock

### Modpack version

1.11.0

### Log Files

https://paste.feed-the-beast.com/view/839c0f54

### Describe the bug

Server will not start

### Steps to reproduce

1. Use .EXE installer for 1.11.0
2. Follow the installation steps
3. Use the .BAT file to start the server
4. Problem occurs https://paste.feed-the-beast.com/view/839c0f54

### Expected behaviour

Server to start

### Additional information

Happens on both of my pcs when trying to run the server, both have the latest java 8 and are running windows 10

**Comment by Raidobw2** [comment] 2022-01-30 02:53
Hi, come on the FTB Discord at first if you request help for a modpack or a server setup. I have the community members to back me up and our Bot to link you things.
This is caused by an incompatible version of Java. Java 8 is good yes, but no later than Java 8 update 312. Java8u321 like you have is incompatible:

You will find older builds of Java 8 on Adoptium's website, at https://adoptium.net/archive.html?variant=openjdk8&jvmVariant=hotspot. Take the JRE for the ` jdk8u312-b07` section from 21 October 2021, otherwise more recent versions might be incompatible.
![image](https://user-images.githubusercontent.com/17010632/151684815-595be190-d3c7-4aff-b046-d513a5e40fbe.png)
Once that's done, uninstall other versions of Java 8, important step.
Boot up your server and that should now work correctly.
Please close the issue if that solves it, thanks.

**Closed** 2022-01-30 03:01 UTC
Labels: FTB OceanBlock, 3: Support Request
