### ISSUE TITLE
[Bug]: FTP Stoneblock 3 Thief silverfish can despawn while holding stolen items.

### ISSUE THREAD

**Issue by derram** [FTBTeam/FTB-Modpack-Issues#1925] opened 2022-11-13 15:36 UTC
### Modpack

FTB Stoneblock 3 

### Modpack version

1.2.1

### Describe the bug

Thief silverfish can despawn while holding equipment. 

### Steps to reproduce

1. Have item stolen

2. Move far enough away.

3. Spend the next hour making new weapons.

### Expected behaviour

The thief silverfish should be persistant while it's holding something.

**Comment by Thunder-Nova** [comment] 2022-11-13 16:52
Yea, noticed that too I was wondering why some of my stuff were gone. And recalled they were stolen.

**Comment by Sunekaer** [comment] 2022-11-13 21:39
Duplicate of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1757

**Closed by Sunekaer** 2022-11-13 21:39 UTC
