### ISSUE TITLE
[Bug]: Out of nowhere Server Crash

### ISSUE THREAD

**Issue by 4w3Official** [FTBTeam/FTB-Modpack-Issues#1997] opened 2022-11-16 22:52 UTC
### Modpack

FTB StoneBlock 3

### Modpack version

1.2.1

### Log Files

latest Log: https://paste.4w3.dev/ogevezipen.txt
Crash Log: https://paste.4w3.dev/afumofufaj.properties

### Describe the bug

Out of nowhere the server crashed - With "Server closed" message
Otherwise no problems at all - everything ran perfectly

### Steps to reproduce

-/-

### Expected behaviour

-/-

**Comment by ukmcplyr** [comment] 2022-11-16 23:14
Likely dupe of #1935

**Comment by Raidobw2** [comment] 2022-11-18 08:38
That looks to be the case indeed, I'll keep only the other issue for tracking purposes in that case. 4w3Official you may wish to subscribe to the other issue to be notified when this is being worked on.
FTB Backups 2 appears to be causing the problem/leading to the crash here, so if you can remove it and see if that fixes the crashes, that'd be great. Please comment in the other issue if you do try that!

**Closed by Raidobw2** 2022-11-18 08:38 UTC
Labels: 1: Mod Issue, FTB StoneBlock 3
