### ISSUE TITLE
[Bug]: Simply Backpacks Auto Pickup bug

### ISSUE THREAD

**Issue by Ghost-Asood** [FTBTeam/FTB-Modpack-Issues#343] opened 2021-11-19 15:26 UTC
### Modpack

DireWolf20 1.16 and Oceanblock

### Modpack version

1.11.0 / 1.9 (oceanblock)

### Describe the bug

get a Common/Uncommon/Rare/Epic backpack from Simply Backpacks mod, turn off auto pickup mode, drop something, turn on auto pickup mode, pick it up, you'll have the same item in your inventory and your backpack.

### Steps to reproduce

1. get a Common/Uncommon/Rare/Epic backpack from Simply Backpacks mod
2. drop/mine something 
3. turn on auto pickup mode
4. pickup the items you dropped/mined
5. tada! now you have the same item in your inv and your backpack

### Expected behaviour

when auto pickup is turned it, items should go only to the backpack and not into both inventory and backpack.

### Screenshots

https://user-images.githubusercontent.com/12798904/142732533-65d8d25b-f77e-4189-bd0f-6c262df19e0c.mp4

**Comment by Ghost-Asood** [comment] 2021-11-20 12:11
@Raidobw2 this also works on Oceanblock 1.9

**Comment by MichaelHillcox** [comment] 2021-11-20 15:46
Can you confirm if you have any baubles on?

**Comment by Ghost-Asood** [comment] 2021-11-20 16:02
other than a magnet from botania, i have nothing on

**Comment by Flanks255** [comment] 2021-11-20 16:05
Have you added any mods?

**Comment by Ghost-Asood** [comment] 2021-11-20 16:14
nope
just the plain modpack

**Comment by MichaelHillcox** [comment] 2021-11-20 16:19
Could you zip your modpack up for me, world and all, then email a link to it at mikey@feed-the-beast.com I can share it with the mod developer and we can look into it more for you as we're currently not able to reproduce the issue and we think it's an edgecase with another mod.

**Comment by Ghost-Asood** [comment] 2021-11-20 17:47
which one, Oceanblock or Direwolf?

**Comment by Raidobw2** [comment] 2021-11-20 22:15
Zip them OceanBlock, doesn't matter too much since the issue is the same in both modpacks.

**Comment by Ghost-Asood** [comment] 2021-11-21 16:20
Update: I can't seem to reproduce this bug on Direwolf anymore, not sure why is that, but on OceanBlock it still works, for me and for other players too

**Comment by Raidobw2** [comment] 2021-11-24 07:14
Hello, I went on with Direwolf20 for Minecraft 1.16.5, version 1.11 and tested this. I do not get any dupes from using the backpack. I've also tested the backpack in #344, same outcome as when I tested in-dev on version 1.12 of DW20 1.16, no dupes.
Please let me know if it's still duping items as I cannot reproduce it. I'd recommend a clean reinstall of the modpack after backupping your worlds. See below:
![backpacks](https://user-images.githubusercontent.com/17010632/143190583-8259e150-e99b-4d7f-9229-8785f27f78ab.gif)
@MichaelHillcox did they send you their world? Everything looks ok on my end, there doesn't seem to be an issue with Simply Backpacks. I checked their inventory as well from the video to see if it could be a bad mod interaction, but no issue with some of those items in my inventory either. Read below and thanks.

I'll be closing this issue in a few days or until I get notified that this still is a thing even with a clean install, as it seems to work fine, even in the 1.11 version.
Thanks!

**Comment by Raidobw2** [comment] 2021-12-26 12:35
I'm unable to reproduce it, this is working normally for me, no dupes. It may have been a bug in earlier versions.

**Comment by Raidobw2** [comment] 2022-01-03 07:40
Could not reproduce in-dev, this seems fixed in 1.13.

**Closed by Raidobw2** 2022-01-03 07:40 UTC
Labels: FTB Presents Direwolf20 1.16, 1: Mod Issue, state: Fixed :heavy_check_mark:
