### ISSUE TITLE
[Bug]: Crafting Multiple Items at once in a Extreme Crafting table Duplicates the output

### ISSUE THREAD

**Issue by Timu420** [FTBTeam/FTB-Modpack-Issues#2157] opened 2022-11-26 10:47 UTC
### Modpack

Stoneblock 3

### Modpack version

1.4.2

### Describe the bug

I placed 23 times the Recipie for Neutronium Compressor in the Extreme Crafting Table. i shift Clicked the on the Compressor and got 45 Compressor. i guess it gave me 1, then was Confused and doubled the rest 22 which it still has to give me. 1+22*2=45.

### Steps to reproduce

1. put the Recipie for a Neutron Compressor 23 times in the Table
2. Shift Click the outpur Compressor
3. get 45

### Expected behaviour

only getting 23 Neutron Compressor

### Screenshots

![image](https://user-images.githubusercontent.com/91256797/204084690-2f764787-e589-40c0-9883-cee365355fd1.png)

**Comment by Draradech** [comment] 2022-11-27 11:49
#1903

**Comment by Draradech** [comment] 2022-11-27 11:53
As more and more people reach the endgame, most will encounter this problem. Especially as there is no autocrafting for the late-game ingredients (endest pearl, infinity catalyst), crafting with stacks at a time will be the norm, not the exception.

**Comment by Sunekaer** [comment] 2022-11-28 17:28
Duplicate of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1903

**Closed by Sunekaer** 2022-11-28 17:28 UTC
Labels: 1: Mod Issue, FTB StoneBlock 3
