### ISSUE TITLE
JEI and inventory hover tooltips not working when potions are applied

### ISSUE THREAD

**Issue by ThatElektrika** [FTBTeam/FTB-Modpack-Issues#6227] opened 2024-11-20 02:37 UTC
### Modpack

FTB Evolution

### Modpack version

1.3.0

### Launcher

CurseForge

### Has the pack been modified

No

### Describe the bug

After getting potion effects (i think from skills, idk) i was no longer able to see the JEI ui and i could no longer see item name tooltips. I've attached a video of it only occurring in the regular inventory UI.

### Steps to reproduce

1. Apply a potion.
2. Open inventory.

### Expected behaviour

JEI and the item name tooltips should be visible

### Screenshots

https://github.com/user-attachments/assets/d44c74c1-cf7a-47d1-99d2-efe87700e0a5

**Comment by sportsziggy** [comment] 2024-11-20 04:51
"Right click any of the icons in the top left of your inventory, and then click the red X on the above icons circled in red to remove them and it will fix your issue."
![image](https://github.com/user-attachments/assets/101bc809-4a1e-4ea2-8c1c-2502266f2553)
From the FTB discord.

**Comment by Gaz492** [comment] 2024-11-20 08:39
Duplicate of #6118

**Closed by Gaz492** 2024-11-20 08:39 UTC
Labels: Bug, FTB Evolution

**Comment by ThatElektrika** [comment] 2024-11-20 13:27
> "Right click any of the icons in the top left of your inventory, and then click the red X on the above icons circled in red to remove them and it will fix your issue."
> ![image](https://private-user-images.githubusercontent.com/1366131/387941877-101bc809-4a1e-4ea2-8c1c-2502266f2553.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMDk0ODksIm5iZiI6MTczMjEwOTE4OSwicGF0aCI6Ii8xMzY2MTMxLzM4Nzk0MTg3Ny0xMDFiYzgwOS00YTFlLTRlYTItOGMxYy0yNTAyMjY2ZjI1NTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjBUMTMyNjI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzEwYzJhMjIwZjJhNzc5OWMwODZjOGM1ZmMzYjZkMmQ0ZDE2MzE4ZDVjODg0MGQ5NmM3MjE2YjNiODhhOGNjMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.eH_cpvx_Lt78WyAzSHfC26-6-ifpoacEqnO9x3dTgrw)
> From the FTB discord.

How is this supposed to fix an issue related to potion effects?

**Comment by sportsziggy** [comment] 2024-11-20 14:42
> > "Right click any of the icons in the top left of your inventory, and then click the red X on the above icons circled in red to remove them and it will fix your issue."
> > ![image](https://private-user-images.githubusercontent.com/1366131/387941877-101bc809-4a1e-4ea2-8c1c-2502266f2553.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMDk0ODksIm5iZiI6MTczMjEwOTE4OSwicGF0aCI6Ii8xMzY2MTMxLzM4Nzk0MTg3Ny0xMDFiYzgwOS00YTFlLTRlYTItOGMxYy0yNTAyMjY2ZjI1NTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjBUMTMyNjI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzEwYzJhMjIwZjJhNzc5OWMwODZjOGM1ZmMzYjZkMmQ0ZDE2MzE4ZDVjODg0MGQ5NmM3MjE2YjNiODhhOGNjMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.eH_cpvx_Lt78WyAzSHfC26-6-ifpoacEqnO9x3dTgrw)
> > From the FTB discord.
> 
> How is this supposed to fix an issue related to potion effects?

Check the duplicated thread




> Duplicate of #6118
