### ISSUE TITLE
FTB Inferno - Enabling Shaders Crashes Client

### ISSUE THREAD

**Issue by Exovi** [FTBTeam/FTB-Modpack-Issues#4523] opened 2024-01-01 05:08 UTC
### Modpack

FTB Inferno

### Modpack version

1.10

### Log Files

https://gist.githubusercontent.com/FTBAuto/8d45ab9db3d441618ccab2a3722c4e9d/raw/c2c6464d4dc7cd15a1bb85cb7972651ee7adaf35/crash-2023-12-31_23.04.44-client.txt

### Describe the bug

Turning on shaders crashes client

Also crashes when loading world with shaders on.

No issues at all with Shaders off.

### Steps to reproduce

Create New World
Enable ComplementaryReimagined_r1.2.2
Crash

### Expected behaviour

Shaders Turn On

**Comment by Exovi** [comment] 2024-01-01 05:09
Crashlog says Evilcraft beacon is the issue, I think? If I am reading it right

**Comment by Gaz492** [comment] 2024-06-20 21:02
Duplicate of #4457

**Closed by Gaz492** 2024-06-20 21:02 UTC
Labels: FTB Inferno
