### ISSUE TITLE
[Bug]: Gravestone mod not keeping stuff

### ISSUE THREAD

**Issue by zookeper** [FTBTeam/FTB-Modpack-Issues#1673] opened 2022-11-06 02:49 UTC
### Modpack

Stoneblock3

### Modpack version

1.0.1

### Describe the bug

Gravestones mod doesn't work.

### Steps to reproduce

die while collecting stuff
(lame mod cant keep up and stuff doesn't get recorded as lost on death)
lose stuff.

### Expected behaviour

Not lose my stuff? it's a gravestones mod....

### Screenshots

5 graves, all with nothing but a book in them, spent 20 mins trying to find grave, realized it never even spawned.

### Additional information

if there is a mod that prevents item loss on death, it should prevent item loss on death.....

**Comment by Sunekaer** [comment] 2022-11-06 09:49
Can you explain more about what you was doing, because im not able to recreate this issue

**Comment by Xavion3** [comment] 2022-11-11 03:15
This sounds like a duplicate of my issue at #1560 

Assuming it is a timing issue as proposed there, reliably reproducing it is likely to be very annoying, but at three reports now it seems like it's definitely a thing.

**Closed** 2022-11-28 17:55 UTC
Labels: 1: Mod Issue, state: Awaiting Reply :speaking_head:, FTB StoneBlock 3
