### ISSUE TITLE
[Bug]: Charged Certus Quartz Dupe Bug

### ISSUE THREAD

**Issue by MisterZam** [FTBTeam/FTB-Modpack-Issues#101] opened 2021-10-08 14:43 UTC
### Modpack

FTB Oceanblock

### Modpack version

1.2.0

### Log Files

No logs needed

### Describe the bug

Charged Certus Quartz inside the krate will be dupe once you right click it with cardbox

### Steps to reproduce

1. Put a krate
2. Insert charged certus quartz
3. Right click the krate with cardboard box
4. Charged Certus Quartz will be yeeted out of the krate (the duped quartz)
5. Shift right click the boarded krate to remove the box
6. Original Charged Certus Quartz still be inside the krate.

### Expected behaviour

Nothing should be dropped when you cardboard box a krate

**Comment by Sunekaer** [comment] 2021-10-09 08:54
Duplicate of #33

**Closed by Sunekaer** 2021-10-09 08:54 UTC
