### ISSUE TITLE
Ingot Duplication Bug

### ISSUE THREAD

**Issue by CameronPersonett** [FTBTeam/FTB-Modpack-Issues#4386] opened 2023-12-02 08:27 UTC
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.7

### Describe the bug

Ender IO allows the grinding ball bonus on ingots, so you can set up a loop between a SAG mill and alloy smelter to gain infinite ingots.

### Steps to reproduce

Place SAG mill next to alloy smelter. Set the touching sides of each machine to push/pull and throw any compatible ingot into the input of the SAG mill. Use whichever grinding stone you can afford that gives higher than 100% main output. When the ingot is pulverized, it will be greater than one dust per ingot depending on the main output percentage. It will be smelted in the alloy smelter and sent right back into the SAG mill.

### Expected behaviour

Only allow one dust per ingot when pulverizing with the SAG mill.

**Comment by Gaz492** [comment] 2024-06-24 10:32
Duplicate of #4007

**Closed by Gaz492** 2024-06-24 10:32 UTC
Labels: FTB Presents Direwolf20 1.20
