### ISSUE TITLE
[Bug]: Consuming the Tome of Knowledge crashes game

### ISSUE THREAD

**Issue by Nibble-Byte** [FTBTeam/FTB-Modpack-Issues#2062] opened 2022-11-20 09:41 UTC
### Modpack

FTB Stoneblock 3

### Modpack version

1.3.0

### Log Files

Log file was too large to upload to pastebin.
Many many many lines of this:
```
[20Nov2022 18:14:20.368] [Render thread/DEBUG] [projecte/]: ** RECEIVED TRANSMUTATION EMC DATA CLIENTSIDE **
[20Nov2022 18:14:20.368] [Render thread/DEBUG] [projecte/]: ** RECEIVED TRANSMUTATION EMC DATA CLIENTSIDE **
[20Nov2022 18:14:20.368] [Render thread/DEBUG] [projecte/]: ** RECEIVED TRANSMUTATION EMC DATA CLIENTSIDE **
[20Nov2022 18:14:20.368] [Render thread/DEBUG] [projecte/]: ** RECEIVED TRANSMUTATION EMC DATA CLIENTSIDE **
[20Nov2022 18:14:20.368] [Render thread/DEBUG] [projecte/]: ** RECEIVED TRANSMUTATION EMC DATA CLIENTSIDE **
[20Nov2022 18:14:20.368] [Render thread/DEBUG] [projecte/]: ** RECEIVED TRANSMUTATION EMC DATA CLIENTSIDE **
```

### Describe the bug

As soon as I consumed the tome of knowledge in the transmutation tablet my game crashed. And it now also crashes whenever trying to interact with the transmutation tablet.

### Steps to reproduce

1. Craft Tome of Knowledge
2. "Learn" the tome in a transmutation tablet
3. Game crashes

### Expected behaviour

I would expect my game not to crash when learning the tome of knowledge

**Comment by NordicGamerFE** [comment] 2022-11-20 09:47
Duplicate of #2018

**Closed** 2022-11-20 12:19 UTC
