### ISSUE TITLE
[Bug]: Chunk Resets upon loading

### ISSUE THREAD

**Issue by DanielABrennand** [FTBTeam/FTB-Modpack-Issues#1934] opened 2022-11-14 00:46 UTC
### Modpack

FTB Inferno

### Modpack version

1.3.0

### Log Files

https://pste.ch/dajecolona.md

### Describe the bug

When loading into a world a specific chunk is reset to its state upon world gen.

### Steps to reproduce

1. Start up Inferno
2. Load into a world
3. Place any block into the specific chunk
4. Save and exit
5. Load Back into the same world to find those blocks gone

### Expected behaviour

The chunk to be in the same modified state that it was in when the world was exited

### Screenshots

Before Saving and exiting:
![2022-11-14_00 35 55](https://user-images.githubusercontent.com/67263968/201553520-90e40872-d95e-437c-81a9-415dfef1fbd8.png)
Upon Loading back into the world:
![2022-11-14_00 37 19](https://user-images.githubusercontent.com/67263968/201553518-6a232ea7-8b36-4389-ac4b-2a792e671c42.png)

### Additional information

World file can be provided (Its too large to upload here, 47MB).

**Comment by Saereth** [comment] 2022-11-21 07:10
Would need some log files here to look for the cause of the data corruption

**Comment by Raidobw2** [comment] 2022-12-02 06:55
Might be this Saereth:
```
[00:37:43] [Server thread/ERROR] [minecraft/ChunkMap]: Failed to save chunk 16,364
java.lang.RuntimeException: StructurePiece "L_Ender.cataclysm.structures.SoulBlackSmithPieces$Piece": "null" missing ID Mapping, Modder see MapGenStructureIO
	at net.minecraft.world.level.levelgen.structure.StructurePiece.m_192644_(StructurePiece.java:76) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:StructurePieceMixin,pl:mixin:A}
	at net.minecraft.world.level.levelgen.structure.pieces.PiecesContainer.m_192749_(PiecesContainer.java:52) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.structure.StructureStart.m_192660_(StructureStart.java:71) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?] {re:mixin,re:classloading,pl:mixin:APP:brutalbosses.mixins.json:StructureSpawnBossMixin,pl:mixin:APP:quark.mixins.json:StructureStartMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.m_188249_(ChunkSerializer.java:436) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?] {re:mixin,re:classloading,pl:mixin:APP:architectury.mixins.json:MixinChunkSerializer,pl:mixin:A}
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.m_63454_(ChunkSerializer.java:377) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?] {re:mixin,re:classloading,pl:mixin:APP:architectury.mixins.json:MixinChunkSerializer,pl:mixin:A}
	at net.minecraft.server.level.ChunkMap.m_140258_(ChunkMap.java:771) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:wyml.mixins.json:AccessorChunkMap,pl:mixin:APP:smoothchunk.mixins.json:ChunkMapMixin,pl:mixin:APP:ftbchunks-common.mixins.json:ChunkMapMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
	at net.minecraft.server.level.ChunkMap.m_202998_(ChunkMap.java:482) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:wyml.mixins.json:AccessorChunkMap,pl:mixin:APP:smoothchunk.mixins.json:ChunkMapMixin,pl:mixin:APP:ftbchunks-common.mixins.json:ChunkMapMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?] {}
	at net.minecraft.server.level.ChunkMap.m_140353_(ChunkMap.java:455) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:wyml.mixins.json:AccessorChunkMap,pl:mixin:APP:smoothchunk.mixins.json:ChunkMapMixin,pl:mixin:APP:ftbchunks-common.mixins.json:ChunkMapMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
	at net.minecraft.server.level.ChunkMap.m_140280_(ChunkMap.java:426) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:wyml.mixins.json:AccessorChunkMap,pl:mixin:APP:smoothchunk.mixins.json:ChunkMapMixin,pl:mixin:APP:ftbchunks-common.mixins.json:ChunkMapMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:313) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:smoothchunk.mixins.json:ServerChunkCacheMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7041_(MinecraftServer.java:603) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_7041_(IntegratedServer.java:174) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:minetogether-common.mixins.json:connect.MixinIntegratedServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:717) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) [?:?] {}
[00:37:44] [Server thread/ERROR] [minecraft/ChunkMap]: Failed to save chunk 15,339
java.lang.RuntimeException: StructurePiece "L_Ender.cataclysm.structures.BurningArenaPieces$Piece": "null" missing ID Mapping, Modder see MapGenStructureIO
	at net.minecraft.world.level.levelgen.structure.StructurePiece.m_192644_(StructurePiece.java:76) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:StructurePieceMixin,pl:mixin:A}
	at net.minecraft.world.level.levelgen.structure.pieces.PiecesContainer.m_192749_(PiecesContainer.java:52) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.structure.StructureStart.m_192660_(StructureStart.java:71) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?] {re:mixin,re:classloading,pl:mixin:APP:brutalbosses.mixins.json:StructureSpawnBossMixin,pl:mixin:APP:quark.mixins.json:StructureStartMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.m_188249_(ChunkSerializer.java:436) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?] {re:mixin,re:classloading,pl:mixin:APP:architectury.mixins.json:MixinChunkSerializer,pl:mixin:A}
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.m_63454_(ChunkSerializer.java:377) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?] {re:mixin,re:classloading,pl:mixin:APP:architectury.mixins.json:MixinChunkSerializer,pl:mixin:A}
	at net.minecraft.server.level.ChunkMap.m_140258_(ChunkMap.java:771) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:wyml.mixins.json:AccessorChunkMap,pl:mixin:APP:smoothchunk.mixins.json:ChunkMapMixin,pl:mixin:APP:ftbchunks-common.mixins.json:ChunkMapMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
	at net.minecraft.server.level.ChunkMap.m_202998_(ChunkMap.java:482) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:wyml.mixins.json:AccessorChunkMap,pl:mixin:APP:smoothchunk.mixins.json:ChunkMapMixin,pl:mixin:APP:ftbchunks-common.mixins.json:ChunkMapMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?] {}
	at net.minecraft.server.level.ChunkMap.m_140353_(ChunkMap.java:455) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:wyml.mixins.json:AccessorChunkMap,pl:mixin:APP:smoothchunk.mixins.json:ChunkMapMixin,pl:mixin:APP:ftbchunks-common.mixins.json:ChunkMapMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
	at net.minecraft.server.level.ChunkMap.m_140280_(ChunkMap.java:426) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:wyml.mixins.json:AccessorChunkMap,pl:mixin:APP:smoothchunk.mixins.json:ChunkMapMixin,pl:mixin:APP:ftbchunks-common.mixins.json:ChunkMapMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:313) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:smoothchunk.mixins.json:ServerChunkCacheMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7041_(MinecraftServer.java:603) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_7041_(IntegratedServer.java:174) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:minetogether-common.mixins.json:connect.MixinIntegratedServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:717) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) [?:?] {}
```

@DanielABrennand Hi, if you still have the problem with the world would you be able to add one or two world files here? In your `saves` folder will be your `world` folder. In this `world` folder is a `region` folder. Inside that folder are two files, `r.0.11.mca` and `r.0.10.mca`. The latter contains the problematic save data where your character is standing in that picture.

If you can add both here (if you still have the world and that problem) that would be awesome. Thanks a lot in advance if you can!

**Comment by Saereth** [comment] 2023-02-05 23:23
this should be fixed in the new cata update

**Closed** 2023-02-07 21:17 UTC
Labels: 1: Mod Issue, state: Fixed in Dev :hammer_and_wrench:, FTB Inferno
