### ISSUE TITLE
[Bug]: Loading the map from FTB Chunks force closes the game

### ISSUE THREAD

**Issue by Techsnologic** [FTBTeam/FTB-Modpack-Issues#996] opened 2022-06-21 21:12 UTC
### Modpack

FTB One

### Modpack version

1.1.0

### Log Files

[crash-2022-06-21_22.03.26-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8952805/crash-2022-06-21_22.03.26-client.txt)
[crash-2022-06-21_21.59.55-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8952806/crash-2022-06-21_21.59.55-client.txt)
[crash-2022-06-21_21.55.16-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8952808/crash-2022-06-21_21.55.16-client.txt)

### Describe the bug

Pressing 'M' or opening the inventory and selecting the FTB Chunks icon brings up a 'Saving World' screen and then crashes Minecraft completely and force closing it.

### Steps to reproduce

1. Open and connect to world
2. Open inventory with E
3. Click on the FTB Chunks icon

OR

1. Open and connect to world
2. Press 'M' on keyboard

### Expected behaviour

Should open the FTB Chunks map to select and claim chunks

### Additional information

Happened in both 1.0.0 and also 1.1.0

**Comment by Saereth** [comment] 2022-06-21 23:58
So far this only seems reproducible on servers

**Comment by clayplumridge** [comment] 2022-07-10 23:11
Just another data point: I'm also only able to repro on a server.

**Comment by Saereth** [comment] 2022-07-10 23:21
@clayplumridge can you get us a copy of the server's latest.log when this is happening as well please

**Comment by clayplumridge** [comment] 2022-07-11 00:26
@Saereth Nothing interesting in the server log; here's one from a fresh start plus immediate repro of the bug: https://www.toptal.com/developers/hastebin/gahusiduge.yaml

May or may not be relevant, but here's some other things that fail on server but work locally:
The One Probe overlay, but it's weird. It displays for exactly the first block you look at on login, but is forever `waiting for server`.
Sort Inventory button, for both the player and storage

Should probably file more bugs for these yeah, even if the root cause might be the same?

**Comment by Saereth** [comment] 2022-07-11 00:28
this is a massively cut down log, nothing about mod loading, forge, java info etc all that is missing here and may be relevant

**Comment by clayplumridge** [comment] 2022-07-11 00:33
That's all that was in latest.log. Extracting either of the .gz files I've got in `~/mc/logs` is similarly useless info as well; nothing about mods, forge, or java. Gonna try `start.sh | dumb.log` and see what that gives. Sec.

**Comment by clayplumridge** [comment] 2022-07-11 00:42
@Saereth above produced similarly useless logs unfortunately. https://www.toptal.com/developers/hastebin/ezevadidaq.yaml
Got any ideas for how to get what you're looking for? As far as I can tell, server just isn't logging any of that info at all.

**Comment by Saereth** [comment] 2022-07-11 00:43
what are you using for hosting? this is highly unusual, any debug log?

**Comment by clayplumridge** [comment] 2022-07-11 00:50
Ubuntu64-21.04, hosting on a personal machine (can provide specs if you need them). Setup via the provided installer script from FTB.

Unless this thing is somehow running as vanilla, not sure what's going on. If it is running as vanilla, I'm unsure how that happened. That'd mean that I somehow didn't notice it failing, but would actually explain why it's working locally. I'd also feel very dumb. I'm gonna verify that...

**Comment by clayplumridge** [comment] 2022-07-11 00:59
Well `/give` doesn't know any of the AE2 items, so I'm gonna guess there's no server-side mods. I have no idea how we managed to play for any amount of time and not notice. Sorry for wasting your time @Saereth , I'll go figure this out on my own.

**Comment by Saereth** [comment] 2022-07-11 01:01
yeah definitely seems the case, no worries! Good luck

**Comment by Saereth** [comment] 2022-07-11 01:02
@Techsnologic you still having this issue? if so can you provide server logs? Otherwise we'll close this issue in 24 hours as we are unable to reproduce it.

**Comment by Raidobw2** [comment] 2022-07-11 02:58
Saereth did we try and repro with Forge client connecting to a vanilla server? I'm starting to think it might be that, since it was only ever reproduced "on a server"/ with a server.

**Comment by Techsnologic** [comment] 2022-07-12 06:20
@Saereth I can confirm that what @Raidobw2 has said is true.
The reason this affected me originally is because of running mods client side but the server side was vanilla.
I was originally running my server via MineOS and struggled to get it to use the forge jar file so it defaulted to the vanilla jar file. Eventually got this fixed by changing over to running the server on a virtual Windows machine instead.

**Comment by clayplumridge** [comment] 2022-07-19 02:38
@Saereth can probably close this out per the above

**Closed** 2022-07-19 02:43 UTC
Labels: prio: High :boom:, state: Confirmed, FTB One
