### ISSUE TITLE
[Bug]: Crash on start due to bad packet

### ISSUE THREAD

**Issue by peauters** [FTBTeam/FTB-Modpack-Issues#1448] opened 2022-10-16 20:16 UTC
### Modpack

FTB Inferno

### Modpack version

1.0.3

### Log Files

ava.lang.ClassCastException: class net.minecraft.client.multiplayer.ClientHandshakePacketListenerImpl cannot be cast to class net.minecraft.network.protocol.game.ClientGamePacketListener (net.minecraft.client.multiplayer.ClientHandshakePacketListenerImpl and net.minecraft.network.protocol.game.ClientGamePacketListener are in module minecraft@1.18.2 of loader 'TRANSFORMER' @6b9c42bd)
	at net.minecraft.network.protocol.game.ClientboundDisconnectPacket.m_5797_(ClientboundDisconnectPacket.java:7) ~[client-1.18.2-20220404.173914-srg.jar%23301!/:?] {re:computing_frames,re:classloading}
	at net.minecraft.network.Connection.m_129517_(Connection.java:168) ~[client-1.18.2-20220404.173914-srg.jar%23301!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.network.Connection.channelRead0(Connection.java:153) [client-1.18.2-20220404.173914-srg.jar%23301!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.network.Connection.channelRead0(Connection.java:53) [client-1.18.2-20220404.173914-srg.jar%23301!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-all-4.1.68.Final.jar%2316!/:4.1.68.Final] {re:mixin,re:computing_frames}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar%2316!/:4.1.68.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar%2316!/:4.1.68.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar%2316!/:4.1.68.Final] {}
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.68.Final.jar%2316!/:4.1.68.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar%2316!/:4.1.68.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar%2316!/:4.1.68.Final] {}
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.68.Final.jar%2316!/:4.1.68.Final] {}
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299) [netty-all-4.1.68.Final.jar%2316!/:4.1.68.Final] {}
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445) [netty-all-4.1.68.Final.jar%2316!/:4.1.68.Final] {}
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50) [netty-all-4.1.68.Final.jar%2316!/:4.1.68.Final] {}
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403) [netty-all-4.1.68.Final.jar%2316!/:4.1.68.Final] {}
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [netty-all-4.1.68.Final.jar%2316!/:4.1.68.Final] {}
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar%2316!/:4.1.68.Final] {}
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar%2316!/:4.1.68.Final] {}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

### Describe the bug

Fail to join world due to bad packet error

### Steps to reproduce

Create new world

### Expected behaviour

New world is created

**Comment by Saereth** [comment] 2022-10-16 20:41
can you give me a list of all mods currently install on the server please

**Comment by peauters** [comment] 2022-10-16 22:59
This was creating a new local game and not connecting to a server, but it was a fresh 1.0.3 install using PolyMC

**Comment by Saereth** [comment] 2022-10-16 23:10
Try reinstalling something isnt right here, will need a full crash log if the reinstall doesnt fix it

**Comment by peauters** [comment] 2022-10-17 20:56
Same thing again on a fresh install. Here is a link to the full log: https://mclo.gs/6RXuUCT

Tried loading a save from a 1.0.2 instance and got the same issue.

(thanks for your help BTW, let me know if there is anything else you need)

**Comment by Saereth** [comment] 2022-10-18 09:27
I can't recreate this. Can you create this with a fresh install on the FTB App, trying to determine if this is an environment issue or a launcher issue

**Comment by Raidobw2** [comment] 2022-10-20 06:28
The JVM has crashed with a SIGSEGV signal and it's using Homebrew Java in PolyMC. Could indicate that native libraries are at fault, if you are running it natively (assuming your processor is a M1). What I'd recommend is using Rosetta and starting the FTB App with it, at least as a comparison. The FTB App uses Temurin JREs by default instead of Homebrew, so that's different, and Rosetta will also translate x86 to ARM64. It probably won't be as good as native performance, but you won't know until you try.
PolyMC had some controversy in the past days so I'd recommend switching to the FTB App for a while until things settle out.

If you still get crashes with the FTB App, post your logs as well. I haven't dug further, but next steps would be to check that your computer uses ipv4 before ipv6 or doing a memtest if this happens regularly.

**Comment by peauters** [comment] 2022-10-22 17:23
Thanks for the advice re PolyMC, I've moved away and was using FTB App for the testing Saereth suggested.

I'm not on M1 and the crash is happening with Recommended as well as the Homebrew installed JVMs.

The segfault occurs when I shutdown the app, not when I get the ClassCastException. I think this is probably something to do with the bad state it gets into as the server components will be running when they are expected to as the client fails to connect and can't shutdown the server correctly.

**Comment by Raidobw2** [comment] 2022-10-24 07:19
I see, in that case did using the FTB App "fix" the issue? Were you able to close the FTB App without the modpack crashing for instance?

**Comment by Blockguy24** [comment] 2022-10-25 02:09
I am getting the exact same issue running FTB Inferno 1.0.3 in the FTB App.

Logs: https://pste.ch/omusawajad

The reproduction steps are the same as the original issue

**Comment by Raidobw2** [comment] 2022-10-25 03:14
I'm unable to reproduce it, like Saereth. I'm using a fresh install of FTB Inferno 1.0.3 on the FTB App.

I have two questions for those having this issue:
1. Do you have an antivirus installed, and if yes, does turning it off change anything?
2. Is ipv6 unchecked in your Ethernet card's properties, and ipv4 is checked? Here's an example. You can get there by pressing Windows + R and putting `ncpa.cpl` in the box, then press Ok. On the Network Card, right click it to access Properties and this is where you should see the boxes.
![image](https://user-images.githubusercontent.com/17010632/197673476-183a34d8-caea-4988-aa88-dfa0466dc36a.png)

**Comment by Blockguy24** [comment] 2022-10-25 03:19
From what I can tell, neither of us are using Windows, but is disabling IPv6 system wide really a solution to the problem?
As for your first point, I have no antivirus running.

**Comment by Raidobw2** [comment] 2022-10-25 05:46
Disabling ipv6 was more like a test than a solution, it was shown in the log at some point. If you prefer using another method to test for that, you should be able to add `-Djava.net.preferIPv4Stack=true` to the FTB App's additional java arguments or to your system's `_JAVA_OPTIONS` variable for Java apps.

If that works I'll pass the word to the app devs. Let me know and thanks

**Comment by Blockguy24** [comment] 2022-10-25 10:20
I tried adding that argument and it still doesn't work.
![image](https://user-images.githubusercontent.com/21016331/197748365-91c0ff17-da65-479d-bc69-baa334f22802.png)
Can you confirm that this was indeed the correct place to put this argument?

**Comment by Raidobw2** [comment] 2022-10-28 00:49
Sorry for the delay, got very busy in the past days. Yes that is where I was referring to for additional java arguments. I've looked thoroughly at the log again and this line got me thinking there might be an error happening unrelated to everything I thought so far, but that it might not be logged.

`Received class net.minecraft.network.protocol.game.ClientboundDisconnectPacket that couldn't be processed` makes me think that the client had an error before receiving a disconnection packet.

There is nothing else written about this error in the logs, nor its cause.

I could imagine a single mod might be causing the issue, but I'm not sure, since it's hard to guess...

- Does this happen on other versions of the pack? What about its initial release?
- If the debug.log isn't too big, can you add it here? You can try zipping it if it's very big. Hoping there is more information before the client receives a disconnection packet

Thanks

**Comment by Blockguy24** [comment] 2022-10-28 11:39
It seems to work fine in 1.0.2, but not in 1.0.3.
It is possible to play the game in 1.0.3 if you attempt to create the world, experience the error, restart the game, and load the new world.
If you copy a save from 1.0.2, you will still have to load the world, encounter the error, restart the game, and then finally load the world.

The log archives contain the entire content of the logs folder (debug.log, latest.log, etc.)

Here's what I did:

- Tried to create a new world in version 1.0.2. This seemed to work fine.
  - Logs: [1_0_2-logs-1.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9887841/1_0_2-logs-1.zip)
  - Save file: [1_0_2-savefile-1.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9887851/1_0_2-savefile-1.zip)
- Restarted the game (still in 1.0.2) and loaded the previously created world. This worked fine.
- Deleted the instance from the FTP App and installed 1.0.3
- Tried to create a new world in version 1.0.3. This did not work.
  - Logs: [1_0_3-logs-1.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9887884/1_0_3-logs-1.zip)
- Upon closing the game, it said that the game had crashed and there was another log file (hs_err_pid56254.log) in the instance directory. This file can be found in 1_0_3-logs-1.zip. Additionally, a folder was created in the saves directory.
  - Save file: [1_0_3-savefile-1.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9887906/1_0_3-savefile-1.zip)
- When starting the game again, there was a new world in the list. This new world can be successfully opened without getting "disconnected".
  - Logs: [1_0_3-logs-2.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9887936/1_0_3-logs-2.zip)
- I closed the game again and saw that the save was modified
  - Save file: [1_0_3-savefile-2.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9887929/1_0_3-savefile-2.zip)
- I copy the working save from 1.0.2 into the 1.0.3 instance
- Attempting to load the 1.0.2 save results in the same error as creating a new world. Checking the world list immediately after this shows that the 1.0.2 world has disappeared for some reason.
- I close the game and experience the same crash message as before. I copy the logs and the 1.0.2 save, which has now been modified
  - Logs: [1_0_3-logs-3.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9887967/1_0_3-logs-3.zip)
  - Save file: [1_0_2-savefile-2.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9887974/1_0_2-savefile-2.zip)
- After re-opening the game, the 1.0.2 world is back in the world list. This world can be opened successfully.
  - Logs: [1_0_3-logs-4.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9887989/1_0_3-logs-4.zip)
  - Save file: [1_0_2-savefile-3.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9887994/1_0_2-savefile-3.zip)

**Comment by Raidobw2** [comment] 2022-11-02 07:32
Sorry again, I'm struggling to keep up with the modpack tracker this week with the release of StoneBlock 3 in the past day.
I have analyzed some of the logs you added here, and found some results.
I will be comparing `1_0_2-logs-1` (left) and `1_0_3-logs-1` (right).

One the working game (left) it only fails to start an audio file, then keeps going. On the right, it doesn't fail to start that file and instead has a big error.
![image](https://user-images.githubusercontent.com/17010632/199425145-ba57cf5c-6a3b-460c-b1bb-d334ee706bf1.png)

If we scroll down a bit and adjust the logs, on the left it finds a Pupfish chunk and connects to the server, while on the right, it force kills the audio and then it throws an error about the file lock for what I assume is the one for `level.dat`. The game immediately closes after that.
![image](https://user-images.githubusercontent.com/17010632/199425811-6f1185cf-1be7-4cf5-b230-539b599ab91b.png)

Can you try removing the FancyMenu mod and addons from 1.0.3 (or any current version that doesn't work) and then load the pack again? Let me know if world creation goes through and thanks for your patience despite the delays.

You could also remove Alex Mobs to test without it.

They look like (delete them):
`fancymenu_forge_2.12.6_MC_1.18.2.jar`
`fm_audio_extension_forge_1.1.1_MC_1.18-1.18.2.jar`

`alexsmobs-1.18.6.jar`
`Alex's Mobs Music Mod.jar`

**Comment by Blockguy24** [comment] 2022-11-02 13:49
It does not appear that removing those mods resolves the issue. Note that I also had to remove `alexsdelight-1.18.2-1.3.3.jar` as it depended on `alexsmobs-1.18.6.jar`

**Comment by Saereth** [comment] 2022-11-02 21:23
can you try on 1.2 once it updates and let me know if that solves it for you

**Comment by Blockguy24** [comment] 2022-11-04 02:52
The issue appears to be fixed on FTB Inferno 1.2.1

**Comment by Raidobw2** [comment] 2022-11-04 10:09
Awesome, I will be closing this issue in that case! Cheers

**Closed by Raidobw2** 2022-11-04 10:09 UTC
Labels: state: Awaiting Reply :speaking_head:, 3: Support Request, FTB Inferno

**Comment by peauters** [comment] 2022-11-05 18:28
Thanks for your help. 

Congrats on a great pack =o)
