### ISSUE TITLE
[Bug]: Game crashes random due to index -1 out of bounds

### ISSUE THREAD

**Issue by lslinnet** [FTBTeam/FTB-Modpack-Issues#1399] opened 2022-10-07 07:27 UTC
### Modpack

FTB Inferno

### Modpack version

1.0.2

### Log Files

[crash-2022-10-07_09.22.42-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9731577/crash-2022-10-07_09.22.42-client.txt)

### Describe the bug

At random roughly 30-40mins after starting to play the game it crashes, the world I have is from 1.0.0 and have been updated across multiple versions. Let me know if you want the save (including my inventory) for testing/reproduction purposes.
I am not certain what mod specifically throws this error otherwise I would have reported it there.

### Steps to reproduce

1. Load world
2. Play for a time
3. Random crash

### Expected behaviour

I expect the game to not crash

**Comment by MichaelHillcox** [comment] 2022-10-07 07:43
Duplicate of #1357

**Closed** 2022-10-07 07:44 UTC
