### ISSUE TITLE
Vanilla+ pack will not run

### ISSUE THREAD

**Issue by logicbug** [FTBTeam/FTB-Modpack-Issues#3635] opened 2023-07-05 21:32 UTC
### Modpack

FTB Vanilla+

### Modpack version

1.1.0

### Describe the bug

Modpack does not start, seems like a problem with dependencies of codechicken?

### Steps to reproduce

Install vanilla+ pack
Go to instance
Start
- fails

### Expected behaviour

Normal start

### Additional information

I have no idea what to expect as in what this pack offers, never tried it before.

**Comment by Gaz492** [comment] 2024-06-05 14:58
This looks to be the same issue as #756 we may release a fix for this providing nothing else breaks by updating the mod mentioned in that issue.

**Comment by Gaz492** [comment] 2024-06-20 21:39
Duplicate of #3635

See https://github.com/FTBTeam/FTB-Modpack-Issues/issues/756#issuecomment-1120337810 for possible fix

**Closed by Gaz492** 2024-06-20 21:39 UTC
Labels: FTB Vanilla+, state: Confirmed
