### ISSUE TITLE
[FTB Lite 3] Outdated CodeChickenCore prevents modpack from launching

### ISSUE THREAD

**Issue by mnmt** [FTBTeam/FTB-Modpack-Issues#2395] opened 2022-12-23 22:33 UTC
### Modpack

FTB Lite 3

### Modpack version

1.5.0

### Describe the bug

With FTB Lite 3, Minecraft cannot launch successfully due to a bug in CodeChickenCore-1.7.10-1.0.7.47-universal.jar ([see here](https://www.curseforge.com/minecraft/mc-mods/codechickencore/files)). 

There is a bug in the automatic downloading of CodeChickenLib that this mod is meant to perform.

An updated version of this mod, CodeChickenCore-1.7.10-1.0.7.48-universal.jar, fixes this issue. This can be seen in the changelog of the mod [here](https://www.curseforge.com/minecraft/mc-mods/codechickencore/files/3293859).

Replacing CodeChickenCore-1.7.10-1.0.7.47-universal.jar with CodeChickenCore-1.7.10-1.0.7.48-universal.jar fixes my problem with launching the modpack.

### Steps to reproduce

1. Install the FTB Lite 3 modpack
2. Click Play
3. It fails to launch

### Expected behaviour

The modpack fails to launch minecraft

**Comment by Gaz492** [comment] 2024-06-05 14:07
Duplicate of #756

**Closed by Gaz492** 2024-06-05 14:07 UTC
Labels: FTB Lite 3
