### ISSUE TITLE
[Bug]: Connecting to Server throws ArrayOutOfBounds

### ISSUE THREAD

**Issue by TheNinsa** [FTBTeam/FTB-Modpack-Issues#143] opened 2021-10-16 13:40 UTC
### Modpack

FTB OceanBlock

### Modpack version

1.2.0

### Log Files

https://paste.feed-the-beast.com/view/97fd60e5

### Describe the bug

I just installed a new Egg Server Instance of FTB OceanBlock on my Server.
After installing the Modpack on my clientside aswell, and connecting to the Server, it crashes.

The serverconse itself only shows me connecting, and a "Lost connection, Reason: Disconnected" with my UUID

### Steps to reproduce

Go to Server Overview under the MultiplayerTab
Click on my added Server

Crash

### Expected behaviour

Well, connecting to the Server

### Additional information

I have installed the server using the provided Server files, the server is running Linux, and a Pterodactyl Interface for control. The only Information given for the Setup is "level-type: default". That has been edited into the Server.properties.

**Comment by Xplodin** [comment] 2021-10-16 18:29
Same crash here. Any workarounds found?

**Comment by Raidobw2** [comment] 2021-10-17 01:15
That was an issue with MineTogether which has been fixed in OceanBlock 1.3.0.
2 options are available right now:
-Update to 1.3.0 or Reinstall 1.3.0. Remember to backup worlds before reinstalling, if you have any.
-Delete the MineTogether mod on crashing clients, until you decide to update to 1.3.0.
&nbsp;&nbsp; FTB App > OceanBlock > Settings > Open Folder > `/mods`

If reinstalling, check this box to see all versions and select 1.3.0.
![image](https://user-images.githubusercontent.com/17010632/137606326-ab843421-38f7-443d-9133-1f6d262aa382.png)

Duplicate of #67, so I will be closing this as it already has been resolved.

**Closed by Raidobw2** 2021-10-17 01:15 UTC
Labels: FTB OceanBlock, Bug, State: Duplicate :books:

**Comment by Xplodin** [comment] 2021-10-17 01:32
this still occurs on 1.3.0
