### ISSUE TITLE
[Bug]: AE2 - cannot access items stored in a subnetwork

### ISSUE THREAD

**Issue by IwaoM** [FTBTeam/FTB-Modpack-Issues#879] opened 2022-05-30 20:55 UTC
### Modpack

FTB Interactions

### Modpack version

2.12.1

### Describe the bug

This bug is related to Applied Energistics 2 - possibly due to the used mod being changed to the Trouser Edition fork.

Storage subnetworking using storage bus + ME interface doesn't seem to work anymore: I am still able to send items to a subnetwork storage from an ME terminal in the main network, but I am unable to see items stored in subnetworks from that same terminal.

This can be a huge issue, as most big AE2 storage systems (such as the SSD - Super Soaryn Drive) use this subnetworking mechanic to avoid using too much channels.

### Steps to reproduce

1. Construct a simple network & subnetwork as illustrated in the first screenshot (see Imgur link). In the image, lime is the main network and red is the subnetwork. The junction between the 2 is as follows : [red cable]-[interface]-[storage bus]-[lime cable].
2. Put some items in both chests - here, red and lime dyes are used.
3. From the red terminal, only the red dyes should be visible.
4. From the lime terminal, both red and lime dyes should be visible, but here, only lime dyes are visible, which means the subnetwork cannot be seen from the main network.

### Expected behaviour

In the Steps to reproduce scenario, both red and lime dyes should be visible from the lime ME terminal.

### Screenshots

https://imgur.com/a/S5GJ8yN (3 pictures)

**Comment by TheonlyTazz** [comment] 2022-05-31 09:53
Thank you for your Issue,
Yes this is confirmed to be an issue on AE2 Unofficial Extended Life Edition, but it seems to be fixed i version `v0.52.8`
which can be downloaded on Curseforge in the meantime.
![AE2 Unofficial Extended Life Edition Curseforge Link](https://www.curseforge.com/minecraft/mc-mods/ae2-extended-life)

This will be fixed in a future update
![grafik](https://user-images.githubusercontent.com/3908847/171146611-6304cc64-a8bd-4600-83db-aabf4b4c656c.png)
![grafik](https://user-images.githubusercontent.com/3908847/171146667-8edc87e1-3bb4-4c1c-8abe-59ec97033e38.png)

**Closed** 2022-06-15 15:24 UTC
Labels: FTB Interactions, state: Fixed :heavy_check_mark:, state: Confirmed, state: Mod Update Available
