### ISSUE TITLE
[Bug]: Crash in oceanblocks when searching for "Hardened" (Crashes just after typing R)

### ISSUE THREAD

**Issue by jslopez29** [FTBTeam/FTB-Modpack-Issues#301] opened 2021-11-11 17:23 UTC
### Modpack

FTB Oceanblock

### Modpack version

1.7.0

### Log Files

https://pste.ch/cecidehagu.makefile

### Describe the bug

Crashing when searching for things in JEI. I wanted to search for "hardened glass" and it crashed around when I typed the "R".
Also happened when trying to search "Quartz dust" in JEI while using the pattern grid from Refined Storage.

### Steps to reproduce

1. Open RS crafting grid
2. Search for hardened glass

Alternatively
1. Open RS pattern grid
2. search for "quartz dust"

### Expected behaviour

Not to crash

**Comment by Sunekaer** [comment] 2021-11-11 19:09
Duplicate of #40

**Closed by Sunekaer** 2021-11-11 19:09 UTC
Labels: state: Duplicate :books:
