### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by Kibyts** [FTBTeam/FTB-Modpack-Issues#630] opened 2022-02-18 15:07 UTC
### Modpack

FTB Ultimate: Anniversary

### Modpack version

1.3

### Describe the bug

https://forum.feed-the-beast.com/threads/ftb-ultimate-anniversary-edition-1-3-client-crash-after-patch.305299/

### Steps to reproduce

As the same thing just happened on a brand new server after several hours of playtime and others have the same problem I decided that this could be a bug.

### Expected behaviour

I expect the client not to crash

**Comment by Raidobw2** [comment] 2022-02-19 08:27
Hello, currently with the FTB App the mod files get "locked" after a play session (like if they were still opened in a program). If you update from 1.2.0 to 1.3.0 after playing, there is a chance, in the current App, that the old files were not deleted.
There was a FTB App patch a few days earlier to solve that issue and many others, although it has been reverted due to changes to be required on our side for authentication.

For now, update modpacks when you initially open Overwolf and the FTB App on a given day.
For the crash log you linked there are two files present for Modular Powersuits:
The actual mod: `ModularPowersuits-1.16.5-2.1.19.jar`
The library mod: `Numina-1.16.5-2.1.18.jar`
![image](https://user-images.githubusercontent.com/17010632/154793010-8ccaa4c8-5df2-4bfa-8653-571d21f633a2.png)

If we take a look at the changelog from 1.3.0, those two files should be having those versions instead:
![image](https://user-images.githubusercontent.com/17010632/154792870-ee87945e-fd28-4e1a-bc15-4130452204ae.png)

In short, currently there is a duplicate of ModularPowersuits in your `mods` folder, possibly for Numina as well.
The old duplicate ModularPowersuits can for example be loaded with the new library Numina. This will result in a crash.

- The solution to this is to remove the duplicates manually in the files which are accessed in the FTB App, inside the modpack's settings page.
- You can also backup all your data for that modpack (`local`, `saves` and `options.txt` most importantly) and reinstall the modpack.
- It's also possible to downgrade and upgrade the modpack as well as this is just another way to reinstall a modpack.

You get the point -- simply for now make sure all file manipulations are done just as you open Overwolf and the FTB App, not after you've played a modpack.
Clear the duplicates in the `mods` folder and let me know if that did it. You might want to link back this issue on the forums as well for the other person that commented on your post.
Cheers.

**Comment by Kibyts** [comment] 2022-02-19 11:57
Oh my... Ok, that was easy. I didn't expect the client to load mod versions the server dosn't request. Or that the server would refuse the connection. But well. This fixed it. Thank you! I will post it in the forums.

**Closed** 2022-02-19 16:32 UTC
Labels: 3: Support Request, FTB Ultimate: Anniversary Edition
