### ISSUE TITLE
[Bug]: Refined Storage Craftingrid Tooltip Bug, when missing items.

### ISSUE THREAD

**Issue by Timu420** [FTBTeam/FTB-Modpack-Issues#2138] opened 2022-11-25 13:59 UTC
### Modpack

Stoneblock 3

### Modpack version

1.4.1

### Describe the bug

Once opeing the Crafting grid via the Block/wireless version, with a Recipie from Roughly enought items Favorited, a tooltip is on the cursor stuck named move Items / Missing Items.

hover over items makes the Tooltip stack with the tooltip of the item.

### Steps to reproduce

1. open Inventory
2. Favorite the Recipie (which you dont have the item/items[Silverfish heart] to craft it) in REI by pressing "A" on the Recipie or moving it to the left of the Screen.
3. Close Inventory
4. open a Crafting grid or open a wireless Crafting Grid
5. Suddenly a Tooltip apears everywhere on your Cursor

### Expected behaviour

Tooltip apearing only when hovering over the missing item of the Favorited Recipie

### Screenshots

![image](https://user-images.githubusercontent.com/91256797/204000239-6969c785-36d6-4bfb-a6cf-5b80f84075ed.png)
notice tooltip on my mouse
it should only apear when Hovering over the Favorited Recipie due to me not having a Silverfish heart

**Comment by Sunekaer** [comment] 2022-11-25 17:36
Duplicate of #2134

**Closed by Sunekaer** 2022-11-25 17:36 UTC
Labels: FTB StoneBlock 3
