### ISSUE TITLE
[Bug]: SB3 Duplication glitch

### ISSUE THREAD

**Issue by Toasty-Engineer** [FTBTeam/FTB-Modpack-Issues#2025] opened 2022-11-18 02:35 UTC
### Modpack

Stoneblock 3

### Modpack version

1.3.0

### Describe the bug

When placing a Tinkers' Construct Crafting Station next to an Ars Noveau Scribe's Table, the Station will attempt to show the storage of the Scribe's Table, even though it has none. This appears as a single unlabelled inventory slot. When placing 2 or more items into this slot, removing them causes you to get one or more extra items (always one less than you insert, to a max of 63)

### Steps to reproduce

1. Place a Crafing Station next to a Scribe's Table.
2. Insert 2 or more of a stackable item into the singular item slot to the left of the interface.
3. Remove the item, get duplicate.
4. Repeat infinitely.

### Expected behaviour

Not a duplication glitch, no random buggy storage slot

### Screenshots

https://www.youtube.com/watch?v=WWtBuRCL40c video explaining the bug

### Additional information

Only works on stackable items, as you need at least two.

**Comment by CarelessSpore** [comment] 2022-11-18 04:40
can also confirm that this works with the RFTools Crafters as well.

**Comment by TheonlyTazz** [comment] 2022-11-19 11:02
duplicate of:
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1938

thanks for the video explaining it tho

**Closed by TheonlyTazz** 2022-11-19 11:02 UTC
Labels: FTB StoneBlock 3
