### ISSUE TITLE
client-specific classes trying to load into server-only environments (RecipesEventJS (from KubeJS))

### ISSUE THREAD

**Issue by lazycooken** [FTBTeam/FTB-Modpack-Issues#5753] opened 2024-09-12 00:21 UTC
### Modpack

FTB Unstable 1.21

### Modpack version

1.20

### Launcher

Server

### Has the pack been modified

No

### Log Files

[latest.log](https://github.com/user-attachments/files/16971702/latest.log)

### Describe the bug

attempts to load Error loading class: dev.latvian.mods.kubejs.recipe.RecipesEventJS on server side 

### Steps to reproduce

Install the mod on a dedicated server.
Start the server.
Observe the error during the startup process.

### Expected behaviour

not attempt to load client side on server side

**Comment by Gaz492** [comment] 2024-09-12 12:40
The issue which was causing the unstable server to not start should be fixed now which was caused by entity model renderer and health indicators

The additional messages saying something tried to load a client only class can safely be ignored and is a mod specific issue, but shouldn't cause any further issues other than displaying a warning message while the server starts up.

**Closed by Gaz492** 2024-09-12 12:40 UTC
Labels: FTB Unstable 1.21
