### ISSUE TITLE
falling forever 

### ISSUE THREAD

**Issue by Tophercodes** [FTBTeam/FTB-Modpack-Issues#5022] opened 2024-03-21 00:33 UTC
### Modpack

FTB Skies

### Modpack version

1.19.2

### Describe the bug

fell off my island I am now falling into the abyss. instead of "coming back around" like normal I am currently at -24000 y 

### Steps to reproduce

I close out of the program. I come back in, and I am still falling

### Expected behaviour

to not fall and keep falling forever.

**Comment by kaitorque** [comment] 2024-03-23 11:51
Also happen to me.
type "/ftbdim home" to tp back to spawn

**Comment by Gaz492** [comment] 2024-06-21 08:19
Duplicate of #4464

**Closed by Gaz492** 2024-06-21 08:19 UTC
Labels: state: Awaiting Reply, FTB Skies
