### ISSUE TITLE
Duplication using hexerei drying rack

### ISSUE THREAD

**Issue by charlesgael** [FTBTeam/FTB-Modpack-Issues#3190] opened 2023-04-20 22:36 UTC
### Modpack

FTB Skies

### Modpack version

1.0.4

### Describe the bug

We are able to duplicate items using hexerei drying rack

### Steps to reproduce

1. Place drying rack on any surface
2. Place items you want duplicated in rack
3. Break rack
4. Items are duplicated
5. Rince and repeat ?

### Expected behaviour

We get back same number of items as put in drying rack

**Comment by koalalord9999** [comment] 2023-04-22 02:18
can confirm

**Comment by koalalord9999** [comment] 2023-04-22 02:25
works in 1.0.6 as well

**Comment by CrimsonXMC** [comment] 2023-04-22 10:14
Duplicate of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2985

**Comment by Saereth** [comment] 2023-04-26 08:07
duplicate issue

**Closed by Saereth** 2023-04-26 08:07 UTC
Labels: state: Duplicate :books:, FTB Skies
