### ISSUE TITLE
[Bug]: Whenever opening the auto-smithing table, the game crashes

### ISSUE THREAD

**Issue by olsen-adam** [FTBTeam/FTB-Modpack-Issues#1834] opened 2022-11-10 20:42 UTC
### Modpack

FTB Stoneblock 3

### Modpack version

1.2.0

### Describe the bug

I have placed down the "Auto-Smithing Table", connected it to power, and inserted 64 netherite ingots. Now whenever I go to open it again, the game crashes.

### Steps to reproduce

1) Place down the Auto-Smithing Table
2) Use it once and keep netherite in the machine.
3) Close the menu.
4) Now whenever you try to open it again, the game will crash.

### Expected behaviour

The game not to crash after opening it once.

**Comment by Sunekaer** [comment] 2022-11-10 20:53
Duplicate of  #1799

**Closed by Sunekaer** 2022-11-10 20:53 UTC
