### ISSUE TITLE
[Bug]: Spawning during boss fights

### ISSUE THREAD

**Issue by Neladden** [FTBTeam/FTB-Modpack-Issues#2183] opened 2022-11-27 23:45 UTC
### Modpack

FTB Inferno

### Modpack version

1.3.0

### Describe the bug

When the "portals" spawn mobs (for example, the bellringer or the typical hourly attack waves), the majority of the mobs (including the boss, if there is one) spawn several hundred blocks below me (since it's obviously in the nether, typically in the lower regions of the nether area) even though the "portal" location is on top of the bedrock. 

### Steps to reproduce

Any portal spawning event (including bellringer).

### Expected behaviour

Some mobs will spawn near the portal location, others deep down in the nether area.

**Comment by orbidlo** [comment] 2022-11-28 09:23
this is duplicate of #1858 and check out the comments for fix until modpack gets updated. Just be warned that updating the portal mob also makes you not have any 30sec warnign between flavour text and invasion spawning.

**Comment by Neladden** [comment] 2022-11-28 16:45
Thank you

**Closed** 2023-01-18 22:09 UTC
Labels: state: Duplicate :books:, FTB Inferno
