### ISSUE TITLE
[Bug]: oceanblock no wireless grid in jei

### ISSUE THREAD

**Issue by dhdzeke** [FTBTeam/FTB-Modpack-Issues#294] opened 2021-11-10 11:10 UTC
### Modpack

ftb ocean block

### Modpack version

1.6.0

### Describe the bug

refined storage crafting grid is not visible in jei but is required to craft in the digital storage quest only way to get the crafting recipe is to click the item in the quest

### Steps to reproduce

1. go to jei search bar 
2. type in wireless
3. view that only wireless crafting grid and creative counterpart show for refined storage in jei
4. done
5.profit ?

### Expected behaviour

show wireless grid in jei

### Screenshots

https://i.imgur.com/6lbQyEL.png

**Comment by Raidobw2** [comment] 2021-11-10 12:46
Hmm, odd, thanks for the report.
To dev: Haven't checked.

**Comment by andr9528** [comment] 2021-11-10 17:14
Playing on version 1.7.0:
![image](https://user-images.githubusercontent.com/21788044/141160445-549f496d-d0ab-4152-ba37-ecb79ae24eb1.png)

If it truely is missing in 1.6.0, it appears to have been fixed in 1.7.0.

**Comment by quietust** [comment] 2021-11-11 02:02
Duplicate of #276?

**Comment by Sunekaer** [comment] 2021-11-11 08:12
This was fixed in 1.7.0 update your client.

**Closed by Sunekaer** 2021-11-11 08:12 UTC
Labels: FTB OceanBlock, cat: Bug, des: Mod Issue
