### ISSUE TITLE
Dupe bug

### ISSUE THREAD

**Issue by PimpmyT00l** [FTBTeam/FTB-Modpack-Issues#3129] opened 2023-04-15 19:47 UTC
### Modpack

FTB Skies

### Modpack version

1.0.7

### Describe the bug

Dupe bug

Using drying rack from hexerei mod

### Steps to reproduce

craft or obtain a drying rack from hexerei

place rack and add items by right clicking

break rack

duplicates all items exactly including enchants etc. (any item in game)

### Expected behaviour

rack to drop as item with contents

**Comment by CrimsonXMC** [comment] 2023-04-15 19:59
Duplicate of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2985

**Comment by 10BamberJ** [comment] 2023-04-16 09:10
you cant even craft them so i dont know where you get the idea of you can dupe with them.

**Comment by CrimsonXMC** [comment] 2023-04-16 09:42
> you cant even craft them so i dont know where you get the idea of you can dupe with them.

you can find them in chests though

**Comment by PimpmyT00l** [comment] 2023-04-16 11:30
they are craftable and very cheap, witchhazel saplings can be sifted from leaves at the start, 3 slabs 2 buttons and a stick,

**Closed** 2023-04-26 20:51 UTC
Labels: state: Duplicate :books:, FTB Skies
