### ISSUE TITLE
Inferno Server Download Error

### ISSUE THREAD

**Issue by ApatheticSympathy** [FTBTeam/FTB-Modpack-Issues#5691] opened 2024-08-28 18:06 UTC
### Modpack

FTB Inferno

### Modpack version

1.10.1

### Has the pack been modified

No

### Log Files

https://pste.ch/cuqomadisu.sql

### Describe the bug

Checksum on metadata file is failing during server file install

### Steps to reproduce

1. Download installer for 1.10.1 Inferno server files
2. Install
3. Error

### Expected behaviour

No error during install

### Additional information

I wasn't sure what log file to add exactly, so I exported text from the console during install that shows the error and expected checksum. I seemingly fixed the issue by moving the /config/metadata.json from my client install to the server folder after choosing to continue despite the error.

**Comment by Gaz492** [comment] 2024-08-29 08:25
This was caused by multiple metadata.json being downloaded, this should be fixed now and not cause any further issues.

**Closed by Gaz492** 2024-08-29 08:25 UTC
Labels: FTB Inferno, Bug
