### ISSUE TITLE
[Bug]: JEI Recipes don't show after updating (Server)

### ISSUE THREAD

**Issue by Brapalx** [FTBTeam/FTB-Modpack-Issues#866] opened 2022-05-28 20:22 UTC
### Modpack

FTB Direwolf20 1.18.2

### Modpack version

1.3.0

### Describe the bug

JEI no longer shows recipes, also patchouli books seem broken (missing recipe errors in botania and hexcrafting books)

### Steps to reproduce

1. Press E 
2. Try to press R or left click on an object in JEI
3. No result

### Expected behaviour

The crafting recipe for an object to show up

**Comment by JakeMoe** [comment] 2022-05-28 21:09
Came here to report this as well.  Single player seems fine, but when logged on to my server and tried to create a chest, nothing showed up in the output for my crafting station.  Looked up the recipe in JEI to see if any changes had been made, but as OP said, no recipe displayed.  After playing around, I found that if I clicked the output slot with the items in the table, I got the item anyway.  Also found that a vanilla crafting table showed the output, but there is nothing in my recipe list (the vanilla list that shows up when I click the book icon in the crafting table or inventory) with "Showing all" selected.

**Comment by Jerah79** [comment] 2022-05-28 22:03
Came to report same. Did notice one other thing that my op character could access crafting but no other characters on my LAN world could access crafting via JEI or normal crafting window via the crafting box. Client side still works even after starting LAN but all other charaters loaded in can not access crafting. Single player crafting still works.

**Comment by shindouj** [comment] 2022-05-28 23:12
Possibly related: Vanilla Stonecutters and recipe guides no longer work as well. It looks like there is something seriously messed up with the new recipe definitions.

**Comment by Nox4041** [comment] 2022-05-28 23:37
Having the same issue. JEI works in single player but no connected to a server.

**Comment by JakeMoe** [comment] 2022-05-29 00:20
Attaching my server's startup log in case it helps.

[2022-05-28-1.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8792381/2022-05-28-1.log.gz)

**Comment by Celebrateee** [comment] 2022-05-29 02:03
I'm also having the same issue with my server.

**Comment by calmcacil** [comment] 2022-05-29 02:05
Oreberries Replanted 1.0.6 -> 1.0.7 fixes this issue for me, not sure why the 1.3.0 update didnt update to the latest version of Oreberries but seems this issue is a caused by that.

**Comment by JakeMoe** [comment] 2022-05-29 02:28
> Oreberries Replanted 1.0.6 -> 1.0.7 fixes this issue for me, not sure why the 1.3.0 update didnt update to the latest version of Oreberries but seems this issue is a caused by that.

This seems to have fixed it for me as well.

**Comment by GameMista** [comment] 2022-05-29 02:33
Looking back at the 1.0.2 version, it actually had 1.0.7 so that mod in particular regressed with the update. Putting it back to 1.0.7 fixed it for me as well.

**Comment by Raidobw2** [comment] 2022-05-29 21:30
Should be fixed in 1.3.1 which was released a few hours ago

**Closed by Raidobw2** 2022-05-29 21:30 UTC
Labels: 1: Mod Issue, state: Fixed :heavy_check_mark:, prio: Critical :skull:, FTB Presents Direwolf20 1.18
