### ISSUE TITLE
Breaking a Mekanism tank voids fluids

### ISSUE THREAD

**Issue by Joprebond** [FTBTeam/FTB-Modpack-Issues#5463] opened 2024-07-09 22:17 UTC
### Modpack

FTB NeoTech

### Modpack version

1.3.0

### Has the pack been modified

Yes

### Describe the bug

CCI was added to the pack

When breaking a mekanism tank with MI fluids in it and you have an empty mekanism tank. The game will void the fluid and stack the tank that had fluids with the empty one. Also to mention i'm breaking it with a Silk touch, Eff 5, Unbreaking 3 mending Utherium pick

### Steps to reproduce

1 Craft 2 mekanism tanks and place only one down in the world
2. Put MI Oxygen in one tank (for example using the me gauge dropper)
3. Break the tank with MI oxygen in it

### Expected behaviour

The Tank that had oxygen in it should retain its inventory.

**Comment by Gaz492** [comment] 2024-07-10 07:45
I've not been able to reproduce this issue. However, it looks like this may be related to #5349
!skip

**Comment by GregsGirl04** [comment] 2024-07-10 15:21
This has been happening to me as well. I have lost quite a few tanks worth of fluid while shuffling tanks around when crafting hydrochloric acid early game.

**Comment by Saereth** [comment] 2024-07-10 19:46
this may be fixed, as I cant reproduce it anymore in dev, but this is indeed a duplicate issue so im closing this, we'll follow up with the original issue https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5349
I've opened an issue with MI to look into it as well

**Closed by Saereth** 2024-07-10 19:46 UTC
Labels: Bug, FTB NeoTech
