### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Wayno** [FTBTeam/FTB-Modpack-Issues#310] opened 2021-11-14 16:02 UTC
### Modpack

FTB Oceanblock

### Modpack version

1.7.0

### Log Files

[23:59:24] [Render thread/INFO] [me.je.ut.LoggedTimer/]: Starting JEI took 8.488 s
[23:59:24] [Render thread/INFO] [FTB Quests/]: Read 123350 bytes, 1828 objects
[23:59:24] [Render thread/INFO] [minecraft/AdvancementList]: Loaded 2173 advancements
[23:59:25] [Render thread/WARN] [botania/]: Template references nonexistent recipe botania:petal_apothecary/orechid of type botania:petal_apothecary
[23:59:25] [Render thread/WARN] [botania/]: Template references nonexistent recipe botania:petal_apothecary/orechid_ignem of type botania:petal_apothecary
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffaf4003153, pid=23576, tid=0x0000000000000be8
#
# JRE version: Java(TM) SE Runtime Environment (8.0_311-b11) (build 1.8.0_311-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.311-b11 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [atio6axx.dll+0xc03153]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# D:\Games\MultiMC\instances\FTB OceanBlock\minecraft\hs_err_pid23576.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code 1.

### Describe the bug

When typing into the search box in refined storage it crashes the whole game

### Steps to reproduce

Type in the search box in refined storage?

### Expected behaviour

not to crash the game

**Comment by Sunekaer** [comment] 2021-11-14 16:19
Please provide the crash log

**Comment by Raidobw2** [comment] 2021-11-14 20:51
Duplicate of #40
Use the linked issue to get the fix by reading my last comment on it.

**Closed by Raidobw2** 2021-11-14 20:51 UTC
Labels: FTB OceanBlock, state: Duplicate :books:
