### ISSUE TITLE
[Bug]: searching for ender tank uses crashes game

### ISSUE THREAD

**Issue by gman4161** [FTBTeam/FTB-Modpack-Issues#1872] opened 2022-11-11 18:24 UTC
### Modpack

Stoneblock 3

### Modpack version

1.2.1

### Describe the bug

searching for ender tank uses, pressing u in REI, etc. crashes the game. 

### Steps to reproduce

open a world
press u on ender tank
crash

### Expected behaviour

game shouldn't crash

**Comment by tyler489** [comment] 2022-11-11 19:48
Crash report?

**Comment by Raidobw2** [comment] 2022-11-13 08:03
This seems like a duplicate of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1574, so I'll close it to avoid tracking the same issue twice

**Closed by Raidobw2** 2022-11-13 08:03 UTC
Labels: 1: Mod Issue, state: Duplicate :books:, FTB StoneBlock 3
