### ISSUE TITLE
[Bug]: Stoneblock 2 version 1.22.0 Error getting files

### ISSUE THREAD

**Issue by H4RV3Y2805** [FTBTeam/FTB-Modpack-Issues#652] opened 2022-02-27 11:12 UTC
### Modpack

Stoneblock 2

### Modpack version

1.22.0

### Log Files

https://paste.ee/p/b31R6

Job 'Mod download' failed to process:
https://dist.modpacks.ch/modpacks/1/FTB Academy-1.0.0/config/brandon3055/ResourceCache/Cache
https://dist.modpacks.ch/modpacks/10/FTB Academy-1.0.0/config/brandon3055/ResourceCache/Cache
https://dist.modpacks.ch/modpacks/10/FTB Academy-1.0.0/config/brandon3055/ResourceCache/Cache

### Describe the bug

Tried to download the 1.22.0 version via MultiMC and get this error.

### Steps to reproduce

Go to MultiMC
Add Instance
FTB
StoneBlock 2
Install
- Error
Reported to MultiMC and they say its a config thing your side.

### Expected behaviour

New modpack install

### Additional information

Great modpack. :-)

**Comment by Raidobw2** [comment] 2022-02-28 15:21
Hello, i'll close this one since it's a duplicate of #643. You can ignore the error, it shouldn't affect anything in the game at all. In fact, it's files from another modpack, which also are temporary files (cache). Our infrastructure team will have it checked on the download servers. Also, consider using the FTB App if you want to support us.

**Closed by Raidobw2** 2022-02-28 15:21 UTC
Labels: FTB Presents Stoneblock 2, state: Duplicate :books:, 3: Infrastructure
