### ISSUE TITLE
Upgraded Coke Oven seems like miss charcoal recipe

### ISSUE THREAD

**Issue by Apolomir** [FTBTeam/FTB-Modpack-Issues#5328] opened 2024-06-18 14:28 UTC
### Modpack

FTB NeoTech

### Is your suggestion related to a problem? Please describe.

Seems like its not possible to make charcoal in upgraded coke oven, but in "Full Steam Ahead!" quest mentioned coke oven to create charcoal. I was a little bit confused why I can't use upgraded coke oven for that...

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/60337783/413f333b-44cd-4bdf-a235-9fd6d42458e7)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/60337783/58e8935d-96a1-4b21-87df-b8e09b128712)

**Comment by ningoroth** [comment] 2024-06-18 15:02
I sometimes experience the same thing (kinda).

Sometimes when I open the game the recipe for bronze (copper + tin) disappears.
This does however fixes itself after reopening the game, but is still tedious.

Have you tried restarting your game?

**Comment by Apolomir** [comment] 2024-06-18 15:13
> I sometimes experience the same thing (kinda).
> 
> Sometimes when I open the game the recipe for bronze (copper + tin) disappears. This does however fixes itself after reopening the game, but is still tedious.
> 
> Have you tried restarting your game?

@ningoroth actually I tried to process charcoal in upgraded coke oven, but it doesn't work (I'm playing on server)

**Comment by Gaz492** [comment] 2024-06-18 15:58
As you have already discussed, this may be related to the issue that ningoroth (#5324)
!ignore

**Comment by Saereth** [comment] 2024-06-21 18:11
I think this should be fixed in the update today, reopen the issue after the update if it persists for you please. I can't reproduce it on the dev branch currently but I did on live.

**Closed** 2024-06-21 19:03 UTC
Labels: state: Fixed in Dev, Enhancement, @Recipe, FTB NeoTech
