### ISSUE TITLE
KubeJS Server Script Apotheosis Gem Crafting Error

### ISSUE THREAD

**Issue by KetHalpak** [FTBTeam/FTB-Modpack-Issues#5219] opened 2024-05-14 06:32 UTC
### Modpack

FTB Skies Expert

### Modpack version

1.8.1

### Describe the bug

Custom recipes for Apotheosis gem crafting are currently invalid due to a configuration error. The current configuration results in an invalid gem being crafted.
This is caused due to a spelling error in the custom recipe config file. 
The attribute 'rarity' has been misspelled as 'rarirty'. Correcting the spelling in this file fixes the issue, resulting in valid gems.

File location: kubejs\server_scripts\mods\apotheosis.js
Lines: 11, 20, 29, 38, 47, 57

### Steps to reproduce

1. Open file apotheosis.js located in kubejs\server_scripts\mods
2. Check lines 11, 20, 29, 38, 47, 57

### Expected behaviour

Valid apotheosis gems produced once spelling error corrected

**Comment by Gaz492** [comment] 2024-06-14 10:51
Duplicate of #5218

**Closed by Gaz492** 2024-06-14 10:51 UTC
Labels: FTB Skies Expert, Bug, Recipe Bug
