### ISSUE TITLE
Client Crash mousing over Ender Gateway

### ISSUE THREAD

**Issue by natebc** [FTBTeam/FTB-Modpack-Issues#5924] opened 2024-10-08 16:53 UTC
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.2.1

### Launcher

Other...

### Has the pack been modified

No

### Log Files

https://gist.github.com/natebc/bcdd5d58d2ec30f4517bd51e53f668e8

### Describe the bug

When mousing over ender gateway the client crashes

### Steps to reproduce

1. craft ender gateway
2. mouse over it (maybe holding shift?)
3. crash!

### Expected behaviour

no crash

**Comment by Alvinek91** [comment] 2024-10-08 18:29
Hiya! I have the same issue. If you hold SHIFT over the ender gateway, the game crash :/

**Comment by mostlygizzards** [comment] 2024-10-09 03:01
Same - crafted one fresh and had the same response.

Client dropped but server was OK

```
[21:00:37] [Netty Server IO #2/ERROR] [minecraft/Connection]: Exception caught in connection
java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(Unknown Source) ~[?:?] {}
        at java.base/sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:?] {}
        at MC-BOOTSTRAP/io.netty.buffer@4.1.97.Final/io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:254) ~[netty-buffer-4.1.97.Final.jar%23103!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.buffer@4.1.97.Final/io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.97.Final.jar%23103!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}
        at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}
        at java.base/java.lang.Thread.run(Unknown Source) [?:?] {re:mixin}
[21:00:37] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: mostlygizzards lost connection: Disconnected
```

**Comment by mostlygizzards** [comment] 2024-10-09 03:06
Repeated - debug.log

```
[08Oct2024 21:04:25.301] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: Rendering screen
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:1120) ~[client-1.21.1-20240808.144430-srg.jar%23422!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.runTick(Minecraft.java:1195) ~[client-1.21.1-20240808.144430-srg.jar%23422!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.run(Minecraft.java:807) ~[client-1.21.1-20240808.144430-srg.jar%23422!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.main.Main.main(Main.java:230) ~[client-1.21.1-20240808.144430-srg.jar%23422!/:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.24.jar%23118!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-4.0.24.jar%23118!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32) ~[loader-4.0.24.jar%23118!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.24.jar%23118!/:4.0]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%23100!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%23100!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%23100!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%23100!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%23100!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%23100!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%23100!/:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?]
Caused by: java.lang.NoClassDefFoundError: dev/shadowsoffire/apothic_attributes/api/IFormattableAttribute
	at TRANSFORMER/gateways@5.0.0/dev.shadowsoffire.gateways.gate.WaveModifier$AttributeModifier.appendHoverText(WaveModifier.java:112) ~[GatewaysToEternity-1.21.1-5.0.0.jar%23518!/:5.0.0]
	at TRANSFORMER/gateways@5.0.0/dev.shadowsoffire.gateways.client.NormalGateClient.appendPearlTooltip(NormalGateClient.java:59) ~[GatewaysToEternity-1.21.1-5.0.0.jar%23518!/:5.0.0]
	at TRANSFORMER/gateways@5.0.0/dev.shadowsoffire.gateways.gate.normal.NormalGateway.appendPearlTooltip(NormalGateway.java:61) ~[GatewaysToEternity-1.21.1-5.0.0.jar%23518!/:5.0.0]
	at TRANSFORMER/gateways@5.0.0/dev.shadowsoffire.gateways.item.GatePearlItem.appendHoverText(GatePearlItem.java:109) ~[GatewaysToEternity-1.21.1-5.0.0.jar%23518!/:5.0.0]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.ItemStack.getTooltipLines(ItemStack.java:770) ~[client-1.21.1-20240808.144430-srg.jar%23422!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.screens.Screen.getTooltipFromItem(Screen.java:243) ~[client-1.21.1-20240808.144430-srg.jar%23422!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.getTooltipFromContainerItem(AbstractContainerScreen.java:184) ~[client-1.21.1-20240808.144430-srg.jar%23422!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.renderTooltip(AbstractContainerScreen.java:179) ~[client-1.21.1-20240808.144430-srg.jar%23422!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.screens.inventory.InventoryScreen.render(InventoryScreen.java:93) ~[client-1.21.1-20240808.144430-srg.jar%23422!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.screens.Screen.renderWithTooltip(Screen.java:112) ~[client-1.21.1-20240808.144430-srg.jar%23422!/:?]
	at TRANSFORMER/neoforge@21.1.61/net.neoforged.neoforge.client.ClientHooks.drawScreenInternal(ClientHooks.java:428) ~[neoforge-21.1.61-universal.jar%23423!/:?]
	at TRANSFORMER/neoforge@21.1.61/net.neoforged.neoforge.client.ClientHooks.drawScreen(ClientHooks.java:422) ~[neoforge-21.1.61-universal.jar%23423!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.GameRenderer.mixinextras$bridge$drawScreen$182(GameRenderer.java) ~[client-1.21.1-20240808.144430-srg.jar%23422!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.GameRenderer.wrapOperation$bid000$konkrete$wrapRenderScreen_Konkrete(GameRenderer.java:2741) ~[client-1.21.1-20240808.144430-srg.jar%23422!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.GameRenderer.mixinextras$bridge$wrapOperation$bid000$konkrete$wrapRenderScreen_Konkrete$183(GameRenderer.java) ~[client-1.21.1-20240808.144430-srg.jar%23422!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.GameRenderer.wrapOperation$cjd000$fancymenu$wrapRenderScreenFancyMenu(GameRenderer.java:4243) ~[client-1.21.1-20240808.144430-srg.jar%23422!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:1092) ~[client-1.21.1-20240808.144430-srg.jar%23422!/:?]
	... 18 more
Caused by: java.lang.ClassNotFoundException: dev.shadowsoffire.apothic_attributes.api.IFormattableAttribute
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:220) ~[securejarhandler-3.0.8.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at TRANSFORMER/gateways@5.0.0/dev.shadowsoffire.gateways.gate.WaveModifier$AttributeModifier.appendHoverText(WaveModifier.java:112) ~[GatewaysToEternity-1.21.1-5.0.0.jar%23518!/:5.0.0]
	at TRANSFORMER/gateways@5.0.0/dev.shadowsoffire.gateways.client.NormalGateClient.appendPearlTooltip(NormalGateClient.java:59) ~[GatewaysToEternity-1.21.1-5.0.0.jar%23518!/:5.0.0]
	at TRANSFORMER/gateways@5.0.0/dev.shadowsoffire.gateways.gate.normal.NormalGateway.appendPearlTooltip(NormalGateway.java:61) ~[GatewaysToEternity-1.21.1-5.0.0.jar%23518!/:5.0.0]
	at TRANSFORMER/gateways@5.0.0/dev.shadowsoffire.gateways.item.GatePearlItem.appendHoverText(GatePearlItem.java:109) ~[GatewaysToEternity-1.21.1-5.0.0.jar%23518!/:5.0.0]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.ItemStack.getTooltipLines(ItemStack.java:770) ~[client-1.21.1-20240808.144430-srg.jar%23422!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.screens.Screen.getTooltipFromItem(Screen.java:243) ~[client-1.21.1-20240808.144430-srg.jar%23422!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.getTooltipFromContainerItem(AbstractContainerScreen.java:184) ~[client-1.21.1-20240808.144430-srg.jar%23422!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.renderTooltip(AbstractContainerScreen.java:179) ~[client-1.21.1-20240808.144430-srg.jar%23422!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.screens.inventory.InventoryScreen.render(InventoryScreen.java:93) ~[client-1.21.1-20240808.144430-srg.jar%23422!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.screens.Screen.renderWithTooltip(Screen.java:112) ~[client-1.21.1-20240808.144430-srg.jar%23422!/:?]
	at TRANSFORMER/neoforge@21.1.61/net.neoforged.neoforge.client.ClientHooks.drawScreenInternal(ClientHooks.java:428) ~[neoforge-21.1.61-universal.jar%23423!/:?]
	at TRANSFORMER/neoforge@21.1.61/net.neoforged.neoforge.client.ClientHooks.drawScreen(ClientHooks.java:422) ~[neoforge-21.1.61-universal.jar%23423!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.GameRenderer.mixinextras$bridge$drawScreen$182(GameRenderer.java) ~[client-1.21.1-20240808.144430-srg.jar%23422!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.GameRenderer.wrapOperation$bid000$konkrete$wrapRenderScreen_Konkrete(GameRenderer.java:2741) ~[client-1.21.1-20240808.144430-srg.jar%23422!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.GameRenderer.mixinextras$bridge$wrapOperation$bid000$konkrete$wrapRenderScreen_Konkrete$183(GameRenderer.java) ~[client-1.21.1-20240808.144430-srg.jar%23422!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.GameRenderer.wrapOperation$cjd000$fancymenu$wrapRenderScreenFancyMenu(GameRenderer.java:4243) ~[client-1.21.1-20240808.144430-srg.jar%23422!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:1092) ~[client-1.21.1-20240808.144430-srg.jar%23422!/:?]
	... 18 more

```

**Comment by mostlygizzards** [comment] 2024-10-09 03:22
Potential duplicate of #5859

**Comment by mostlygizzards** [comment] 2024-10-09 03:31
Potential duplicate of #5863

**Closed** 2024-10-14 14:22 UTC
Labels: state: Fixed in Dev, Bug, FTB Presents Direwolf20 1.21
