### ISSUE TITLE
[Bug]: Sheep wouldn't spawn (video attached)

### ISSUE THREAD

**Issue by Sabster** [FTBTeam/FTB-Modpack-Issues#785] opened 2022-05-17 08:13 UTC
### Modpack

Direwolf20 1.18

### Modpack version

1.0

### Describe the bug

I have a server (still have the saved world) that was using the same seed that DW20 uses in his lets play video.  At one point, I built a sheep pen (26 x 18) and dragged a couple sheep into the pen (using wheat).  I later found 2 or 3 more sheep, carried them into the pen and when I placed them down, they disappeared...  I thought it was a bug with carrying sheep, but then when i tried to breed the two sheep that I lead over to the pen, the same thing happened to the baby.  Only as I was standing there, I saw a patch of grass turn to dirt.

I went into creative mode and killed the sheep in the pen - spawned in some sheep (using an egg) - and could hear them, but could never see them.

With that in mind, I couldn't get it to happen again when I created a new world...  So I don't know how you could recreate this bug without that world...

### Steps to reproduce

Use the seed from DW20's video (DW201182WOOHOO (I think)) - go into creative mode near the village (near spawn) and try and summon a sheep...

Again, reset the world (though I still have this saved) and it worked that time... 

### Expected behaviour

Should be able to see the sheep - I could hear them...

### Screenshots

Soon as it's done uploading:  https://youtu.be/DM3EV-6HK28

**Comment by TheonlyTazz** [comment] 2022-05-17 10:55
Duplicate of: https://github.com/FTBTeam/FTB-Modpack-Issues/issues/774
Fixed in Dev

**Closed** 2022-05-17 10:56 UTC
Labels: state: Duplicate :books:, state: Fixed in Dev :hammer_and_wrench:, FTB Presents Direwolf20 1.18
