### ISSUE TITLE
Client Crashes When Placing Engineer's Blueprint into Engineer's Workbench

### ISSUE THREAD

**Issue by Shockspore** [FTBTeam/FTB-Modpack-Issues#6060] opened 2024-11-02 19:14 UTC
### Modpack

FTB Inferno

### Modpack version

1.10.1

### Launcher

CurseForge

### Has the pack been modified

No

### Log Files

[crash-2024-11-02_14.33.01-client.txt](https://github.com/user-attachments/files/17608058/crash-2024-11-02_14.33.01-client.txt)

### Describe the bug

placing an Engineer's Blueprint into the Engineers workbench from Immersive Engineering causes client side crashes when attempting to render the workbench.

### Steps to reproduce

1. place down Engineer's Workbench from Immersive Engineering
2. place Engineer's Blueprint into first slot in the Workbench
3. If your client tries to render the workbench, the game crashes
4. if you are far enough away or facing away it will not crash.

### Expected behaviour

Placing the Engineer's blueprint should allow you to craft the item listed on it using the required materials.

### Additional information

Does not crash the server, only crashes client's.

**Comment by Gaz492** [comment] 2024-11-19 07:28
Duplicate of #5996

**Closed by Gaz492** 2024-11-19 07:28 UTC
Labels: FTB Inferno, Bug
