### ISSUE TITLE
[Suggestion]: Add ExtraStorage

### ISSUE THREAD

**Issue by Joly0** [FTBTeam/FTB-Modpack-Issues#1978] opened 2022-11-15 16:09 UTC
### Modpack

FTB Stoneblock 3

### Is your suggestion related to a problem? Please describe.

Its quite frustrating to only have base crafters and small storage disks in refined storage. It would be great to have larger disks, more spaces in crafters and fast exporter and importers

Something else for ae2 would be neat aswell

### Mod suggestion

Would be great to add
https://www.curseforge.com/minecraft/mc-mods/extrastorage

**Comment by Sunekaer** [comment] 2022-11-15 16:53
Duplicate of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1599

**Closed by Sunekaer** 2022-11-15 16:53 UTC
