### ISSUE TITLE
FTB Skies Expert server crashes on first start

### ISSUE THREAD

**Issue by tpwrules** [FTBTeam/FTB-Modpack-Issues#5245] opened 2024-05-24 00:58 UTC
### Modpack

FTB Skies Expert

### Modpack version

1.8.1

### Describe the bug

The following mod files are client only and having them on the server crashes it. 
* `mods/entity_model_features_forge_1.19.2-2.0.2.jar`
* `mods/entity_texture_features_forge_1.19.2-6.0.1.jar`
* `mods/entity_texture_features_forge_1.19.2-6.0.1.jar`

Deleting them seems to fix it and the server starts successfully after. I used the latest x86_64 linux file available from the FTB site, called `serverinstall_117_11927`.

### Steps to reproduce

1. Use `serverinstall_117_11927` to install a server in a fresh folder
2. Attempt to start the server

### Expected behaviour

Starts without crashing.

**Comment by WyFryMU** [comment] 2024-05-24 01:01
Duplicate of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5180

**Closed** 2024-06-03 15:38 UTC
Labels: FTB Skies Expert
