### ISSUE TITLE
Tin plates

### ISSUE THREAD

**Issue by DaniloDa1105** [FTBTeam/FTB-Modpack-Issues#5226] opened 2024-05-17 23:15 UTC
### Modpack

FTB Revelation

### Modpack version

1.12.2

### Describe the bug

We have the problem that it is not possible to produce tin plates in our world. If we make the forging hammer and the tin ingot next to each other, the end product (tin plate) is not displayed. However, the preview is displayed correctly. Without these plates, it is difficult for us to make energy.

### Steps to reproduce

1. Take the forging hammer next to the tin ingot in the crafting table
2. You cannot see any result

### Expected behaviour

please solve the problem for the other players and if it is possible for our world too

### Screenshots

![FTB Minecraft 2 0](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/170146538/a92c4e42-4dda-4af2-8371-d351412c76e4)
![FTB Minecraft](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/170146538/7386f873-d711-4325-9b67-e3ed485f5ddc)

### Additional information

I hope you can open the screenshots

**Comment by Gaz492** [comment] 2024-06-06 11:15
Duplicate of #5175

**Closed by Gaz492** 2024-06-06 11:15 UTC
Labels: FTB Revelation
