### ISSUE TITLE
[Bug]: MineTogether crash when launching

### ISSUE THREAD

**Issue by Gogbe** [FTBTeam/FTB-Modpack-Issues#1611] opened 2022-11-03 21:10 UTC
### Modpack

StoneBlock 3

### Modpack version

1.0.2

### Log Files

[crash-2022-11-03_16.05.00-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9932965/crash-2022-11-03_16.05.00-client.txt)

### Describe the bug

I am unable to launch the pack.

### Steps to reproduce

1. Launch the Pack
2. Crashes.

### Expected behaviour

I get to the main menu

### Additional information

I have a Radeon graphics card. That is the only thing I can think of that may be affecting it.

**Comment by Raidobw2** [comment] 2022-11-04 10:01
You can try updating your graphics driver, but if that error is persistent for now the only way to launch your game will be to remove the MineTogether mod.

I've spoken with the MineTogether team today and they have been doing a lot of fixes for the next StoneBlock 3 patch which will come very soon, thanks for your patience until then!

**Comment by Raidobw2** [comment] 2022-11-04 10:19
Hey, actually the MineTogether team could use your `latest.log` to debug this issue. Let me know if you've got it nearby and thanks in advance!

**Comment by Raidobw2** [comment] 2022-11-04 11:46
Linked with https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1597

**Comment by Raidobw2** [comment] 2022-11-04 12:23
Sorry for spamming so much. Please try with Java 17!

**Comment by Sunekaer** [comment] 2022-11-05 17:06
duplicate of  #1597

**Closed by Sunekaer** 2022-11-05 17:06 UTC
Labels: 1: Mod Issue, FTB StoneBlock 3
