### ISSUE TITLE
Game crashs when trying to break a placed Zombie Piglin Statue

### ISSUE THREAD

**Issue by DarkageMan** [FTBTeam/FTB-Modpack-Issues#5914] opened 2024-10-06 18:38 UTC
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.2.1

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

[crash-2024-10-06_12.32.50-client.txt](https://github.com/user-attachments/files/17270549/crash-2024-10-06_12.32.50-client.txt)

### Describe the bug

I misplaced a Zombified Piglin Statue on the ground. When I tried to break it with an empty hand the game crashed immediately. Started game again and tried to break with a pickaxe with same result.  

### Steps to reproduce

Walk up to placed Zombified Piglin Statue. Click to interact/break statue. Immediate Game Crash.

### Expected behaviour

the statue to break and go into my inventory

### Screenshots

![2024-10-06_12 32 40](https://github.com/user-attachments/assets/c2c37474-f289-42d5-955f-ce77db76c2c2)

**Comment by Gaz492** [comment] 2024-10-07 08:01
This is a known issue caused by the mod neat. This should hopefully be fixed in the next pack update.
Also closing this as its a duplicate of #5846

**Closed by Gaz492** 2024-10-07 08:01 UTC
Labels: Bug, FTB Presents Direwolf20 1.21
