### ISSUE TITLE
[Bug]: Crash while clicking between JEI panes after searching for uses of sawdust

### ISSUE THREAD

**Issue by WebDragon** [FTBTeam/FTB-Modpack-Issues#954] opened 2022-06-14 02:24 UTC
### Modpack

FTB Direwolf20 1.18

### Modpack version

1.4.1

### Log Files

https://pste.ch/erejayeziv.rb

### Describe the bug

had searched the use of sawdust from mekanism and was clicking around the jei interface panes between page 1 and 2 and had just tried clicking back to pane 1

not sure if reproduceable

### Steps to reproduce

1. search item in JEI by choosing 'U' to see the uses for the item (in this case, sawdust)
2. click between pages using the right and left arrow buttons
3. suddenly experience a crash while clicking the left arrow to get back to page 1 of the interface

### Expected behaviour

normal jei clicking

**Comment by TheonlyTazz** [comment] 2022-06-17 09:15
could not replicate this issue, i have been clicking through JEI for atleast 5minutes and coulndt find the cause, can you retry this on the current 1.5.1 version and give us some feedback?

**Comment by WebDragon** [comment] 2022-06-17 22:19
yeah it was suuuuuuper random -- I haven't been able to replicate it either and have no idea what caused it in the first place. If I see it again in a later version I will definitely follow up with a further crash log

**Comment by TheonlyTazz** [comment] 2022-06-18 06:46
I will close it for now as it has been a one-off time it happened, if you can manage to replicate it consistently please open up a new issue

**Closed by TheonlyTazz** 2022-06-18 06:46 UTC
Labels: 1: Mod Issue, state: Awaiting Reply :speaking_head:, FTB Presents Direwolf20 1.18
