### ISSUE TITLE
Pretty Pipes crash the game if placed inside of a Compact Machine (only if you try to open preview by right clicking the machine with empty hand)

### ISSUE THREAD

**Issue by Code7737** [FTBTeam/FTB-Modpack-Issues#3352] opened 2023-05-12 13:58 UTC
### Modpack

FTB StoneBlock 3

### Modpack version

1.7.0

### Log Files

[crash-2023-05-12_19.41.00-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11464738/crash-2023-05-12_19.41.00-client.txt)

### Describe the bug

The title is self-explanatory.
Pretty Pipes crash the game if placed inside of a Compact Machine (only if you try to open preview by right clicking the machine with empty hand)

### Steps to reproduce

1. Place a compact machine and enter it
2. Place a pipe from Pretty Pipes mod
3. Exit the machine
4. Click it with empty hand (to preview its contents)

### Expected behaviour

The game won't crash

### Additional information

I tried the item pipe from Pretty Pipes and Maximum Compact Machine.
Idk if I got the right log.

**Comment by UnRealDinnerbone** [comment] 2023-05-17 15:06
I'm unable to reproduce this issue, any block in specific the pipez are connected to?

**Comment by Code7737** [comment] 2023-05-18 10:39
just a random pipe out there, disconected from anything.

https://github.com/FTBTeam/FTB-Modpack-Issues/assets/133375498/dc26149b-5923-44f1-bad5-a32befef79e7

here is a video of me replicating the problem.

**Comment by Code7737** [comment] 2023-06-02 16:56
no clue how to remove this "awaiting reply" tag. is it the reason no one replies?

**Comment by Code7737** [comment] 2023-06-08 08:32
@UnRealDinnerbone happy birthday!

**Comment by UnRealDinnerbone** [comment] 2023-06-08 13:19
Thanks. I'm assuming you know because of a message in game?

**Comment by Code7737** [comment] 2023-06-10 03:41
yea

**Comment by Code7737** [comment] 2023-06-10 13:13
yeah

**Comment by UnRealDinnerbone** [comment] 2024-06-24 20:28
This issue should have been fixed with mod updates https://github.com/CompactMods/CompactMachines/issues/554

**Closed by UnRealDinnerbone** 2024-06-24 20:28 UTC
Labels: state: Confirmed, state: Awaiting Mod Update, FTB StoneBlock 3
