### ISSUE TITLE
Mana Duplication

### ISSUE THREAD

**Issue by YozoraGD** [FTBTeam/FTB-Modpack-Issues#4867] opened 2024-03-05 15:23 UTC
### Modpack

FTB University 1.19

### Modpack version

1.4.2

### Describe the bug

This bug allows players to duplicate infinite amount of mana.

### Steps to reproduce

Setup the AE2 system as below and try to pull mana from the gui (notice that the storage bus is attached to the mana p2p tunnel instead of directly attached to mana pool).

https://github.com/FTBTeam/FTB-Modpack-Issues/assets/50094654/1f4847b9-53ff-4a36-a2de-98eb10cfb646

### Expected behaviour

Nothing happens when trying to pull mana from the system.

**Comment by UnRealDinnerbone** [comment] 2024-06-24 18:06
I'm unable to reproduce this issue. Is there anything else going on?

**Comment by UnRealDinnerbone** [comment] 2024-06-25 13:37
Going to close this issue then. If it happens again, please let us know.

**Closed by UnRealDinnerbone** 2024-06-25 13:37 UTC
Labels: FTB University 1.19
