### ISSUE TITLE
[Bug]: Chunk Failed to Load

### ISSUE THREAD

**Issue by bahaynes** [FTBTeam/FTB-Modpack-Issues#573] opened 2022-01-19 23:06 UTC
### Modpack

FTB Oceanblock

### Modpack version

1.11

### Log Files

Error: https://pste.ch/pumiripige.pl

Full log: https://pste.ch/otagaxazax.sql

### Describe the bug

A chunk of the world fails to load on sever restart. Included mekanism power generation, refined storage disk drives, storage blocks, and crafters, as well as pipez cables. 

### Steps to reproduce

This one's difficult to reproduce. I'm hoping for some insight into what actually went wrong.

### Expected behaviour

Chunk loads when server restarts.

### Screenshots

![2022-01-19_18 20 12](https://user-images.githubusercontent.com/6018512/150234059-b62a7dc2-066c-4056-ae6a-5f3c6c7a82a4.png)

**Comment by Raidobw2** [comment] 2022-01-20 08:06
Hi, it looks like a Refined Storage NBT tag somewhere might have been corrupted (`at com.refinedmods.refinedstorage.apiimpl.network.Network.update`), preventing the chunk to load. Can you try a few things?

First, you can try to break those 3 blocks from Refined Storage that propagate your network, next to the chunk border:
![image](https://user-images.githubusercontent.com/17010632/150294649-16851b79-b9f1-400e-84f6-771478c92d7b.png)
Then type `save-all` as an operator in the game/console and reboot the server. Let me know if the next server boot works.

If that reboot didn't work:
Please send me the corrupted region file here or on the FTB Discord through DMs, to whichever you prefer. This is located inside the problematic save, inside the `region` folder. I would only need the `r.0.9.mca` file since it is the problematic region containing the erroring chunk (17, 304) at coordinates (276, 138, 4872), where you are standing.

Then you'd have to use a backup if you can. In the `backups` folder you'll find copies of previous worlds. You can try one of those, simply by taking the world that is inside one of the latest zips in that folder and using it to start the server.

If the backups are too old but that chunk you're standing on works and still has machinery/builds to spare, I can help you out by putting that old chunk back onto the current world as a sort of patch. This means you would have the same current world but that one old chunk you'd be standing in. Let me know in that case once you've tried a few things from the above suggestions before getting to this one.

**Comment by bahaynes** [comment] 2022-01-20 14:15
This is super helpful, thank you! I'll try this tonight and see how it goes.

**Comment by bahaynes** [comment] 2022-01-21 01:36
After removing adjacent RS blocks and restarting the server, the log was the following: https://paste.feed-the-beast.com/view/a2b0e02f (Logs for the last day here: https://paste.fee
d-the-beast.com/view/202c8b32)

The chunk still appears to be missing. 
This is the region file (I believe).
[r.0.9.mca.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7909660/r.0.9.mca.zip)


Thanks again for the help!

**Comment by Raidobw2** [comment] 2022-01-21 03:51
Hi, I've looked in the file you sent me and loaded in-game, but didn't find any good info...

Basically the problematic chunk on the left is containing only 54 fake lights (the mechanic of the floodlight is to place invisible light sources it seems) and no other machinery or blocks, which is weird. According to the direction of your cables on the adjacent chunk, the chunk at the right (and where the blaze smeltery is), these cables go into the problematic chunk.
But that problematic chunk is empty basically, there no longer are traces of any machines in there.
![image](https://user-images.githubusercontent.com/17010632/150462069-483d419b-b504-4676-ab87-40037074e09d.png)

I am standing inside the now "normal" chunk which is supposed to be corrupted. The smeltery is the adjacent chunk I've checked to compare as well.
![image](https://user-images.githubusercontent.com/17010632/150462118-44f06602-956c-4347-b9bb-e474484ac1fd.png)

Have you tried using a backup from my previous suggestions? Did it work?
Please let me know and thanks!

**Comment by bahaynes** [comment] 2022-01-21 19:30
I'll look through the backups. I'm seeing the same thing in NBT edit, including in several of the backups so far.

**Comment by bahaynes** [comment] 2022-01-22 00:28
So the data does appear to be in the backup. I copied the tile entities from the backup into the current world save, but it didn't seem to do anything.

**Comment by bahaynes** [comment] 2022-01-22 00:32
Out of curiosity, could I swap out a region mca file from the backup into the current save?

**Comment by bahaynes** [comment] 2022-01-22 02:40
Looks like that worked well enough. Thanks for helping me troubleshoot and fix this!

**Comment by Raidobw2** [comment] 2022-01-22 03:06
Yes swapping a region file is no problem, the worlds are completely modular. I'm not sure what could have caused this... Could it have been a power cut or unexpected shutdown at the wrong moment? If you're ok with it I would close this issue since we could not find the cause for now, and it's solved. I'd recommend staying aware of the problem and if it happens again you can comment here or reopen it, I will see it.

**Comment by bahaynes** [comment] 2022-01-22 04:55
Sounds good, thanks again!

**Closed** 2022-01-23 07:42 UTC
Labels: FTB OceanBlock, 3: Support Request
