### ISSUE TITLE
Spirit deployer is not working.

### ISSUE THREAD

**Issue by LostRager** [FTBTeam/FTB-Modpack-Issues#4656] opened 2024-02-16 21:44 UTC
### Modpack

FTB Skies Expert

### Modpack version

1.0.1

### Describe the bug

Spirit deployer does not work. Tried 3 different worlds and regiven myself the quest reward to see if that works. Nope. Nothing happends.

### Steps to reproduce

get Spirit deployer -> try to use.

### Expected behaviour

it should work

**Comment by pikminman13** [comment] 2024-02-16 22:21
this is fixed in 1.0.2 by just not having the deployer and instead using the schematicannon as intended

**Closed by pikminman13** 2024-02-16 22:21 UTC
Labels: FTB Skies Expert
