### ISSUE TITLE
Immersive engineering recipe problem

### ISSUE THREAD

**Issue by MoonStalk** [FTBTeam/FTB-Modpack-Issues#2628] opened 2023-01-31 12:13 UTC
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.2.1

### Describe the bug

Trying to use control click + button to auto craft missing components doesn't appear to work for some recipe items (possibly only for Immersive Engineering).

selecting the auto crafting component recipe and making the item works fine.  Once created the component is usable via click crafting the recipe

Behavior applies even to IE components in IE recipes if the item has a variant, such as treated wood planks (horizontal, vertical, etc)

### Steps to reproduce

have auto crafting recipe for iron plates and no iron plates created
Search for Iron mechanical component in JEI and bring up the ingredients
try to click + to load the ingredients into the crafting grid, but the + button is red
mouse over + button to see that it says you have no iron plates and no option to auto craft them

### Expected behaviour

offer ctrl-click + button to allow auto crafting of missing components

### Screenshots

![image](https://user-images.githubusercontent.com/34584644/215755102-93a13c90-d735-4a79-b1e5-30c9d2c8788e.png)
![image](https://user-images.githubusercontent.com/34584644/215755215-bb076f38-9b44-408f-b04b-9c0cbf29a4e8.png)

### Additional information

playing on a linux dedicated server from a windows system.

**Comment by MoonStalk** [comment] 2023-01-31 12:14
if I create an auto crafting pattern for IE iron plates, ctrl+click options appears for the missing plate

**Comment by Saereth** [comment] 2023-02-22 04:04
I didnt get around to this earlier but I cant reproduce this now in 1.3.2 so im marking as resolved

**Closed by Saereth** 2023-02-22 04:04 UTC
Labels: state: Fixed :heavy_check_mark:, FTB Presents Direwolf20 1.19
