### ISSUE TITLE
Tin Block Wrong

### ISSUE THREAD

**Issue by DiggityMan420** [FTBTeam/FTB-Modpack-Issues#4235] opened 2023-11-14 17:14 UTC
### Modpack

FTB Genesis

### Modpack version

1.1.1

### Describe the bug

quest text explains wrong way to convert a tin block not a simple shapecraft its a stone cutter see pics

### Steps to reproduce

craft 9 tin ingots
into a tin block and try to convert

### Expected behaviour

correct quest descriptions

### Screenshots

![Screenshot_9](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/45196448/88b31a9e-8006-48d3-b40c-61513ff8f26c)
![Screenshot_10](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/45196448/c31ab23f-5c06-4fd9-b712-9467b94070b4)
![Screenshot_11](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/45196448/ecde5dd6-097c-405b-9b0d-319026c55ecd)
![Screenshot_12](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/45196448/3bc84e1f-f32f-455d-a312-18146f5add4f)
![Screenshot_13](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/45196448/0c01aed3-a293-452c-a133-75d050bb67e6)
![Screenshot_14](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/45196448/10ee9671-c6f7-4495-b79c-0b7409f305a1)
![Screenshot_15](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/45196448/ea7e46cf-5b71-4e39-9a75-cd7b71b31693)

**Comment by yarma92** [comment] 2023-11-15 11:21
Duplicate of #4208

**Comment by Saereth** [comment] 2023-11-16 02:26
new version of ic2 coming out in next update supports tags so this will no longer be an issue

**Closed as completed** 2023-11-18 02:36 UTC
Labels: state: Fixed in Dev, state: Awaiting Mod Update, FTB Genesis
