### ISSUE TITLE
[Bug]: Checking matter ball recipe crashes game

### ISSUE THREAD

**Issue by IThundxr** [FTBTeam/FTB-Modpack-Issues#1806] opened 2022-11-09 22:46 UTC
### Modpack

FTB StoneBlock 3

### Modpack version

1.2.0

### Log Files

https://mclo.gs/8r48mAc latest.log
https://mclo.gs/AjzLah9 crashreport

### Describe the bug

Basically checking the recipe of matter balls crashes the game

### Steps to reproduce

1. see recipe for matter ball
2. game crashes

### Expected behaviour

The recipe for matter balls to show up

**Comment by Sunekaer** [comment] 2022-11-10 08:27
Duplicate of #1719

**Closed by Sunekaer** 2022-11-10 08:27 UTC
Labels: 1: Mod Issue, FTB StoneBlock 3
