### ISSUE TITLE
FTB Industrial Contraption ingots appear to have no use in crafting 

### ISSUE THREAD

**Issue by SekhetBR** [FTBTeam/FTB-Modpack-Issues#2789] opened 2023-03-05 12:48 UTC
### Modpack

FTB One

### Modpack version

2.0

### Describe the bug

The FTB IC ingots in FTB One don't craft into anything, with a few minor (but also broken) exceptions. This issue is exacerbated by the fact that smelting ores and chunks directly yields FTB IC ingots.

My best guess is that it's something to do with tags. One can see and use Mekanism, Thermal (and so on) ingots in the crafting recipes. The FTB IC ingots aren't visible in the recipes and one can't craft (or process) with the FTB IC ingots manually. This extends to (almost) all uses of the FTB IC ingots - for example, the Uranium doesn't work as fuel in the Reactors mod anymore. It seems like the FTB IC ingots are no longer recognized as forge ingots.

There is a workaround, which also seems like it shouldn't be A Thing, but it does work. One can get Mekanism ingots by running Ore through an Enrichment Chamber and smelting the result in an Energized Smelter. I say that this doesn't seem like it should be A Thing on account of it looks to me like FTB IC ingots are acting like they're the default processing result. Also, it's the FTB IC ores that are being delivered by the Ore Miner Djinn. I assume I'll find FTB IC ores in new Mining Dimension chunks also, but I haven't checked yet.

The workaround is not perfect, and there are additional issues. For instance, it's really really hard to make Electrum, although it can be done. The crafting recipe for Electrum Blend that appears to be the default in an RS system and the Occultism storage system is for the Thermal version of Electrum Blend, which has no use. To get the Mekanism version (which you can smelt into Electrum Ingots) one has to craft it manually in a crafting GUI that shows the button for the Polymorph mod. Weirdly, the Mekanism version is the default option in GUIs that show the Polymorph button. 

### Steps to reproduce

1. Run FTB One
2. Directly smelt some (for example) lead from ore or chunks in any furnace-like machine, including a vanilla furnace.
3. Look up the crating recipes for the FTB IC ingot that results from the smelting operation.
4. Note that there are no recipes or uses (can't even make them into lead blocks).
5. Try to use the FTB IC ingot for something without resort to... JEI? REI? Whichever one.
6. Be shook.
7. Check Discord.
8. Cry.
9. Pet cat for one (1) hour.
10. Attempt multi-step processing with Mekanism and generate Mekanism ores. 

### Expected behaviour

Ingots produced by smelting generally have uses.

**Comment by RoshTMG** [comment] 2023-03-05 13:14
Yeah, you can look at the FTBIC bars with mekanism's dictionary and see that none of the FTBIC have entries, meaning that they're unusable. They don't even show up in JEI. They're completely broken. Can't actually play how you want with this pack because of this bug. Thermal Expansion for example can't get much further than a dynamo because all the machines require machine frames, which require tin, all of which is totally broken because of FTBIC. It requires all sorts of jumping through hoops in other mods to get just TF working.

It really doesn't help that since these bars have no ore dictionary entries, you can't even use the oredictionificator to convert the bars. I've been struggling with this for a couple days now, frustrating. For now, I think the best you can do is just to switch bars in creative if that's possible for you.

**Comment by MechBFP** [comment] 2023-03-05 13:23
Duplicate of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2784

**Comment by Saereth** [comment] 2023-03-08 18:59
you can convert these to useable ingots now with a shapecraft and they should no longer be produced by machines

**Closed by Saereth** 2023-03-08 18:59 UTC
Labels: state: Fixed in Dev :hammer_and_wrench:, FTB One
