### ISSUE TITLE
Quest detection not working

### ISSUE THREAD

**Issue by JJSax** [FTBTeam/FTB-Modpack-Issues#5122] opened 2024-04-10 00:33 UTC
### Modpack

FTB Skies Expert

### Modpack version

1.7.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14925520/latest.log)

### Describe the bug

I have gray checkmarks above half of chapter 2's quest line.  I thought for awhile that this was due to them not having quest rewards, but the T1 rocket does have rewards and it's the same color, and previous ones are green without rewards.

### Steps to reproduce

I'm not sure how to reproduce or if it's how it always is.

### Expected behaviour

I expected green check marks, and the green color on quest line two on the left side bar once I completed the chapter.

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/5084938/ee2db65e-ca6a-467f-8262-7035c649477b)
Notice that I'm holding 2 marine fabric, yet that is one that doesn't seem to be completed.  

### Additional information

I am demonstrating in my image that I'm holding marine fabric, but I've also held the latex bucket and made the protective fabric as well.  I started this modpack on (I believe) the previous version of the pack, and then updated.  I am pretty sure I updated before reaching these points in the questline but I'm not 100% sure on that.

**Comment by JJSax** [comment] 2024-04-10 04:23
And it would seem it's happening in chapter 3 as well.  I just did the springaline desh ingot and it's a gray check box but it won't let me get the rewards.

**Comment by Joplaya** [comment] 2024-04-11 22:58
I have the same issue, it seems to be the quest for Latex bucket - the one at the bottom of the quest page coming after the fluid extractor quest works (green tick), the instance in the middle which leads to marine fabric and polyethylene doesn't detect and only has a grey tick even when you have a latex bucket in hand.

**Comment by isochronous** [comment] 2024-04-16 03:57
Same. Even if I force complete in editor mode it stays gray.

**Comment by Joplaya** [comment] 2024-04-17 19:39
Can confirm the issue isn't resolved in current 1.7.0.
Cannot confirm if I personally completed the quest before updating to 1.7.0.

**Comment by isochronous** [comment] 2024-04-17 22:32
I was able to work around this by setting the quests that are dependent on
the latex bucket quest to only require one dependency, rather than all
dependencies. I was then able to force complete those quests and the rest
followed.

**Comment by Mejval5** [comment] 2024-04-22 10:34
I started playing on 1.7.0 and have the same issue. The latex bucket is greyed out even though I have the prerequisite.
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/48858230/959b74d7-eb8a-4fcc-8677-5bca0c0e52cf)

**Comment by Mejval5** [comment] 2024-04-22 10:43
The fix is as follows:
1. Find your game folder (via the ftb launcher let's say).
2. Go to config/ftbquests/quests/chapters
3. Open getting_on_up.snbt
4. Find these two quests that are dependencies and remove the latex bucket as dependency (delete the "6F91DBD099B24967")

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/48858230/0ec04e09-6493-4ff9-a98d-f4ee3546ed10)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/48858230/98f6e227-5756-4b6a-9944-085afbe5d0a3)

After I removed them:
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/48858230/3892f630-355b-43a0-99ec-19dd3bca697c)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/48858230/c8ddff3d-06fb-4d00-a35d-3b67dd7cc7f5)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/48858230/8dd9dfc9-f6bc-497e-ab05-80718af7b572)

It's still stuck there, I suppose you can remove it also from the quest line by deleting this whole thing
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/48858230/32dc2937-fd12-4ac8-a2d6-fbe10d393ebe)

I don't think it's important thing to have. It can be probably also deleted from the original pack.
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/48858230/1723e6a5-9628-4cb1-98b2-6f96b197660b)

**Comment by Mejval5** [comment] 2024-04-22 10:49
I also had to do:
/ftbquests editing_mode true

and then click on the Reset Progress and then Complete Instantly
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/48858230/0f89bce9-6815-471e-94fa-8da2248141ad)

(I also tried to remove the polyethylene bucket from the quest hence the stone block)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/48858230/1330d9e5-f0cf-4cc0-bf40-f802679a873b)

**Closed** 2024-05-03 01:13 UTC
Labels: state: Fixed in Dev :hammer_and_wrench:, FTB Skies Expert
