### ISSUE TITLE
[Bug]: JVM crashes when trying to extract items using Pipez from Inventory Connector of Tom's Simple Storage Mod

### ISSUE THREAD

**Issue by Lauriichan** [FTBTeam/FTB-Modpack-Issues#1278] opened 2022-08-17 08:58 UTC
### Modpack

FTB One

### Modpack version

1.3.0

### Log Files

https://gist.github.com/Lauriichan/308d121880679dbfce9649231b227db3

### Describe the bug

I wanted to extract items from the Inventory Connector of Tim's Simple Storage Mod and immediately after changing the Item Pipe to extract mode the server crashed

### Steps to reproduce

1. Place a Inventory Connector
2. Place some chests around it
3. Try to extract items from it using an Item Pipe

### Expected behaviour

The pipe should extract the items normally and not to crash the JVM

**Comment by Lauriichan** [comment] 2022-08-17 09:03
This only happend when trying to transfer those items into a Tesseract, I've no idea why

**Comment by Raidobw2** [comment] 2022-08-25 09:37
Hi @Lauriichan, the author of Pipez asked me for crash logs today. Do you have any of the crash logs (including jvm crashes) available so I could relay them information?

I've tried reproducing the issue in development though I am unable to do it currently, the server is doing fine (5ms per tick). If you happen to have a picture of the pipe setup you used in-game, I'll gladly take it to try and reproduce the issue.

Thanks in advance

**Comment by Lauriichan** [comment] 2022-08-25 20:31
Hey @Raidobw2 
Sadly I deleted my FTB One Server about 2 days ago because of the many issues I had with this pack especially lag related issues
I just were not able to play with more than 10 tps on my server when using the available storage mods which just was no fun.
So I've none of the files anymore they're completely gone

**Comment by Raidobw2** [comment] 2022-08-26 03:01
No problem, thanks for getting back to me. I'll see again if I can reproduce it with a different in-game setup and then reply to the author of the mod

**Comment by Saereth** [comment] 2023-02-05 21:37
Since we've had no further luck reproducing this and most mods are updated for 2.0 coming out, I'm closing this.

**Closed by Saereth** 2023-02-05 21:37 UTC
Labels: 1: Mod Issue, FTB One
