### ISSUE TITLE
[Bug]: Krate hopper and compacting upgrade causing compacted chunks to disappear when using a filter

### ISSUE THREAD

**Issue by Aberranthian** [FTBTeam/FTB-Modpack-Issues#339] opened 2021-11-19 12:45 UTC
### Modpack

FTB OceanBlock

### Modpack version

1.8.0, 1.9.0

### Describe the bug

I have the output from a sluice (chunks of ore etc...) in a chest. I'm using a krate next to the chest with a hopper upgrade as well as a compacting upgrade. After setting up the filters, the krate pulls in the ore chunks (according to the filter placed on the input) and once it gets to 4 it compresses them down but instead of getting a cluster back, it just disappears. 
TLDR: Krate is eating the stuff it compacts when a hopper and compacting upgrade are used together and a filter is set.

### Steps to reproduce

1. Place chest with ore chunks in it.
2. Place a krate next to the chest with a hopper upgrade and a compacting upgrade set to 2x2 compacting.
3. Place a filter in the input side filter slot that has the items whitelisted that you want the krate to pull.
4. Set the krate to take input from the chest.

### Expected behaviour

The krate should compress the chunks into clusters for me to use

**Comment by xdarkxtriviumx** [comment] 2021-11-19 13:07
After further testing, it seems like the bug only presents itself when using a filter in conjunction with the two upgrades. I will update the bug report to reflect the inclusion of the filter

**Comment by Warzer1** [comment] 2021-11-19 17:04
I had seen this issue as well.  Was using a storage drawer above the krate with filter, hopper and compacting upgrades.  Hopper configured to export top compressed sand.  it would compact then vanish instead of exporting to the drawer.  With some tweaking I did get it to work.  it was something about slot 1 that kept deleting the block.when it was compacting not in slot one it seems to have worked as expected.

**Comment by xdarkxtriviumx** [comment] 2021-11-19 17:57
> I had seen this issue as well. Was using a storage drawer above the krate with filter, hopper and compacting upgrades. Hopper configured to export top compressed sand. it would compact then vanish instead of exporting to the drawer. With some tweaking I did get it to work. it was something about slot 1 that kept deleting the block.when it was compacting not in slot one it seems to have worked as expected.

I ended up getting around the issue by using the Pipez mod for transferring the items into the krate with just a compacting upgrade, and using another pipe for exporting when compacting is finished. (In case anyone needs a temporary work-around). The downside is that the upgrade necessary for a whitelisted pipe export uses diamonds, so you need to have progressed far enough to have them available.

**Comment by JeffBittle** [comment] 2021-11-22 21:59
I luckily noticed this when I was in a creative world designing a way to auto-compact my sluice resources, so I didn't lose any actual material.  I think the issue is in how the mod handles its filters, the description claims that the filter determines what is allowed to be moved into or out of the krate.  What it actually seems to do is to determine what items are allowed to exist in the krate at all, which is similar, but not _quite_ the same thing.  If you're whitelisting the resource chunks so they're allowed into a 2x2 compacting upgraded krate, they come in, the compacting happens, but then the resulting cluster is not in the filter, so it isn't allowed to be in the krate so it just ceases to exist.

I ended up finding a slightly cheaper workaround than the above, although the compacting upgrade itself already takes diamonds so you need to have progressed that far either way.  First, I had my iron+ sluices each exporting into their own inventory, it doesn't matter what, but I used the smallest krates.  I then used item Pipez to pull all items from those inventories to deposit them into 3 different krates which each had a filter, one for all the 2x2 compactables, one for all the 3x3 compactables and one for the non-compactables.  The non-compactables krate was done, but the other two then had an additional, unfiltered, krate next to it which had a hopper upgrade and a compacting upgrade in it.  The hopper was configured to auto-pull items from the krate next to it and the compacting was set appropriately, one for the 2x2 stuff and one for the 3x3 stuff.  Then, I setup filters for the finished compacted products and on those same krates I configured an additional hopper side to auto-push items to another inventory with those filters installed on only the output, just to separate the final product from the partial chunks and such that would be sitting in the compacting krates.  That allows me to then pipe only the finished products out of the last inventory to be stored or processed, without any additional filtering.

So, it's a little tricky, but definitely doable.  I also realized after getting it worked out that the 3x3 compacting is probably not that useful since you could just take the stuff that would need to be 3x3 compacted and immediately pipe it into a compacting drawer setup to have it done automatically.  But it could be useful if you aren't using drawers, which at the time I hadn't gotten a whole drawer system set up yet.

**Comment by Sunekaer** [comment] 2021-12-05 15:08
https://github.com/owmii/krate/issues/18

**Closed** 2024-06-04 15:50 UTC
Labels: FTB OceanBlock, state: Awaiting Mod Update
