### ISSUE TITLE
Open to Lan server causes clients to get connection lost failed to encode packet error

### ISSUE THREAD

**Issue by psykoloGG** [FTBTeam/FTB-Modpack-Issues#6207] opened 2024-11-17 00:55 UTC
### Modpack

FTB Evolution

### Modpack version

1.3.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

On one computer start the world and open to LAN.
On another when connecting getting the error connection lost failed to encode packet.

Modpack was not modified in any way.

### Steps to reproduce

1. Create world
2. Open to LAN
3. (On another computer) Connect trough server browser

### Expected behaviour

connection lost failed to encode packet

**Comment by Gaz492** [comment] 2024-11-18 07:29
Duplicate of #6061

**Closed by Gaz492** 2024-11-18 07:29 UTC
Labels: Bug, FTB Evolution
