### ISSUE TITLE
[Suggestion]: Give lava egg more uses and make it basically a lava bucket

### ISSUE THREAD

**Issue by IThundxr** [FTBTeam/FTB-Modpack-Issues#1877] opened 2022-11-11 21:23 UTC
### Modpack

FTB StoneBlock 3

### Is your suggestion related to a problem? Please describe.

Basically lava egg being a lava bucket would be very nice since we wont need to make lava bucket

### Mod suggestion

Basically make the lava egg a valid furnace fuel item and change recipes using lava buckets to use a tag which has both lava bucket and lava egg

**Comment by Sunekaer** [comment] 2022-11-13 18:24
Duplicate of #1848

**Closed by Sunekaer** 2022-11-13 18:24 UTC
Labels: 2: Enhancement, FTB StoneBlock 3
