### ISSUE TITLE
Cannot load modpack anymore

### ISSUE THREAD

**Issue by snicoara** [FTBTeam/FTB-Modpack-Issues#2269] opened 2022-12-09 05:05 UTC
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.2

### Log Files

[crash-2022-12-09_15.59.30-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10191893/crash-2022-12-09_15.59.30-client.txt)

### Describe the bug

Only started today - unable to launch the modpack. Have tried deleting the pack and reinstalling twice, exactly the same error occurs. I've made no changes to the pack.

### Steps to reproduce

1. Launch modpack

### Expected behaviour

Expected to launch the modpack without error

**Comment by s-thomae** [comment] 2022-12-09 06:02
After client side removal of "Better With Llamas" and Better with Rabbits" the Pack loaded again. (Server was untouched)

My Log File Hinted at the Llama-Mod, and i haven't seen a Rabbit in stoneblock for ever.

**Comment by hgjensen** [comment] 2022-12-09 07:02
> After client side removal of "Better With Llamas" and Better with Rabbits" the Pack loaded again. (Server was untouched)
> 
> My Log File Hinted at the Llama-Mod, and i haven't seen a Rabbit in stoneblock for ever.

Had same issue today. Can confirm the game can boot when removing "BetterThan*.jar".
Attached crashlog

[crash-2022-12-09_07.56.52-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10192529/crash-2022-12-09_07.56.52-client.txt)

**Comment by hgjensen** [comment] 2022-12-09 07:07
> > After client side removal of "Better With Llamas" and Better with Rabbits" the Pack loaded again. (Server was untouched)
> > My Log File Hinted at the Llama-Mod, and i haven't seen a Rabbit in stoneblock for ever.
> 
> Had same issue today. Can confirm the game can boot when removing "BetterThan*.jar". Attached crashlog
> 
> [crash-2022-12-09_07.56.52-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10192529/crash-2022-12-09_07.56.52-client.txt)

See this related issue - it's probably the same issue.
[https://github.com/iChun/BetterThanLlamas/issues/3](https://github.com/iChun/BetterThanLlamas/issues/3)

**Comment by Bendder** [comment] 2022-12-09 12:03
I'm having the same issue.. : [https://paste.atlauncher.com/view/82e01476-48e2-4a00-9588-272300a06a0f](url)

**Comment by NordicGamerFE** [comment] 2022-12-09 12:11
If you are having this issue a full guide how to fix it can be found at #2278

**Comment by manmaed** [comment] 2022-12-09 12:38
The issue is fixed in [1.4.3](https://feed-the-beast.com/modpack/100_ftb_stoneblock_3) of Stoneblock 3

**Comment by manmaed** [comment] 2022-12-09 13:09
This issue is fixed in [1.10.3](https://feed-the-beast.com/modpack/95_ftb_presents_direwolf20_1_18) of Direwolf20 1.18

**Comment by ZEYDEN88** [comment] 2022-12-09 16:32
bonjour, est-ce que le problème va être résolue pour la 1.8 ? car même problème pour moi et mon frère qui jouons sur deux ordinateur diffèrent

**Comment by manmaed** [comment] 2022-12-09 16:39
> bonjour, est-ce que le problème va être résolue pour la 1.8 ? car même problème pour moi et mon frère qui jouons sur deux ordinateur diffèrent

direwolf20 et stoneblock 3 ont été corrigés

**Comment by ZEYDEN88** [comment] 2022-12-09 16:40
étrange, sur direwolf20 1.18 version 1.10.3 ça fonctionne bien mais plus sur la version direwolf 1.18 version 1.8.0

**Closed** 2022-12-10 18:24 UTC
Labels: 1: Mod Issue, state: Fixed :heavy_check_mark:, prio: Critical :skull:, FTB Presents Direwolf20 1.18, FTB StoneBlock 3
