### ISSUE TITLE
[Bug]: Crash with Enchantment Library

### ISSUE THREAD

**Issue by LaboePlay** [FTBTeam/FTB-Modpack-Issues#1438] opened 2022-10-14 19:56 UTC
### Modpack

FTB Inferno

### Modpack version

1.0.3

### Describe the bug

Enchantment Library when place some items in it cause game crash I'm not sure what else items can cause crash after it crashed 2 times i stopped using it.

### Steps to reproduce

1. Open library gui.
2. place drill in it
3. Game crash

### Expected behaviour

It's feature to see what enchantments can add in that specific item.

### Screenshots

![game crashed](https://user-images.githubusercontent.com/115666782/195931172-edfa020f-be06-4fc6-b5ac-0949adb3aa1b.png)

**Comment by Saereth** [comment] 2022-10-14 19:59
Need crash logs please

**Comment by LaboePlay** [comment] 2022-10-14 20:02
[crash-2022-10-14_23.00.50-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9789718/crash-2022-10-14_23.00.50-client.txt)
[crash-2022-10-14_22.41.52-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9789720/crash-2022-10-14_22.41.52-client.txt)

**Comment by Saereth** [comment] 2022-10-14 20:06
opened an issue with the mod dev
https://github.com/Shadows-of-Fire/Apotheosis/issues/675

**Comment by Saereth** [comment] 2022-10-14 20:41
can you show me what all enchantments you have in your library please? having difficulty reproducing this even with an exact copy of that drill

**Comment by LaboePlay** [comment] 2022-10-15 06:42
> can you show me what all enchantments you have in your library please? having difficulty reproducing this even with an exact copy of that drill

aqua affinity, backstabbing, bane of arthropods, bane of illagers, blast protection, bullseye
,capacity, capturing, channeling, cromatic aberration, curse of binding, curse of breaking, curse of vanishing, curse of vengeance, depth strider, double jump, efficiency, feather falling, fire aspect, fire protection, flame, fortune, frost walker, holding, icy thorns, impact, impaling, infinity, knockback, lavawaxed, life stealing, looting, loyalty, luck of sea, lure, mana boost, mana regen, mending, miner's fervor, multishot, nature's blessing, nature's mend, obliteration, piercing, poison tip, potato recovery, power, preserving, projectile protection, protection, punch, quick charge, range, rebounding, recall, reflective defences, respiration, returning board, riptide, serpent charmer, severing, sharpness, shield bash, sleight of hand, sliding, smite, soul stealer, spearfishing, splitting, stable footing, straddle jump, sweeping edge, teleportation, temptation, unbreaking, unusing and wall running

**Comment by Saereth** [comment] 2022-10-15 11:55
I put everysingle enchant in the pack in mine with the same drill and I still cant reproduce this yet on the dev build. That being said my dev build has the latest release of apoth so it may be fixed. Let me know if you encounter this after 1.0.4 comes out

**Comment by Saereth** [comment] 2022-10-15 18:11
I still cant reproduce this, could you possible send me a zip of your world save to test myself?

**Comment by LaboePlay** [comment] 2022-10-15 18:38
> I still cant reproduce this, could you possible send me a zip of your world save to test myself?

I'm not sure where to upload 762000 byte zip save file?

**Comment by Saereth** [comment] 2022-10-15 18:41
google drive or drop box link would be fine

**Comment by Saereth** [comment] 2022-10-15 18:41
I'll need the coordinates of your enchanting library as well

**Comment by LaboePlay** [comment] 2022-10-15 19:04
**https://drive.google.com/file/d/1fOBelHgUMTBx60MTpaDLLvMiX54oFp6x/view?usp=sharing**
Coordinates to library is 277,129,5385
Also i just tested my new drill and it crash game too
![newdrill](https://user-images.githubusercontent.com/115666782/196003699-cd3bf7f5-1b9e-4d19-9737-a5240b0dc4ca.png)

**Comment by Saereth** [comment] 2022-10-16 17:07
ok I cant reproduce this with your save in my dev world so I suspect one of the mods I updated for 1.0.4 fixes it. Going to mark fixed in dev, if you run into this again after 1.0.4 comes out let me know

**Closed** 2022-10-26 21:46 UTC
Labels: 1: Mod Issue, state: Fixed in Dev :hammer_and_wrench:, FTB Inferno

**Comment by Pumbar** [comment] 2022-10-31 12:35
Had same problem, took enchants out of the library one by one and ended up with Recall.
Others (that I have so far) seems to work.
