### ISSUE TITLE
[Bug]: Simply backpacks hotkey does not work

### ISSUE THREAD

**Issue by zhongjiedong** [FTBTeam/FTB-Modpack-Issues#566] opened 2022-01-16 15:05 UTC
### Modpack

Oceanblock

### Modpack version

1.11

### Describe the bug

Whatever hotkey i set the common backpack will not open. I have not yet tried with another one

### Steps to reproduce

try opening the backpack using any hotkey

### Expected behaviour

backpack should open

**Comment by Raidobw2** [comment] 2022-01-20 02:37
Hi, have you checked in your keybinds that you don't have a conflict for that backpack key? Sometimes keybind conflicts will cause some things to fail, check it out and let me know!
To unbind something you click on it once then press the Escape key, it will unbind it.

**Comment by zhongjiedong** [comment] 2022-01-20 08:29
I figured it out, you have to manually open the backpack at least once by putting it on your hotbar and right clicking before the hotkey will work.

**Comment by MichaelHillcox** [comment] 2022-01-20 11:43
@Flanks255

**Comment by Flanks255** [comment] 2022-01-20 21:38
Not really a bug persay, as it was the intended behavior with the new system out of caution, but i think since the chances of you having an unmigrated v1 backpack anymore are fairly slim ill change this soon so the hotkey will open even uninitialized backpacks.

**Comment by Raidobw2** [comment] 2022-01-21 02:51
Thanks Flanks

**Closed** 2022-03-27 11:01 UTC
Labels: FTB OceanBlock, 1: Mod Issue, state: Fixed in Dev :hammer_and_wrench:
