### ISSUE TITLE
[Suggestion]: ExtraStorage

### ISSUE THREAD

**Issue by justinpierson** [FTBTeam/FTB-Modpack-Issues#1970] opened 2022-11-15 10:07 UTC
### Modpack

Stoneblock 3

### Is your suggestion related to a problem? Please describe.

I have always liked having more crafters!

### Mod suggestion

Extrastorage:
https://www.curseforge.com/minecraft/mc-mods/extrastorage

**Comment by Sunekaer** [comment] 2022-11-15 11:55
Duplicate of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1599

**Closed by Sunekaer** 2022-11-15 11:55 UTC
