### ISSUE TITLE
[Bug]: SB3 Crash while selecting energy condenser category in REI

### ISSUE THREAD

**Issue by AWDoBaun** [FTBTeam/FTB-Modpack-Issues#1764] opened 2022-11-08 15:03 UTC
### Modpack

FTB StoneBlock 3

### Modpack version

1.1.0

### Describe the bug

While scrolling through the list of all recipes in REI i came to the recipes for the AE2 Matter Condenser

### Steps to reproduce

search REI for Inscriber
type "u" for uses - REI starts on the crafting tab for the recipe that uses the inscriber
click on the first inscriber tab and see recipes that can be made in the inscriber
click on the word "Inscriber" (tooltip: View All Categories) under that tab to see all recipes starting with focus on the inscriber recipes.
![image](https://user-images.githubusercontent.com/12954977/200599232-c00df6d1-f05e-4aec-9e85-4d27506d1f78.png)
Click the "Matter Condenser" to the left of the Inscriber -> crash game
[crash-2022-11-08_07.41.06-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9962414/crash-2022-11-08_07.41.06-client.txt)

### Expected behaviour

no crash, see what can be condensed

**Comment by Sunekaer** [comment] 2022-11-08 15:40
Duplicate of  #1719

**Closed by Sunekaer** 2022-11-08 15:40 UTC
