### ISSUE TITLE
NeoTech Immersive Engineering Coke Brick missing recipe

### ISSUE THREAD

**Issue by BroderBrago** [FTBTeam/FTB-Modpack-Issues#5468] opened 2024-07-11 15:23 UTC
### Modpack

FTB NeoTech

### Modpack version

1.4.0

### Has the pack been modified

No

### Describe the bug

Immersive Engineering Coke Brick, used to construct the Immersive Engineering Coke Oven does not have a producible recipe. Recipe should, after looking at the Immersive Engineering Wiki consist of Sandstone, Clay, and Brick. Currently only shows recipe using coke brick slabs, which in themselves are only craftable using coke brick.

### Steps to reproduce

1. Open EMI
2. Search for Immersive Engineering's Coke Brick
3. Look at lack of recipe

### Expected behaviour

Recipe for coke brick based on sandstone, clay and brick

### Screenshots

Screenshot of EMI crafting recipe with only 1 crafting option.
![Screenshot 2024-07-11 172134](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/175332152/6c51f31e-9ec5-4810-b9d0-0cf6974811bb)

### Additional information

Tried ./reload command and rebooting instance without success

**Comment by Gaz492** [comment] 2024-07-11 15:41
Duplicate of #5467 which has been fixed in dev and pending a release

**Closed by Gaz492** 2024-07-11 15:41 UTC
Labels: Bug, FTB NeoTech
