### ISSUE TITLE
[Bug]: FTB Oceanblock Honey and Quantum ring issues

### ISSUE THREAD

**Issue by TheDireWolf13** [FTBTeam/FTB-Modpack-Issues#113] opened 2021-10-11 01:52 UTC
### Modpack

FTB OceanBlock

### Modpack version

1.2.0

### Describe the bug

Unable to get honey due to lack of bees and no drops listed in crates, barrels, etc. Unable to make honey seeds.

Quantum ring issues with making quantum singularity. When dropped with ender dust and exploded doesn'n give quantum singularity just basic singularity back.

### Steps to reproduce

check jei for honey and nothing shows up for rewards.

Quantum Singularity:
1.throw down ender dust and singularity
2. place and light tnt within range
3. grab the drop and its a basic singularity again not a quantum one.

### Expected behaviour

hopeful update or addition.

**Comment by Sunekaer** [comment] 2021-10-11 11:39
Bees can spawn when growing trees, this is vanilla MC behaviour.
The Quantum Singularity is a duplicate of #64

**Closed as completed by Sunekaer** 2021-10-11 11:39 UTC
