### ISSUE TITLE
Unable to launch Stoneblock 3

### ISSUE THREAD

**Issue by Spacemoney21** [FTBTeam/FTB-Modpack-Issues#2681] opened 2023-02-08 01:04 UTC
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Describe the bug

Unable lo launch the game at al because of said issue I've tried using earlier versions along with uninstalling yet nothing has worked

### Steps to reproduce

Go to StoneBlock 3 instance.
launch game.
Crashes.

### Expected behaviour

Game to Launch 

### Screenshots

![Screenshot 2023-02-07 200042](https://user-images.githubusercontent.com/124747609/217402088-a9a3ab25-9f22-4fa4-b3ef-e73b0749b9df.png)

**Comment by RebelRK99** [comment] 2023-02-09 07:45
I'm also having this issue

**Comment by MichaelHillcox** [comment] 2023-04-02 11:59
Duplicate of #2679 please comment there if this is still an issue for you.

**Closed by MichaelHillcox** 2023-04-02 11:59 UTC
Labels: FTB StoneBlock 3
