### ISSUE TITLE
[Bug]: Particles flash when breaking blocks

### ISSUE THREAD

**Issue by kalisture** [FTBTeam/FTB-Modpack-Issues#1445] opened 2022-10-15 23:33 UTC
### Modpack

Inferno

### Modpack version

1.0.3

### Describe the bug

When breaking blocks, and collecting said block, are particles flash black. Have seen issue posted elsewhere.|
Graphics drivers are up to date.

### Steps to reproduce

1. Break a block
2. Collect pickup while particles are out
3. Particles flash black

### Expected behaviour

Particles don't flash black

**Comment by Raidobw2** [comment] 2022-10-16 01:24
Hi, can you check in Task Manager which of your GPU is being used to play the game? Also, do you happen to have a screenshot or recording of the odd particle flashing?

**Comment by Saereth** [comment] 2022-11-09 21:38
no followup on this for almost a month, closing as no reponse and unable to reproduce

**Closed by Saereth** 2022-11-09 21:38 UTC
Labels: state: Awaiting Reply :speaking_head:, 3: Support Request, FTB Inferno

**Comment by northmatt** [comment] 2022-12-09 21:18
I do have a similar issue with Inferno. However it isnt much to do with breaking blocks, just starts to "randomly" happen.

Particles will start to render overtop of everything (ignores depth buffer?) apart from GUI. They will not be lit and render as completely blacked out. The flashes will only last for 0.1s - 0.3s at a time. The flashes typically happen every 1s - 15s. It has sometimes fixed itself after 10 - 15 minutes. While I havent tested with all settings it still seems to happen no matter what option each setting is at (ex: with/without shaders, min/all particles).

I have only managed to fix it once by randomly turning on/off my shaders. Otherwise only other fix I know is relaunching the game. 

Have a 5600X CPU, x570 TUF Plus (BIOS 4403, Chipset Driver 4.08.09.2337) Motherboard, 2x16GB 3600-14-14-14-32 Memory, RTX 3080 10GB (Asus TUF VBIOS 94.02.42.40.66, Graphics Driver 517.48) GPU, and Windows 10 (Version 10.0.19043, Build 19043) OS.

I can open a new issue if it helps.
