### ISSUE TITLE
[Bug]: Updates to new profile 

### ISSUE THREAD

**Issue by IamStig** [FTBTeam/FTB-Modpack-Issues#1018] opened 2022-06-24 00:44 UTC
### Modpack

Direwolf20

### Modpack version

1.18.2

### Describe the bug

Prior to 1.5 pack update the pack actually updated the existing profile, now on 1.5 and 1.6 it has created a new profile. I have tried multiple times to update but can see any way to force it to update the profile. I can't find a setting to tell the app to do an update, or a fresh install for that matter. It may seem trivial....just copy over the world save.....and the Sound muffler settings....and the keybind settings.....and the waypoint files......and the map display files (didn't work that one out a week ago when I had the same problem on 1.5)
I know there are others that are NOT having this issue .....but I am and I think this will be my last FTB app modpack if I can't get a solution.... it just isn't worth the frustration.

### Steps to reproduce

Can't tell you how to reproduce the steps I do to have this problem are-
1 Click on "update available"....blue banner just above the FTB presents that changes to green Play button on hover
2 Click "Versions"
3 Select/highlight the latest version
4 Click "Update"
5 Start the pack to see that there is not a current save game and I will have hours of working out how to get back some of the lost information instead of hour of playing and days of "can't be bothered with this crap I might just watch TV or find a non FTB pack to play"

### Expected behaviour

When I click update it actually updates the profile and I can just play it from where I left of with no loss of saved data, time or motivation

### Additional information

I have app version 202206081143-2e021f8e74-release. Is that the latest? Is there an option anywhere in the app to update the app? Can you add a screen that pops up after clicking update that asks "Do you wan't to update to a new profile" with a check box (that is not saved and always starts empty), maybe an explanation that no player data including saved games will be transferred and then another update button.

**Comment by Raidobw2** [comment] 2022-06-28 00:15
Hello, sorry that's a bug with the app and developers have become aware of it recently.
You can copy those folders/files from an old direwolf20 profile into your new profile to retain some configuration:
`local` - holds your minimap data from FTB Chunks and your waypoints
`saves` - holds your worlds
`servers.dat` - holds your known servers in the multiplayer menu
`options.txt` - holds your keybinds and settings

`resourcepacks` - holds any resourcepacks you have (also called texture packs)
`shaderpacks` - holds your shaders, if you have any with Optifine/Oculus

**Comment by IamStig** [comment] 2022-07-12 10:08
You say it is "completed"....I just tried to update DW20 pack from version 1.5.1 to 1.7.0, I first restarted the app expecting it to tell me IT was updating.... it did not. I went ahead with the pack "update" .... it didn't.
How is this "completed"

**Comment by TheonlyTazz** [comment] 2022-07-12 10:12
I am sorry for having the Issue closed, i have tried updating my 1.4.0 instance earlier on my instance without any issues and assumed this issue got fixed. Guess this has to go to the FTBApp issue then

**Comment by IamStig** [comment] 2022-07-12 10:25
Yeah mate I got a message from R3GEN back on 28/6 saying it was an App issue "sorry that's a bug with the app and developers have become aware"..... not sure why it isn't shown here. Given it is only 2 week I am not surprised it is not fixed yet tbh I think the app needs a rework.....be nice if there was a version shown somewhere AND an app update/check path. I will likely be done with the pack before a resolution is pushed.

**Comment by Raidobw2** [comment] 2022-07-12 22:48
Hello @IamStig, my last message contained some information to move over data from a previous profile to a new profile. Did that help?

Just to make sure I'm understanding the issue correctly, updating the modpack created a new profile for you? I have to assume this profile did not contain your save, so you had to refer to my message to get your save back. The video Tazz posted explains what the issue is, which is indeed an app bug.

All we can do here is teach you how to transfer saves and data between profiles, the app issue is taken in charge by other developers since we mostly work on modpacks (here is the modpack tracker).

**Comment by Raidobw2** [comment] 2022-07-13 02:20
I'll add more information onto the issue reported to our app team, thanks.

As this seems to be resolved for you for now and your game is working again, I'll be closing this. Let us know in the future if you encounter any more issues, and have fun playing! :)

**Closed by Raidobw2** 2022-07-13 02:20 UTC
Labels: 3: Support Request, FTB Presents Direwolf20 1.18
