### ISSUE TITLE
[Bug, RoadRunner]: FTB Oceanblock 1.2.0 Crash to desktop up TP between Dims / Chunks

### ISSUE THREAD

**Issue by 2ndRecon** [FTBTeam/FTB-Modpack-Issues#78] opened 2021-10-04 12:37 UTC
### Modpack

Oceanblock

### Modpack version

1.2.0

### Log Files

Crash 1 (after player sleeping)
https://pastebin.com/ZHfdNrb8

Crash 2 (When TP'ing between chunks or from Nether to Overworld)

https://pastebin.com/Bz7wXvKF

### Describe the bug

Since upgrading to Oceanblock ver. 1.2.x we are now seeing random client C2D with corresponding server process Halt.

I have included pastebins of the corresponding crashes and happy to provide more information as needed.

I am running other 36.2.2 based packs including the previous versions of this pack and had no similar issues with C2D of the client with a corresponding server halt.
(i mention forge version because I noted in the patch you went from Forge 36.2.2. to 36.2.4 as well) 

**_**In the future please include this callout in the patch / release notes as a changing forge version can be significant for server ops._**

Server is Ubuntu 20.04.3 LTS
Client is Windows 10
Native Launcher (FTB App)

// - Note: Other clients have C2D as well, both on Win 10 and FTB App

Here is also a snap from the latest.log for the server, showing the exception which appears to have triggered the FE_Halt.

https://pastebin.com/W7NgwJna

Hope this helps. 

### Steps to reproduce

Indeterminant

Be an OP player.
TP between Dims or Player Bases in different Chunks
Intermittent C2D w/ accompanying server halt. 

### Expected behaviour

Expected behavior is as before on 1.1.x w/ Forge 36.2.2 = No crashes

**Comment by Raidobw2** [comment] 2021-10-06 08:35
@2ndRecon Sorry for the late reply, just saw.
The first crash is due to RoadRunner (RoadRunner-mc1.16.5-1.1.1.jar), a fork of Lithium. Only present on server side. There is a notice at the bottom of the crash: "RoadRunner != Lithium: This instance was launched using RoadRunner, which is an *unofficial* Lithium fork! Please **do not** report bugs to them!"

Fortunately the author of that mod is on our team so i'll have him see this if appropriate.
If it causes other problems for the time being, remove that optimization mod from the server to prevent additional crashes.

The second crash goes like this: 
```
Stacktrace:
        at net.minecraft.server.dedicated.ServerHangWatchdog.run(ServerHangWatchdog.java:43) [?:?] {re:classloading}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241] {}
```

Which was caused by the watchdog thread. This is usually a failsafe thread which shuts down the server if it's experiencing a lot of lag. You can disable it in server.properties, by setting `max-tick-time=-1`. This watchdog thread is used on bigger servers where hardware issues need to be addressed quickly, on small servers or with bad hardware, it is generally not needed.


**For Sunekaer**:
RoadRunner needs one of 2 things it looks like: Remove from server pack or have it fixed by Max.
Fixing it will be the preferred solution, but i'll leave the decision to you, we've only had this one crash logged so far.
Also they left a message:
"In the future please include this callout in the patch / release notes as a changing forge version can be significant for server ops." => Talking about Forge version changes on changelogs.

I haven't made the issue on Max's tracker yet, Sune (Mod Issues). Ping me if you want one, that's stuff i can do.

**Comment by Sunekaer** [comment] 2021-10-06 14:09
https://github.com/MaxNeedsSnacks/roadrunner/issues/12

**Comment by Sunekaer** [comment] 2021-12-05 13:22
Closing issue as a workaround was implemented in an earlier version of the pack.

**Closed by Sunekaer** 2021-12-05 13:22 UTC
Labels: FTB OceanBlock, cat: Bug, des: Mod Issue, state: Awaiting Mod Update
