### ISSUE TITLE
[Bug]: Client keeps crashing at startup

### ISSUE THREAD

**Issue by MishaczeQ** [FTBTeam/FTB-Modpack-Issues#1612] opened 2022-11-03 21:12 UTC
### Modpack

Stoneblock 3

### Modpack version

1.0.2

### Log Files

https://pastebin.com/erkRevv0

### Describe the bug

I run the game one time, changed key-mapping for REI "use" and "recipe", closed the game.
Since then game crashes every time when I try to start it. 
Restarting FTB-App / Overwolf / PC itself doesn't help.

### Steps to reproduce

1. Start the game
2. Change keybinds for REI use: ".", recipe ","
3. Close the game
4. Start the game

### Expected behaviour

Launching the instance

**Comment by Sunekaer** [comment] 2022-11-05 17:06
duplicate of  #1597

**Closed by Sunekaer** 2022-11-05 17:06 UTC
Labels: 1: Mod Issue, FTB StoneBlock 3
