### ISSUE TITLE
client-specific classes trying to load into server-only environments

### ISSUE THREAD

**Issue by lazycooken** [FTBTeam/FTB-Modpack-Issues#5751] opened 2024-09-12 00:13 UTC
### Modpack

FTB Unstable 1.21

### Modpack version

1.20

### Launcher

Server

### Has the pack been modified

No

### Log Files

[latest.log](https://github.com/user-attachments/files/16971641/latest.log)

### Describe the bug

When running the Minecraft server with NeoForge and installed mods, the server attempts to load a client-side class (net.minecraft.client.resources.model.ModelBakery$ModelBakerImpl) on a dedicated server, causing the following error:

### Steps to reproduce

Install the mod on a dedicated server.
Start the server.
Observe the error during the startup process.

### Expected behaviour

Client-only classes should not be loaded on a dedicated server. Mods should properly separate client-side and server-side functionality.

**Comment by Gaz492** [comment] 2024-09-12 12:39
The issue which was causing the unstable server to not start should be fixed now which was caused by entity model renderer and health indicators

The additional messages saying something tried to load a client only class can safely be ignored and is a mod specific issue, but shouldn't cause any further issues other than displaying a warning message while the server starts up.

**Closed by Gaz492** 2024-09-12 12:39 UTC
Labels: FTB Unstable 1.21
