### ISSUE TITLE
[Bug]: lossing item of the interaction of blood magic and trinkets mods

### ISSUE THREAD

**Issue by smig00** [FTBTeam/FTB-Modpack-Issues#326] opened 2021-11-17 04:29 UTC
### Modpack

Ftb Oceanblock

### Modpack version

1.8.0

### Describe the bug

when dying from a blood sacrifice and you have a broken totem trinket activated when you die you lose all the items in your inventory with no gravestone or gravestone log

### Steps to reproduce

broken totem trinket
dying by sacrifice with blood magic

### Expected behaviour

losing items withouth a gravestone ore gravestone log

**Comment by Raidobw2** [comment] 2021-11-17 06:20
Could be linked to WayofTime/BloodMagic#1861 and #156.

To be investigated.

**Comment by Sunekaer** [comment] 2021-11-18 12:55
Yeah sounds like duplicate of 156.

**Closed by Sunekaer** 2021-11-18 12:55 UTC
Labels: FTB OceanBlock, cat: Bug, des: Mod Issue, prio: Low :sunrise_over_mountains:
