### ISSUE TITLE
[Bug]: Instant crash when joining server

### ISSUE THREAD

**Issue by DanJHawes** [FTBTeam/FTB-Modpack-Issues#1333] opened 2022-09-18 06:05 UTC
### Modpack

FTB One

### Modpack version

1.3.0

### Log Files

https://pste.ch/utonihudop

### Describe the bug

When attempting to join any FTB One server, the instance will load the terrain and then instantly save the world and crash.

https://user-images.githubusercontent.com/84057351/190888076-f167fb22-b190-4fb1-a9dd-e8f6d857f86d.mp4

### Steps to reproduce

1. Launch FTB App
2. Install FTB One 1.3.0
3. Once Installed, click "Play"
4. Once the FTB One instance of launched, click "Multiplayer"
5. Direct Connect to a FTB One server (A list can be found here: https://forum.feed-the-beast.com/servers/categories/ftb-one.86/) 
6. The instance will get to the "Loading Terrain" screen and audio may start playing from inside the server, but it will then show a "Saving World" screen and crash the instance.

### Expected behaviour

You join the server and don't crash

### Additional information

I've had this occur on 3 different computers (1x windows 11, 2x windows 10)
I've reinstalled the FTB App
I've reinstalled the FTB One app
I've reinstalled the latest Java version
I've tried this with 3 different FTB servers (2 from the list linked above, 1 private server)

Lastest log and the crash report from the minecraft instance is attached
[crash-2022-09-20_19.27.18-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9606629/crash-2022-09-20_19.27.18-client.txt)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9606630/latest.log)

**Comment by Raidobw2** [comment] 2022-09-18 21:05
Is there a crash log created in the `crash-reports` folder or can you post your latest.log from the `logs` folder? Both these I am referring to are logs from the minecraft game and not the ftb app

**Comment by DanJHawes** [comment] 2022-09-20 09:33
> Is there a crash log created in the `crash-reports` folder or can you post your latest.log from the `logs` folder? Both these I am referring to are logs from the minecraft game and not the ftb app


I've attached the crash report .txt as well as the latest log that was generated alongside it. To a man who's never read a MC crash report before, it looks like the game is crashing when attempting to render a roost from the chickens mod, but this could be a red herring. 

[crash-2022-09-20_19.27.18-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9606162/crash-2022-09-20_19.27.18-client.txt)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9606185/latest.log)

**Comment by DanJHawes** [comment] 2022-09-20 10:18
If it does happen to be the chickens mod, the night of the first crash I got I had actually placed ~14 roosts down and filled them with chickens. I then connected these roosts with pipes. I had roosts in the world earlier that caused no issue. But these were the first I had connected pipes to

**Comment by Raidobw2** [comment] 2022-09-21 08:17
The crash helped! That looks exactly like https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1098.

The solution for the future would be to always empty the roosts with cables (prevent overflowing as well, make sure there's always enough storage), this would prevent any issues when removing the chickens until FTB One is updated again.

If you can't load in your world right now, enter your `saves` folder, open `ClientLevel/region` and locate `r.0.0.mca`. Copy this file to your desktop and rename it `r.0.0.mca.txt` and then drag it here in the window, it'll upload it.
I'll fix that file for you and you'll simply need to remove the `.txt` from the name and place it back into the `region` folder once I give it back.

**Comment by DanJHawes** [comment] 2022-09-22 05:04
Thank you, I've attached the r.0.0.mca(.txt) file to this comment. I've had a look at the linked ticket (#1098) and from what I understand it's caused by non-chickens items being placed in the roosts via pipes \ hoppers. Am I safe to assume that I can avoid this in the future by making sure the pipes are set to remove blocks and not pipe into the roosts ? 
[r.0.0.mca.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9622325/r.0.0.mca.txt)

**Comment by Raidobw2** [comment] 2022-09-22 05:18
Yup, that would take care of it normally. Always empty the roosts of their blocks. I should have fixed it here, let me know if that works. You just have to delete the old region file and replace it with this one, and make sure to remove the `.txt` before trying it out.
All I did was remove the block entity Roost at coordinates (125x, 54y, 0z), so let me know if that loads up properly and everything works. It had 16 sand in it, that's all there was in it.
[r.0.0.mca.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9622415/r.0.0.mca.txt)

**Comment by DanJHawes** [comment] 2022-09-22 05:50
Hi Raidobw2, I've tried it out and it looks to still be crashing. I did have a handful of roosts with chickens in them connected to the pipes so this might be causing it. I've attached the latest .MCA.txt file as well. I'd be happy to do the editing myself but I'm not sure how to open \ edit the .MCA file and my Java might be a bit rusty


[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9622579/latest.log)
[crash-2022-09-22_15.44.33-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9622583/crash-2022-09-22_15.44.33-client.txt)
[r.0.0.mca.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9622590/r.0.0.mca.txt)

**Comment by Raidobw2** [comment] 2022-09-22 07:32
I see what the issue is now, there's multiple of the roost causing problems. I've fixed this one by removing all roosts in that specified chunk. I loaded in-game and got to the specified coordinates no problem, so that should work.
[r.0.0.mca.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9623392/r.0.0.mca.txt)

I believe you might have to recover the chickens, since I had to delete them in the process. Simply use these commands one after another, paste them in your game after you've opped yourself on the server and you'll have all your chickens:
```
/give @s chickens:chicken_item{ChickenType:{id:"chickens:redstone_chicken"}, gain:10, growth:10, strength:10}
/give @s chickens:chicken_item{ChickenType:{id:"chickens:ender_chicken"}, gain:10, growth:10, strength:10}
/give @s chickens:chicken_item{ChickenType:{id:"chickens:log_chicken"}, gain:10, growth:10, strength:10}
/give @s chickens:chicken_item{ChickenType:{id:"chickens:quartz_chicken"}, gain:10, growth:10, strength:10}
/give @s chickens:chicken_item{ChickenType:{id:"chickens:coal_chicken"}, gain:10, growth:10, strength:10}
/give @s chickens:chicken_item{ChickenType:{id:"chickens:glowstone_chicken"}, gain:10, growth:10, strength:10}
/give @s chickens:chicken_item{ChickenType:{id:"chickens:glass_chicken"}, gain:10, growth:10, strength:10}
/give @s chickens:chicken_item{ChickenType:{id:"chickens:gold_chicken"}, gain:10, growth:10, strength:10}
/give @s chickens:chicken_item{ChickenType:{id:"chickens:sand_chicken"}, gain:10, growth:10, strength:10}
/give @s chickens:chicken_item{ChickenType:{id:"chickens:iron_chicken"}, gain:10, growth:10, strength:10}
```

That should be all the chickens I had to remove in those problematic roosts. Let me know if that works now

**Comment by DanJHawes** [comment] 2022-09-27 06:38
I've only just had time to check it out. This fixed it! Thank you so much. I'm starting with daily backups now to avoid anything like this in the future. Thank you so much for your help

**Comment by Raidobw2** [comment] 2022-09-27 08:22
Glad that fixed it! 😄 

I'll be closing the issue in that case since we'll be tracking the main issue at #1098.
The issue is fixed in the Chickens mod but we need to update the pack from 1.19 -> 1.19.2, which hasn't happened yet.
https://github.com/CreeperHost/Chickens/issues/6

Until FTB One updates for Minecraft 1.19.2, the best solution is to always extract items from the roosts using pipes. If you have the pipes (Pipez) send the items to a trash can if your first buffer is full, this problem should never happen again.

Though, in the case the issue reappears or another issue arises - keep your backups within a hand's reach and don't hesitate to ask for help on the modpack tracker by making a new issue.

Have fun playing!

**Closed by Raidobw2** 2022-09-27 08:22 UTC
Labels: 3: Support Request, FTB One
