### ISSUE TITLE
Crash to desktop when hovering certain block in JEI

### ISSUE THREAD

**Issue by zircuitz** [FTBTeam/FTB-Modpack-Issues#5988] opened 2024-10-19 16:24 UTC
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.3.0

### Launcher

Prism

### Has the pack been modified

No

### Log Files

Full run log (Stripped sensitive information): https://pastejustit.com/hhj8aif9kq

Crash report: https://pastejustit.com/qiiqybnju2

### Describe the bug

When hovering over a certain block within JEI, the game crashes to desktop.

I'm not sure what the block is, but here is a photo of it in JEI:
![image](https://github.com/user-attachments/assets/4f667243-bc89-4a68-a383-d5a4732b4623)

### Steps to reproduce

1. Load up a world.
2. Open inventory and search for "block anc"
3. Hover the mouse over the very last block in JEI. Or this block: 
![image](https://github.com/user-attachments/assets/5e8ecc57-25b7-4e24-87e1-bdc93f47b3fa)

### Expected behaviour

Tooltip should display without crashing the game.

### Additional information

This specific crash happened on a server run on Ubuntu Server. A friend of mine tried to reproduce the problem, and got the exact same crash.

The server is running on version 1.3.0 of the pack, with NeoForge 21.1.61

The server is not outputting any errors in the console when the crash occurs. Only that the player disconnected.

**Comment by CoolAEW** [comment] 2024-10-19 16:34
I can confirm that this issue also happens when using the FTB Electron App launcher

**Comment by zperk13** [comment] 2024-10-19 18:51
Duplicate of #5899

**Comment by zircuitz** [comment] 2024-10-19 19:09
> Duplicate of #5899

Well It's for version 1.2.1 of the pack, and It was labeled as "Fixed in dev". Is it still not fixed in 1.3.0? Did the fix not make it into 1.3.0 of the pack?

**Comment by zperk13** [comment] 2024-10-19 21:01
Fair point, I didn't notice that. I do not know the answer to your question

**Comment by Gaz492** [comment] 2024-10-21 06:54
I've reported the issue to the mod author https://github.com/ldtteam/Structurize/issues/705
![](!skip)

**Closed** 2024-11-07 07:13 UTC
Labels: state: Fixed in Dev, state: Confirmed, state: Awaiting Mod Update, Bug, @Reported to Mod Dev, @Mod issue, FTB Presents Direwolf20 1.21
