### ISSUE TITLE
[Bug]: Not showing toomanyitems

### ISSUE THREAD

**Issue by Redhoppy22** [FTBTeam/FTB-Modpack-Issues#3309] opened 2023-05-05 03:39 UTC
### Mod

FTB Mindcrack

### Mod version

8.3.2

### Forge / Fabric version

I think 1.4.7

### Modpack & version

FTB Mindcrack 8.3.2

### What issue are you having?

Hi, I am playing FTB Mindcrack, and there is no toomanyitems when I open my inventory...  I did try pressing I and O to open up the side inventory, but it's not working...  Is there a bug with Mindcrack or something?

### Crashlogs

No crashes

### Steps to reproduce

Hi, I am playing FTB Mindcrack, and there is no toomanyitems when I open my inventory...  I did try pressing I and O (which are the defaults to open the side inventory)  to open up the side inventory, but it's not working...  Is there a bug with Mindcrack or something?

**Comment by Raidobw2** [comment] 2023-05-05 14:30
This might be the same problem that was encountered in https://github.com/FTBTeam/FTB-Modpack-Issues/issues/553, try following my instructions there to see if that solves it

**Comment by Gaz492** [comment] 2024-06-20 15:31
Duplicate of #1286

**Closed by Gaz492** 2024-06-20 15:31 UTC
Labels: FTB MindCrack Pack, state: Confirmed
