### ISSUE TITLE
[Bug]: FTB Infinity Evolved Skyblock NEI crash

### ISSUE THREAD

**Issue by leonthegamechanger** [FTBTeam/FTB-Modpack-Issues#727] opened 2022-04-17 19:32 UTC
### Modpack

FTB Infinity Evolved Skyblock

### Modpack version

2.0.1

### Log Files

net.minecraft.util.ReportedException: Updating screen events
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1654) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at codechicken.nei.PositionedStack.setPermutationToRender(PositionedStack.java:95) ~[PositionedStack.class:?]
	at codechicken.nei.PositionedStack.<init>(PositionedStack.java:34) ~[PositionedStack.class:?]
	at WayofTime.alchemicalWizardry.client.nei.NEIBloodOrbShapedHandler$CachedBloodOrbRecipe.setIngredients(NEIBloodOrbShapedHandler.java:47) ~[NEIBloodOrbShapedHandler$CachedBloodOrbRecipe.class:1.7.10-1.3.3-17]
	at codechicken.nei.recipe.ShapedRecipeHandler$CachedShapedRecipe.<init>(ShapedRecipeHandler.java:35) ~[ShapedRecipeHandler$CachedShapedRecipe.class:?]
	at WayofTime.alchemicalWizardry.client.nei.NEIBloodOrbShapedHandler$CachedBloodOrbRecipe.<init>(NEIBloodOrbShapedHandler.java:24) ~[NEIBloodOrbShapedHandler$CachedBloodOrbRecipe.class:1.7.10-1.3.3-17]
	at WayofTime.alchemicalWizardry.client.nei.NEIBloodOrbShapedHandler.forgeShapedRecipe(NEIBloodOrbShapedHandler.java:129) ~[NEIBloodOrbShapedHandler.class:1.7.10-1.3.3-17]
	at WayofTime.alchemicalWizardry.client.nei.NEIBloodOrbShapedHandler.loadCraftingRecipes(NEIBloodOrbShapedHandler.java:83) ~[NEIBloodOrbShapedHandler.class:1.7.10-1.3.3-17]
	at codechicken.nei.recipe.TemplateRecipeHandler.loadCraftingRecipes(TemplateRecipeHandler.java:331) ~[TemplateRecipeHandler.class:?]
	at codechicken.nei.recipe.ShapedRecipeHandler.loadCraftingRecipes(ShapedRecipeHandler.java:107) ~[ShapedRecipeHandler.class:?]
	at WayofTime.alchemicalWizardry.client.nei.NEIBloodOrbShapedHandler.loadCraftingRecipes(NEIBloodOrbShapedHandler.java:75) ~[NEIBloodOrbShapedHandler.class:1.7.10-1.3.3-17]
	at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:466) ~[TemplateRecipeHandler.class:?]
	at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:20) ~[GuiCraftingRecipe.class:?]
	at codechicken.nei.ItemPanel.mouseUp(ItemPanel.java:258) ~[ItemPanel.class:?]
	at codechicken.nei.LayoutManager.onMouseUp(LayoutManager.java:166) ~[LayoutManager.class:?]
	at codechicken.nei.guihook.GuiContainerManager.mouseUp(GuiContainerManager.java:365) ~[GuiContainerManager.class:?]
	at codechicken.nei.guihook.GuiContainerManager.overrideMouseUp(GuiContainerManager.java:357) ~[GuiContainerManager.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java) ~[bex.class:?]
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146286_b(GuiContainerCreative.java:462) ~[bfl.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306) ~[bdw.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java) ~[bex.class:?]
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146274_d(GuiContainerCreative.java:566) ~[bfl.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268) ~[bdw.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640) ~[bao.class:?]
	... 9 more

### Describe the bug

Every time i try using NEI the game Crashs

### Steps to reproduce

1. Press E to open the inventory
2. left click on an item to view the recipe
3. game is chrashing  

### Expected behaviour

see the recipe

### Screenshots

-

### Additional information

-

**Comment by Raidobw2** [comment] 2022-04-17 21:53
Hello, it seems to be caused by Blood Magic's items in NEI, ultimately by CodeChickenLib. Can you backup all your instance data and try to reinstall the modpack? Then paste back in your save and other files (apart from mods and config) and see if that works.

If that doesn't work, see if deleting the `NEI` folder in your `config` folder works.

Let me know if you managed to play or not after that

**Comment by leonthegamechanger** [comment] 2022-04-18 11:34
deleting the NEI folder in the config folder worked i had no issues since i tried it.

**Comment by leonthegamechanger** [comment] 2022-04-18 11:37
I tried it all but when i am using NEI in creative mode it gives me like it should the item after that i tried it in recipe mode but it crashed again. :(

**Comment by Raidobw2** [comment] 2022-04-18 16:30
Which item exactly is it?

**Comment by leonthegamechanger** [comment] 2022-04-18 17:44
It’s on any item

**Comment by Raidobw2** [comment] 2022-04-19 03:55
I can't reproduce it... First copy your saves and all of the instance data elsewhere. Then press Windows + R and type `%localappdata%\.ftba\instances` and press Ok. In your instances folder, delete the `.localCache` file. Then, reinstall the modpack (FTB Infinity Evolved Skyblock). It's this one just to be sure:
![image](https://user-images.githubusercontent.com/17010632/163916664-a30297ad-d94c-4a6f-9803-7f970e83afc3.png)
You have to get it from the FTB App: https://feed-the-beast.com/app
You'll have to do the same fix that is in the FTB Discord in the `#infinity-evolved` channel (the pinned message). It says to Open the Folder of the instance and edit `excompressum.cfg` in the `config` folder. In that file search for `B:"Skip Auto Sieve Skins"=false` and change it to `B:"Skip Auto Sieve Skins"=true`, then save the file.
Then play the modpack and that should be a fresh install. If you still get the error try with a brand new world and let me know if the error happens there too. I couldn't make my game crash at all using the FTB App, see below for an example of what I tried.

https://user-images.githubusercontent.com/17010632/163916915-099c3510-916b-4f39-98f2-8e17e196f326.mp4

**Comment by leonthegamechanger** [comment] 2022-04-19 18:18
here is the server report:

[18:17:22] [Server thread/INFO]: TostBrotLeon lost connection: TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: java.io.IOException: Connection reset by peer], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}

**Comment by Raidobw2** [comment] 2022-04-19 20:17
Are they using the same version as you are? And did they also do the fixes in the `#infinity-evolved` channel?

Nitrado does have server support, so I'm hoping you also contacted them because I'm not your provider, therefore I am not the one to setup the modpack on the machine. On my side it works fine with a local server after doing the fixes in that Discord channel. I can click recipes and the game does not crash, neither do I get kicked.

You're getting a connection reset by peer which is the equivalent of closing the connection abruptly, like slamming down the phone. Is it possible to get your client full crash report as well? Thanks in advance

**Comment by Raidobw2** [comment] 2022-05-28 09:52
Glad Nitrado could figure it out, I'll go ahead and close this issue then

**Closed by Raidobw2** 2022-05-28 09:52 UTC
Labels: FTB Infinity Evolved Skyblock, 3: Support Request
