### ISSUE TITLE
[Bug]: Startup gets stuck at providing API when trying to launch sky odyssey

### ISSUE THREAD

**Issue by Nineaga1n** [FTBTeam/FTB-Modpack-Issues#1483] opened 2022-10-22 15:17 UTC
### Modpack

Sky Odyssey

### Modpack version

1.4.1

### Log Files

https://pste.ch/xiqupuwice

### Describe the bug

Every time I try to start up the pack the startup just gets stuck at Providing API. And after a while it just starts reading tips as if it has started. (i did try the show instance button.) It sometimes gets stuck while it says "initializing mod phase 1: simpleinventorysorting" or "initializing mod phase 1: kleeslabs" in the top bar.

### Steps to reproduce

Try opening the modpack

### Expected behaviour

Launching Sky odyssey.

**Comment by GamingWithJanko** [comment] 2022-10-23 15:22
Same problem here!

**Comment by Raidobw2** [comment] 2022-10-24 08:32
I see, this looks more like a FTB App issue than a modpack issue. I've managed to load the pack a few times the past week for other support cases. Can both of you verify some things:
- Is there a VPN running? If yes try to turn it off
- Is there an antivirus running and does turning it off allow the pack to start momentarily?
- For Windows users, in the folder `c:\Windows\System32\Drivers\etc` contains a file named `hosts` that you can open with Notepad. If there is anything else than lines starting with the `#` symbol, remove them. Check your browsing habits and what you download if that's the case, since softwares modifying contents there without any comments could potentially be harmful.
- Make sure you have enough free RAM in your computer, you can see that in Task Manager.
- If the game manages to start a bit, are you able to obtain the game log and post it here? If it's not empty, there could be info as to why it's stopped loading

Thanks in advance for checking those things and let me know here your findings

**Comment by GamingWithJanko** [comment] 2022-10-25 19:13
-  Got none.
-  Only Windows Defender is running.
-  Done.
-  8 GB should be plenty.
-  I think I have the logs laying around. I'll appendd them in a bit.

**Comment by Raidobw2** [comment] 2022-10-28 00:57
Sorry for the delay, I managed to take a look at the log, you can remove it if you want.

I haven't seen anything out of the ordinary, but this shows right before it stops:
![image](https://user-images.githubusercontent.com/17010632/198424744-5ce90f30-7911-4d1d-9cf1-60a6e6446fb3.png)

I've seen similar issues on some other packs before like Revelation and Stoneblock 2, which also are on 1.12.2.

So could you try removing MineTogether from the mods folder and let me know if that works?

**Comment by GamingWithJanko** [comment] 2022-10-29 00:56
Checked and it sure booted up just fine now.

**Comment by Raidobw2** [comment] 2022-11-02 07:38
Oh, so just to confirm, removing MineTogether fixed it and allowed you to play the game?

**Comment by GamingWithJanko** [comment] 2022-11-02 11:12
Sure did.

**Comment by Raidobw2** [comment] 2022-11-02 13:25
Ok, thanks for the feedback. Will check with the MT team, please leave this opened

**Comment by GamingWithJanko** [comment] 2022-11-02 19:30
I can't change the status anyway. It's not originally my ticket. ¯\_(ツ)_/¯

**Comment by Raidobw2** [comment] 2022-11-03 10:29
For those that had the issue, I'll ask for a favor... Would you be able to add the latest MineTogether mod in 1.12.2 to this pack instead and verify with one launch if that works instead? (you can remove it afterwards if you prefer)

It can be found here: https://www.curseforge.com/minecraft/mc-mods/creeperhost-minetogether/files/3328387

I've gotten in touch with the mod developer, but since I'm unable to reproduce it, I can't tell him if it's fixed or not... This would also help me in knowing if this works and can be shipped with the modpack since it is marked as a beta version.

One game load should suffice if anyone wants to help. I'd appreciate it a lot and thanks in advance!

**Comment by GamingWithJanko** [comment] 2022-11-05 14:06
Imma test it in a few.

Stay tuned.

**Comment by GamingWithJanko** [comment] 2022-11-05 15:17
Yup, it loaded up just fine now.

**Comment by Raidobw2** [comment] 2022-11-06 02:33
Awesome, thanks a lot for the feedback, again 🙂 cheers

**Closed** 2023-02-07 21:17 UTC
Labels: FTB Sky Odyssey, 1: Mod Issue, state: Fixed in Dev :hammer_and_wrench:, state: Mod Update Available
