### ISSUE TITLE
[Bug]: FTBQuest crashes when opening quest book

### ISSUE THREAD

**Issue by tekman123** [FTBTeam/FTB-Modpack-Issues#2127] opened 2022-11-25 01:24 UTC
### Modpack

stoneblock 3

### Modpack version

1.4.1

### Log Files

https://pste.ch/leqocezipu.pl

### Describe the bug

when I open the quest book it crashes my client to desktop

### Steps to reproduce

1. open questbook

### Expected behaviour

not to crash to desktop when opening quest book

**Comment by Sunekaer** [comment] 2022-11-25 17:39
Duplicate of #2117

**Comment by tekman123** [comment] 2022-11-25 19:38
I know this is marked as closed due to it being a duplicate but it's not an exact duplicate as my issue doesn't happen only when I click on recipes through the quest book. It happens when I open the quest book Period. I don't get a chance to see text or anything contained in the book

**Comment by Cloudhunter** [comment] 2022-11-25 19:50
I concur with @tekman123 - the crash log appears to be completely different, and so are the reproduction methods.

@Sunekaer mind taking another look?

**Comment by Raidobw2** [comment] 2022-11-25 21:59
@tekman123 would you be able to add your world download here as well as the `config/ftbquests` folder from your client (zipped)? You can zip both together if you want, we think a data somewhere might be corrupt and this would be helpful for us. Thanks in advance

**Comment by tekman123** [comment] 2022-11-25 22:55
@Raidobw2 I wouldn't mind doing that at all. Problem is I already rolled my server back to 1.3.0 as well as my client and everyone on my server so that we could play last night.  I can always update a copy of the server and start it up as well as get a copy of my config/ftbquests from my client after update I suppose

**Comment by tekman123** [comment] 2022-11-25 23:45
UPDATE: updating to 1.4.2 and I can no longer reproduce this issue but on 1.4.1 3 of us were able to do so

**Comment by Raidobw2** [comment] 2022-12-02 11:17
I see, thanks for the feedback! In that case I'll assume this is fixed, otherwise we can use the info in here to help with case https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2117.
REI was updated in 1.4.2 so maybe that was it.
I'll go ahead and close this now, if it happens again, comment on 2117 if it's still open, or make a new issue for it, thanks.

**Closed by Raidobw2** 2022-12-02 11:17 UTC
Labels: 1: Mod Issue, FTB StoneBlock 3
