### ISSUE TITLE
Game "stop responding" every time it saves

### ISSUE THREAD

**Issue by AtomicDonuts** [FTBTeam/FTB-Modpack-Issues#2407] opened 2022-12-25 11:41 UTC
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Log Files

https://pste.ch/kazuwafepu.md

### Describe the bug

Whenever i try to save the world the game "not responding" and never recover. Console crash and i need to kill the process from the Task Manager. 
If i create a new world, the problem is not present. As soon as i close the launcher and reopen it, i cant save the world anymore.
If i open the Game Menu, the saving process begin resulting the freezing of the instance. 
If the backup process starts (via autosave or via command) the result is the same. 

### Steps to reproduce

1) Open an existing world
2) Start a saving process ( via command /backup start or opening the achiviement, or opening the menu)
3) Game stop working

### Expected behaviour

Game working

### Screenshots

![image](https://user-images.githubusercontent.com/39431742/209466500-31e410df-71f0-4182-ac77-93f24b9a2cee.png)

### Additional information

I tried to:
Change Client (using multimc)
Change Java Version (Oracle and Windows)
Change allocated ram ( giving it 8GB)
Open different world from other mc version
Update and downgrade the mod pack
Deleting FTB Backup
Moving the folder on another drive ( SSD and HDD) 

Im using 64 Java on Win10 22H2 with 16Gb of RAM.

**Comment by Raidobw2** [comment] 2023-01-26 04:44
Sorry for replying so late... thanks for reporting

The log unfortunately doesn't contain any crash info, but your screenshot does:
![image](https://user-images.githubusercontent.com/17010632/214760047-26152f15-7c5a-41c7-9408-54c853e79fd7.png)


I've tested:
- Checking uses/recipes for Mycelial Generators, works and I see recipes
- Placing some down, giving them items to consume to make energy, works, they generate RF
- Quitting the world, entering it again, works as normal

Got no crashes, so I'll assume this is fixed. I did update some mods like RoughlyEnoughItems, so perhaps this was fixed within them.

If you encounter this problem still, try adding a screenshot of the mycelial generators around your base if you have some (they seem to be the root of the issue).
Otherwise, install a 2nd instance of the pack and copy paste your `saves` folder to it. Try seeing if that 2nd instance works instead.

I'll be closing this once 1.6.0 comes out next week, since I couldn't reproduce an error I'll assume all is good after updating the mods.

**Closed** 2023-02-03 18:38 UTC
Labels: state: Fixed in Dev :hammer_and_wrench:, FTB StoneBlock 3
