### ISSUE TITLE
[Suggestion]: Adding Refined Storage Addons ?

### ISSUE THREAD

**Issue by Steinzu** [FTBTeam/FTB-Modpack-Issues#1633] opened 2022-11-04 17:46 UTC
### Modpack

FTB Stoneblock 3

Hello o/

I was wondering if adding any of the refined storage addons was planned ? Would be a little bit more confortable to at least have ExtraStorage for auto-crafting.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/extrastorage

Shouldn't really need a presentation but it adds higher tiers of transportation means, storage disks and crafters.

**Comment by Sunekaer** [comment] 2022-11-05 16:23
Duplicate of #1599

**Closed by Sunekaer** 2022-11-05 16:23 UTC
Labels: FTB StoneBlock 3
