### ISSUE TITLE
[Bug]: Server crash with REI and Extreme Crafting

### ISSUE THREAD

**Issue by RickieGamer** [FTBTeam/FTB-Modpack-Issues#2132] opened 2022-11-25 04:29 UTC
### Modpack

StoneBlock 3

### Modpack version

1.4.1

### Log Files

https://mclo.gs/ljnlYKe

### Describe the bug

Using REI to auto insert items into the extreme crafting table crashes the server

### Steps to reproduce

REI Neutronium Compressor
click + to insert items
watch crash

### Expected behaviour

to not crash

**Comment by CCNetwork-Randy-Marsh** [comment] 2022-11-25 09:35
Just experienced server crash with this error (Sorry for posting here) we just had the same issue so i didnt know if i should post here or how to "help"


### I had the same exact issue

1. **1. I went to my extreme crafting table**
2. ** tryed to use the white + to make a neurtronium collector ** 
3. Crashed my MULTIPLAYER server, On this, This is a huuuuge Issue guys

`[10:31:16] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: org/apache/commons/codec/binary/Base64
        at me.shedaniel.rei.plugincompatibilities.Gz93JOB0wWD.jMRoV261Dd5.aTO6BDiZMTl(JEIExtraPlugin.java:90) ~[REIPluginCompatibilities-forge-8.0.32.jar%23206!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
        at me.shedaniel.rei.plugincompatibilities.Gz93JOB0wWD.i08f7uq4bMj.provide(JEIExtraPlugin.java:76) ~[REIPluginCompatibilities-forge-8.0.32.jar%23206!/:?] {re:classloading,pl:rei_plugin_compatibilities:B,pl:runtimedistcleaner:A}
        at me.shedaniel.rei.impl.common.transfer.MenuInfoRegistryImpl.lambda$get$4(MenuInfoRegistryImpl.java:91) ~[RoughlyEnoughItems-8.3.571.jar%23213!/:?] {re:classloading,pl:rei_plugin_compatibilities:B,pl:runtimedistcleaner:A}
        at me.shedaniel.rei.impl.common.transfer.MenuInfoRegistryImpl.getInternal(MenuInfoRegistryImpl.java:121) ~[RoughlyEnoughItems-8.3.571.jar%23213!/:?] {re:classloading,pl:rei_plugin_compatibilities:B,pl:runtimedistcleaner:A}
        at me.shedaniel.rei.impl.common.transfer.MenuInfoRegistryImpl.get(MenuInfoRegistryImpl.java:91) ~[RoughlyEnoughItems-8.3.571.jar%23213!/:?] {re:classloading,pl:rei_plugin_compatibilities:B,pl:runtimedistcleaner:A}
        at me.shedaniel.rei.impl.common.transfer.InputSlotCrafter.start(InputSlotCrafter.java:68) ~[RoughlyEnoughItems-8.3.571.jar%23213!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
        at me.shedaniel.rei.RoughlyEnoughItemsNetwork.lambda$onInitialize$4(RoughlyEnoughItemsNetwork.java:126) ~[RoughlyEnoughItems-8.3.571.jar%23213!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
        at dev.architectury.networking.forge.NetworkManagerImpl.lambda$createPacketHandler$6(NetworkManagerImpl.java:150) ~[architectury-4.10.86-forge.jar%2347!/:?] {re:classloading,pl:rei_plugin_compatibilities:B,pl:runtimedistcleaner:A}
        at dev.architectury.networking.transformers.SplitPacketTransformer.inbound(SplitPacketTransformer.java:174) ~[architectury-4.10.86-forge.jar%2347!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
        at dev.architectury.networking.forge.NetworkManagerImpl.lambda$createPacketHandler$7(NetworkManagerImpl.java:145) ~[architectury-4.10.86-forge.jar%2347!/:?] {re:classloading,pl:rei_plugin_compatibilities:B,pl:runtimedistcleaner:A}
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.network.NetworkInstance.dispatch(NetworkInstance.java:68) ~[forge-1.18.2-40.1.84-universal.jar%23265!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
        at net.minecraftforge.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:78) ~[forge-1.18.2-40.1.84-universal.jar%23265!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
        at java.util.Optional.map(Optional.java:260) ~[?:?] {re:mixin}
        at net.minecraftforge.network.NetworkHooks.onCustomPayload(NetworkHooks.java:78) ~[forge-1.18.2-40.1.84-universal.jar%23265!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7423_(ServerGamePacketListenerImpl.java:1439) ~[server-1.18.2-20220404.173914-srg.jar%23260!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.ServerPlayNetHandlerAccess,pl:mixin:A}
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:35) ~[server-1.18.2-20220404.173914-srg.jar%23260!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:8) ~[server-1.18.2-20220404.173914-srg.jar%23260!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
        at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[server-1.18.2-20220404.173914-srg.jar%23260!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.2-20220404.173914-srg.jar%23260!/:?] {re:classloading,pl:rei_plugin_compatibilities:B,re:mixin}
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%23260!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.2-20220404.173914-srg.jar%23260!/:?] {re:mixin,re:computing_frames,pl:rei_plugin_compatibilities:B,re:classloading,pl:rei_plugin_compatibilities:B}
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:799) ~[server-1.18.2-20220404.173914-srg.jar%23260!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164) ~[server-1.18.2-20220404.173914-srg.jar%23260!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%23260!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:782) ~[server-1.18.2-20220404.173914-srg.jar%23260!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[server-1.18.2-20220404.173914-srg.jar%23260!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[server-1.18.2-20220404.173914-srg.jar%23260!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:761) ~[server-1.18.2-20220404.173914-srg.jar%23260!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[server-1.18.2-20220404.173914-srg.jar%23260!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23260!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:833) [?:?] {}
Caused by: java.lang.ClassNotFoundException: org.apache.commons.codec.binary.Base64
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
        ... 35 more
[10:31:16] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 2a9cb2cc-d44a-4cc0-933a-1fe255f6e063
[10:31:16] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /home/container/./crash-reports/crash-2022-11-25_10.31.16-server.txt
[10:31:16] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[10:31:16] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[10:31:16] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: CCN_Randy_Marsh lost connection: Server closed
[10:31:16] [Server thread/INFO] [minecraft/DedicatedServer]: CCN_Mr.Loot left the game
[10:31:16] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[10:31:22] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[10:31:57] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[world]'/bloodmagic:dungeon
[10:31:57] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[world]'/ftbsbc:team/faces-sea-miked
[10:31:57] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[world]'/compactmachines:compact_world
[10:31:57] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[world]'/ftbsbc:team/unprized-potiches-fencers
[10:31:57] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[world]'/ftbsbc:team/galaxes-gavottes-corking
[10:31:57] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[10:31:57] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[10:31:57] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[world]'/ae2:spatial_storage
[10:31:57] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (worldtest): All chunks are saved
[10:31:57] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (dungeon): All chunks are saved
[10:31:57] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (faces-sea-miked): All chunks are saved
[10:31:57] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (compact_world): All chunks are saved
[10:31:57] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (unprized-potiches-fencers): All chunks are saved
[10:31:57] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (galaxes-gavottes-corking): All chunks are saved
[10:31:57] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[10:31:57] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[10:31:57] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (spatial_storage): All chunks are saved
[10:31:57] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage: All dimensions are saved
[10:31:58] [Server thread/INFO] [FTB Chunks/]: Shutting down map thread
[10:31:58] [Server thread/INFO] [ne.cr.ft.or.qu.co.QuartzScheduler/]: Scheduler ftbbackups2_$_NON_CLUSTERED shutting down.
[10:31:58] [Server thread/INFO] [ne.cr.ft.or.`

**Comment by andremiller** [comment] 2022-11-25 17:59
Just came to report the same issue.

Before 1.4 clicking the recipe in with REI on our server didn't work. It didn't crash the server, but just refused to work.

Now, with 1.4.1 update, clicking the recipe into the extreme crafter from REI crashes our multiplayer server.

Logs: https://mclo.gs/gATSah7

**Comment by Sunekaer** [comment] 2022-11-25 18:26
https://github.com/shedaniel/RoughlyEnoughItems/issues/1240

**Comment by Raidobw2** [comment] 2023-01-26 06:06
The mod has been updated prior to today and put into the 1.5.0 release, this should be fixed in 1.5.0+ actually
(See linked issue by Sunekaer, mod has received fixes)

**Closed** 2023-01-26 06:06 UTC
Labels: 1: Mod Issue, state: Fixed :heavy_check_mark:, FTB StoneBlock 3
