### ISSUE TITLE
[Bug]: Bee Hives Lose data when silktouched

### ISSUE THREAD

**Issue by tyler489** [FTBTeam/FTB-Modpack-Issues#1381] opened 2022-10-03 23:48 UTC
### Modpack

Inferno

### Modpack version

1.0.0

### Describe the bug

When Silktouching a bee hive that contains a bee or a any amount of honey, the data is lost, and says 0 bees, 0 honey.

### Steps to reproduce

Find a Full Beehive
Break it with silktouch
Lose all bees and honey

### Expected behaviour

Mimic Vanilla Behavior, Keep the bees and honey level.

**Comment by Saereth** [comment] 2022-10-05 19:09
I cannot reproduce this, seems to work fine for me
![image](https://user-images.githubusercontent.com/9200909/194142437-d8391d33-8b02-4c0b-a853-ac583dfeb079.png)

**Comment by Saereth** [comment] 2022-10-10 18:48
this may be something that got fixed in the productive bees update, closing for now though as I cant reproduce it anymore, re-open if you can help reproduce

**Closed by Saereth** 2022-10-10 18:48 UTC
Labels: 1: Mod Issue, state: Testing required, FTB Inferno
