### ISSUE TITLE
[Bug]: Crash - IllegalStateException: Accessing PalettedContainer from multiple threads

### ISSUE THREAD

**Issue by bogie** [FTBTeam/FTB-Modpack-Issues#2088] opened 2022-11-21 19:00 UTC
### Modpack

Stoneblock 3

### Modpack version

1.3.1

### Log Files

https://pste.ch/oloponugef.rb
[2022-11-21-2.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10059759/2022-11-21-2.log.gz)
[2022-11-21-1.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10059770/2022-11-21-1.log.gz)
[debug-2.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10059771/debug-2.log.gz)
[debug-1.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10059772/debug-1.log.gz)

### Describe the bug

Game crashes from time to time during scheduled ftbbackup.

Shortly before/after backup there is also an error related to mekanism:
"[Mekanism/]: Stack size changed by a different amount", it references mekanism mechanical pipes. Not sure if this is related.

This first time started happening when using Watch of the Flowing Time to tick accelerate mekanism setups(using their pipes). This is a guess, as such the reason could be entirely different.

### Steps to reproduce

1. run server version 1.3.1
2. tick accelerate mekanism pipes
3. automated backup runs
4. crash
5. ???
6. profit

### Expected behaviour

Well, a backup shouldnt crash the server.

**Comment by perennialpersephone** [comment] 2022-11-22 07:09
#1935 Might consider adding to this post.

**Comment by Sunekaer** [comment] 2022-11-23 15:27
Duplicate of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1935

**Closed by Sunekaer** 2022-11-23 15:27 UTC
Labels: FTB StoneBlock 3
