### ISSUE TITLE
Unhandled NoSuchFileException in FTB Backups

### ISSUE THREAD

**Issue by destinatech** [FTBTeam/FTB-Modpack-Issues#3328] opened 2023-05-08 22:43 UTC
### Modpack

FTB Skies

### Modpack version

1.0.9

### Log Files

[server console snippet](https://pste.ch/epuhenixam.sql)

[latest.log](https://pste.ch/zitajadicu.sql)
[debug.log](https://pste.ch/uqekucafaj.md)

### Describe the bug

Apologies if this is dupe. I did a few searches but didn't turn up this particular splat.

Whilst in the middle of creating a backup FTB Backups chokes thusly:

```
[23:00:00] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage: All dimensions are saved
[23:00:00] [FTB Backups backup thread 0/ERROR] [ne.cr.ft.FTBBackups/]: Failed to create backup
> java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /home/minecraft/servers/ftb/skies/1.0.9-pristine/./world/./level14065582984954086041.dat
[...]
        at TRANSFORMER/ftbbackups2@1.0.18/net.creeperhost.ftbbackups.utils.FileUtils.pack(FileUtils.java:37)
        at TRANSFORMER/ftbbackups2@1.0.18/net.creeperhost.ftbbackups.BackupHandler.lambda$createBackup$4(BackupHandler.java:252)
[...]
Caused by: java.nio.file.NoSuchFileException: /home/minecraft/servers/ftb/skies/1.0.9-pristine/./world/./level14065582984954086041.dat
```

The exception itself doesn't actually make it to log files. I captured as much context as was available on the server console (linked above).

The backup job following the failed one above did complete successfully though, so not entirely fatal.

### Steps to reproduce

Unknown.

### Expected behaviour

Fewer unhandled exceptions

**Comment by MichaelHillcox** [comment] 2023-05-09 22:00
Likely an edge case, did this actually crash the server?

**Comment by ukmcplyr** [comment] 2023-05-10 05:03
Bah. Forgot to sign out of my work alt when I submitted this...

No crash but it did fail again in the same way at least once more an hour after the first failure and apparently half a dozen or so more times while I was offline. So a decent number of missing backups.

Hasn't happened again over the past 12+ hours though, so hopefully it is just an edge case.

**Comment by Saereth** [comment] 2023-05-10 07:20
I have run into this, rarely, on my server as well, havent been able to pin down what causes it, so if you can find any steps to help reproduce that would be helpful

**Comment by ukmcplyr** [comment] 2023-05-10 10:20
Sure, will do. I was definitely idle the second time it happened, with very minimal sifting going on in the background at most.   But I'll see what I can come up with when I get a free hour or two. :+1:

**Comment by ukmcplyr** [comment] 2023-05-16 18:59
No luck reproducing this unfortunately.

I have noticed previously some annoying slowdowns in FTB Backups when zipping a very small (sub-25MB) `world/` once and, more commonly, on server shutdown.  Probably unrelated to this, though.

**Comment by Saereth** [comment] 2023-05-19 01:30
I've not been able to reproduce this since the latest update either so closing for now, hopefully resolved

**Closed by Saereth** 2023-05-19 01:30 UTC
Labels: FTB Skies
