### ISSUE TITLE
[Bug]: Unable to complete flint pickaxe quest

### ISSUE THREAD

**Issue by TobiDoes** [FTBTeam/FTB-Modpack-Issues#1976] opened 2022-11-15 15:34 UTC
### Modpack

FTB Inferno

### Modpack version

1.3.0

### Describe the bug

Unable to Complete Flint Pick Quest 

### Steps to reproduce

try to Complete Flint Pick Quest 

### Expected behaviour

after the crafting of a flint pick it completes

**Comment by orbidlo** [comment] 2022-11-15 17:36
Duplicate of #1886

**Comment by Shinino** [comment] 2022-11-19 19:35
Workaround for now:  Create Tinker's Construct version (with parts et al), and it'll finish.

**Closed** 2023-01-18 22:31 UTC
Labels: state: Fixed in Dev :hammer_and_wrench:, FTB Inferno
