### ISSUE TITLE
[Bug]: Crash on Event toast 

### ISSUE THREAD

**Issue by Petrisis** [FTBTeam/FTB-Modpack-Issues#100] opened 2021-10-08 11:08 UTC
### Modpack

FTB OceanBlock

### Modpack version

1.2.0

### Log Files

[logfile](https://gist.github.com/Petrisis/6aa031f289503db96bc1e3af7c1b1fe8)

### Describe the bug

i was starting the game, looked into the questbook and started mining my tree. on fourth wood pickup the world & game closed itself

### Steps to reproduce

1. start a new world
2. punch the tree til4 wood

### Expected behaviour

i think it should not crash on giving me achievement toast =)

**Comment by Sunekaer** [comment] 2021-10-09 08:53
Duplicate of #52

**Closed by Sunekaer** 2021-10-09 08:53 UTC
