### ISSUE TITLE
[Bug]: Game crashes when using framed drawers

### ISSUE THREAD

**Issue by LCoolJT** [FTBTeam/FTB-Modpack-Issues#2123] opened 2022-11-24 23:10 UTC
### Modpack

FTB Stoneblock 3

### Modpack version

1.4.1

### Describe the bug

When using chisel variants of blocks for the framed drawer the game crashes.
If this is done in some remembering grid the grid will become useless for further use(causing crashes when opened).

### Steps to reproduce

1.have a framed drawer.
2.have two blocks that are some chisel variant(smooth black concrete)
3.combine the items as said in the item describtion of framed drawer
[crash-2022-11-25_00.07.30-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10087633/crash-2022-11-25_00.07.30-client.txt)

### Expected behaviour

logs out and game crashes

**Comment by Sunekaer** [comment] 2022-11-25 17:23
Duplicate of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1650

**Closed by Sunekaer** 2022-11-25 17:23 UTC
Labels: 1: Mod Issue, FTB StoneBlock 3
