### ISSUE TITLE
[Bug]: Minetogether crashing server

### ISSUE THREAD

**Issue by DeeDoubleYous** [FTBTeam/FTB-Modpack-Issues#907] opened 2022-06-06 13:28 UTC
### Modpack

Plexiglass mountain

### Modpack version

1.0.1

### Log Files

https://pastebin.com/ahLKmzWZ

### Describe the bug

Trying to start a server for the first time and it crashes before getting to world generation. Removing minetogether allows it to load up.

### Steps to reproduce

Install the server with the server installer and try to launch. Disable minetogether and it will launch and generate the world correctly. Doesn't seem to be a problem on the client.

### Expected behaviour

The world gens as expected and the server launches

**Comment by Raidobw2** [comment] 2022-06-06 23:44
It's caused by a client class being loaded on the server. I'll be fixing that today, I'm hoping 1.0.2 will be approved for tomorrow. Thanks for reporting!

> If you are getting a server crash with version 1.0.1 of FTB Plexiglass Mountain, navigate and open the file at config/minetogether.json and replace its contents with the text at https://paste.feed-the-beast.com/view/fdffd1d5, then save the file. This will disable something in the mod that currently prevents it from loading correctly on servers. This has been reported to the infrastructure team and they will be looking into fixing it as soon as possible, though it may take up to 24h due to time differences.

**Comment by Raidobw2** [comment] 2022-06-07 09:53
Should be fixed and released in 1.0.2

**Closed by Raidobw2** 2022-06-07 09:53 UTC
Labels: 1: Mod Issue, state: Fixed :heavy_check_mark:, FTB Plexiglass Mountain
