### ISSUE TITLE
[Bug]: Functional Storage - Pull Upgrade

### ISSUE THREAD

**Issue by Flatts3000** [FTBTeam/FTB-Modpack-Issues#2129] opened 2022-11-25 03:06 UTC
### Modpack

FTB Stoneblock 3

### Modpack version

1.4.1

### Describe the bug

Puller upgrade doesn't work with compacting drawer when the item is supposed to go in the bottom left slot.

I've included a video. IDK if its just with Chicken's Roosts or not.

https://www.dropbox.com/home?preview=2022-11-24+21-50-01.mp4

### Steps to reproduce

Put a Roost from Chickens on top of a Compacting Drawer from Functional Storage.
Put a Puller Upgrade in the Compacting Drawer set to "Up"
Put a Chicken in the drawer to output an item.

### Expected behaviour

The drawer should pull the item from the Roost

### Screenshots

https://www.dropbox.com/home?preview=2022-11-24+21-50-01.mp4

**Comment by Sunekaer** [comment] 2022-11-25 17:02
Duplicate of #1784

**Closed by Sunekaer** 2022-11-25 17:02 UTC
Labels: 1: Mod Issue, FTB StoneBlock 3
