### ISSUE TITLE
stoneblock 3 crash

### ISSUE THREAD

**Issue by briosky** [FTBTeam/FTB-Modpack-Issues#2275] opened 2022-12-09 10:06 UTC
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.2

### Log Files

[crash-2022-12-09_09.47.38-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10194264/crash-2022-12-09_09.47.38-client.txt)

### Describe the bug

when I try to start it after the red screen and the word save world the modpack crash

### Steps to reproduce

1. click play 
2. wait for launch minecraft
3. appear red minecraft preview
4. screen whit word "saving world"
5. crash

### Expected behaviour

start the modpack

**Comment by NordicGamerFE** [comment] 2022-12-09 10:53
@briosky please attach a crash log its found in your stoneblocks 3 folder in a folder called crash log.

**Comment by NordicGamerFE** [comment] 2022-12-09 10:54
Probably duplicate of #2269

**Closed** 2022-12-09 11:44 UTC
Labels: state: Duplicate :books:, FTB StoneBlock 3
