### ISSUE TITLE
[Bug]: Corrupted chunk data on server

### ISSUE THREAD

**Issue by lemar94** [FTBTeam/FTB-Modpack-Issues#694] opened 2022-03-26 14:40 UTC
### Modpack

FTB Ocean Block

### Modpack version

1.11.0

### Describe the bug

After playing for a while on a newly created server and logging of, the chunk data of the server seems to be corrupted when logging in again. In this case you can still log in to the server but see missing chunks. If you restart the server the conencting is lost directly after logging in.
I've tried with different maps and the error occures on all of them.

The attached logiles are from the same restarted server.

[Logfile_RestartedServer.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8355629/Logfile_RestartedServer.log)

### Steps to reproduce

1. Create a new server.
2. Create a new island.
3. Play for some time.
4. Log Out
5. Re-Log In to the running server.

### Expected behaviour

Server should be able to reload the correct map.

**Comment by Raidobw2** [comment] 2022-03-26 18:21
Hi, it looks in the log that the world has many corrupted chunks that could not be read. I'd suggest to look into your server folder and into the `backups` folder. Inside, take the latest file and extract it. Replace your current world with that backup world and try to load it up.
Let me know if that works, I either think that the server was not closed properly or that a power cut happened while playing, so it caused file corruption.

**Comment by lemar94** [comment] 2022-04-07 10:47
Please apologize for the late response.
In the meantime i found that my issues where caused by the server itself and not the modpack as you already presumed.

**Comment by Raidobw2** [comment] 2022-04-08 05:46
Oh I see. Can I close this issue then, was the problem solved?

**Comment by TheonlyTazz** [comment] 2022-05-17 18:51
Issue was found caused by server not modpack, closing issue

**Closed by TheonlyTazz** 2022-05-17 18:51 UTC
Labels: FTB OceanBlock, 3: Support Request
