### ISSUE TITLE
Dedicated server does not stop

### ISSUE THREAD

**Issue by misterzirillo** [FTBTeam/FTB-Modpack-Issues#2492] opened 2023-01-11 22:10 UTC
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.1.0

### Log Files

```
> stop
[14:56:45] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping the server
[14:56:45] [Server thread/INFO] [ne.cr.ft.or.qu.co.QuartzScheduler/]: Scheduler ftbbackups2_$_NON_CLUSTERED shutting down.
[14:56:45] [Server thread/INFO] [ne.cr.ft.or.qu.co.QuartzScheduler/]: Scheduler ftbbackups2_$_NON_CLUSTERED paused.
[14:56:45] [Server thread/INFO] [ne.cr.ft.or.qu.co.QuartzScheduler/]: Scheduler ftbbackups2_$_NON_CLUSTERED shutdown complete.
[14:56:45] [Server thread/INFO] [ne.cr.ft.FTBBackups/]: Shutting down the config watcher executor
[14:56:45] [Server thread/INFO] [ne.cr.ft.FTBBackups/]: Shutting down backup cleaning executor
[14:56:45] [Server thread/INFO] [ne.cr.ft.FTBBackups/]: Shutting down backup executor
[14:56:46] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[14:56:46] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[14:56:46] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
```

### Describe the bug

When using `stop` command or ctrl-c from the console the server does not stop. Log output seems to indicate the server is stopping, but the process never terminates even after 10 minutes of waiting. I have observed a small amount of data loss when killing the process.

### Steps to reproduce

1. Start dedicated server
2. Press ctrl-c or execute `stop` command

### Expected behaviour

Process terminates

### Additional information

OS: Archlinux

**Comment by specCon18** [comment] 2023-01-13 00:54
what OS are you hosting on.

**Comment by misterzirillo** [comment] 2023-01-13 06:12
Archlinux

**Comment by Saereth** [comment] 2023-01-14 00:57
Can you try removing ftb backups and see if this issue still occurs for you? I can't reproduce it myself on ubuntuu 22

**Comment by misterzirillo** [comment] 2023-01-15 00:06
@Saereth removing ftbbackups doesn't have an effect. Running the server in a `ubuntu:kinetic` container didn't work either.

**Comment by Saereth** [comment] 2023-01-30 18:08
Unfortunately I cant reproduce this so I'm not even sure how to help you troubleshoot it further

**Comment by misterzirillo** [comment] 2023-01-30 23:15
I am now running the server on a ubuntu 22.04 host -- same issue there. 

The only thing I can think of is that my world is somehow causing the problem. I started the world in single player then copied the world folder to my dedicated server install before the initial startup. Perhaps that is the problem?

**Comment by FagSoft** [comment] 2023-02-08 11:32
I had the same problem when a chunk/block had corrupted NTB data. Tried starting with a different world, or a backup that worked?

**Comment by Saereth** [comment] 2023-02-28 20:12
this should be fixed in the update with the ftb chunks update

**Closed** 2023-02-28 20:35 UTC
Labels: state: Fixed in Dev :hammer_and_wrench:, FTB Presents Direwolf20 1.19
