### ISSUE TITLE
Going to the nether teleports to x and y coordinates about 10000

### ISSUE THREAD

**Issue by WMooon** [FTBTeam/FTB-Modpack-Issues#3867] opened 2023-09-05 19:50 UTC
### Modpack

FTB Skies

### Modpack version

1.3.1

### Describe the bug

I build a nether portal and when entered i got teleported to 10000 ~ 12000 coordinates (portal was near 00s) and when i go back to the overworld the portal spawns at 80000 ~ 100000.
When i checked 00s in the nether i saw a piglin structure (maybe portal spawns far because of that). If i build portal on the 00s it spawns near central sheep and if i go to the portal offers to create a new island.
That means if i go to the nether i basically lose all my progress.
I only can return to my island if i die and respawn

### Steps to reproduce

1. Seed -5971690553855469081
2. Chose the first island
3. Build nether portal

### Expected behaviour

Not teleporting me to 

### Screenshots

![2023-09-05_22 44 16](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/144169583/5966f64f-18c4-490d-8726-cbf3e3770e36)
![2023-09-05_22 44 33](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/144169583/80f5d865-4575-4a49-a811-72ddfa459e37)
![2023-09-05_22 45 31](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/144169583/6c39c856-63d2-4894-9227-08e4bd7ab2d1)
![2023-09-05_22 47 23](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/144169583/378551f7-6699-4ea3-b818-c42dcd8b9f4e)
![2023-09-05_22 47 42](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/144169583/7148003c-491e-47ac-a0d3-0a74bdeaecec)
![2023-09-05_22 47 45](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/144169583/ab4bb79a-d8e7-4448-afb4-d64a970f08dd)
![2023-09-05_22 48 00](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/144169583/f3fa80ba-eb7a-4e3a-80a0-8b4e63682271)

**Comment by Saereth** [comment] 2023-12-06 21:58
I cant reproduce this but team dimensions has been updated several time since this version so I'm tentatilvely marking it fixed in dev, if you run into this issue after 1.4.0 update comes out reopen the issue please

**Closed** 2023-12-06 23:38 UTC
Labels: state: Fixed in Dev :hammer_and_wrench:, FTB Skies
