### ISSUE TITLE
[Bug]: Avaritia Extreme Crafting Table incompatibility with REI (and RS auto-crafting)

### ISSUE THREAD

**Issue by wrincewind** [FTBTeam/FTB-Modpack-Issues#1741] opened 2022-11-07 18:35 UTC
### Modpack

FTB Stoneblock 3

### Modpack version

1.1.0

### Describe the bug

the Avaritia Extreme Crafting table doesn't seem to like being used. I've tried refined storage and shift-clicking recipes from REI, but without any luck.

When i try to make a Neutron Compressor for example, i open the crafting table, open the recipe in REI, click or shift-click the [+] button at the bottom right, and get the following error: 

"Internal Error: Container Info does not exist on the server!" 

When I try to auto-craft with RS, i can setup the recipe just fine, but the crafter reports 'error: no machine found'. 

I've tried with AE2, but it cannot even encode patterns for extreme crafting (it only allows for 18 items max for 'processing patterns')

I'm not sure if this is a bug with Avaritia, or if there's something REI or RS can do to work around this issue, or if there's a companion mod out there that could assist, or what.

I've checked on the discord already and I've seen a few people asking for help with this, but no responses, which leads me to believe that there's no easy fix. 

i've also tried with JEI - clicking and shift-clicking works fine in the crafting table with that mod, so maybe it's an REI issue? 

### Steps to reproduce

1. place an avaritia crafting table
2. open up REI
3. shift-click a recipe into the crafting table
4. observe that the crafting has failed with an error message.

### Expected behaviour

the crafting table to be usable in some way that doesn't involve manually dragging individual items onto the table.

**Comment by Dima-Kevanishvili** [comment] 2022-11-08 09:27
REI works on my end but I have another problem with Extreme Crafting Table. 
If I insert recipe from REI (Even worse if I shift+insert), I'm getting a momentary freeze and the action is delayed. Then if I Shift+Click the output item from the table I again get a freeze and weird change in amount of input items.  Overall it is very slow and seems like more items you craft at the same time, bigger the freeze is. I actually got a crash when this was happening couple of times.
Here's the vid of reproduction: https://imgur.com/a/7UiydrZ
I agree with RS Auto crafting, seems like there's no real way to auto craft with Avaritia. How about adding Extended Crafting mod in the modpack? I think this would fix all the problems with this.

I'm wondering whether I should make a separate issue for this, If so please state and I will.

**Comment by Raidobw2** [comment] 2022-11-08 10:15
Dima-Kevanishvili the issue you're mentioning would likely already be reported at https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1747, but feel free to add more info to it there

**Comment by Dima-Kevanishvili** [comment] 2022-11-08 10:28
> Dima-Kevanishvili the issue you're mentioning would likely already be reported at #1747, but feel free to add more info to it there

Thanks. I'll add the details there then.

**Comment by AWDoBaun** [comment] 2022-11-17 20:52
I'll add some detail, this is currently happening to me on a server ( running 1.3.0 ).
![image](https://user-images.githubusercontent.com/12954977/202557271-df0f6eed-fa8a-4bd8-8029-17cc2baacd11.png)

But with the same build in Single player there is no error, the avaritia extreme table loads the recipe fine.

**Comment by melbellrocks** [comment] 2022-11-23 07:10
Getting the same error, this is from the console when it happens:

[23.11 01:10:07] [Server] java.lang.NullPointerExceptionContainer Info does not exist on the server!
[23.11 01:10:07] [Server] 	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
[23.11 01:10:07] [Server] 	at TRANSFORMER/roughlyenoughitems@8.3.571/me.shedaniel.rei.impl.common.transfer.InputSlotCrafter.start(InputSlotCrafter.java:68)
[23.11 01:10:07] [Server] 	at TRANSFORMER/roughlyenoughitems@8.3.571/me.shedaniel.rei.RoughlyEnoughItemsNetwork.lambda$onInitialize$4(RoughlyEnoughItemsNetwork.java:126)
[23.11 01:10:07] [Server] 	at TRANSFORMER/architectury@4.10.86/dev.architectury.networking.forge.NetworkManagerImpl.lambda$createPacketHandler$6(NetworkManagerImpl.java:150)
[23.11 01:10:07] [Server] 	at TRANSFORMER/architectury@4.10.86/dev.architectury.networking.transformers.SplitPacketTransformer.inbound(SplitPacketTransformer.java:174)
[23.11 01:10:07] [Server] 	at TRANSFORMER/architectury@4.10.86/dev.architectury.networking.forge.NetworkManagerImpl.lambda$createPacketHandler$7(NetworkManagerImpl.java:145)
[23.11 01:10:07] [Server] 	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
[23.11 01:10:07] [Server] 	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
[23.11 01:10:07] [Server] 	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
[23.11 01:10:07] [Server] 	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
[23.11 01:10:07] [Server] 	at TRANSFORMER/forge@40.1.84/net.minecraftforge.network.NetworkInstance.dispatch(NetworkInstance.java:68)
[23.11 01:10:07] [Server] 	at TRANSFORMER/forge@40.1.84/net.minecraftforge.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:78)
[23.11 01:10:07] [Server] 	at java.base/java.util.Optional.map(Optional.java:260)
[23.11 01:10:07] [Server] 	at TRANSFORMER/forge@40.1.84/net.minecraftforge.network.NetworkHooks.onCustomPayload(NetworkHooks.java:78)
[23.11 01:10:07] [Server] 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerGamePacketListenerImpl.m_7423_(ServerGamePacketListenerImpl.java:1439)
[23.11 01:10:07] [Server] 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:35)
[23.11 01:10:07] [Server] 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:8)
[23.11 01:10:07] [Server] 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22)
[23.11 01:10:07] [Server] 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.TickTask.run(TickTask.java:18)
[23.11 01:10:07] [Server] 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157)
[23.11 01:10:07] [Server] 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
[23.11 01:10:07] [Server] 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:799)
[23.11 01:10:07] [Server] 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164)
[23.11 01:10:07] [Server] 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131)
[23.11 01:10:07] [Server] 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:782)
[23.11 01:10:07] [Server] 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776)
[23.11 01:10:07] [Server] 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140)
[23.11 01:10:07] [Server] 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:762)
[23.11 01:10:07] [Server] 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689)
[23.11 01:10:07] [Server] 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261)
[23.11 01:10:07] [Server] 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by neldridge** [comment] 2022-12-02 17:41
I'm also experiencing this issue on my server, pack version 1.4.2

**Comment by neldridge** [comment] 2022-12-03 14:42
I duplicated my server, ran git init on my data folder, commited the server pack as-is for 1.4.2. After, I then copied my single-player folder overtop; there are a number of differences in the config/kubejs folder. 

I found there were recipes missing from kubejs/server_scripts/mods/avaritia.js, after copying over the recipes- they still did not work in the extreme crafting table.

**Comment by Sedus** [comment] 2022-12-10 18:26
Same on 1.4.3 server.

**Comment by neldridge** [comment] 2022-12-12 14:01
Please.... this is so painful; is there some way I can help test this and move it along? @Raidobw2

**Comment by Raidobw2** [comment] 2023-01-26 06:41
Sorry for replying so late... It seems this might have been fixed in 1.5.0. Since then REI has had a bunch of updates, so it looks like the integration is working properly again. It does look (and is) slow even when done manually, though I don't know how the code is done... but it works! At least.

![neutronium_compressor](https://user-images.githubusercontent.com/17010632/214772722-1e8c693b-1abb-49d9-872b-fb97a3b87226.gif)

I'll mark this as fixed in-dev for now, which I'll close properly once SB3 1.6.0 is out next week. Let me know if you still experience this on any 1.5.0+ game. Note that 1.5.0 currently holds a world join issue due to flywheel https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2404#issuecomment-1364625915, though that's fixed in 1.6.0.

**Closed** 2023-02-03 18:38 UTC
Labels: 1: Mod Issue, state: Fixed in Dev :hammer_and_wrench:, FTB StoneBlock 3
