### ISSUE TITLE
[Bug]:  Crash with Ender Chest @enderStorage

### ISSUE THREAD

**Issue by skyfyx** [FTBTeam/FTB-Modpack-Issues#1705] opened 2022-11-06 22:04 UTC
### Modpack

StoneBlock 3

### Modpack version

1.0.2

### Describe the bug

When we look what we can do with the Ender Chest ( from EnderStorage) we have a crash. ( 3 people on a server ) 

### Steps to reproduce

1. go to Stoneblock 3 Modpack 
2. open your REI 
3. Right click to see what you can do with Ender chest ( EnderStorage )
4. Crash !

### Expected behaviour

not a crash

### Additional information

Sorry if it's bad in english , i'm not an english person.

**Comment by Sunekaer** [comment] 2022-11-07 17:15
duplicate of #1574

**Closed by Sunekaer** 2022-11-07 17:15 UTC
