### ISSUE TITLE
[Bug]: Auto Smithing causes server crash

### ISSUE THREAD

**Issue by robbert229** [FTBTeam/FTB-Modpack-Issues#1737] opened 2022-11-07 17:44 UTC
### Modpack

FTB Stoneblock 3

### Modpack version

1.1.0

### Log Files

https://pastebin.com/sVKPRdbD

### Describe the bug

I hooked up the new auto smithing table to refined storage using a crafter, and upon ordering a netherite upgrade from functional storage the server crashed. Each time when I attempt to restart the server it crashes again.

### Steps to reproduce

1. place auto smithing table
2. place a refined storage crafter and importer next to it.
3. create a crafting reciepe for the functional storage netherite upgrade
4. request the netherite upgrade

### Expected behaviour

No server crash

**Comment by Sunekaer** [comment] 2022-11-07 19:16
Duplicate of #1723

**Closed by Sunekaer** 2022-11-07 19:16 UTC
Labels: FTB StoneBlock 3
