### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by SpyroManiac** [FTBTeam/FTB-Modpack-Issues#875] opened 2022-05-30 12:54 UTC
### Modpack

Direwolf20 1.18

### Modpack version

1.3.1

### Describe the bug

When creating a new superflat world it generates a normal world instead

### Steps to reproduce

1. click "singleplayer"
2. click "create new world"
3. click "more world options..."
4. select superflat as world type
5. finish creating new world

### Expected behaviour

A superflat world got created

**Comment by quietust** [comment] 2022-05-30 13:18
Duplicate of #813.

**Closed** 2022-05-30 13:44 UTC
