### ISSUE TITLE
Xycraft grains of Infinity recipe not working

### ISSUE THREAD

**Issue by NotPiffany** [FTBTeam/FTB-Modpack-Issues#5843] opened 2024-09-26 18:24 UTC
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.2.1

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

The grains of infinity recipe for the Xycraft extractor isn't working. I tried setting it up with the extractor pointing both up and down in case the JEI diagram was upside down, but no luck.

### Steps to reproduce

1. Place down a reinforced obsidian block.
2. Place down four cobbled deepslate blocks N,S,E,W of the reinforced obsidian.
3. Place an extractor on top of the reinforced obsidian.
4. Place an inventory on top of the extractor

### Expected behaviour

The extractor should start working and place grains of infinity inside the inventory.

**Comment by Soaryn** [comment] 2024-09-26 19:34
Requires Fire below the target block. Admittedly, that was supposed to be a Forgecraft only recipe.

This is wrong appearing due to Fire not having a backing item anymore unlike older minecraft versions. So it needs some form of fire block (likely just normal fire)

**Comment by NotPiffany** [comment] 2024-09-26 23:23
A campfire does not work, but netherrack set on fire does. Thanks, Soaryn.

**Comment by Soaryn** [comment] 2024-09-27 05:50
Ohhh campfire is a good idea to add though!

**Comment by becky15675** [comment] 2024-10-03 07:13
Thank you Soaryn, this frustrated me a lot and had given up on it until I stumbled upon this. I got it working once I put the fire under the reinforced obsidian and yes, I too would like to use a campfire instead of flames

**Comment by 1John5vs7** [comment] 2024-10-05 13:28
Thanks @Soaryn for the explanation. Just in case anyone is confused by the language when Soaryn says "target block", that means  the block immediately under the Extractor.

I did:

Top layer:     Extractor
Middle layer:     Reinforced Obsidian with Cobbled Deepslate North, South, East, and West of it
Next layer:  fire
Bottom layer: netherrack

Just light the netherrack on fire and slap the reinforced obsidian down 1 block above the fire and your extractor should now get you 1 grain of infinity per 10 seconds!

**Comment by mostlygizzards** [comment] 2024-10-09 03:36
Confirmed fix here

![image](https://github.com/user-attachments/assets/630000f9-4fdc-4790-a9b2-e30e10f62f4f)
![image](https://github.com/user-attachments/assets/89f4a270-91d0-4d94-b344-a8d357bf0e32)

**Comment by Soaryn** [comment] 2024-10-09 08:14
Not exactly a bug in how the extractor operates, just the fact that there is no item for fire 😅 

All of this is to be redone in the future, just dont have a timeframe on that yet.

**Comment by 1John5vs7** [comment] 2024-10-09 10:52
Feels like the more important thing is to clarify the orientation of
exterior vs source block in the GUI.

**Comment by 1John5vs7** [comment] 2024-10-09 10:52
Extractor*

**Comment by IamStig** [comment] 2024-10-12 09:35
Thanks zperk13 I will shut down #5919 now.
I was thinking....does Xycraft have a lava block like the water block? (I don't have MC open atm) if it does, or one might be added, could that be used for these builds? in place of lava ...and fire maybe. it would be able to be used in the diagrams too. And would allow for far tidier builds. Maybe if @Soaryn Soaryn is getting notifications he might have a thought on this.

**Comment by Raidobw2** [comment] 2024-11-10 23:31
It seems this could potentially be fixed in the modpack by overriding the original fire recipe with a fix and adding a new recipe with the campfire.

`kubejs/data/xycraft_machines/recipe/extractor/enderio/grains_of_infinity.json`

<details>
  <summary>kubejs/data/xycraft_machines/recipe/extractor/enderio/grains_of_infinity.json</summary>
  
  ```json
  {
    "type": "xycraft_machines:extractor",
    "adjacent": [
      {
        "block": "minecraft:cobbled_deepslate",
        "predicate_type": "xycraft_core:block_rule"
      },
      {
        "block": "minecraft:cobbled_deepslate",
        "predicate_type": "xycraft_core:block_rule"
      },
      {
        "block": "minecraft:cobbled_deepslate",
        "predicate_type": "xycraft_core:block_rule"
      },
      {
        "block": "minecraft:cobbled_deepslate",
        "predicate_type": "xycraft_core:block_rule"
      }
    ],
    "catalyst": {
      "block": "minecraft:fire",
      "predicate_type": "xycraft_core:block_rule"
    },
    "output": {
      "Count": 1,
      "id": "enderio:grains_of_infinity"
    },
    "target": {
      "block": "enderio:reinforced_obsidian_block",
      "predicate_type": "xycraft_core:block_rule"
    },
    "ticks": 200,
    "hidden": true,
    "valid_directions": [
      "down"
    ]
  }
  ```

</details>

`kubejs/data/xycraft_machines/recipe/extractor/enderio/grains_of_infinity_campfire.json`

<details>
  <summary>kubejs/data/xycraft_machines/recipe/extractor/enderio/grains_of_infinity_campfire.json</summary>
  
  ```json
  {
    "type": "xycraft_machines:extractor",
    "adjacent": [
      {
        "block": "minecraft:cobbled_deepslate",
        "predicate_type": "xycraft_core:block_rule"
      },
      {
        "block": "minecraft:cobbled_deepslate",
        "predicate_type": "xycraft_core:block_rule"
      },
      {
        "block": "minecraft:cobbled_deepslate",
        "predicate_type": "xycraft_core:block_rule"
      },
      {
        "block": "minecraft:cobbled_deepslate",
        "predicate_type": "xycraft_core:block_rule"
      }
    ],
    "catalyst": {
      "block": "minecraft:campfire",
      "predicate_type": "xycraft_core:block_rule"
    },
    "output": {
      "Count": 1,
      "id": "enderio:grains_of_infinity"
    },
    "target": {
      "block": "enderio:reinforced_obsidian_block",
      "predicate_type": "xycraft_core:block_rule"
    },
    "ticks": 200,
    "valid_directions": [
      "down"
    ]
}
```

</details>

Fortunately there is a neat "hidden" property on the recipe serializer, which will hide the fire recipe from JEI. Both recipes would still be usable, but only the campfire one would show a visual in JEI, so this would be a non-breaking change for old setups using fire.

![image](https://github.com/user-attachments/assets/2ea37e35-3d54-4df1-8782-14b7256dd490)

**Comment by Gaz492** [comment] 2024-12-02 10:37
This is fixed in the latest version of the pack

**Closed by Gaz492** 2024-12-02 10:37 UTC
Labels: state: Fixed in Dev, state: Testing required, Bug, FTB Presents Direwolf20 1.21

**Comment by 1John5vs7** [comment] 2024-12-02 12:54
Awesome, thanks!
