### ISSUE TITLE
[Bug]: Some raw materials (chunks) don't have consistent recipes in Mekanism

### ISSUE THREAD

**Issue by csuarezmtz** [FTBTeam/FTB-Modpack-Issues#952] opened 2022-06-13 16:53 UTC
### Modpack

FTB Presents Direwolf 20 1.18

### Modpack version

1.4.1

### Describe the bug

Raw silver (silver chunks) don't have the same recipes to get processed in Mekanism (they cannot be place inside the Purifying Chamber). Happens for other ores also.

### Steps to reproduce

1. Try to place raw silver into the Purifying Chamber or it's factory equivalents

### Expected behaviour

Raw material prcessing recipes should be consistent

**Comment by csuarezmtz** [comment] 2022-06-13 17:24
- Tested and happens for silver and nickel, but works fine for lead (would appear it has to do with ores tagged for Immersive Engineering)

**Comment by quietust** [comment] 2022-06-14 14:06
Currently, Mekanism >2x ore multiplication only works with the metals natively recognized by Mekanism itself: vanilla metals (copper/iron/gold), tin, lead, osmium, and uranium.

Effectively, this is a duplicate of #810.

**Comment by TheonlyTazz** [comment] 2022-06-17 09:17
as quietust already stated, duplicate of #810 and Sune explained that there are no clump versions of those metals in mekanism:

Sunekaer:
> That's because there are no clump versions of those metals in mekanism

**Closed by TheonlyTazz** 2022-06-17 09:17 UTC
Labels: FTB Presents Direwolf20 1.18
