### ISSUE TITLE
Puffish Skills to upgrade Ultimine doesn't work.

### ISSUE THREAD

**Issue by Storyboard-MC** [FTBTeam/FTB-Modpack-Issues#6059] opened 2024-11-02 18:32 UTC
### Modpack

FTB Evolution

### Modpack version

1.0.3

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

I have upgraded my FTB Ultimine capabilities to 64 blocks but its still stuck at 16, I am running my world through FTB Worlds, but also does the same thing in Single Player.

### Steps to reproduce

1. Level up Mining Skill to get skills points for Mining
2. Level up the Ultimine Perks
3. See that the Ultimine is still at 16.

### Expected behaviour

The ultimine perk should upgrade the amount of 32 blocks.

### Screenshots

![image](https://github.com/user-attachments/assets/358aea1f-ae84-47aa-b1d1-fb6264314143)
![image](https://github.com/user-attachments/assets/cddba668-1845-4cf8-92b7-fcf76cb9210d)

### Additional information

As you can see from the screenshots the upgrade doesn't work as intended.

**Comment by alfredggttv** [comment] 2024-11-04 17:48
This is due to the ranks file being reset to default and not having the extra ranks we are granting for Ultimine. We are working with the mod dev to see about fixing it.

In the meantime, you can manually update your ranks.snbt file to fix the issue. This file can be found here:
`FTBEvolution/saves/worldname/serverconfig/ftbranks/ranks.snbt`

This file should look like this:

```snbt
{
	member: {
		name: "Member"
		power: 1
		condition: "always_active"
	}
	vip: {
		name: "VIP"
		power: 50
		ftbranks.name_format: "&bVIP {name}"
	}
	admin: {
		name: "Admin"
		power: 1000
		condition: "op"
		ftbranks.name_format: "&2{name}"
	}
	ultimine_upgrade1: {
		name: "ultimine_upgrade1"
		power: 2
		ftbultimine.max_blocks: 32
	}
	ultimine_upgrade2: {
		name: "ultimine_upgrade2"
		power: 3
		ftbultimine.max_blocks: 48
	}
	ultimine_upgrade3: {
		name: "ultimine_upgrade3"
		power: 4
		ftbultimine.max_blocks: 64
	}
	ultimine_upgrade4: {
		name: "ultimine_upgrade4"
		power: 5
		ftbultimine.max_blocks: 96
	}
	ultimine_upgrade5: {
		name: "ultimine_upgrade5"
		power: 6
		ftbultimine.max_blocks: 128
	}
}
```

**Comment by RoyalReject** [comment] 2024-11-04 21:40
It seems the ranks file is not provided in the defaultconfigs, this is what is copied over to the serverconfig file on world creation. Resulting in the default config file

**Comment by Storyboard-MC** [comment] 2024-11-05 01:52
Main problem for me tho, Since I am on an FTB Worlds server I cannot add that or modify it

**Comment by ttechr** [comment] 2024-11-07 14:56
> This is due to the ranks file being reset to default and not having the extra ranks we are granting for Ultimine. We are working with the mod dev to see about fixing it.
> 
> In the meantime, you can manually update your ranks.snbt file to fix the issue. This file can be found here: `FTBEvolution/saves/worldname/serverconfig/ftbranks/ranks.snbt`
> 
> This file should look like this:
> 
> ```
> {
> 	member: {
> 		name: "Member"
> 		power: 1
> 		condition: "always_active"
> 	}
> 	vip: {
> 		name: "VIP"
> 		power: 50
> 		ftbranks.name_format: "&bVIP {name}"
> 	}
> 	admin: {
> 		name: "Admin"
> 		power: 1000
> 		condition: "op"
> 		ftbranks.name_format: "&2{name}"
> 	}
> 	ultimine_upgrade1: {
> 		name: "ultimine_upgrade1"
> 		power: 2
> 		ftbultimine.max_blocks: 32
> 	}
> 	ultimine_upgrade2: {
> 		name: "ultimine_upgrade2"
> 		power: 3
> 		ftbultimine.max_blocks: 48
> 	}
> 	ultimine_upgrade3: {
> 		name: "ultimine_upgrade3"
> 		power: 4
> 		ftbultimine.max_blocks: 64
> 	}
> 	ultimine_upgrade4: {
> 		name: "ultimine_upgrade4"
> 		power: 5
> 		ftbultimine.max_blocks: 96
> 	}
> 	ultimine_upgrade5: {
> 		name: "ultimine_upgrade5"
> 		power: 6
> 		ftbultimine.max_blocks: 128
> 	}
> }
> ```

I did this and rebooted the server as well as reloaded the ftbranks ingame and the ultimine ones are not showing up when listing them ingame.

**Comment by ttechr** [comment] 2024-11-08 02:53
> Main problem for me tho, Since I am on an FTB Worlds server I cannot add that or modify it

Do you have op on the server? If so you can add it through the chat and give yourself the rank as well.

**Comment by Temil2006** [comment] 2024-11-09 19:13
i saw in patch notes there is a mention to this issue being fixed in 1.2.0 version.
--- Ranks for ultimine upgrades not being properly created

However, I still seem to have the same issue. are these patch notes stating it's fixed meaning the issue is fixed, or that it's still an issue, but just the creation of the rank settings is fixed?

**Comment by alfredggttv** [comment] 2024-11-09 19:20
We've run into a separate problem, and are taking a look how to fix it.

**Comment by Temil2006** [comment] 2024-11-09 19:24
> We've run into a separate problem, and are taking a look how to fix it.

understood. if you need anyone to test before release, feel free to ping me directly via discord or here. happy to test, have both test server and prod server up.

**Comment by Temil2006** [comment] 2024-11-09 19:45
what I did with my players is I did the following command 1 time for them .. which reset there points, without reseting there levels or xp. when puting the points in, it all worked great, and set the correct mining amounts. just saying, maybe a 1 time "reset" for the players after the update, would be handy for fixing this for them.

/puffish_skills skills reset <player> mining

**Closed** 2024-11-13 21:50 UTC
Labels: state: Fixed in Dev, Bug, !Reported to Mod Dev, @Mod issue, FTB Evolution
