### ISSUE TITLE
Stoneblock 2 Crashes upon launch consistently after previously being playable

### ISSUE THREAD

**Issue by RGBSoul** [FTBTeam/FTB-Modpack-Issues#4881] opened 2024-03-07 00:20 UTC
### Modpack

FTB Presents Stoneblock 2

### Modpack version

1.22.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14517058/latest.log)

### Describe the bug

Stoneblock 2 crashes on launch after being playable the previous day

### Steps to reproduce

1. Download and start stoneblock 2
2. Play and adjust some settings
3. Next day, try to launch game, and crash upon start

### Expected behaviour

Stoneblock 2 starts properly

### Additional information

crash log mentions something about key pressing, after playing the game I had swapped shift and control keys for sprint and crouch, but that may be irrelevant.

**Comment by faizjamil** [comment] 2024-03-09 00:08
Unable to reproduce on a fresh Stoneblock 2 instance. Changed Sprint to LSHIFT and Sneak to LCONTROL and was able to relaunch the game fine.

@RGBSoul
Have you tried creating a new profile/instance of Stoneblock 2 and then moving over your saves to that new profile/instance?
I would not add or remove any mods before trying this.

If that fixes your issue I suggest closing this issue since that kind of instance-specific issue may not be worth investigating. Especially if you cannot reproduce the issue.

**Comment by RGBSoul** [comment] 2024-03-09 02:34
faizjamil, I appreciate your effort on helping my issue, however I have found that this is a fairly common problem that exists with minecraft itself, specifically in versions below 1.13, which the modpack runs 1.12.2, and it has something to do with the game crashing while trying to go full screen, there are some workarounds to this issue, however none of them are a permanent solution, and i'm not exactly sure why this happens or what causes it, so we can close this issue however I would appreciate if a less tedious workaround or solution comes to light, because for the moment if i close the game while it is in fullscreen, if i do not change fullscreen to false manually in options.txt, the game will open to a crash.

**Closed** 2024-03-09 17:52 UTC
Labels: FTB Presents Stoneblock 2
