### ISSUE TITLE
[Bug]: permanent levitation

### ISSUE THREAD

**Issue by Devilaux** [FTBTeam/FTB-Modpack-Issues#2015] opened 2022-11-17 20:23 UTC
### Modpack

FTB Stoneblock 3

### Modpack version

1.2.1

### Describe the bug

I'm stuck floating/levitating in my world, after opening a giant compact chance cube (the one that throws potions around). Tried creative mode, can go up and down, but as soon as i go into survival mode, it comes back. Cant jump at all. 

Tried removing effects via commands, but no effects detected. Tried giving me the levitation effect, it works, but back to beeing stuck in the air again as soon as that effect wears off. 

### Steps to reproduce

Open a giant compact chance cube under water. 

### Expected behaviour

Effect goes away

**Comment by NordicGamerFE** [comment] 2022-11-18 06:04
Duplicate of #1809

**Closed** 2022-11-19 18:08 UTC
