### ISSUE TITLE
PNC nuking server

### ISSUE THREAD

**Issue by Ghostl00l** [FTBTeam/FTB-Modpack-Issues#4997] opened 2024-03-18 01:54 UTC
### Modpack

FTB Skies Expert

### Modpack version

1.5.0

### Describe the bug

Whenever we complete the Reinforced Stone quest in Pneumaticraft chapter, the server gets destroyed from to many quest completions. We get all the old pneumaticraft stuff we had done before quests where up for it, and quests we have already completed are triggering again.

### Steps to reproduce

All we do is complete the reinforced stone quest in the pneumaticraft chapter and it nukes the server

### Expected behaviour

I expected the game to be able to handle completing a simple quest.

**Comment by Saereth** [comment] 2024-03-22 16:05
Provide crash logs please

**Comment by LeanderBockholt** [comment] 2024-03-25 11:20
I Had a similar Problem with my Ars Novuea Questline after I Updated to 1.6. The Server was stopped due to Tick needing more than 60000 MiliSeconds.
I fixed it for me by setting the max Time per Tick to 10 Minutes = 600000 MiliSeconds and that fixed it for me.

**Comment by Saereth** [comment] 2024-03-29 16:15
ok so this is a duplicate of the quest issue seems, gonna close to consolidate issues

**Closed by Saereth** 2024-03-29 16:15 UTC
Labels: state: Awaiting Reply :speaking_head:, FTB Skies Expert
