### ISSUE TITLE
FTB Skies Greater Band of Aura not providing any mana at all

### ISSUE THREAD

**Issue by ChewedPencil** [FTBTeam/FTB-Modpack-Issues#3139] opened 2023-04-16 02:58 UTC
### Modpack

FTB Skies

### Modpack version

1.0.6

### Describe the bug

Wearing the Greater Band of Aura does nothing at all. I will show that its SUPPOSED to be doing something when holding an item it is supposed to be adding mana to if you have it in your hand and watch it bob as it seems to be filling, but the meter doesnt go any higher

### Steps to reproduce

Wear any Band of Aura

Hold mana holding item

watch it wriggle like a potato imbued with a spark of life and a positive attitude!

### Expected behaviour

I expect that the Greater Band of aura to be adding 10 points of mana to my items when worn

**Comment by Saereth** [comment] 2023-06-13 05:02
working fine here, cant reproduce so I'll assume it was fixed in the last update for that mod 
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/9200909/7abc54cc-0218-41e1-a361-f2f10b648089)

**Closed by Saereth** 2023-06-13 05:02 UTC
Labels: 1: Mod Issue, FTB Skies
