### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ReptarG59** [FTBTeam/FTB-Modpack-Issues#1917] opened 2022-11-13 05:11 UTC
### Modpack

FTB Stoneblock 3

### Modpack version

1.21

### Describe the bug

Can't encode processing patterns with ae2 from rei

### Steps to reproduce

Go to pattern encoding terminal and try to add a processing recipe from rei

### Expected behaviour

pattern should be added to ae2 pattern encoding terminal

**Comment by Sunekaer** [comment] 2022-11-13 21:09
Duplicate of #1800

**Closed by Sunekaer** 2022-11-13 21:09 UTC
Labels: FTB StoneBlock 3
