### ISSUE TITLE
[Bug, Mekanism]: Item duplication using Mekanism Cardboard Box

### ISSUE THREAD

**Issue by poempelhase** [FTBTeam/FTB-Modpack-Issues#33] opened 2021-09-28 08:19 UTC
### Modpack

FTB OceanBlock

### Modpack version

1.1.0

### Describe the bug

Putting a Cardboard Box on a container drops certain items even though they're still inside the container. So far I could reproduce this behaviour with Wyvern Pickaxes and Charged Certus Quartz, but there may be be other affected items.

### Steps to reproduce

1. Put item in container (Tested with vanilla barrel and obsidian chest)
2. Right click Mekanism Cardboard Box on the container
3. Affected items drop
4. Remove Cardboard Box
5. Duplicated items remain in the container

### Expected behaviour

Items should not drop from wrapping containers in a Box

**Comment by Sunekaer** [comment] 2021-09-28 08:24
https://github.com/mekanism/Mekanism/issues/7053

**Comment by Raidobw2** [comment] 2021-09-28 23:46
Can confirm this enabling the dupe of certain items. OceanBlock version 1.1.0
![cardboard_dupe](https://user-images.githubusercontent.com/17010632/135180113-e521f635-2f72-45cb-9587-2b822043558b.gif)

**Comment by Raidobw2** [comment] 2021-12-23 11:18
The issue on Mekanism's side was closed. There was no notice or any info given why it was closed. To be checked in the next days if Mek implemented a fix or talked with the Forge devs.

**Comment by poempelhase** [comment] 2021-12-23 11:20
According to the changelog for Mekanism 10.1 which was released today, some dupe bugs were fixed in this release.
[https://www.reddit.com/r/feedthebeast/comments/rmcthj/mekanism_101_released/](url)

**Comment by Raidobw2** [comment] 2021-12-27 02:16
Yes I see 10.1 mentions the fix, thank you!

**Closed** 2022-03-27 11:01 UTC
Labels: FTB OceanBlock, 1: Mod Issue, state: Fixed in Dev :hammer_and_wrench:
