### ISSUE TITLE
[Suggestion]: Refined Storage RSInfinityBooster

### ISSUE THREAD

**Issue by Hexeption** [FTBTeam/FTB-Modpack-Issues#80] opened 2021-10-04 13:00 UTC
### Modpack

FTB OceanBlock

### Is your suggestion related to a problem? Please describe.

Be nice to have able to have unlimited range on Refined Storage wireless terminal.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/rsinfinitybooster

**Comment by Sunekaer** [comment] 2021-10-05 13:43
Duplicate of #21

**Closed by Sunekaer** 2021-10-05 13:43 UTC
Labels: FTB OceanBlock, State: Duplicate :books:, Note: Mod Suggestion
