### ISSUE TITLE
[Bug]: Entity Invisiblity [even chests]

### ISSUE THREAD

**Issue by TarConvent** [FTBTeam/FTB-Modpack-Issues#1652] opened 2022-11-05 11:45 UTC
### Modpack

FTB StoneBlock 3

### Modpack version

1.0.2

### Describe the bug

Entities such as mobs/chests/player are invisible even to Hit-Box indicator F3+B

### Steps to reproduce

Haven't figured a way to reproduce the instance of invis entities

### Expected behaviour

happened at the start of creation of world

### Screenshots

![oie_512405632yj4Qs1](https://user-images.githubusercontent.com/25818470/200118150-709a368b-269f-4831-ab86-64c95ff6c706.png)
![oie_5124224HPoVlLNF](https://user-images.githubusercontent.com/25818470/200118195-7eb0b730-2217-4b8c-9317-a2cd893cbf6d.png)

**Comment by Sunekaer** [comment] 2022-11-05 12:33
Duplicate of #1542 - Restart your game and it will be fixed :)

**Closed by Sunekaer** 2022-11-05 12:33 UTC
Labels: FTB StoneBlock 3
