### ISSUE TITLE
Wither Skeleton Trophy Crashing 

### ISSUE THREAD

**Issue by Darphbobo2024** [FTBTeam/FTB-Modpack-Issues#5878] opened 2024-10-01 00:15 UTC
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.21 1.2.1

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

[19:09:11] [Render thread/ERROR] [obtrophies/]: Failed to render entity entity.minecraft.wither_skeleton as a trophy
[2024-09-30-1.log.gz](https://github.com/user-attachments/files/17197715/2024-09-30-1.log.gz)

### Describe the bug

I placed the Wither Trophy down on a grass block and it crashed the game. 

### Steps to reproduce

1. Get trophy from Wither Skeleton
2. Place from in hand onto grass block. 
3. Click Trophy.
4. Game crashes.

### Expected behaviour

See trophy information.

**Comment by Gaz492** [comment] 2024-10-01 12:40
Duplicate of #5846

**Closed by Gaz492** 2024-10-01 12:40 UTC
Labels: Bug, FTB Presents Direwolf20 1.21
