### ISSUE TITLE
item appears multiple time when using an external storage on drawer controller

### ISSUE THREAD

**Issue by anddek1602** [FTBTeam/FTB-Modpack-Issues#2701] opened 2023-02-10 23:30 UTC
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Describe the bug

I linked my refined storage with all of my drawers via the drawer controller with an external storage, linked with a network receiver. Now, when I access my system, everything duplicates itself with a stack (as you can see in the screenshot) while not taking extra space

### Steps to reproduce

1. Link some drawers with a drawer controller
2. Generate things and add it to the drawers
3. Link the drawer controller with an external storage to the refined storage system
4. Check the refined storage system

### Expected behaviour

Normally the grids should just show how much there is in every drawer

### Screenshots

![Screenshot 2023-02-11 002019](https://user-images.githubusercontent.com/125098408/218221516-e91d424c-b5db-4323-8aef-ec3e4ef65693.png)

**Comment by faanlez** [comment] 2023-02-20 14:33
This is caused by Controller Extension. You'll have to remove the Extensions and break and replace the Controller to fix it.

Already an issue up on Functional Storage's tracker:

https://github.com/Buuz135/FunctionalStorage/issues/163

**Comment by UnRealDinnerbone** [comment] 2023-12-12 01:03
Close this issue as the mod issue has been open since February, without any update

**Closed by UnRealDinnerbone** 2023-12-12 01:03 UTC
Labels: 1: Mod Issue, state: Awaiting Mod Update, FTB StoneBlock 3
